galaxyproject/training-material

Exome-Seq/tutorials/Exome-Seq.md
I can't pull
```
bgruening/galaxy-exome-seq-training
```
but there is
```
bgruening/galaxy-training-exome-seq
```
=> Fix container name

_includes/main_footer.html, _includes/main_header.html, _layouts/base_slides.html, _layouts/home.html, _layouts/tutorial_hands_on.html, _layouts/tutorial_slides.html
Hi,
I made some small changes in templates
- In home page to remove mention of repository moving
- Add link to material file on GitHub in all material to fix typos
I also add on all training material a mention of a collaborative work and a link to the contributors of the topics.
Bérénice
=> Small changes in templates and add links to contributors in each material

assets/css/slides.css
- Make sure title is always centered even if an individual slide is marked as ``class: left``.
- If ``code`` tags appear in ``reduced90``, ``reduced70``, or ``enlarge120`` - modify fixed font size accordingly.
- Add a couple new styles for separating slides into left and right content down the middle as well as a strike through style.
I updated the Galaxy Architecture slides to use this modified template in galaxyproject/galaxy#3594.
=> Align remarkjs CSS with Galaxy Architecture slides from galaxyproject/galaxy

RNA-Seq/tutorials/de_novo.md
Fixed typo in filtering expression. Added link to Dataset collections tutorial on new.galaxyproject. Fixed typo on number of genes listed in output file. Added missed parameter for featureCounts.
=> Fixed typos for de_novo tutorial

_layouts/topic.html, metadata/Dev-Corner.yml
I love this project and support what it is trying to do - but I see Planemo's docs as the canonical tutorial for tool development and I'd hope we don't have to compete I guess on this one tutorial? I'm happy to take suggestions and PRs to improve the docs.
xref #75 
I'd like to build out slides in this repository for Conda ( #231 ) and Dockerizing tools ( #232 ) - but I guess only if y'all let me link to the Planemo docs as the canonical walkthrough tutorial. Similar to what I am doing in this PR.
=> Add a link out to Planemo's tool development tutorial.

CONTRIBUTING.md, Gemfile, Makefile, README.md, environment.yml, topics/training/tutorials/create-new-tutorial-jekyll/tutorial.md
Hi,
On the advise of @bgruening, we can use conda to manage the installation Jekyll and its modules.
It can then simplified the Makefile. 
I documented that in the dedicated tutorial. In the same time, I simplified the CONTRIBUTING.md and the README.md to link to the "Train the trainers" tutorials where everything needed to develop a tutorial is explained.
Bérénice
=> Use of conda to simplify Jekyll and module installation

topics/transcriptomics/metadata.yaml, topics/transcriptomics/tutorials/srna/tutorial.md
Added the link to the Zenodo dataset of downsampled reads and annotation files.  Updated wording for "Data upload and organization" section. Deleted comment for inserting Zenodo link.
=> Added Zenodo link to sRNA-seq tutorial

topics/dev/tutorials/tool-integration/slides.html
The commit removes hands-on from the tool_integration slides and links the Planemo tutorial
ping @jmchilton @martenson @bebatut @abretaud @bgruening
=> dev-corner - tool_integration - remove hands-on and link planemo tutorial

_config.yml
Thanks to #432, we can now see diffs of what has changed on the deployed website.
I have looked at [the first diff after the figurify plugin has been merged](https://github.com/galaxyproject/training-material/commit/a93aaa185162435412f0f685c93533cad4c94c96), and a slide deck has been figurified 😝 This PR excludes the `base_slides` layout to avoid that.
Cheers,
W.
=> Add base_slides to the list of excluded layouts

_layouts/base_slides.html, _layouts/tutorial_hands_on.html
Hi,
I fixed some failing links at the top and bottom of tutorials (after the restructuration of May).
I also added the list of contributors if found in the metadata of a tutorial (filled in #407) on the tutorial and slides
Bérénice
=> Fix links + add contributors at bottom of tutorials

_plugins/jekyll-figurify.rb
Hi,
ping @willdurand 
I removed the alt text as possible caption text to use only the title
Bérénice
=> figurify plugin: Remove the alt text as possible caption

.travis.yml, README.md, bin/publish, topics/assembly/tutorials/debruijn-graph-assembly/tutorial.md
- Replaces vl check with htmlproofer
- Enables travis testing on the gh-pages branch so that we can set up a daily travis cron job on the served site to continually test links
- Badge on readme now reflects build status of gh-pages branch (this will fail for a while until we go back and add alt-texts for images in existing materials, but maybe this will be good encouragement to do this sooner rather than later :) )
there are also some more broken links reported by htmlproofer, will fix those in a later PR
ping @bebatut
=> Site proofing

CONTRIBUTING.md, README.md
As spotted by @joachimwolff in #447, the role of a maintainer is not clear. I tried to clarify it a bit.
I also had link to the "Train the trainers" tutorials in the README file (it was missing)
=> Try to clarify maintainer role and add link to training tutorials

.travis.yml, Makefile, bin/publish
Hi,
This PR prevents the website to be broken by ensuring that an error at build time is caught by Travis. I have also added a check to the `publish` script to avoid publishing an empty website. Both changes should avoid yesterday's situation.
Note: the `|| return 0` should be removed as soon as all htmlproofer errors are fixed.
=> Make sure the Travis build fails when website cannot be built

.travis.yml
⚠️  Not merging before YAML linting and #493 
---
I removed the `|| return 0` in Travis, to make sure that Travis tests can fail
=> Activate correct Travis check

topics/metagenomics/metadata.yaml
At https://galaxyproject.github.io/training-material/topics/metagenomics/
=> Fix missing link to Introduction slides for metagenomics

topics/proteomics/tutorials/metaproteomics/tools.yaml, topics/proteomics/tutorials/metaproteomics/tutorial.md
Added a tools file for the metaproteomics tutorial. 
Missing is still the entry for "Split Tabular Columns" - I did not know which tool the corresponds to. 
I was wondering if there is way to specify visualizations that need to be installed/configured. For this tutorial the required Unipept Tree viewer seems not to work by default.
=> metaproteomics minor improvements

topics/metagenomics/tutorials/mothur-miseq-sop/tutorial.md
If data is imported from Zenodo and the pair names are left to their defaults in the collection creation step, it will cause problems towards the end of the tutorial, so I've added a warning about this.
=> Mothur-MiSeq- SOP: add warning about dataset pair names

.travis.yml
I just realized we are not running htmlproofer/yamllint on PRs from other forks, this should fix that.
see for example #553, the **push** job fails, but the **pr** job succeeds because `$TRAVIS_BRANCH` then gets the value of `master` and only `make build` is run. (and for PRs from other forks this is the only test that is run)
ping @bebatut
=> fix travis testing on PRs

bin/docker-install-tutorials.sh
run the installation of tutorials as user `galaxy` to prevent problems when some files in conda are owned by root (as mentioned by @nekrut on Gitter)
=> docker: switch to galaxy user for install

CONTRIBUTORS.yaml
@AisanjiangW changed their github username (used to be ewran)
=> contributors: update changed github username

topics/admin/tutorials/database-schema/tutorial.md
in order to access the PostgreSQL database on the command line. This has become necessary due to a (security) fix within the docker container.
I will update the tutorial to use 'pgadmin' in time for GCC1018 (as discussed with @bgruening yesterday)
=> change to user galaxy

topics/transcriptomics/tutorials/ref-based/tools.yaml
`trimgalore` (particularly from `iuc`) does not exist in the Tool Shed so update to an existing tool.
=> Update RNA-based tutorial tool

Makefile, environment.yml
- Add npm as dependency
- Use npm to install decktape
- Update decktape command to create PDF for the slides
=> Update decktape installation

_config.yml, _layouts/topic.html, topics/assembly/metadata.yaml, topics/chip-seq/metadata.yaml, topics/epigenetics/metadata.yaml, topics/introduction/metadata.yaml, topics/metagenomics/metadata.yaml, topics/proteomics/metadata.yaml, topics/sequence-analysis/metadata.yaml, topics/training/tutorials/create-new-tutorial-metadata/tutorial.md, topics/transcriptomics/metadata.yaml, topics/variant-analysis/metadata.yaml
To fix #287
On the topic page:
It links to the workflow on GitHub
To add that, some metadata are added for the tutorials
```
-
title: "De novo transcriptome reconstruction with RNA-Seq"
type: "tutorial"
name: "de-novo"
zenodo_link: "https://zenodo.org/record/254485#.WKODmRIrKRu"
galaxy_tour: ""
workflows:
-
name: rnaseq-denovo-transcriptome-reconstruction
title: "Full"
....
```
We can then have several workflows for a tutorial and link them from the topic page.
The training tutorial on metadata is updated
=> Add link to workflows in the topic page

topics/metagenomics/tutorials/mothur-miseq-sop/tutorial.md
- Section "Hands-on: Subsampling": count.groups input clarified as a collection in final "check" step
- Section "Hands-on: Correlation": Fix tool name from Get.communitype to Get.communitytype in last hands-on step
=> Typo fix and clarified an input as a collection

templates/tutorials/tutorial1/tutorial.md
The template `tutorial.md` file uses two different syntaxes for icons at the top of marked-up sections: one is `:bulb:` and the other is `{% icon tip %}`. The latter is configurable at the repo level with `_config.yml` and I'm told is the recommended way to do things. I'm not sure if including both syntaxes is deliberate? This PR updates the template to use only the `{% icon name %}` syntax, and adds an explanatory comment.
=> Using latest syntax for icons in template tutorial.md

.travis.yml
This should reduce the number of jobs per build, especially for the `gh-pages` branch. ~~It also skips `htmlproofer` for PRs since no one really cares (I mean PRs get still merged while it is red and it is red all the time, which is very frustrating) and we can still have the report on `gh-pages` builds.~~
It allows `htmlproofer` to fail since this tool is not reliable and generates various random false positives. It is still run, but does not determine the status of the build anymore (🎉 welcome back green statuses).
=> Add constraints on travis-ci

.travis.yml, Makefile
html proofer currently fails on links to the github repo (e.g. "edit on github" links or links to tours etc)  for PRs that create new tutorials/topics/files because these files do not yet exist in the master branch of this repo. Using the `--url-swap` option in htmlproofer we can rewrite those links on the fly to point to the repo and branch of origin of the PR
so for instance, for this PR it should rewrite links like `github.com/galaxyproject/training-material/tree/master/<etc>` to `github.com/shiltemann/training-material/tree/linkchecking/<etc>`
could use some testing
ping @bebatut
=> add --url-swap to htmlproofer

_layouts/topic.html, assets/css/main.scss, topics/assembly/metadata.yaml, topics/sequence-analysis/metadata.yaml, topics/transcriptomics/metadata.yaml, topics/variant-analysis/metadata.yaml
As asked in #349, this PR should add the possibility to have tags for the tutorials in the metadata files that will be display below the tutorial name on the topic page: 
Several tags can be added for a tutorial as a list:
PS: Currently the labels are not links. But we could think (in the future) to extend this feature to list all the tutorials with the same tag. But I am not sure if it will be easy...
=> Add category tags for tutorials

topics/transcriptomics/tutorials/de-novo/tutorial.md
https://zenodo.org/record/583140/files/G1E_rep1_forward_read_%28SRR549355_1%29 was not previously being displayed
=> Fix for display of input datasets in de novo rna-seq

topics/variant-analysis/metadata.yaml, topics/variant-analysis/tutorials/non-dip/tutorial.md
Move dataset to zenodo for non-dip variant calling.
https://github.com/galaxyproject/training-material/issues/672
=> non-dip variant calling zenodo

topics/chip-seq/tutorials/estrogen-receptor-binding-site-identification/tutorial.md
=> Fix effective genome size for MACS2 callpeak (estrogen tutorial - Chip-seq)

topics/admin/slides/introduction.html
I do not know how to link relatively here.
Also a slide is inserted with a link to 'Related tutorials' (https://github.com/galaxyproject/training-material/blob/master/topics/admin/tutorials/dev-to-production/tutorial.md) that is incomplete and shouldn't be linked I think
=> fix links in admin intro slides

topics/contributing/tutorials/create-new-topic/tutorial.md
New topics also need the default index.md file to have the new topic's name. (Issue faced in the GCCBOSC2018 workshop)
=> Update tutorial to include changing index.md

topics/dev/tutorials/conda/slides.html
Right now it looks like this: 
And a bunch of the following slides are unviewable. But this fix is just a guess as to what's wrong (I'm using the PR to build the slides to test).
=> Attempt to fix slide render problem with Tool Deps and Conda slides

_layouts/topic.html, topics/dev/metadata.yaml
I noticed that this page https://galaxyproject.github.io/training-material/topics/dev/ had an empty item at the bottom so added support for usernames without a `name` field attached to it. Probably not necessary to do that since everyone has a `name:` but it made tracking down the underlying metadata issue a bit easier.
=> Allow usernames without names

topics/sequence-analysis/metadata.yaml
Added the QCFAIL blog entry in the References. This would be the result:
=> added QCFAIL blog link

topics/assembly/metadata.yaml, topics/assembly/tutorials/ecoli_comparison/data-library.yaml, topics/assembly/tutorials/ecoli_comparison/tutorial.md
Replacement of zenodo link by a zenodo repo that contains only the dataset necessary for the training. The previous Zenodo repo contains also the raw data, too big for the import.
=> Replacement of zenodo link 

_layouts/base_slides.html, assets/css/slides.css
fixes https://github.com/galaxyproject/training-material/issues/825
adds a link back to the topic page to all slides
=> Add a back/up button to slides

topics/admin/tutorials/ansible/tutorial.md
Figured this might be useful to provide some heuristics for choosing a role. E.g. trying to find the right one from [these](https://galaxy.ansible.com/search?vendor=false&keywords=telegraf&order_by=-relevance&page_size=10) or [these](https://galaxy.ansible.com/search?vendor=false&keywords=rabbitmq&order_by=-relevance&page_size=10) is not trivial.
=> Ansible: add note about choosing a role

.yamllint
To avoid error with automatically generated content
=> Make yamllint less strict for indentation

.yamllint
no longer fail the travis test due to trailing spaces in yaml files
=> yamllint: don't fail on trailling whitespace

_config.yml, _includes/default-header.html, _layouts/badges.html, _layouts/faq.html, _layouts/hall-of-fame.html, _layouts/home.html, _layouts/topic.html, _layouts/tutorial_hands_on.html, snippets/add_tag.md, snippets/change_datatype.md, snippets/import_from_data_library.md, snippets/import_via_link.md, topics/transcriptomics/tutorials/ref-based/tutorial.md
With this PR, it is possible to share some parts between different tutorials.
For example here in the ref-based tutorial, the boxes to explain how to import from link, from data library or how to add tags are now in a file in the `_includes` folder. We can then add the same box (without duplicating the text) in other tutorial.
We can even have variables, like `datatype` in the example (`{% include _includes/change_datatype.md datatype="fastqsanger" %}`)
We can even go further. I started for the ChIP-seq tutorial to add some sections that could be in `topics/sequence-analysis/tutorials/mapping`, e.g: 
```
{% include topics/sequence-analysis/tutorials/mapping/mapping_explanation.md
to_identify="binding sites"
mapper="Bowtie2"
mapper_link="http://bowtie-bio.sourceforge.net/bowtie2/index.shtml …
```
=> Add possibility of shared parts inside tutorials

_config.yml
To avoid emails from GitHub like:
```
The page build failed for the `gh-pages` branch with the following error:
The tag `icon` on line 2 in `snippets/add_tag.md` is not a recognized Liquid tag. For more information, see https://help.github.com/articles/page-build-failed-unknown-tag-error/.
For information on troubleshooting Jekyll see:
https://help.github.com/articles/troubleshooting-jekyll-builds
If you have any questions you can contact us by replying to this email.
```
=> Add nojekyll file to avoid GitHub page to try to build

_layouts/tutorial_hands_on.html, assets/css/main.scss
To solve #981, a feedback form can be embedded at the bottom of the tutorial (with the tutorial name already filled):
There is 2 issues with the current implementation:
- I can not get rid of the header of the form (previous screenshot)
I tried to play with it both on Google form side and CSS. But no way to get rid of it. I think we will keep it this way
- When leaving the page, a pop up box open with "This page is asking you to confirm that you want to leave - data you have entered may not be saved" (on Firefox)
@willdurand any idea?
=> Embed a short feedback form at the bottom of the tutorial

_layouts/tutorial_hands_on.html
on the top of a tutorial if there is a `slides.html` associated to the `tutorial.md`
=> Make associated slides display and not introduction slides

topics/introduction/tutorials/galaxy-intro-ngs-data-managment/tutorial.md
This should address #1017 for this tutorial and move the formatting in line with Markdown standards as described in the [Markdown tutorial](http://galaxyproject.github.io/training-material/topics/contributing/tutorials/create-new-tutorial-content/tutorial.html).
=> Replace <div> elements with comment blocks

_layouts/base_slides.html, _layouts/topic.html
Links to internal training material, pointed to by entries in the "Requirements" section of many training's slides, were broken. This fixes the issue.
Example:
In the Quality control slides, [page #2](https://galaxyproject.github.io/training-material/topics/sequence-analysis/tutorials/quality-control/slides.html#2) links to the required introductory material using the following link
`https://galaxyproject.github.io/training-material/introduction/`
instead of
`https://galaxyproject.github.io/training-material/topics/introduction/`
=> fixed links to section requirements within all slides

_layouts/base_slides.html
Thanks @nsoranzo, found in https://github.com/galaxyproject/training-material/pull/1019.
Also fixes favicon in slides.
As part of testing I noticed that the magic metadata stuff introduced in https://github.com/galaxyproject/training-material/pull/966 is broken with `--incremental`. Neat. It looks like `page.topic_name` is not set on subsequent incremental runs.
=> Fix a couple broken links

topics/proteomics/tutorials/database-handling/tutorial.md
Removed append parameter from decoy database. There is no such a parameter in version 2.2 or 2.3.
Default parameters can be used.
=> Removed non existing "append" parameter

topics/proteomics/tutorials/protein-id-oms/tutorial.md
Point 3 and 4 were redundant, therefore Point 3 was removed.
Select tool was changed to the whole name to avoid misunderstandings, Point 4 was described more clear.
Questions are still valid and do not need further adaptions.
=> Hands-on Analysis of Contaminants was made less confusing

topics/dev/tutorials/toolshed/slides.html
Noticed that slides were failing due to `toolshed.g2.bx.psu.edu/&quot;`, trying with a `#` after it to see if I can get the slides checker to pass
Please do not merge until after slide check has run.
=> test fixing a couple urls

topics/transcriptomics/tutorials/network-analysis-with-heinz/tutorial.md
one broken link slipped through before we had the new test in place, this fixes it
=> Heinz: remove broken link to unneeded image

topics/sequence-analysis/tutorials/quality-control/tutorial.md
Here's a little PR to:
- remove last traces of trim galore (was replaced with cutadapt earlier)
- fix 2 little typos
=> Quality control: fix typos

topics/transcriptomics/tutorials/ref-based/tutorial.md
the zenodo urls had some leading spaces causing upload to fail if copy-pasted as-is
=> Ref-based RNA-seq: fix leading spaces in URLs

_layouts/home.html
It looks like #1086 was because of the lack of a trailing slash. I'm not sure why that caused the insecure redirect, but it's an easy fix.
First few requests are normal, last request is after going back to index and manually editing link.
=> Fixes #1086

Makefile, _config.yml, _layouts/base.html, _layouts/base_slides.html
@martenson I think this should work to prevent people who spin up a dev instance from using our ga ID, we set an environment variable in travis and use the [jekyll-environment-variables plugin](https://github.com/ajwhite/jekyll-environment-variables)
xref: https://github.com/galaxyproject/training-material/pull/1100
=> [martenson-patch-3] Google analytics ID via travis variable

topics/transcriptomics/tutorials/ref-based/tools.yaml
The only use of `length_and_gc_content` tool was removed in commit e15717d8ad7ed9d20578c0d3808e29cad3efd691 .
=> Update tools.yaml for ref-based tutorial

_config.yml, topics/contributing/tutorials/create-new-tutorial-content/tutorial.md
While reviewing a PR that included a tool with a lot of repeat parameters, I thought it would be a lot clearer if these are prefixed with a `plus` icon, as they are in Galaxy:
so I added such an icon
=> Add an icon for repeat parameters

_config.yml, _layouts/topic.html, _layouts/tutorial_hands_on.html, assets/css/main.scss
To fix (at least partially): #404 
A dropdown menu to select the language is added in the topic menu and on the top of the tutorial:
The non english links redirect to Google translate. The hands-on boxes are not translated.
=> Add translation support

topics/genome-annotation/tutorials/annotation-with-maker/tutorial.md
Just a little typo in the first phrase of the maker tutorial.
The funny thing is that when google translates (with the typo) it in french, it becomes exactly the opposite of what I meant (_less_ complicated instead of more complicated)
=> Maker: fix typo

topics/transcriptomics/tutorials/ref-based/tutorial.md
the box with zenodo urls had some leading spaces when rendered, causing upload to fail if copy-pasted directly from the tutorial.
=> fix leading spaces

snippets/import_from_data_library.md
in my last workshop it wasn't immediately clear to a lot of the participants that this was an *alternative* to the url import rather than something they had to do *in addition*. And the instructions were a bit out of sync with the new data library UI
=> Data library import snippet: update instructions

Makefile, _config.yml, _layouts/topic.html, _layouts/tutorial_hands_on.html, assets/css/main.scss, bin/validate-frontmatter.rb, snippets/display_extra_training.md, topics/assembly/metadata.yaml, topics/assembly/tutorials/ecoli_comparison/tutorial.md, topics/assembly/tutorials/unicycler-assembly/tutorial.md, topics/chip-seq/metadata.yaml, topics/chip-seq/tutorials/tal1-binding-site-identification/tutorial.md, topics/contributing/tutorials/create-new-topic/tutorial.md, topics/contributing/tutorials/create-new-tutorial-content/tutorial.md, topics/epigenetics/metadata.yaml, topics/genome-annotation/metadata.yaml, topics/metagenomics/metadata.yaml, topics/proteomics/metadata.yaml, topics/sequence-analysis/metadata.yaml, topics/sequence-analysis/tutorials/mapping/tutorial.md, topics/sequence-analysis/tutorials/quality-control/tutorial.md, topics/statistics/metadata.yaml, topics/transcriptomics/metadata.yaml, topics/variant-analysis/metadata.yaml
This PR implements the possibility to display possible follow-up tutorials at the end of a tutorial:
I also restructured the requirements on the top of the tutorials and in the topic page:
To support that, the description of requirements in metadata has been adapted and is harmonized with follow-up training description:
```
requirements:
-
type: "internal"
topic_name: sequence-analysis
tutorials: 
- quality-control
follow_up_training:
-
type: "internal"
topic_name: transcriptomics
tutorials: 
- ref-based
-
type: "internal"
topic_name: chip-seq
tutorials: 
- formation_of_super-structures_on_xi
```
=> Support learning paths

topics/metabolomics/metadata.yaml
update metadata after changes introduced to support learning paths (https://github.com/galaxyproject/training-material/pull/1149) (to fix failing links)
=> Metabolomics: update requirements metadata format

topics/metagenomics/tutorials/mothur-miseq-sop/tools.yaml
since we moved the newick display tool to iuc
ping @erasche this should result in GalaxyEU being identified as a supporting server :)
=> mothur miseq sop: update tool list

bin/add_galaxy_instance_annotations.py
@shiltemann and I were wondering why EU was marked as not supporting her mothur miseq tutorial. I've updated the annotation generation script to support checking a single server:
```console
$ python bin/add_galaxy_instance_annotations.py \
--server https://usegalaxy.eu --verbose
...
DEBUG:root:MISSING:none:metagenomics/mothur-miseq-sop: toolshed.g2.bx.psu.edu/repos/dcorreia/newick_display
...
```
And can easily see that this tool should have its ID updated to the new IUC tool. (Or we can find out other things we're missing to support different trainings.)
=> Allow checking specific servers for inability to support a training

topics/admin/tutorials/reports/tutorial.md
These are way too easy to miss, I wonder if there is a way Jekyll can complain about undefined variables.
=> Escape template sections

topics/transcriptomics/tutorials/ref-based/tutorial.md
The ref-based RNA-Seq [hands-on](https://galaxyproject.github.io/training-material/topics/transcriptomics/tutorials/ref-based/tutorial.html) tutorial shows the heatmap2 (2.2.1) tool, and set its "Advanced - log transformation" parameter. However, [the parameter gets renamed in the latest version (2.2.1+galaxy1) as "Data transformation"](https://github.com/galaxyproject/tools-iuc/issues/2274). Since the last version is the one that gets shown by default, I propose to provide both parameter labels in the tutoral
=> updated heatmap2 field label

.travis.yml, _config.yml, _layouts/topic.html, _layouts/tutorial_hands_on.html, bin/publish-archive, faq.md, topics/contributing/tutorials/create-new-topic/tutorial.md, topics/dev/tutorials/visualization-generic/tutorial.md, topics/instructors/tutorials/setup-galaxy-for-training/tutorial.md
This adds a script which will check out all git tags in the repo and automatically build them if they haven't previously been built.
The results are stored http://galaxy-training.s3-website.us-east-1.amazonaws.com/ which will be proxied in the near future, so it will become something like:
```
training.galaxyproject.org/<normal website>
training.galaxyproject.org/archive/2019-01-01/<archived website>
```
Tags are fairly lightweight and easy to add as needed per-training or per-month. I propose that it is done automatically per-month, but this will be done in a separate PR. I have added an experimental tag that will show up when this is merged.
The versions currently on the S3 bucket are built from the tags in my fork and will disappear when we merge this.
=> Automatic archival builds of repository tags

Makefile, _config.yml, _layouts/base.html, _layouts/tutorial_hands_on.html, bin/publish-archive, topics/admin/tutorials/tool-management/tutorial.md, topics/dev/tutorials/interactive-tours/slides.html, topics/dev/tutorials/webhooks/slides.html, topics/instructors/tutorials/setup-tiaas-for-training/tutorial.md, topics/introduction/README.md, topics/proteomics/tutorials/database-handling/workflows/readme.md, topics/proteomics/tutorials/protein-id-sg-ps/workflows/readme.md, topics/transcriptomics/README.md
Training material will now be accessible from https://training.galaxyproject.org/ with /topics directly from the root. This is currently partially live, in an attempt to cause the minimum amount of disruption.
I've coded the assets to use the full site url so the old github pages will still render correctly. If this wasn't done, the assets would attempt loading from `/assets` instead of `/training-material/assets` and be unavailable and break.
I've also fixed some other incorrect uses of site.url instead of site.baseurl, one from an admin tuto that would break if you ran the command.
Lastly moves archive index page into /archive so that will load properly too.
With this PR merged, everything should be done, https://training.galaxyproject.org/ should have all content and browsing around on …
=> Update for proxying

topics/epigenetics/tutorials/hicexplorer/tutorial.md
The sentence is linking to dm6_genes.bed, which is not required below (as far as I understood). It also points to a different zenodo repository, than the one mention at the beginning
=> small fix in HiCExplorer tutorial

_config.yml, _includes/default-header.html, _layouts/base_slides.html, _layouts/tutorial_hands_on.html, assets/css/main.scss
Because this project is only possible because of the contributions of this awesome community, @erasche and I thought they should be credited more prominently, and added an author line below the tutorial title:
The names link to the hall-of-fame entry for the contributor (did same in slides)
Also added a link to the contributor hall of fame on the main page nav bar:
=> Highlight contributors more prominently throughout the site

topics/admin/tutorials/ansible-galaxy/galaxyservers.txt, topics/admin/tutorials/ansible-galaxy/tutorial.md
I should not have included that originally, of course users would copy and paste it.
=> Remove email address from admin tuto

topics/chip-seq/tutorials/formation_of_super-structures_on_xi/workflows/formation_of_super_structures_on_xi.ga, topics/genome-annotation/tutorials/annotation-with-maker/workflows/main_workflow.ga, topics/introduction/tutorials/galaxy-intro-short/workflows/Galaxy-Workflow-galaxy-intro-short.ga, topics/introduction/tutorials/galaxy-intro-strands/workflows/Galaxy-Workflow-galaxy-intro-strands-2.ga, topics/introduction/tutorials/galaxy-intro-strands/workflows/Galaxy-Workflow-galaxy-intro-strands.ga, topics/metabolomics/tutorials/msi-analyte-distribution/workflows/main_workflow.ga, topics/proteomics/tutorials/mass-spectrometry-imaging-loading-exploring-data/workflows/ms_imaging_loading_exploring_data.ga, topics/proteomics/tutorials/proteogenomics-dbcreation/workflows/galaxy-workflow-mouse_rnaseq_dbcreation.ga, topics/proteomics/tutorials/proteogenomics-dbsearch/workflows/galaxy-workflow-mouse_rnaseq_dbsearch.ga, topics/proteomics/tutorials/proteogenomics-novel-peptide-analysis/workflows/galaxy-workflow-mouse_novel_peptide_analysis.ga, topics/sequence-analysis/tutorials/de-novo-rad-seq/workflows/Galaxy-Workflow-de-novo-rad-seq.ga, topics/sequence-analysis/tutorials/ref-based-rad-seq/workflows/Galaxy-Workflow-Workflow_constructed_from_history__STACKS_RAD__population_genomics_with_reference_genome_.ga, topics/sequence-analysis/tutorials/ref-based-rad-seq/workflows/workflow.ga, topics/statistics/tutorials/classification_regression/workflows/GradientBoostingRegression_TutorialWorkflow.ga, topics/statistics/tutorials/classification_regression/workflows/LinearSupportVectorClassifier_TutorialWorkflow.ga, topics/statistics/tutorials/iwtomics/workflows/IWTomics_Workflow.ga, topics/transcriptomics/tutorials/clipseq/workflows/init_workflow.ga, topics/transcriptomics/tutorials/de-novo/workflows/transcriptomics-denovo-workflow.ga, topics/transcriptomics/tutorials/goenrichment/workflows/goenrichment-workflow.ga, topics/transcriptomics/tutorials/rna-seq-genes-to-pathways/workflows/rna-seq-genes-to-pathways.ga, topics/transcriptomics/tutorials/rna-seq-reads-to-counts/workflows/rna-seq-reads-to-counts.ga, topics/transcriptomics/tutorials/scrna-raceid/workflows/main_workflow.ga, topics/transcriptomics/tutorials/scrna_preprocessing/workflows/scrna_mp_celseq.ga, topics/variant-analysis/tutorials/dunovo/workflows/dunovo.ga, topics/variant-analysis/tutorials/dunovo/workflows/variant-calling.ga
Changed all oneline workflows to the unflattened JSON one using 
```
cat wf.ga | jq . -S > out.ga
```
from https://github.com/usegalaxy-eu/workflow-testing
This way small changes to the workflow can be easily compared.
=> Unflattened one-line workflows

topics/transcriptomics/tutorials/de-novo/tours/tour.yaml
Seems there is a _ between repX and forward/reverse missing!
Working:
https://zenodo.org/record/583140/files/G1E_rep1_forward_read_%28SRR549355_1%29?download=1
Currently not working:
https://zenodo.org/record/583140/files/G1E_rep1forward_read%28SRR549355_1%29
=> Fix of broken zenodo links for tour data

Makefile
> miniconda changed, not dropping the slash, just now has an additional folder named condabin, which contains just the executable conda, and the rest like activate are still in regular bin folder
solution finally figured out by @shiltemann <3
Apparently makefile doesn't have a parent directory function (and everything online just implements their own), so shelling out.
=> Try to fix makefile

_layouts/topic.html, _plugins/colour-tags.rb
Imports the same algorithm\* that I used for [colour tags in Galaxy](https://github.com/galaxyproject/galaxy/pull/7072), for similar reasons (distinguishing similar tags).
\* = there's a proper hash function in ruby so used that instead; I made the colours a bit lighter here to be less intrusive
=> Import colour tags from Galaxy

environment.yml
Fixes warning during `make create-env`
=> Add pip as requirement in environment.yml

_includes/contributor-badge-list.html, _includes/contributor-badge.html, _layouts/base_slides.html, _layouts/topic.html, _layouts/tutorial_hands_on.html, assets/css/slides.css
Slides and topics now use the same icon+name, as in the byline of the tutorials.
=> Standardise contributor lists everywhere

.travis.yml, bin/publish-archive
I don't know what I was thinking with the original implementation. It's clearly written like it's meant to be run on a cron job somewhere, and that's not the case here. Travis gets notified of new tags, and builds those, so all of my concerns with "tagging stuff that's too old because travis does shallow clones" goes away completely.
I've scrapped most of the publish-archive, it should be much simpler now, just builds the current version if it's building a git tag.
=> Fix archival builds

topics/galaxy-data-manipulation/tutorials/collections/tutorial.md
because that is a library, not a history.
=> history to library label in collections tutorial

_includes/instance-dropdown.html, _includes/resource-handson.html, _includes/resource-slides.html, _includes/resource-tours.html, _includes/resource-workflows.html, _includes/resource-zenodo.html, _layouts/topic.html, _layouts/tutorial_hands_on.html, assets/css/main.scss
Per discussion in #1389 it was discussed that a number of items could be moved to the overview box, which would give us some more room in the header for things in the future. (E.g. search box more nicely integrated.)
I thought about a two column layout (for large screens) but haven't really tested that yet.
=> Move header items to overview box

_layouts/tutorial_hands_on.html
Because *of course* an empty string is truthy.
Fixes cases like:
Thanks for the report @shiltemann
=> Handle zenodo_link: "" case

topics/admin/tutorials/ansible-galaxy/tutorial.md, topics/admin/tutorials/ansible/slides.html, topics/admin/tutorials/ansible/tutorial.md
And some small fixes to the ansible-galaxy tutorial.
=> Ansible:  consistently use "inventory" file instead of "hosts"

bin/add_galaxy_instance_annotations.py
The list of public Galaxy servers was moved to the hub, this updates the annotation script to get the list from new location.
ping @erasche
=> Fix for Galaxy server annotation

topics/admin/tutorials/ansible/tutorial.md
It seems the examples for running ansible on a remote machine vs localhost were swapped. The "You are installing ansible on a machine that will manage a second, remote machine" part listed using the `localhost ansible_connection=local` option.
=> Swap examples for localhost vs remote machine

topics/admin/tutorials/uwsgi/slides.html
It may be clearer to have the installation command in its own line ("pip" at the end of the row may be missed by readers)
=> Formatting of installation command

topics/admin/tutorials/ansible-galaxy/tutorial.md
Less confusing wording for the templates. That main level directory was never mentioned before (and problably it does not exists). Also, these templates could go into the `galaxyproject.nginx` role, but it may be too confusing so it's better to avoid mentioning that here.
=> Nginx templates should be in the main directory

topics/admin/tutorials/ansible-galaxy/tutorial.md
As opposed to other values, miniconda_prefix must be in double quotes (as the solution shows), otherwise the user gets an error.
=> Miniconda prefix must be in double quotes

_layouts/base_slides.html, assets/css/slides.css
@erasche implemented awesome copy functionality for code blocks in tuturials in https://github.com/galaxyproject/training-material/pull/1383, this does the same for slides, which could be useful for admin/dev slides that have hands-on assignments in slides
=> add copy functionality for code blocks on slides

topics/sequence-analysis/tutorials/mapping/tutorial.md
There is a QC step at the beginning of the mapping tutorial. We discussed @erasche, @shiltemann and others to remove it and link to the QC tutorial instead to then avoid duplications.
We also plan to expand the QC tutorial with more explanations about the different outputs to FastQC and things expected given the different sequencing technologies
=> Remove QC step from mapping tutorial and refer to QC tutorial

CODEOWNERS, topics/chip-seq/metadata.yaml, topics/transcriptomics/metadata.yaml
We created GitHub teams for the maintainers of each topic (thanks @martenson & @erasche!). Adding them in CODEOWNERS file for automatic review requests to this team whenever changes are made to their topic. 
All maintainers should now also have the ability to approve and merge pull requests (and please feel free to do so for your topic!)
ping @galaxyproject/training 
P.S. Please let us know if you are no longer able to be a maintainer for a topic (or if you would like to volunteer to become a maintainer)
=> Add maintainer teams as codeowners

CODEOWNERS
the trailing `*` only matches files directly in the folder, while intended match was any files in any subfolders
=> CODEOWNERS: update to include subfolders

.travis.yml, bin/add_galaxy_instance_badges.py, bin/make_release.py
@erasche set up the infrastructure to automatically create [archives of the website](https://training.galaxyproject.org/archive/) every time we create a release. This PR creates a release and archive build during our monthly travis cron job 
WIP til @erasche can test it for me, thanks!
=> Automatic monthly releases (and archive builds)

_includes/tutorial_list.html
To fix the display of the first line (Introduction) in topics:
And also remove the line extension if no Galaxy instances:
=> Fix topic table display for introduction slides

topics/metabolomics/tutorials/lcms/tutorial.md
In the hands on section of **Reducing the dataset to keep ions of interest only** the `Sample metadata file` is set to `Generic_Filter_Batch_correction_linear_dataMatrix.tsv`.
This results in an error. 
Should it instead be: 
`Generic_Filter_Quality Metrics_sampleMetadata_completed.tsv`?
This results in no error.
=> Fixed an incorrect input data file error in Generic Filter section

.travis.yml
When our travis jobs are assigned a xenial machine, the wrong version of ruby was being picked up in the tests (e.g. like in https://github.com/galaxyproject/training-material/pull/1527) this appears to fix that
=> travis: use language: ruby

.travis.yml
The monthly cron job deployed to gh-pages, because that task was second. I've moved it to be first so that the proper version gets deployed to gh-pages before the custom version is built in `bin/publish-archive`.
=> Fix build ordering

Makefile
It's not [necessarily guaranteed](https://stackoverflow.com/questions/1647480/in-what-order-prerequisites-will-be-made-by-the-gnu-make) what the ordering will be.
Some of the dependencies depend on `build`, others do not. The `check-frontmatter` does not depend on build, and catches errors that can kill the build. So if another task is executed first (depending on build), and fails to build, the user will never see the useful error message. This ensure that that never happens, and that they're executed in safe order.
=> Force ordering of linting

Gemfile, Gemfile.lock, Makefile
Jekyll has been updated 2 days ago to version 4.0.0. Some changes will be interested for us. But some of the external plugins we are using are incompatibles (e.g. `jekyll-environment-variables`) and then `jekyll serve` is not working (locally and on Travis).
This PR fixes Jekyll to the previous version
The nokogiri version in the Gemfile.lock was reported as a potential security vulnerability. I updated it
=> Fix jekyll version & update nokogiri version

_layouts/topic.html, _layouts/tutorial_hands_on.html, bin/schema-topic.yaml, topics/admin/metadata.yaml, topics/contributing/tutorials/create-new-topic/tutorial.md, topics/dev/metadata.yaml
This embeds the admin and dev chat channels on their respective tutorial and topic pages, to provide better support to people attempting the tutorials.
=> Add gitter sidecar for admin/dev topics

bin/add_galaxy_instance_badges.py
Jekyll is currently failing on master for `make annotate` for badge creation. Indeed, if there is a `/` in the tutorial title, it will be added in the path where to create the badge:
```
badges/cache/Annotating%20a%20protein%20list%20identified%20by%20LC--MS/MS%20experiments-Supported-green.svg: No such file or directory
Traceback (most recent call last):
File "bin/add_galaxy_instance_badges.py", line 175, in <module>
CACHE_DIR, (instance, topic, training), args.output
File "bin/add_galaxy_instance_badges.py", line 77, in badge_it
), CACHE_DIR)
File "bin/add_galaxy_instance_badges.py", line 65, in realise_badge
subprocess.check_call(cmd)
File "/home/travis/miniconda3/envs/galaxy_training_material/lib/python3.6/subprocess.py", line 291, in check_call
raise CalledProcessError(retcode, cmd) …
```
=> Replace / in badge labels and values

topics/transcriptomics/tutorials/scrna-preprocessing-tenx/tutorial.md
- The axis were named wrongly in the package description ( see also: https://github.com/MarioniLab/DropletUtils/issues/22)
- once you have selected  "Ranked Barcodes", you cannot select  Method:EmptyDrops
=> fixes to Introspective Method

topics/variant-analysis/tutorials/exome-seq/tutorial.md, topics/variant-analysis/tutorials/exome-seq/workflows/workflow_exome_seq_from_premapped.ga, topics/variant-analysis/tutorials/exome-seq/workflows/workflow_exome_seq_full.ga, topics/variant-analysis/tutorials/somatic-variants/tutorial.md
Different possibilities for filtering BAM reads get explained in
detail now in the exome-seq and somatic variants tutorials.
Dysfunctional usage of gemini annotate has been eliminated from the
somatic variants tutorial.
=> Update variant analysis tutorials

topics/sequence-analysis/tutorials/mapping/slides.html
During our workshop last week we noticed one of the links was broken. Replaced it with another resource (thanks for finding it @erasche!)
=> Mapping: update broken link in slides

_includes/contributor-author-list-comma.html, _includes/contributor-author-list.html, _layouts/tutorial_hands_on.html
This adds a box which helps users cite the tutorial + training material. the urls should be correct when deployed.
Hopefully it will make it easier for users to find the proper citations.
=> Add citation to every tutorial page

assets/js/main.js
I don't use a mouse normally, for navigating the web, I use my keyboard. This change makes those clickable for me, and should improve the accessibility a little bit. xref https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/button_role
Note the `G` over the plus vs the one below (manually edited HTML for the screenshot).
=> This behaves like a toggle button so mark the role

Makefile, bin/check-broken-boxes, topics/computational-chemistry/tutorials/analysis-md-simulations/tutorial.md, topics/computational-chemistry/tutorials/md-simulation-gromacs/tutorial.md, topics/computational-chemistry/tutorials/setting-up-molecular-systems/tutorial.md, topics/contributing/tutorials/create-new-topic/tutorial.md, topics/contributing/tutorials/create-new-tutorial/tutorial.md, topics/ecology/tutorials/de-novo-rad-seq/tutorial.md, topics/ecology/tutorials/genetic-map-rad-seq/tutorial.md, topics/ecology/tutorials/regionalGAM/tutorial.md, topics/ecology/tutorials/species-distribution-modeling/tutorial.md, topics/epigenetics/tutorials/atac-seq/tutorial.md, topics/galaxy-data-manipulation/tutorials/upload-rules/tutorial.md, topics/galaxy-ui/tutorials/history-to-workflow/tutorial.md, topics/genome-annotation/tutorials/annotation-with-maker/tutorial.md, topics/genome-annotation/tutorials/genome-annotation/tutorial.md, topics/instructors/tutorials/setup-galaxy-for-training/tutorial.md, topics/introduction/tutorials/galaxy-intro-101/tutorial.md, topics/introduction/tutorials/galaxy-intro-strands/tutorial.md, topics/metabolomics/tutorials/lcms/tutorial.md, topics/statistics/tutorials/iwtomics/tutorial.md, topics/statistics/tutorials/machinelearning/tutorial.md, topics/transcriptomics/tutorials/clipseq/tutorial.md, topics/transcriptomics/tutorials/goenrichment/tutorial.md, topics/transcriptomics/tutorials/rna-seq-reads-to-counts/tutorial.md, topics/transcriptomics/tutorials/scrna-scater-qc/tutorial.md, topics/variant-analysis/tutorials/exome-seq/tutorial.md, topics/variant-analysis/tutorials/non-dip/tutorial.md
This PR implements a makefile target which checks that in every enabled tutorial:
- There are no blockquotes without classes (commonly caused with accidental line breaks in the middle of a hands on that isn't noticed)
- There are no blockquotes with unexpected/wrong classes (e.g. typos)
This is added as a mandatory travis test. To make it more pleasant for contributors, it attempts to locate the usage of the broken box and greps for context to help users to locate the issue.
In a pretend world where the matrix class didn't exist, this will show the relevant source code and files.
I've fixed many boxes in existing tutorials, and changed some usages to be more correct.
**Edit** maintainers were pinged due to changes to tutorials to bring them into compliance.
=> Broken box detection

_includes/tutorial_list.html, _plugins/jekyll-jsonld.rb
- Remove it from topics, just on tutorials, no more duplication
- Remove some of the extra fields that aren't being consumed or used (e.g. workflows are just Things, if we had a better class for them maybe it would be worth it, but since no one is going to consume then just useless a bit)
- Hardcode URL since we want going through the right site
=> Cleanup json ld for tess

topics/admin/docker/Dockerfile, topics/assembly/docker/Dockerfile, topics/computational-chemistry/docker/Dockerfile, topics/contributing/docker/Dockerfile, topics/dev/docker/Dockerfile, topics/ecology/docker/Dockerfile, topics/epigenetics/docker/Dockerfile, topics/genome-annotation/docker/Dockerfile, topics/imaging/docker/Dockerfile, topics/introduction/docker/Dockerfile, topics/metabolomics/docker/Dockerfile, topics/metagenomics/docker/Dockerfile, topics/proteomics/docker/Dockerfile, topics/sequence-analysis/docker/Dockerfile, topics/statistics/docker/Dockerfile, topics/transcriptomics/docker/Dockerfile, topics/variant-analysis/docker/Dockerfile
I've experienced some problems with the latest galaxy container which were not present in version 19.01. For example the `galaxy-wait -g $galaxy_instance` is not available. To overcome problems like this in the future, I suggest that we increase the galaxy docker version manually after testing. Although this is maybe not feasible long term, it will decrease the amount of problems with building the containers... I am now testing all the containers one by one using docker version 19.01 :
Future plans:
Having the possibility to build the container with all the data libraries like we did in the past, but as an option with for example a -data flag. This to enable the use-case of @TKlingstrom
=> Docker update

topics/admin/tutorials/ansible/tutorial.md
(1) escape `apikey = {{ apikey }}` with `{% raw %}` tags (this was showing up in the tutorial as `apikey = ` )
(2) enable ansible to find the secret variable file and the password file.
=> fix ansible-vault exercise in ansible tutorial

topics/genome-annotation/tutorials/genome-annotation/tutorial.md
Given [suboptimal feedback](https://github.com/galaxyproject/training-material/issues/989#issuecomment-565807493) temporarily disable until it can be updated to current standards, and potentially split into tutorials for how to use each subcomponent.
=> Temporarily disable GA tutorial pending updates

_plugins/jekyll-figurify.rb
Previously if you scaled an image with a caption like this:
```markdown
```
the caption did not get rendered, this should fix that
ping @erasche can you check if this looks ok?
=> support captions on scaled images

topics/computational-chemistry/tutorials/cheminformatics/workflows/main_workflow.ga, topics/contributing/tutorials/create-new-tutorial/workflows/example-workflow.ga, topics/epigenetics/tutorials/estrogen-receptor-binding-site-identification/workflows/chip_seq.ga, topics/epigenetics/tutorials/estrogen-receptor-binding-site-identification/workflows/qc_mapping.ga, topics/epigenetics/tutorials/ewas-suite/tours/tour.yaml, topics/epigenetics/tutorials/formation_of_super-structures_on_xi/workflows/formation_of_super_structures_on_xi.ga, topics/introduction/tutorials/galaxy-intro-101-everyone/workflows/main_workflow.ga, topics/proteomics/tutorials/database-handling/workflows/wf_database-handling.ga, topics/proteomics/tutorials/database-handling/workflows/wf_database-handling_mycoplasma.ga, topics/proteomics/tutorials/ntails/workflows/WF_ntails.ga, topics/proteomics/tutorials/protein-id-sg-ps/workflows/wf_proteinID_SG_PS.ga, topics/proteomics/tutorials/protein-id-sg-ps/workflows/wf_proteinID_SG_PS_multipleFiles.ga, topics/proteomics/tutorials/proteogenomics-dbcreation/workflows/galaxy-workflow-mouse_rnaseq_dbcreation.ga, topics/proteomics/tutorials/secretome-prediction/workflows/WF_secretomePrediction_goWolfpsort.ga, topics/sequence-analysis/tutorials/mapping/workflows/mapping-jbrowse.ga, topics/visualisation/tutorials/circos/workflows/main_workflow.ga
Multiple tools were not detected by ephermeris 'workflow-to-tools'. It turned out that this was caused by the lack of a "tool_shed_repository" key in the step of the workflow. I made a script that detects and fixes these problems where possible. I am still trying out the workflows for a manual check, but the results seem already promising.
- Added tool_shed_repository keys were possible in following workflows:
-> CTB workflow
-> Find Exons with the highest number of SNPs (or other features)
-> Database Handling Tutorial Workflow2 including Mycoplasma
-> Database Handling Tutorial Workflow
-> tails triple dimethyl OpenMS2.1
-> ProteinID_SG_PS_Tutorial_WF_datasetCollection
-> Peptide and Protein ID Tutorial
-> Secreted Proteins via GO annotation and WoLF PSORT for shCTSB paper ( …
=> Fixing multiple workflows

topics/sequence-analysis/tutorials/mapping/tutorial.md
Just a fix for a little mistake in the mapping tutorial: there is no (longer?) a Trim Galore step before using bowtie2.
=> Mapping tutorial: remove reference to trim galore

topics/metagenomics/tutorials/plasmid-metagenomics-nanopore/tutorial.md
at GCC this tutorial caused some issues when there were a lot of participants. To reduce the number of jobs generated, I cut the number of files in half, using only those that are explicitly mentioned in the tutorial (e.g. in questions or explanations)
ping @willemdek11 can you have look to see if this is ok?
=> [Antibiotic Resistance Detection] use fewer input files

assets/css/main.scss
Hi, not sure how this happened.
The `matrix-table` mixin class is defined twice, same parameters and everything.
=> Fix to SCSS: Duplicate Matrix definition

bin/check-contributors.rb
Wrote this as a break between papers, it will check the git log of a given file for the contributors which could be missing.
There is commonly the case of a user using multiple emails, and so this script can read from a local map of emails → usernames.
We could just add these extra emails to the yaml file, but given my personal perspective on the issue, I think maybe it's fine just to have a local map since not so many people might be running this to find missing contributors. (E.g. I know if I have old emails addresses that were included as commits, I'm not sure I want those in a more public contributors.yaml file and I'm sure I'm not alone.)
@bebatut
=> Add script to check contributors

LICENSE.md, README.md, _includes/default-footer.html, _includes/license.html, _layouts/base_slides.html, _layouts/home.html, _layouts/tutorial_hands_on.html
Someone asked lately if he could reuse the infrastructure and scripts. We realized that the current LICENSE (CC-BY) is not covering that.
So here I changed the LICENSE file to MIT and made sure that CC-BY 4.0 (for content) is mentioned on the README, home page, FAQ.
Hopefully we can get the explicit approval of all the contributors.
=> LICENSE update: Add MIT license for infrastructure / scripts

topics/transcriptomics/tutorials/scrna-scanpy-pbmc3k/tutorial.md
when I select 'No' the tool fails,
and when I select 'Yes' I can reproduce the figure
=> fix "Clustering 3K PBMCs with Scanpy"

topics/admin/tutorials/ansible-galaxy/tutorial.md, topics/admin/tutorials/connect-to-compute-cluster/tutorial.md, topics/admin/tutorials/cvmfs/tutorial.md, topics/admin/tutorials/heterogeneous-compute/tutorial.md, topics/admin/tutorials/tiaas/tutorial.md
So that `-i hosts` does not need to be invoked in every Ansible tutorial.
I did leave `-i hosts` in a few tutorials because they either precede this training (ansible) or are more self-contained (monitoring, jenkins).
=> Make the creation of an ansible.cfg with `inventory` set non-optional

topics/metagenomics/tutorials/metatranscriptomics/slides.html
a trailing space after `???` marker for speaker notes caused them to be shown on the slide
=> [metatranscriptomics slides] fix speaker notes for group abundance slides

topics/admin/tutorials/tool-management/slides.html, topics/admin/tutorials/toolshed/slides.html, topics/dev/tutorials/toolshed/slides.html
- Move explanation of suites from TM to TS
- Remove "Dependency resolvers" from TM (already in TS)
- Remove conda recipe example from TS (off topic)
- Remove duplicated "Key points" slide from dev TS
xref. https://github.com/galaxyproject/training-material/issues/1809
=> Cleanup Tool Shed and Tool Management slides

topics/admin/tutorials/external-auth/slides.html, topics/admin/tutorials/external-auth/tutorial.md
=> Missing redirect for upstream-auth tutorial, nicer diffs

topics/climate/metadata.yaml, topics/climate/tutorials/panoply/tutorial.md
The training is ready to be reviewed. Especially nice to get feedback from non climate specialists because panoply is a tool that could be used by anyone interested in visualizing netCDF data on maps.
=> Climate panoply tutorial remove enable false for review

snippets/admin-testing.md, topics/admin/tutorials/ansible-galaxy/tutorial.md, topics/admin/tutorials/ansible/tutorial.md
To address the mistaken belief in that
> This is focused for paid distros. Centos 7/8 builds do not work due to package requirements and availability
[from the tutorial feedback](https://github.com/galaxyproject/training-material/issues/989#issuecomment-624070315)
=> Add admin training compatibility notice

topics/visualisation/metadata.yaml
since github isn't showing it:
```
commit 9e2512eebc37b0c11b040bbf84c3d977b13bda47 (HEAD -> fix, origin/fix, master)
Author: Helena Rasche <hxr@hx42.org>
Date:   Thu May 28 08:04:30 2020 +0200
more weird bytes
diff --git a/topics/visualisation/metadata.yaml b/topics/visualisation/metadata.yaml
index 79a777574..75452ce97 100644
--- a/topics/visualisation/metadata.yaml
+++ b/topics/visualisation/metadata.yaml
@@ -1,4 +1,4 @@
-<U+FEFF>---
+---
name: "visualisation"
type: "use"
title: "Visualisation"
```
=> Remove unnecessary unicode bytes

_config.yml, _includes/resource-handson.html, _layouts/topic.html, _layouts/tutorial_hands_on.html
Fixes https://github.com/galaxyproject/training-material/issues/1878
Also switches to native names for languages as is more preferred. I don't super love this translation icon but that should be fixed with #1898 and the newer icon https://fontawesome.com/icons/language?style=solid
=> Make translations more obvious

_includes/help.html, _layouts/home.html, _layouts/topic.html, _layouts/tutorial_hands_on.html, bin/schema-topic.yaml, bin/schema-tutorial.yaml, topics/genome-annotation/metadata.yaml, topics/transcriptomics/tutorials/scrna-preprocessing-tenx/tutorial.md, topics/transcriptomics/tutorials/scrna-preprocessing/tutorial.md, topics/transcriptomics/tutorials/scrna-raceid/tutorial.md, topics/transcriptomics/tutorials/scrna-scanpy-pbmc3k/tutorial.md, topics/transcriptomics/tutorials/scrna-scater-qc/tutorial.md, topics/transcriptomics/tutorials/scrna-umis/tutorial.md
@hexylena previously enabled embedding the Gitter sidecar to quickly access the admin Gitter channel from the admin tutorials. This allows the same to be specified on the tutorial level.
The sidecar will open the tutorial-level Gitter channel if defined, otherwise the topic-level Gitter channel, and defaults to the GTN lobby if neither are defined
Since @nomadscientist recently had the great idea to create a dedicated [single-cell Gitter channel](https://gitter.im/Galaxy-Training-Network/galaxy-single-cell), I have specified this channel for the various single-cell tutorials (let me know if I've missed any)
=> Gitter sidecar

assets/js/theme.js
For @TKlingstrom :)
Just add `?theme=....` e.g. `https://training.galaxyproject.org/?theme=rainbow` will work after deployment.
=> Support setting theme by URL

topics/admin/tutorials/ansible/tutorial.md, topics/admin/tutorials/connect-to-compute-cluster/slides.html, topics/admin/tutorials/tool-management/slides.html, topics/admin/tutorials/tool-management/tutorial.md, topics/admin/tutorials/toolshed/slides.html, topics/dev/tutorials/tool-integration/slides.html
- Move Tool Dependencies slides from "Tool Shed" to "Tool Management"
- Restore and update slides deleted in #1831
- Change slide deck and tutorial titles to "Galaxy Tool Management with Ephemeris"
Also 2 small unrelated clean-ups:
- Clarify `configfiles` in "Tool development and integration into Galaxy" slides
- Introduce Ansible Vault before the Hands-on in Ansible tutorial
=> Re-add Tool Dependencies slides to admin

topics/statistics/tutorials/regression_machinelearning/data-library.yaml
The links for datasets should be downloadable and should not show them as raw files. That's why I think the datasets do not get automatically uploaded to the data library. The links in "Basics of machine learning" tutorial has downloadable links mentioned in the yaml file 
Thanks!
ping @bgruening
=> Add download links for datasets

Makefile, _config-dev.yml, _plugins_dev/jekyll-scholar-fake.rb
The `jekyll-scholar` plugin was resulting in very long build times; this disables the plugin by default. It led to a ~3x speedup for me for the initial build,  and might also fix the problem with re-build times in the `--incremental` increasing over time (not sure tho)
This means citations/the bibliography will no longer be rendered when you do `make serve`, but `make serve-full` will enable you to still build the full site. A hint to this effect is shown in the tutorials in place of the real citations. `--incremental` is now also enabled on by default
we could also leave make serve as it is now, and add a make-quick target? There are also other things we could disable, e.g. all the contributor pages, but that doesn't take all that much time
=> Speed up jekyll serve

topics/admin/tutorials/pulsar/tutorial.md
fix a typo; the job conf template path is referenced without the .j2 extension.
=> Update pulsar tutorial.md

topics/assembly/tutorials/debruijn-graph-assembly/workflows/debruijn-graph-job1.yml, topics/assembly/tutorials/debruijn-graph-assembly/workflows/debruijn-graph-tests.yml, topics/assembly/tutorials/debruijn-graph-assembly/workflows/debruijn-graph.ga, topics/assembly/tutorials/general-introduction/data-library.yaml, topics/assembly/tutorials/general-introduction/workflows/assembly-general-introduction-job.yml, topics/assembly/tutorials/general-introduction/workflows/assembly-general-introduction-test.yml, topics/assembly/tutorials/general-introduction/workflows/assembly-general-introduction.ga
Both passing on usegalaxy.org.au.  The debruijn-graph-assembly one was generated with `planemo workflow_test_init` from https://github.com/galaxyproject/planemo/pull/1028 (thank you @mvdbeek for putting me on to this)
=> Update test for assembly general-introduction and add test for debruijn-graph-assembly

topics/admin/tutorials/ansible-galaxy/tutorial.md
Adds the missing section on creation of a simple job conf file to the ansible-galaxy tutorial. This allows for a single day or other shortened course to then go onto other modules like the Pulsar tutorial with the required job conf file in place.
=> Added job conf section to ansible-galaxy tutorial

_plugins/jekyll-tool-tag.rb, assets/css/main.scss, topics/contributing/tutorials/create-new-tutorial-content/tutorial.md, topics/introduction/tutorials/galaxy-intro-101-everyone/tutorial.md, topics/introduction/tutorials/galaxy-intro-101/tutorial.md, topics/introduction/tutorials/galaxy-intro-peaks2genes/tutorial.md, topics/introduction/tutorials/galaxy-intro-short/tutorial.md, topics/introduction/tutorials/galaxy-intro-strands/tutorial.md, topics/visualisation/tutorials/circos/tutorial.md
In support of https://github.com/galaxyproject/galaxy/pull/10024, we can now annotate training materials with the precise tool ID and optionally version.
We will add this to planemo so most people won't care about it, but for the older tutorials we can migrate them or encourage authors to, in order to take advantage of the webhook.
Please see https://github.com/galaxyproject/galaxy/pull/10024 for more information on what the tool tag will be used for.
I have converted a couple of training materials, but we should focus on doing the rest of the introductory ones before merging.
=> New tool tag / GTN webhook

topics/variant-analysis/tutorials/tb-variant-analysis/tutorial.md
Minor change to add tool link for tbvcfreport tool to M. tuberculosis variant annotation tutorial
=> Add tool link for tbvcfreport

topics/variant-analysis/tutorials/tb-variant-analysis/workflows/tb-variant-analysis-test.yml
The current test fails on usegalaxy.org.au because it looks for 'c.481C>T' which gets rendered as 'c.481C&gt;T' there. This PR updates that test to look for 'Leu161Leu' instead (part of the same output row) to avoid problems with HTML escapes.
=> change expected test output for tbvcfreport

Makefile
Named slides in remark allow for referencing specific slides via anchors, but htmlproofer will fail on such links because the html for the slides is rendered on the fly, so this ignores these anchors on `slides.html`, should fix the errors on https://github.com/galaxyproject/training-material/pull/2014
=> htmlproofer: do not check anchors on remark slides

.dockstore.yml
My admin powers have been defeated. 
```
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: At least 1 approving review is required by reviewers with write access.
To github.com:galaxyproject/training-material.git
! [remote rejected]     master -> master (protected branch hook declined)
error: failed to push some refs to 'git@github.com:galaxyproject/training-material.git'
```
=> Tweak dockstore YAML (just trying to trigger a Dockstore update)

topics/computational-chemistry/tutorials/analysis-md-simulations/workflows/main_workflow-test.yml, topics/computational-chemistry/tutorials/analysis-md-simulations/workflows/main_workflow.ga, topics/computational-chemistry/tutorials/md-simulation-gromacs/tutorial.md, topics/computational-chemistry/tutorials/md-simulation-gromacs/workflows/main_workflow-test.yml, topics/computational-chemistry/tutorials/md-simulation-gromacs/workflows/main_workflow.ga, topics/metagenomics/tutorials/general-tutorial/workflows/amplicon-job.yml, topics/metagenomics/tutorials/general-tutorial/workflows/amplicon-test.yml, topics/proteomics/tutorials/protein-quant-sil/workflows/workflow-test.yml, topics/proteomics/tutorials/protein-quant-sil/workflows/workflow.ga
Tests added/updated for
```
topics/computational-chemistry/tutorials/analysis-md-simulations/workflows/main_workflow.ga
topics/computational-chemistry/tutorials/md-simulation-gromacs/workflows/main_workflow.ga
topics/metagenomics/tutorials/general-tutorial/workflows/amplicon.ga
topics/proteomics/tutorials/protein-quant-sil/workflows/workflow.ga
```
Test are copied and adapted from usegalaxy-eu/workflow-testing (discussed in https://github.com/usegalaxy-eu/workflow-testing/issues/3)
=> Some workflow test updates

topics/contributing/tutorials/github-command-line-contribution/tutorial.md
Some of the links to the github repo went instead to the training website - I removed the .url extension on these (and added in underscore) so that they link to the actual github repo. (I think this should work?)
=> Contributing fixes

_layouts/base.html, _layouts/base_slides.html
So we did a partial move to the new domain (training.galaxyproject.org) from our old galaxyproject.github.io address and let people update their address books when they felt like it.
This is the next part of that move: now all traffic going to galaxyproject.github.io will be redirected automatically to the new domain.
I had avoided this during the original move because I didn't have a clean solution for it (I was thinking we would have to add redirects to each html page or something crazy, and that was going to be very difficult to make work.) Thanks to @dannon for the idea, this is a lot simpler. We add some JS to do the redirection, if and only if they're on that domain. (@Dannon I've requested a review, can you do a sanity check for me? Does this look ok?)
In the future we can discuss …
=> The final redirect

topics/climate/tutorials/climate-101/tutorial.md
Found a missing link in climate 101 tutorial.
=> Galaxy paper-cut: fix missing link for zenodo (input data) in climate101

_plugins/jekyll-topic-filter.rb
for example to fix this ordering (in proteomics topic):
=> Sort tutorials case-insensitively on topic page

topics/sequence-analysis/tutorials/mapping/slides.html
We were teaching this today and noticed the alignment game linked from the slides was not working properly. But a version cached by waybackmachine still worked, so updating the link temporarily until the game works again
=> [Mapping slides] alignment game broken, use waybackmachine link until fixed

assets/css/main.scss
Before | After 
--- | ---
(open those in a new tab, it's easier to see.) But it's always low key bothered me.
=> Reduce whitespace small width

topics/ecology/tutorials/PAMPA-toolsuite-tutorial/tutorial.md
This is something where for sure trainees will make mistake... at least with this tool and the concatenate one.... Maybe only keep one "version" of each tools ? ITM be sure we can make the same operations, it seems to me this is not the case so "we" have to work on it carefully
=> Cut columns from a table -> Cut columns from a table (cut)

topics/introduction/tutorials/galaxy-intro-101/tutorial.md
I love the galaxy 101 tutorial, much prefer it to some of the others, but the UCSC steps cause *so* much pain with users. We tell them about how uniform all galaxy tools are... and then show them the one type of tool that doesn't behave like 99% of the tools they will use.
This simplifies that and should make the tutorial much easier.
=> Move UCSC steps into tips, and use data from zenodo

_includes/analytics.html
The stats can be made public here: https://plausible.galaxyproject.eu/training.galaxyproject.org and it can be a nice replacement for google's
=> Testing plausible analytics as replacement for google

topics/admin/tutorials/ansible-galaxy/tutorial.md
Another tiny correction for the ansible-galaxy tutorial
=> ansible-galaxy: fix wrong file name

topics/proteomics/metadata.yaml
@foellmelanie, @PratikDJagtap and @subinamehta have kindly agreed to be topic maintainers for Proteomics topic, thanks!! :tada: 
@martenson could you add them to the @galaxyproject/training-proteomics team?
=> Add Proteomics topic maintainers

.github/workflows/deploy-s3.yml, .github/workflows/deploy.yml, _includes/analytics.html, _layouts/base.html, _plugins/jekyll-environment_variables.rb, robots.html
To allow users to build the website on their own fork, without search engines indexing it
also removes google analytics since we switched to Plausible
ping @hexylena please check the changes to the github actions workflows
=> Populate robots.txt file when served from a fork

.github/workflows/deploy-s3.yml, .github/workflows/deploy.yml, robots.html
follow up to https://github.com/galaxyproject/training-material/pull/2205, we can use predefined github repo owner variable as suggested by @nsoranzo (thanks!)
=> Robots.txt fix: use github env variable

topics/admin/tutorials/ansible-galaxy/galaxy.yml, topics/admin/tutorials/ansible-galaxy/group_vars/galaxyservers.yml, topics/admin/tutorials/ansible-galaxy/requirements.yml, topics/admin/tutorials/ansible-galaxy/tutorial.md
- Sort package names in pre-task
- Update `geerlingguy.pip` role to 2.0.0
- Add `miniconda_manage_dependencies: false` to tutorial
- Clarify `galaxy_config_templates` origin
=> Various fixes for ansible-galaxy tutorial

topics/transcriptomics/tutorials/ref-based/tutorial.md
Following @mgabere comment
Gene C should be 33/0.4 = 83    55/0.9= 61.11     200/2.5 = 80
Gene B should be 2/0.4 = 5      6/0.9= 6.67   12/2.5 = 4.8 
Gene A should be 0/0.4 = 0   10/0.9 = 11.11   4/2.5 = 1.6
fixes #2224
=> correct deseq2 normalization step 7

topics/admin/tutorials/ansible-galaxy/tutorial.md, topics/admin/tutorials/ansible/tutorial.md
Ansible broke something in 2.10.4 for us, and now we have to document a workaround explicitly when it used to be just done implicitly.
Additionally this addresses the issue from #2223
=> Fix ansible galaxy issues

topics/admin/tutorials/ansible-galaxy/tutorial.md
If for some reason the value of galaxy_user.name gets changed, the playbook will fail when the uchida.miniconda role tries to become an fixed (e.g. "galaxy") user. The change fixes that. The required variable is added immediatly after the writing of the playbook, so it should not be an issue.
=> Using galaxy_user variable also for miniconda become_user

topics/transcriptomics/tutorials/scrna-scanpy-pbmc3k/tutorial.md
Said cells rather than genes. This is embarrassing to even propose as a change. I am ashamed. Enjoy this one-word improvement of a mammoth tutorial.
=> Tiniest of typos

topics/admin/tutorials/tool-management/tutorial.md
The installed tool for the "Hands-on: Installing a single tool" step has been changed from bwa to pilon.  The tested tool has been changed from bamtools_filter to pilon.  The reason for this change is to avoid the error 'NoneType has no attribute view' which comes from running tests for some tools where pysam is not also installed.  pilon was chosen because it doesn't take up much more conda space than bwa and it installs is about the same amount of time.
There is a new tip for splitting the screen with byobu, because at some point the video tutor will split their byobu screen and instruct the students to do the same.
=> Minor updates to tool management tutorial for admin training 2021

topics/admin/tutorials/singularity/tutorial.md
the singularity_go_path variable disappears and reads as `singularity_go_path: ""`
=> add raw tags around a yaml block in singularity tutorial

topics/admin/tutorials/tool-management/slides.html
@hexylena this is last-minute.  The questions, objectives and key points now form part of the slide show and I'd like to change them to fit better with the content of the slides.   I got rid of the objectives altogether but I can replace them with revised objectives if need be.
=> Tool management slides: update questions and key points, delete objectives

topics/admin/tutorials/singularity/tutorial.md
It's not relevant without the "Use Singularity containers from CVMFS" part.
=> Remove the CVMFS tutorial requirement

topics/admin/tutorials/singularity/tutorial.md
So through the :sparkles: magic :sparkles: of git/GH, commits from forks are included in the parent repository.
As they haven't merged my PR yet (https://github.com/CyVerse-Ansible/ansible-singularity/pull/1), *and* they pull their role from github rather than publishing on ansible, we can simply point at my PR commit and it behaves just like we want, pulling that PR commit.
The commit is **required** for GAT, it skips a 1-2 minute build on *every* run of the role.
=> Singularity role imposter

.github/workflows/cron.yml, .github/workflows/video.yml
I keep getting emails like "[nsoranzo/training-material] Run failed: Autogenerated and Deploy Videos - master (d86a8bf)"
=> Skip cron and video CI jobs on forks

_layouts/base.html
This reverts commit f108a976480273f25a63ac9ddb31d6a8e6637193 which accidentally removed analytics from non-slide pages.
=> Correct stats

_includes/tutorial_list.html, topics/transcriptomics/metadata.yaml, topics/transcriptomics/slides/introduction.html, topics/transcriptomics/tutorials/de-novo/tutorial.md, topics/transcriptomics/tutorials/ref-based/tutorial.md, topics/transcriptomics/tutorials/rna-seq-counts-to-genes/tutorial.md, topics/transcriptomics/tutorials/rna-seq-counts-to-viz-in-r/tutorial.md, topics/transcriptomics/tutorials/rna-seq-genes-to-pathways/tutorial.md, topics/transcriptomics/tutorials/rna-seq-reads-to-counts/tutorial.md, topics/transcriptomics/tutorials/rna-seq-viz-with-cummerbund/tutorial.md, topics/transcriptomics/tutorials/rna-seq-viz-with-heatmap2/tutorial.md, topics/transcriptomics/tutorials/rna-seq-viz-with-volcanoplot/tutorial.md, topics/transcriptomics/tutorials/scrna-plates-batches-barcodes/slides.html, topics/transcriptomics/tutorials/scrna-preprocessing-tenx/tutorial.md, topics/transcriptomics/tutorials/scrna-preprocessing/tutorial.md, topics/transcriptomics/tutorials/scrna-raceid/tutorial.md, topics/transcriptomics/tutorials/scrna-scanpy-pbmc3k/tutorial.md, topics/transcriptomics/tutorials/scrna-scater-qc/tutorial.md, topics/transcriptomics/tutorials/scrna-umis/tutorial.md, topics/transcriptomics/tutorials/small_ncrna_clustering/tutorial.md
There are a LOT of tutorials in the transcriptomics topic, it would be nice to create some subtopics. I had a first go at it, but am not an expert, so please let me know what would be good groupings, @mblue9, @bebatut, and others?
Currently I made the following subtopics:
- Introduction (with intro slides and ref-based tutorial)
- End-to-End (@mblue9's 3 tutorials that form a unit, please let me know what a better name would be here?)
- Single Cell (@mtekman, @nomadscientist let me know if there is some logical ordering to these that might be nice to enforce?)
- Visualisation
- Anything else ends up in "Other"
Thoughts? Any subtopics we should add/remove/rename? Tutorials that need to move to a different subtopic?
=> Add subtopics for transcriptomics

topics/admin/tutorials/reports/tutorial.md
Need to put the reports location into the nginx config via the galaxy.j2 nginx template not into the groupvars/galaxyservers.yml file
=> Reports location in galaxy.j2 template

bin/ari-map.yml
not sure if the > is correct. In the text it is written: '>'
=> add spelling for proteomics slides

topics/variant-analysis/tutorials/tb-variant-analysis/tutorial.md
There was a missing `{: .hands_on}` at the close of the last hands on section, this fixes it
=> Fix last hands on section in M. tuberculosis variant analysis tutorial

topics/variant-analysis/tutorials/tb-variant-analysis/tutorial.md
The kraken2 step in the M. tuberculosis variant analysis tutorial requires high RAM usage, which is not possible on all Galaxy configurations. This PR adds a note about this step being optional in the tutorial.
=> M. tb variant analysis: Make note about kraken2 analysis step using lots of RAM

topics/proteomics/tutorials/proteogenomics-dbcreation/tutorial.md
A few questions as well:
- Which files need to have the dbkey set to mm10 in the first Hands-on? I just set all of them.
- The StringTie input is listed as `FASTQ_ProB_22LIST.BAM` but I believe this should be `HISAT_Output.BAM`? It is the only
BAM file in the history at this stage.
- The StringTie reference GTF is the original one uploaded, not the one we manipulated the chromosome names of in the second hands-on. Using the original results in a 42 line dataset and the StringTie warning: `"WARNING: no reference transcripts were found for the genomic sequences where reads were mapped!"` whereas using the manipulated GTF results in a 127 line dataset and no warning. Just wanted a confirmation from the tutorial authors before changing that since it's not as if I know what I'm doing. 😂 
- I …
=> Proteomics dbcreation tutorial small fixes and clarifications

topics/variant-analysis/tutorials/tb-variant-analysis/workflows/tb-variant-analysis-test.yml
While working through the tutorial I found a couple of problems with the "Text transformation" step and the step where this output is used. This PR corrects them.
=> Correct sed/M. tuberculosis variant report steps for M. tb variant analysis

_includes/default-header.html, _includes/extras.html, _includes/help.html, _layouts/tutorial_hands_on.html, assets/css/main.scss
I have reworked the help menu a bit, to 
1. Add link to plausible page metrics (number of views etc). Tutorial creators often ask for this info for their reporting etc.
2. Add link to Gitter
2. Disable TeSS search (it doesn't work currently, we can re-enable in the future)
3. Add the language selector here, to save some space on the top menu (we can see that this isn't often used anyway)
4. Add some icons to the help menu
5. Add tutorial search box to all pages
=> Rework the help menu

_layouts/home.html
We have two cool new GTN/community videos, so I wanted to feature those on the GTN home page :tada: 
- The community video created by @beatrizserrano 
- The GTN video created by Geert Bonamie.
Also embeds the GTN twitter timeline.
=> Add GTN videos to homepage

topics/introduction/tutorials/galaxy-intro-ngs-data-managment/tutorial.md
"Boolean bits" may be confusing to the reader: a Boolean is a data type, whereas a bit is a unit of information. So, "Boolean" cannot be used as a qualifier for "bits". If "...bits (0, 1)" is not clear enough, another option is "...bits (0, 1) representing Boolean values (true, false)"; but I would suggest just "bits (0, 1)" - for that's what the text is describing.
=> Rephrase reference to "bits"

_config.yml, topics/galaxy-interface/tutorials/upload-rules-advanced/tutorial.md
Small papercut fix for #2392 
Hello GTN, this is my first PR here! :) A few comments on what I did, although it admittedly wasn't much. 
- I'm not sure if I used the correct comment block, but it seemed the most appropriate. 
- I also deliberated over whether to add the JSON editor bits as a comment, and highlight the Saved Rules Selector to be used in the tutorial, but wasn't quite sure how to concisely guide users in checking out the JSON editor without getting them confused.  
- A third option is to have users use the JSON editor and then delete a rule, (accidentally/on purpose). Afterwards, they can use the Saved Rules Selector to load the last rule set in it's entirety.  
Let me know how to proceed. :)
=> added saved rules selector to the tutorial, and moved json editor to a comment box

.github/workflows/ci.yml, .github/workflows/cron.yml, .github/workflows/deploy-s3.yml, .github/workflows/deploy.yml, .github/workflows/docker-build.yaml, .github/workflows/video.yml
builds have started to fail since new ubuntu images started being used for actions (e.g. https://github.com/galaxyproject/training-material/pull/2437), use the 18.04 image until this gets fixed upstream so that we can deploy
ping @hexylena
=> [CI] use ubuntu 18.04 image for ci

bin/format_tutorial_for_article.py
Fix to regex for non backwards relative paths
python bin/format_tutorial_for_article.py -t topics/transcriptomics/tutorials/scrna-raceid
Before it would error out an image entry such as:
'![Histograms of raw and filtered data]({{site.baseurl}}{% link topics/transcriptomics/images/raceid_filter_plots.png %} "RaceID Histograms of raw and filtered data")\n'
Also, the `check_exists` function modified to allow boolean return. This can be used to check whether or not the tutorial path needs to  be appended to the image path (depending on whether or not the image path is relative)
=> [Small Patch] Format tutorial for paper

topics/contributing/tutorials/running-jekyll/tutorial.md
This PR update the "Running website" tutorial to:
- Remove step to activate conda environment
- Use `make serve-quick` instead of `make serve`
=> Some updates - Topic: Contributing - Tutorial: Running website

_includes/extras.html
I was looking the stat page on GTN website. I saw it was not linked. But maybe it was intended (then feel free to close this PR)
=> Add link in extra to GTN stat page

topics/transcriptomics/tutorials/droplet-quantification-preprocessing/tutorial.md
From @nomadscientist 's [answer key](https://humancellatlas.usegalaxy.eu/u/wendi.bacon.training/h/pre-processing-with-alevin---part-1---answer-key) I can see that Alevin 1.3.0 is the version that should be used, and I'm having trouble with the currently cited version, so I've edited that. I've also linked the answer key for the benefit of students.
=> Fix Alevin version, link answer key

topics/transcriptomics/tutorials/scrna-plates-batches-barcodes/slides.html
Convert the Plates, Batches, and Barcodes slide deck into a video
=> Add video transcripts to plates, batches, and barcodes slide deck

topics/assembly/tutorials/chloroplast-assembly/tutorial.md
In order to use a single criterion, this RP proposes to replace the **plant** label with **plants**, thus unifying the labels.
=> Unify trainings plant tags

faqs/galaxy/analysis_results_may_vary.md
because there were no spaces at the end of each line.
Put everything on one line to avoid this problem.
=> spaces missing in the sentence

topics/variant-analysis/tutorials/tb-variant-analysis/tutorial.md
This clarifies the use of `sed` in the M. tuberculosis variant annotation tutorial
=> Minor clarification re: use of sed

.github/workflows/optimize-images.yml
Copied from https://github.com/galaxyproject/galaxy-hub/pull/733, thanks @davelopez!
This should make shallow clones faster in the future.
=> Add Github action to optimize all images

topics/introduction/tutorials/galaxy-intro-short/tutorial_ES.md
As part of the 21.05 release testing plan, we try to run through some of the GTN tutorials and identify parts that may have changed or no longer work in the new version of Galaxy. In this case, I decided to try the brand new Spanish version of `A short introduction to Galaxy` tutorial.
I found a couple of typos and slightly change some phrases that sounded good to me.
Nice job with the curated translation!
=> Fix some typos in tutorial_ES.md

topics/metagenomics/tutorials/metatranscriptomics-short/workflows/workflow3_functional_information.ga, topics/metagenomics/tutorials/metatranscriptomics-short/workflows/workflow3_functional_information_quick.ga
Workflow 3 for the short tutorial was missing one of the input files for `Combine MetaPhlAn2 and HUMAnN2` tool, so I added this (Cut predicted taxon relative abundance table)
ping @bebatut does this look ok? ping @subinamehta FYI
=> [Metatranscriptomics] update workflows to include missing input

CONTRIBUTORS.yaml, bin/check-broken-tool-links.sh, topics/transcriptomics/tutorials/ref-based/tutorial.md
I have updated the ref-based tutorial (tools links) as per the comments on the last pull request on my_new_branch
I can created this branch instead, since I have got multiple errors on the last one that I couldnot resolve after many trials
Last comment: some tools e.g. filter, their usegalaxy tool links are different (without the toolshred)
=> Engy branch: add tool links to ref-based transcriptomics tutorial

search.md
search is currently broken because of invalid json here, it does not reproduce locally but there seems to be an empty entry sneaking in there somehow. hopefully this fixes it? ping @hexylena
=> [Tutorial Search] explicitly list topic types

search.md
Maybe finally fixes the search. Ping @shiltemann 
Added an if block around search queries <2 characters to prevent the `w is undefined` error appearing in the logs
=> [Tutorial Search] modify filter

.gitpod.yml, Makefile
[gitpod.io](https://gitpod.io) has Ruby built in (thanks @shiltemann for pointing that out) and can thus can be setup with a simple `bundle install` (now added as a target `bundle-install` in the Makefile).
This PR adds that Makefile target, a `serve-gitpod` target for serving on a `gitpod.io` machine and a `.gitpod.yml` for configuring initialisation and ports.
=> Provide support for working on gitpod.io

.github/workflows/git-gat.yml, topics/admin/tutorials/cvmfs/tutorial.md
git-gat/test will be triggered if there are any changes to the admin topic. This'll extract the commits and build them.
git-gat/deploy will only run if the repo owner is galaxyproject (so on main branch + PRs from people opening branches from this repo)
=> Fix git-gat test for repos that don't have permissions

_config.yml, _layouts/tutorial_hands_on.html, _plugins/abbr.rb, assets/css/main.scss, bin/schema-tutorial.yaml, bin/validate-frontmatter.rb, news/_posts/2021-05-25-abbreviations-tag.md, news/_posts/2021-05-25-new-dev-tutorial.md, topics/contributing/tutorials/create-new-tutorial-content/tutorial.md, topics/dev/tutorials/bioblend-dev/tutorial.md
Referencing abbreviations is really kind of annoying to do, and I'm so used to LaTeX's abbreviation abilities which are fantastic and so easy to use. So I've re-implemented something similar here. Note that on first use the term is expanded and include `term (abbr)` and on subsequent uses is just abbreviated with the abbreviation and the abbr tag which provides hover information. 
After reviewing @rikeshi's new tutorial I noticed that terms like HDA/HDCA/LDA are defined and referenced and it made sense to implement a plugin to help make this process easier. I've done this with @rikeshi's tutorial to start with as a demonstrator. cc @simonbray 
The `/jobs` &lbrace;API&rbrace; will return &lbrace;JSON&rbrace;. When we call the &lbrace;API&rbrace; we'll get back this result …
=> Add Abbreviation plugin

topics/admin/tutorials/cvmfs/tutorial.md
Hi,
In CVMFS the maf files stored [there](http://datacache.galaxyproject.org/managed/align/30_WAY_MULTIZ_HG38/) are Multiple Alignment Format  not Mutation Annotation Format.
Still, there might be other Mutation Annotation Format files elsewhere. I don't know who may know. @natefoo ?
Please wait for confirmation before merging.
=> fix maf acronym in CVMFS tutorial

.github/workflows/git-gat.yml, topics/admin/tutorials/ansible-galaxy/tutorial.md
No changes to code.
@hexylena I can't quite make out what's being said here:
> Some of these can be worked around, by running the portions of the roles that deploy these directories on the shared filesystem. Then Galaxy and the shared filesystem can run off of two different copies of them, if that is better for performance
=> Add client build info to ansible-galaxy and a few other verbiage changes.

.github/workflows/git-gat.yml, bin/knit-automated.sh, topics/admin/tutorials/gxadmin/tutorial.md, topics/admin/tutorials/monitoring/tutorial.md, topics/admin/tutorials/reports/tutorial.md, topics/contributing/tutorials/admin-knitting/tutorial.md
- updates gxadmin to a version which didn't have an ansible metadata issue
- fixes the bad check for fork vs branch in git-gat
- supplies the `-C` flag to check less context in the building of git-gat diffs to make it less picky about context when building from commits. 
- add `galaxy_reports_path`
=> Fix reports path missing and fix gxadmin warning about dupe key

topics/dev/tutorials/debugging/tutorial.md
Because there's a call to a different `get` method on the next line.
=> Clarify which `get` method

.github/workflows/monthly-release.yml, _includes/extras.html, _plugins/jekyll-environment_variables.rb, assets/css/main.scss, news/_posts/2021-06-01-archive-menu.md
We'll now have a menu item in the Extras dropdown to link to a few recent tags in the archive as well as a button for all older versions.
Per suggestion from @shiltemann we limit this to only a couple tags, with the presumption that the primary use will be teachers going "oh, shoot, someone changed something, let me revert to a previous version"
=> Add archive menu to extras

topics/epigenetics/tutorials/atac-seq/tutorial.md
As the bedgraph to bigwig was an issue on usegalaxy.org with the tiaas priority. @jennaj suggested to add a tip to speed up the process and decrease the memory usage.
=> ATACseq: Add a tip to speed bedgraph-to-bigwig

faqs/gtn/issues_galaxy.md
so many times people ask questions and don't include everything we need. This could provide a single thing we can link to which asks the main questions
That way we can respond with "Could you please provide more information to help us debug your issue? (link)"
=> Add faq on reporting bugs

assets/css/syntax_highlighting.css
@natefoo  https://github.com/galaxyproject/training-material/issues/2583#issuecomment-871492929 This is more or less the styling I use in my terminal (as a red-green impaired human) and it works quite well, and should be black-white colourblind friendly
```
[color "diff"]
meta = bold
frag = magenta bold
old = strike reverse
new = blue dim reverse
```
=> colour blind friendly diff colouring

topics/dev/tutorials/architecture/slides.html
Just fixing a few typos found while looking at the slides
Nice slides!
=> Fix typos in architecture slides

topics/contributing/tutorials/create-new-tutorial-slides/slides.html
This replaces the contents of one contributing slide with some html character codes which won't be accidentally detected as the slide-splitting/presenter notes.
This caused the video to be recorded with slightly out of sync images/audio at the end.
This seems like an acceptable solution, it's unlikely any other slide deck will need to do this, no one else is going to be using `???` or `---` intentionally on their slide, on it's own line (maybe within a line, but, that's not an issue.)
=> Fix offset due to wrongly detected end of slide

topics/genome-annotation/tutorials/annotation-with-maker/workflows/main_workflow.ga
This PR includes the following modifications:
- Add best practices information
- Update _gffread_ tool version to  2.2.1.2 (previous version, 2.2.1.1. is not available in usergalaxy.org)
- Update _fasta statistics_ tool to 1.0.1 (previous version, 1.0.0, is not available in usegalaxy.org)
=> Update maker workflow

topics/variant-analysis/tutorials/sars-cov-2-variant-discovery/tutorial.md
Among others:
- Fixes links to auxiliary datasets
- Mentions need to adjust autodetected format for some of them
- Fixes mix-up of by-sample and by-variant reports in hands-on
- Adds workflowhub link, which became available only recently, for
consensus WF
=> SARS-CoV-2 mutation and lineage calling: Fix issues found in first round of user training

faqs/galaxy/datasets_import_from_data_library.md
You cannot be sure about paths in the DL on different Galaxy instances,
but you can provide a likely path to try unless the instructor says
otherwise.
=> Make path option in DL import snippet more useful

_layouts/base_slides.html
Most common slide formats default to 16:9 since a while, this enables the more modern aspect ratio for us as well.
(probably merge after gcc to not surprise anyone?)
Before | After
-- | --
=> Make slides 16:9

Makefile
They have re-added the feed to the hub. This reverts commit c5529ad930c038fb0c5bdf9230f08efea9cfa652.
=> Revert "Temporarily disable annotations"

topics/galaxy-interface/tutorials/upload-rules-advanced/tutorial.md
The "Apply rule to Collection" tool has been renamed to "Apply Rules" as part of https://github.com/galaxyproject/galaxy/pull/11068.
Also fixed a few typos while at it.
=> Update advanced rule-building to use new 21.09 tool name

topics/variant-analysis/tutorials/sars-cov-2-variant-discovery/data-library.yaml
This typo caused the dataset to be excluded from auto-populated DLs,
which would then break paired collection building for users.
=> Fix dataset type in SARS-CoV-2 data library

CODEOWNERS
Now everybody in @galaxyproject/training-spanish will be notified whenever a PR is made touching a translated tutorial, so that they can help make the required changes in the other language.
If you ever want to be removed from this group and stop receiving these notifications, just let us know. If any other Spanish speakers would like to be added to this group and help out with translations please let us know as well!
@nomadscientist any tutorials missing?
=> Add Spanish team as codeowners to all translated tutorials

topics/introduction/tutorials/galaxy-intro-101-everyone/tutorial.md, topics/introduction/tutorials/galaxy-intro-101/tutorial.md, topics/introduction/tutorials/galaxy-intro-peaks2genes/tutorial.md, topics/introduction/tutorials/galaxy-intro-short/tutorial.md, topics/introduction/tutorials/galaxy-intro-strands/tutorial.md
Hi, I checked the alt texts of the images in **Introduction to Galaxy Analyses** hands-on tutorial materials and I found out that some alt texts were not descriptive enough. 
This defeats our goal of making the materials accessible to visually impaired users.
Out of the 9 tutorial materials, 5 materials needed the improvement which I have done.
I also corrected an error in status description image alt text of Introduction to Genomics and Galaxy tutorial: It read _'successful'_ instead of _'failed'._
What do you think?
=> Improved and corrected some alt texts to improve accessibility

CONTRIBUTORS.yaml, _layouts/faq.html
added contributors to the FAQ page.
=> add contributors to FAQ page

.github/workflows/matrix.yml, bin/news.rb
This is a script which compares against an old git commit for:
- new news posts
- new slides
- new tutorials
- new contributors
And then will post that to our matrix channel. It will run daily at noon-ish and post to the GTN matrix/gitter channel.
You can test locally by doing something like:
```
$ ruby bin/news.rb -p HEAD~90
- [Advanced Python](topics/data-science/tutorials/python-advanced-np-pd/tutorial.html)
- [Introduction to Python](topics/data-science/tutorials/python-basics/tutorial.html)
- [Plotting in Python](topics/data-science/tutorials/python-plotting/tutorial.html)
- [dplyr & tidyverse for data processing](topics/data-science/tutorials/r-dplyr/tutorial.html)
...
```
and seeing the nice markdown output. It takes a commit hash or something that can be resolved with `git log`. …
=> Detect "news" and send it to Matrix & Gitter

Makefile, _includes/tutorial_list.html, _layouts/feedback.html, _layouts/home.html, _layouts/tutorial_hands_on.html, _plugins/jekyll-topic-filter.rb, topics/data-management/metadata.yaml, topics/transcriptomics/tutorials/full-de-novo/workflows/index.md
Now hidden topics will be shown in dev builds of the training material (dev = anything other than the deployment script where we explicitly set JEKYLL_ENV=production)
And within that all of the `enable:false` tutorials will be shown, with the additional tag of 'work-in-progress' applied to those tutorials.
This one should help you @robertmand
=> Show enable:false in non-production builds

.github/workflows/deploy.yml, _includes/resource-video-library.html, topics/dev/tutorials/tool-from-scratch/tutorial.md
Previously, the multi-video tutorials (e.g. debugging and tool development) were not linked from the GTN tutorials yet, this should fix that
=> GTN Video Library: support multi-video tutorials

faqs/galaxy/datasets_import_via_link.md
Galaxy doesn't use the URL as the name anymore so should this bit below be removed from the snippet? (did that in this PR)
```
{% if include.renaming == undefined or include.renaming == true %}
* By default, Galaxy uses the URL as the name, so rename the files with a more useful name.
{% endif %}
```
=> Update snippet import_via_link to remove rename

topics/proteomics/tutorials/DIA_Analysis_MSstats/workflows/Galaxy-Workflow-DIA_MSstats_Training_export_tabular-test.yml, topics/proteomics/tutorials/DIA_Analysis_MSstats/workflows/Galaxy-Workflow-DIA_MSstats_Training_export_tabular.ga, topics/proteomics/tutorials/DIA_Analysis_MSstats/workflows/Galaxy-Workflow-DIA_MSstats_Training_msstats_input_tabular-test.yml, topics/proteomics/tutorials/DIA_Analysis_MSstats/workflows/Galaxy-Workflow-DIA_MSstats_Training_msstats_input_tabular.ga
This updates the workflows associated with the tutorial to use histogram/histogram_rpy instead of dna_filtering/histogram_rpy.  This is already up-to-date in the tutorial.md file.
=> Add workflow tests for DIA_MSstats_Training tutorial

topics/introduction/tutorials/galaxy-intro-101/tutorial.md
`Show beginning1` is failing in Galaxy Europe (broken pipe in cat). `toolshed.g2.bx.psu.edu/repos/bgruening/text_processing/tp_head_tool/1.1.0` works better
The error seems discussed and somehow fixed (https://github.com/galaxyproject/galaxy/pull/12112). Not sure why not still failing
=> Galaxy 101: Change tool id for Select first

_config.yml, _includes/resource-slides.html, _includes/resource-video-library.html, _includes/resource-zenodo.html, _includes/tutorial_list.html, _layouts/base_slides.html, _layouts/tutorial_hands_on.html, _plugins/plaintext-slides.rb, assets/css/slides.css, topics/transcriptomics/slides/introduction.html
added a column for the GTN video library recordings to the topic page. Also added the date of the latest recording to the dropdown.
Removed the tours column since we are not really mainaining those actively.
and also: 
- use different icon for video slides to distinguish from live recordings
- add link to video slides on main slide deck
- re-use the slides include for topic-introduction slides
- generate plaintext slides for introductory slide decks
- rename "Galaxy instances" column to "Galaxy servers"
=> Video library: add column to topic page, add dates

topics/computational-chemistry/tutorials/setting-up-molecular-systems/tutorial.md
We've had a bug report from someone that pasted the link directly.
The direct link seems better here.
Note also that this is sniffed as a pqr file. Is that correct (or unavoidable) or do we need to tighten Galaxy's sniffers ?
=> Add zenodo download link in molecular systems tutorial

Makefile, environment.yml
Ruby 2.4 does not support `array.append` as it seems. Ruby >2.5 does. So this will install a newer Ruby version in the standard conda env. This will probably break other things. We should also pin the environment.yml file again.
=> install recent ruby verion and fixes

topics/sequence-analysis/tutorials/mapping/slides.html
Fixed:
- The GCSA link was identical to the HISAT2 link.
- The HISAT2 line was broken due to a missing closing parenthesis
- The MMP link was to an unrelated chemistry method with the same acronym, when really there is no separate link to MMP cause it's defined in the RNASTAR paper itself.
=> Fix some links in the read mapper overview slide

Gemfile.lock
1.13.2 seems to have disappeared since dependabot issued that PR, which broke our build.
=> bump nokogiri again

.github/workflows/video.yml, package.json
There's no version currently with this as a CLI option (even though there's a fork with it available) so we'll just update the script in place. This is normal. Nothing to see here. :grimacing:
=> upgrade the timeout for pages to load on GH machines

_plugins/snippet.rb, bin/ari-prep-script.rb, topics/admin/faqs/diffs.md, topics/admin/tutorials/ansible-galaxy/tutorial.md
By manually replacing them with BRs before the newline deleter can get
to them
This fixes issues that are currently live:
Before | after
--- | ---
=> Stop deleting newlines within pre blocks

_layouts/faq-page.html
It was showing the "general question" header (but not the Qs) on the topic-level FAQ pages
=> [FAQs] Show general Qs only on tutorial-level FAQS

topics/dev/tutorials/core-contributing/__init__.py_diff.md, topics/dev/tutorials/core-contributing/tutorial.md
Suggested change for the "Contributing a New Feature to Galaxy Core" tutorial. Moving the table definition from `mapping.py` to `__init__.py`. Also, I think it should be noted that python 3.7 is required for FastAPI.
=> Update core-contributing tutorial

topics/contributing/tutorials/github-interface-contribution/tutorial.md
Changing broken links found within the “[Contributing with GitHub via its interface](https://training.galaxyproject.org/training-material/topics/contributing/tutorials/github-interface-contribution/tutorial.html)” tutorial page. The GTN Repository link within the page does not open the GitHub page instead it loads the same page (tutorial page).
- Changed the link of the GTN Repository found under the “Introduction” section Line 2 in a parentheses
- Changed the link of the GTN Repository found under the “GitHub” section first line (the one that says “The GitHub repository for the training material is:”)
- Changed the link of the GTN repository found under “Hands-on: Familiarization with GitHub” first line (the one that says “Go on the GitHub repository:”)
=> Changing broken links within a tutorial page

faqs/galaxy/datasets_icons.md
The following Pull Request is a part of the Issue: _Move FAQs to GTN_ of the [Galaxy_Hub repository](https://github.com/galaxyproject/galaxy-hub).
I have added the dataset icons in the GTN.
=> [FAQs] Added Datasets Icons in GTN

faqs/galaxy/histories_unsharing_histories.md
The following Pull Request is a part of the Issue: Move FAQs to GTN of the [Galaxy_Hub repository](https://github.com/galaxyproject/galaxy-hub).
I have added [Find Histories that have been shared with you, and unshare those not needed](https://galaxyproject.org/support/account-quotas/#find-histories-that-have-been-shared-with-you-and-unshare-those-not-needed) in the GTN.
=> [FAQ] Added unsharing of histories

faqs/galaxy/tools_sorting.md
The following Pull Request is a part of the Issue: Move FAQs to GTN of the [Galaxy_Hub repository](https://github.com/galaxyproject/galaxy-hub).
I have added [Sorting your inputs](https://galaxyproject.org/support/sort-your-inputs/) in the GTN.
=> [FAQ] Added FAQ for sorting inputs for input errors

topics/introduction/tutorials/galaxy-intro-101/tutorial.md, topics/introduction/tutorials/galaxy-intro-101/workflows/galaxy-intro-101-workflow.ga
This PR replaces the tool [Replace first lines](https://usegalaxy.eu/root?tool_id=Show beginning1) by [Replace first lines (head)](https://usegalaxy.eu/root?tool_id=toolshed.g2.bx.psu.edu/repos/bgruening/text_processing/tp_head_tool/1.1.0). The reason is that the first tool doesn't work in usegalaxy.eu.
=> Galaxy 101: replace Select first lines tool

faqs/galaxy/histories_shared.md
The following Pull Request is a part of the Issue: _Move FAQs to GTN_ of the [Galaxy_Hub repository](https://github.com/galaxyproject/galaxy-hub).
I have added [A history was shared with me, where can I find it?](https://galaxyproject.org/support/missing-history/) in the GTN.
=> [FAQs] Added FAQ in GTN for finding/working on shared histories

faqs/galaxy/datatypes_tabular.md
There are 2 "Datatypes" areas, I guess that happens because one of them has the tag in capitals, but not sure. Trying to fix it here.
=> Fix capital in FAQ datatype area

.github/workflows/deploy.yml, _layouts/tutorial_hands_on.html, bin/filter-pyolite-safe, bin/schema-tutorial.yaml, jupyter/index.md, jupyter/lab/index.html, topics/contributing/tutorials/create-new-tutorial-content/tutorial.md, topics/data-science/tutorials/python-advanced-np-pd/tutorial.md, topics/data-science/tutorials/python-basics/tutorial.md, topics/data-science/tutorials/python-plotting/tutorial.md
The python notebooks *should* all work directly in JupyterLite with the pyodide kernel that runs in-browser. A lot of what we do is very very simple stuff. See their demo for what's possible: https://github.com/jupyterlite/demo 
So! Let's build jupyterlite into the GTN, and then connect specific, known-functional notebooks with that!
And then it's live immediately (ish. It's pretty slow to start but after it's fine.)
=> Add JupyterLite to GTN, launch python notebooks there

faqs/galaxy/datasets_chromosome_identifiers.md
I changed the first two links to the GTN FAQ links (Even though the first one was working changed both to make it consistent). The last two links added lead to the Galaxy Hub FAQ Page since it has no GTN FAQ link (If it shouldn't lead to the Galaxy Hub FAQ page then I can remove the link).
=> Fixing FAQ - Mismatched Chromosome identifiers and how to avoid them

faqs/galaxy/analysis_job_failure_input_problem.md
This PR is a part of the issue: _Move FAQs to the GTN_ ([Determining the job failure type](https://galaxyproject.org/support/tool-error/#determining-the-job-failure-type)) of the [Galaxy Hub Repository](https://github.com/galaxyproject/galaxy-hub)
Though this PR, can't be worked upon as it has reference from PR #3379 #3380 #3381 #3393 
Once the above-mentioned PR gets merged, I'll update the links here.
=> [FAQ] Added FAQ regarding input problems faced in job failures

faqs/galaxy/analysis_job_failure_excess_memory.md
This PR is a part of the issue: _Move FAQs to the GTN_ ([Determining the job failure type](https://galaxyproject.org/support/tool-error/#determining-the-job-failure-type)) of the [Galaxy Hub Repository](https://github.com/galaxyproject/galaxy-hub)
Though there is a reference to PR #3378. Once the PR gets merged, I'll update the link here.
=> [FAQ] Added FAQ for 'exceeds memory allocation' in job failure

faqs/galaxy/analysis_job_failure_walltime.md
This PR is a part of the issue: _Move FAQs to the GTN_ ([Determining the job failure type](https://galaxyproject.org/support/tool-error/#determining-the-job-failure-type)) of the [Galaxy Hub Repository](https://github.com/galaxyproject/galaxy-hub)
Though there is a reference to PR #3378. Once the PR gets merged, I'll update the link here.
=> [FAQ]  Added FAQ for walltime errors in job failure

faqs/galaxy/analysis_job_failure_value_error.md
This PR is a part of the issue: Move FAQs to the GTN ([Determining the job failure type](https://galaxyproject.org/support/tool-error/#determining-the-job-failure-type)) of the [Galaxy Hub Repository](https://github.com/galaxyproject/galaxy-hub)
=> [FAQ] Added FAQ related to ValueError in job failure

faqs/galaxy/analysis_job_failure_cluster_failure.md
This PR is a part of the issue: _Move FAQs to the GTN_ ([Determining the job failure type](https://galaxyproject.org/support/tool-error/#determining-the-job-failure-type)) of the [Galaxy Hub Repository](https://github.com/galaxyproject/galaxy-hub)
=> [FAQ] Added FAQ for 'canceled by admin' or a cluster failure in job failure

topics/transcriptomics/tutorials/ref-based/tutorial.md
Reorganized an option to match the current 2.0.1+galaxy2 Featurecounts tool form
Questions:
1. This creates a mismatch between the tool version in the tutorial (2.0.1) and the current version (2.0.1+galaxy2) at usegalaxy.* servers. 
2. I didn't change the tool version link yet -- should that be done?
3. What else needs to be changed if we do this -- the workflow? anything else
Ok to reject this -- not sure how it is decided what is worth updating versus not
=> Update ref-based tutorial.md

assets/js/main.js
replaces https://github.com/galaxyproject/training-material/pull/3435
This *should* survive reloads, as it uses the same mechanism as themes (which do).
=> Store CYOA choice in localstorage

faqs/galaxy/datasets_moving_datasets_between_galaxy_servers.md, faqs/galaxy/datasets_troubleshooting_custom_genome.md, faqs/galaxy/tools_tool_doesnt_recognize_any_input_datasets.md
1. Fixing moving datasets between Galaxy servers FAQ format as shown in the picture (adding on the destination text on a new line).
2. Replacing the link in Tool doesn't recognize any datasets of the section convert datatype because the link was for change datatype not convert datatype.
3. Adding a link in troubleshooting custom genome fasta FAQ as indicated in the text.
=> Fixing FAQ format and links

_includes/instance-dropdown.html, _includes/resource-video-library.html
Some videos are neither covering the slides or the tutorial directly, but are more of a quick demo or background video. We can now support these kinds of videos as well
=> Video library connecton: support "demo" type videos

topics/introduction/tutorials/galaxy-intro-101/tutorial.md
In `Hands-on: Sorting` replace the text 'output from **Group**' with 'output from **Datamash**'.  Group is not used in the tutorial, the grouping step is performed with Datamash.
=> Fix an error in Galaxy 101 tutorial

topics/transcriptomics/tutorials/ref-based/workflows/deg-analysis.ga
This PR includes the following changes:
- modifies the DESeq2 factor level groups in order to fix the following error:
`parameter 'groups': invalid options ('paired') were selected (valid options: untreat,treat,single.counts,paired.counts)
`
- changes the output format to *tabular* of the Concatenate output in order to fix the following error:
`
parameter 'field2': requires a value, but no legal values defined
`
=> Reference-based RNA-Seq data analysis: fix DEG workflow

topics/galaxy-interface/tutorials/workflow-reports/workflows/galaxy-101-everyone.ga
we use the png output for the report but it appeared to be hidden by default
=> Workflow Reports: update worfklow to not hide PNG output

faqs/galaxy/workflows_publish.md, topics/contributing/tutorials/create-new-tutorial/tutorial.md
For completeness, technically you do have to publish it until galaxyproject/galaxy#14348 is deployed.
=> Add instructions to make workflow accessible in the creating tutorial tutorial

topics/transcriptomics/tutorials/scrna-case_alevin-combine-datasets/tutorial.md
=> fix alevin combine

_includes/resource-handson.html, _includes/resource-workflows.html, _includes/resource-zenodo.html, _includes/tutorial_list.html, _plugins/jekyll-jsonld.rb, assets/css/main.scss
This PR is borne of two separate instances:
- I was annoyed at trying to find the tutorial link on mobile, I had to scroll left and right which felt ridiculous
- I watched a novice user try and click the tutorial title and was surprised when it went nowhere.
It links to the hands on, if one is present, otherwise to the slides.
Small Screens | large screens
--- | ---
=> A nicer layout for mobile

topics/variant-analysis/tutorials/microbial-variants/tutorial.md
Removed one extra leading space from each get data snippet's zenodo URL. Was five spaces, now four spaces, and fixes batch copy/paste into Upload tool.
=> Fix FTP links microbial-variants

_includes/extras.html, bin/prepare_feedback.py, feedback.md, metadata/feedback.csv
This adds a link back to the GTN tutorial from the cards on the feedback page (fixes https://github.com/galaxyproject/training-material/issues/2987)
And fixes the links from the "Extras" menu on tutorial and topic pages to just to the right section on the feedback page
=> Feedback: add links back to tutorial, fix links from tutorial/topic pages to the feedback

_layouts/tutorial_hands_on.html, assets/css/main.scss
currently it is not collapsible anymore, this brings it in line with all the other new and accessible boxes
ping @hexylena
=> [Tutorial Template] Use new-style details box for BibTex citation

faqs/galaxy/tools_similar.md, topics/introduction/tutorials/galaxy-intro-peaks2genes/tutorial.md
There are often mixups between tools for which many different tools with similar names exist (sort, cut, etc), and this FAQ recommends using tutorial more or checking of full tool name matches.
fixes https://github.com/galaxyproject/training-material/issues/3636 as reported by @gallardoalba
=> [FAQ] new FAQ to address potential mixup of tools with similar names

robots.html
as it also pollutes the search results and we do not need it
=> Tell robots to ignore archive

topics/dev/tutorials/visualization-generic/tutorial.md
fixes https://github.com/galaxyproject/training-material/issues/3288
@beatrizserrano I removed the links that are not working. I left two that still looked ok. Do you think these are still helpful of should I just remove them too?
=> [Dev] Generic Viz Plugins: remove broken links

_plugins/jekyll-jsonld.rb
Example:
```
"description": "The questions this  addresses are:\n - What is typing?\n - How does it improve code?\n - Can it help me?\n\n\\nThe objectives are:\n - Understand the utility of annotating types on one's code\n - Understand the limits of type annotations in python\n\n",
```
https://tess.elixir-europe.org/materials/hands-on-for-python-type-annotations-tutorial
=> Fix `\\n` appearing in JSON-LD rather than `\n`

_includes/contributors-line.html, _includes/news-card.html, _layouts/news.html
fixes https://github.com/galaxyproject/training-material/issues/3695
and also the issue where authors are no longer showing up on the news cards:
=> [News] Add dates to posts and fix an issue with author line on the card view

faqs/gtn/gtn_news_create_post.md, news.md, topics/contributing/tutorials/create-new-tutorial-content/tutorial.md
realized we don't have good instructions for this yet, and would be great to get contributors to write news posts when new tutorials are added, so now we have something to point them to
=> [FAQs] add an FAQ for creating a GTN news post

_layouts/tutorial_hands_on.html
currently author names missing from the "cite this tutorial" section if `contributions:` style metadata used
=> [Template] support new contributions metadata in "cite this tutorial"

_layouts/base.html
TeSS' scraper complains about invalid HTML (although seems to cope regardless):
```
ERROR <https://training.galaxyproject.org/training-material/topics/admin/tutorials/job-destinations/faqs/>: 354:5: ERROR: That tag isn't allowed here  Currently open tags: html, body.
<script type="text/javascript" src="/training-material/assets/js/jquery.slim.min.js"></script>
^
```
=> Move `script` tags inside `body`

topics/metagenomics/tutorials/mothur-miseq-sop/content.md
currently the new style boxes are broken in the 16S tutorials because of it's custom file structure
fixes https://github.com/galaxyproject/training-material/issues/3746
=> [Metagenomics] 16S tutorial: add a layout so it is recognized as a page for boxify plugin

.github/workflows/ci.yml
until I've had time to turn it into a proper CYOA tutorial (since all PRs are failing on html proofer on the `content.md` file thats a bit weird an non-standard
=> ignore 16S tutorial in html-proofer

.github/workflows/video.yml
Allow the docker image to write out pdfs - failing at present.
=> add write permissions for pdfs to video action

topics/introduction/tutorials/igv-introduction/tutorial.md
as more up to date resources to learn IGV exist like their website, and this particular tutorial is not up to GTN standards.
Fixes https://github.com/galaxyproject/training-material/issues/1892
=> Moving IGV introduction tutorial to draft mode

topics/admin/tutorials/ansible-galaxy/tutorial.md, topics/admin/tutorials/interactive-tools/tutorial.md, topics/dev/tutorials/interactive-environments/slides.html
So students can now check truly *all* logs from one place (gravity/systemd pending)
- galaxy
- slurm
- nginx
- pulsar
- rabbitmq
- etc
(I guess if we move to dockerized rabbitmq, that would be a step backwards in logging unification)
=> Move nginx logging to syslog/journalctl

topics/transcriptomics/tutorials/mirna-target-finder/tutorial.md
The overexpressed/repressed transcripts were swapped in the former version. It fixes the mRNA section (sorry, I forgot to include it in the previos PR https://github.com/galaxyproject/training-material/pull/3775).
=> Arabidopsis transcription training: fix missing details

assets/css/main.scss
The `border: none` caused it to have no outline under firefox's high contrast mode.
By adding this invisible border, we can then be sure it'll get a black outline.
After | Before
--- | --
=> Add invisible border to tab

assets/css/main.scss
This PR fixes the following error:
```
/home/galaxy/anaconda_ete/envs/galaxy_training_material/envs/galaxy_training_material/share/rubygems/gems/jekyll-sass-converter-3.0.0/lib/jekyll/converters/scss.rb:175:in rescue in convert': Can't find stylesheet to import. (Jekyll::Converters::Scss::SyntaxError) make: \*\*\* \[Makefile:75: serve-quick\] Error 1
```
=> Fix bug base urls

topics/transcriptomics/tutorials/ref-based/tutorial.md, topics/transcriptomics/tutorials/ref-based/workflows/deg-analysis.ga
At usegalaxy.eu we have received several bug reports of users trying to run the Compute step of the tutorial with version 2.0 of the tool instead of the desrcibed version 1.6.
Turns out the newer version catches a bug in the tutorial that the old version swallowed silently: for the goseq step you want True/False classification of *all* gene IDs investigated, but DeSeq2 emiits adjusted p-values of "NA" for the least significant genes and for those the expression `bool(c7<0.05)` cannot be computed. The old tool version just skips these lines meaning not all gene IDs were making it into the goseq analysis.
The new tool version can be configured to retain all lines and classify them correctly.
=> Update Compute tool to latest version

topics/contributing/tutorials/create-new-tutorial-content/tutorial.md
When icons are included in the text of the tutorial, there is an error with generated Jupyter Notebook which says: "The editor could not be opened due to an unexpected error: Unexpected token f in JSON at position XXXX".  I tested out that it's due to the icon symbols, so just wanted to point that out and save people's time on debugging :)
=> Icons in Automatic Jupyter Notebooks

_includes/extras.html, _layouts/base.html, _layouts/base_slides.html, _plugins/gtn.rb, _plugins/gtn/scholar.rb, _plugins/jekyll-scholar.rb, assets/js/main.js, assets/js/theme.js, references.md
This prevents the flash of white between page loads by changing around how the theme is set. Before we waited for the document to be loaded to change the theme (bad)
Now we change it as soon as the `<body>` element is there, and then handle setting up buttons later on once jquery is loaded (not time sensitive.)
=> Accelerate theme loading, experiment collecting "top cited papers"

assets/js/theme.js
To avoid confusion experienced by e.g. @mvdbeek where I'm guessing he landed on a non-home page without the tip box.
=> Only activate theme on home page landing

faqs/galaxy/account_create.md, faqs/galaxy/account_reduce_quota_usage.md, faqs/galaxy/analysis_differential_expression_help.md, faqs/galaxy/troubleshooting_cluster_failure.md, faqs/galaxy/troubleshooting_excess_memory.md, faqs/galaxy/troubleshooting_input_problem.md, faqs/galaxy/troubleshooting_value_error.md, faqs/galaxy/troubleshooting_walltime.md
Due to how we strip metadata from the compiled content object in the template. The list based redirect_from, combined with some of the whitespace led to the rest of the content being in a UL and the regex replace not capturing it properly
=> Fix truly cursed parsing failure

_layouts/home.html, _plugins/api.rb, _plugins/jekyll-topic-filter.rb, bin/lint.rb, faqs/gtn/gtn_workflow_testing.md, manifest.json
- makes the "how to change theme" a bit more prominent" due to a comment received
- adds a manifest.json for PWA support (this doesn't really do anything, but users can click on it and "add to homescreen" in android which. I guess is a thing, maybe someone really loves the GTN like that :sweat_smile:)
- Improves API to include more information in individual tutorial APIs (previously restricted to topic API)
- Workflow creator metadata (name + orcid), license now mandatory
- Workflow tests now mandatory
=> Miscellaneous stuff

topics/single-cell/tutorials/scrna-umis/tutorial.md
Figure 5 in this tutorial shows two genes each with two transcripts. gene 1 has UMI coloured pink and blue. Gene 2 has pink and green. The text, though, describes Gene 2 as being brown and green. This may be confusing to some students. The commit here changes the tutorial text so that Gene two is described as pink and green. The alternative would be to edit Figure 5?
=> Update tutorial.md - suggested rewording to match figure 5

topics/single-cell/tutorials/scrna-case_alevin-combine-datasets/tutorial.md
I'm currently proofing this tutorial for Smorgasbord 2023 and experiencing difficulties in getting the dataset into galaxy.org.
- Zenodo transfers are failing on the transfer files
- importing a history from usegalaxy.eu is complicated 
Workaround: propose additional link to a newly created history on galaxy.org This holds the data from @nomadscientist usegalaxy.eu history including the #tags
=> Change to import history text

topics/admin/tutorials/pulsar/tutorial.md
Add consumer_timeout to rabbitmq_config and make sure rabbitmq role is run after nginx. There are still problems as the container continually restarts and the container log complains about not being able to read `/etc/ssl/user/privkey-rabbitmq.pem` which is owned by root with 640 permissions. After changing permissions on that file to 644, the docker container is able to stay up, but I imagine the proper solution is for the file to be owned by somebody else (rabbitmq?)
TODO: job conf diffs will be different as this takes place after the job destinations tutorial.
=> More pulsar tutorial updates for GAT2023

topics/admin/tutorials/ansible-galaxy/tutorial.md
Fix a few typos in the "Galaxy Installation with Ansible" tutorial.
=> Fix typos in "Galaxy Installation with Ansible" tutorial

topics/admin/tutorials/apptainer/tutorial.md
Now that the Ansible-Galaxy tutorial does not use job_conf.yml.j2, neither should the Apptainer tutorial.
=> Don't use job_conf.yml.j2 in the Apptainer tutorial

topics/admin/tutorials/ansible-galaxy/tutorial.md, topics/admin/tutorials/apptainer/tutorial.md, topics/admin/tutorials/backup-cleanup/tutorial.md, topics/admin/tutorials/celery/tutorial.md, topics/admin/tutorials/connect-to-compute-cluster/tutorial.md, topics/admin/tutorials/cvmfs/tutorial.md, topics/admin/tutorials/data-library/tutorial.md, topics/admin/tutorials/ftp/tutorial.md, topics/admin/tutorials/job-destinations/tutorial.md, topics/admin/tutorials/monitoring/tutorial.md, topics/admin/tutorials/pulsar/tutorial.md, topics/admin/tutorials/reports/tutorial.md, topics/admin/tutorials/tiaas/tutorial.md, topics/admin/tutorials/tus/tutorial.md
You unfortunately have to `sudo systemctl start gravity-tusd` for now after installation until I fix this in Gravity (`galaxyctl graceful` intentionally does not restart tusd, but it should start it if it's not running).
=> Run tusd with gravity

topics/admin/tutorials/celery/tutorial.md, topics/admin/tutorials/ftp/tutorial.md, topics/admin/tutorials/job-destinations/tutorial.md, topics/admin/tutorials/monitoring/tutorial.md, topics/admin/tutorials/pulsar/tutorial.md, topics/admin/tutorials/reports/tutorial.md, topics/admin/tutorials/tiaas/tutorial.md
When tpv is added, environments are removed, including local_env.
the mapping:
```
>       tools:
>         - class: local # these special tools that aren't parameterized for remote execution - expression tools, upload, etc
>           environment: local_env
```
needs to be removed at this point or data fetch jobs fail. Another mapping (testing tool to tpv_dispatcher) is added later in the tutorial.
Making this a draft PR as I'm not sure how to handle the diffs here and later on.  Can we leave the tools section empty like so?
```
tools:
```
=> keep local_env in galaxy_job_config when tpv_dispatcher is added

topics/admin/tutorials/ansible-galaxy/tutorial.md
- Make the `.gitignore` tip part of the hands-on. Fix https://github.com/galaxyproject/training-material/issues/4029 .
- Add missing `git config` command to properly view secrets diffs
- Add more explanations.
=> Git-related improvements to Ansible-galaxy tutorial

topics/admin/tutorials/tiaas/tutorial.md
The `training.*` role had all of its settings within a rule without an `- if` condition, meaning that the rule was never matched and the settings were not applied.
=> fix tiaas role in tiaas/tutorial.md

.github/workflows/ci.yml
Turns out that ready_for_review is all we need. review_requested just causes an extra action run (that gets cancelled then) on opening regular PRs and on moving draft PRs out of draft stage.
=> Remove review_requested from list of ci triggers

topics/genome-annotation/tutorials/apollo/slides.html
Fixing the display of this slide: https://training.galaxyproject.org/training-material/topics/genome-annotation/tutorials/apollo/slides.html#7
=> Apollo slides: fix overlapping text

topics/statistics/tutorials/machinelearning/data-library.yaml, topics/statistics/tutorials/machinelearning/tutorial.md
- Fix datatype of library files. The `sklearn_svm_classifier` only supports `tabular` files.
- Add tool ids to hands-on sections.
- Fix accessibility of a link.
- Misc small fixes/improvements.
=> Fixes for the "Basics of machine learning" tutorial

topics/variant-analysis/tutorials/trio-analysis/tutorial.md, topics/variant-analysis/tutorials/trio-analysis/workflows/main_workflow.ga
Updated the PyEGA version in the workflow and tutorial.
I want everything in the div box in EGA to be not visible when clicking on Zenodo. But with the previous version it still showed everything. I'm hoping this fixes it.
=> Update PyEGA to version 5 and remove EGA track if Zenodo track is chosen.

_plugins/gtn.rb, bin/workflow-test.rb
The assembly/largegenome WFs used capital letters, I missed that I'd run `downcase` on the workflows in the TRS API endpoint we created, so this caused an issue. Now the filter does the downcasing resulting in matching IDs.
=> Fix TRS import for workflows with capital letters

topics/fair/images/ro-crate-intro/crate1-folders.svg
There was a bug in the previous SVG as the selectable-text layer was visible, as well as the rendered-text layer.
=> avoid double-fonts in RO-Crate SVG

_includes/extras.html, topics/fair/tutorials/fair-intro/tutorial.md
Fixed two minor typos.
I also noticed that the "edit on github" link is broken on https://training.galaxyproject.org/training-material/topics/fair/tutorials/fair-intro/tutorial.html, there's a `/` missing
=> FAIR intro: fix typos

galaxy_instances.yaml, news/_posts/2023-06-07-pan-galactic-search.md, search-tools.html
which I completely forgot existed (and is like, halfway impossible to find.) only findable if you know the name https://galaxyproject.org/search/?q=galaxycat#gsc.tab=0&gsc.q=galaxycat but hopefully the GTN can help the SEO here a bit.
=> Point tool search users to the GalaxyCat

CONTRIBUTORS.yaml, _plugins/jekyll-webfinger.rb, bin/schema-contributors.yaml
This can make it easier to announce news on the fedi, as we can write things like "Thanks @abretaud@training.galaxyproject.org" and it'll mention @abretaud's account :)
requires https://github.com/galaxyproject/infrastructure-playbook/pull/44
=> add a Webfinger endpoint, allowing mentioning fedi users by GTN handle

topics/evolution/tutorials/mtb_transmission/tutorial.md
Updating Identifying tuberculosis transmission links: from SNPs to transmission clusters, 
Analysis Part 2 under "Clean up the table",
In step 1. Replace Text Tool: 
“File to process”: Single file (output of Concatenate datasets tool)  should refer to the previous step, which was "Collapse Collection" so it would clear up any confusion.
=> In Identifying tuberculosis - Changed Concatenate datasets to Collapse Collection on data

_includes/pathway-card.html, assets/css/main.scss, learning-pathways/admin-training.md, learning-pathways/genome-annotation-eukaryote.md, learning-pathways/genome-annotation-prokaryote.md, learning-pathways/index.md, learning-pathways/intro-to-galaxy-and-ecology.md, learning-pathways/intro-to-galaxy-and-genomics.md, learning-pathways/intro-to-r-and-ml.md, learning-pathways/metagenomics.md, learning-pathways/pathway-example.md, learning-pathways/train-the-trainers.md
Now that we have a fair number of learning pathways, we should display them a bit more efficiently
This groups them by topic (science, dev/admin, instructors, like the topics) and shows them as smaller cards
=> Update Pathways Page

topics/admin/tutorials/backup-cleanup/tutorial.md
`gxadmin galaxy cleanup` requires some python scripts which require dependencies installed in the virtual env unless these are all covered by pre-task? If the latter is the case please ignore and close. If not, then it's possible better to move this to one of the `galaxyproject.galaxy` tasks?
=> Small update to cron job for cleanup

topics/single-cell/tutorials/scrna-case_JUPYTER-trajectories/tutorial.md
Please see https://github.com/igraph/python-igraph/issues/699 for why this is necessary.
=> use igraph instead of python-igraph, as the latter name is deprecated for "pip install"

_plugins/notebook.rb
Utilises pre-existing code to convert images into base64 and embed them into the generated Jupyter notebook
=> Fixes #4305

_layouts/contributor_index.html
So you don't have to count them manually. Really only matters for funding agencies/reporting.
=> Add LPs to HoF chart

faqs/galaxy/datasets_upload_ftp.md
Since FTP is no longer supported on UseGalaxy.org, we are adding banners to let users know and direct them to alternatives.
=> Adding banner to show that FTP is no longer supported on UseGalaxy.org

assets/css/slides.scss
- Quick fix for overlapping icons on GTN.
- Related to [this issue](https://github.com/galaxyproject/galaxy/issues/16634) on the main Galaxy repo.
- Putting PR in "draft" until @shiltemann has time to preview.
- Preview of suggested change below:
=> Fix for tutorial nav back button

topics/variant-analysis/tutorials/tb-variant-analysis/tutorial.md, topics/variant-analysis/tutorials/tb-variant-analysis/workflows/tb-variant-analysis.ga
Minor update to TB Variant Analysis tutorial that updates tb_variant_filter version to 0.4.0. (The changes in the updated tool are not needed for this tutorial because it uses Snippy / FreeBayes VCF, but the update is made just to ensure we track the upstream tool version)
=> TB Variant Analysis: Update tb_variant_filter to v. 0.4.0

topics/admin/tutorials/stop-worrying-love-systemd/tutorial.md, topics/data-science/tutorials/python-multiprocessing/tutorial.md
=> Misc systemd, python tutorial fixes

topics/contributing/tutorials/create-new-tutorial-content/tutorial.md
This is super minor, but useful for tutorial creators to remember how to internally link to other tutorials without just copying the actual link.
=> Add internal linking section

topics/admin/tutorials/ansible-galaxy/tutorial.md, topics/dev/tutorials/interactive-tools/tutorial.md
I noticed that the IT tutorial (missing config file) and the ansible galaxy tutorial (conda cannot resolve) do not work out of the box anymore. This PR proposes necessary corrections and version updates so that the tutorials work with the current version of Galaxy.
=> Fix fatal errors in GxIT and ansible tutorials

_plugins/jekyll-figurify.rb
yeah this was wrong semantically. we should have something in the pipeline to check the validity of our html at some point eh, we have a number of complaints on [w3's validator](https://validator.w3.org/nu/?doc=https%3A%2F%2Ftraining.galaxyproject.org%2Ftraining-material%2Ftopics%2Fintroduction%2Ftutorials%2Fgalaxy-intro-short%2Ftutorial.html). At least half will be fixed by this PR.
We have an "html-validator" ruby library as part of the GTN but that's actually quite misleading, it doesn't validate the whole HTML, just parts of it :/
=> fix figcaption complaints

_includes/analytics.html, _includes/extras.html, preferences.md
they were not being loaded properly as a result of my user-preferences changes, I thought they were but nah. So this changes how it works, instead of conditionally loading the javascript, it's always loaded and we use two different opt-ins, namely setting the plausible specific variables + sentry-init.
=> Fix analytics

_plugins/jekyll-tool-tag.rb, assets/css/main.scss
cc @nomadscientist @lldelisle  we've discussed this in the past but it continues to be an issue so time to finally do it. It's a bit more verbose, but tutorials are already verbose, and reproducibility of using the correct tool version is more important.
=> Add tool version to tool buttons

topics/admin/tutorials/ansible-galaxy/tutorial.md
@natefoo this is why it didnt work during gat
=> fix ansible-vault diff

Gemfile, Gemfile.lock, Makefile, _plugins/api.rb, _plugins/gtn.rb, _plugins/gtn/mod.rb, _plugins/jekyll-topic-filter.rb, _plugins/notebook.rb
Based on the example by @supernord, fyi @uwwint
This currently doesn't feel terribly complete, e.g. 
- no workflow is directly mentioned (we can point to a URL? how do we do that?), should that look like the example here? https://www.researchobject.org/ro-crate/1.1/workflows.html#complete-workflow-example
- Should we provide a zip? is that the useful artefact for WFH, or is the json fine (and it will lookup/fetch the galaxy workflow file itself)
- Not sure what we should do about the `version` field, that's... complicated to detect a good linear number over time. We could probably detect # of commits to that file and use that as the version, probably the safest to ensure changes are detected properly.
- and of course, how do we get that into WFH.
=> Export ro-crate-metadata.json for building RO Crates of the Workflows

_includes/analytics.html
might give us some useful data in plausible/google search console on how folks are finding the GTN and what phrases they're using.
=> add gsc verificaiton

_config.yml, _layouts/tutorial_hands_on.html, _plugins/gtn.rb
for all tutorials. It can give a teacher a feeling of "is this material being updated over time or just dumped in"
screenshot from galaxy intro for ansible
=> expose version number

FUNDERS.yaml, _layouts/base.html, _layouts/faq.html, _layouts/learning-pathway.html, _plugins/gtn/boxify.rb, _plugins/gtn/contributors.rb, _plugins/jekyll-jsonld.rb, bin/workflows-fetch.rb
- adds version field
- improved educational roles
- separate out contributors
- remove redundant "Hands on for "X"' which is just excessive
- standardised draft status
=> Improve TeSS scraping

Makefile
The [GTN tutorial on viewing the site locally](https://training.galaxyproject.org/training-material/topics/contributing/tutorials/running-jekyll/tutorial.html) basically says that one should run
1. `make create-env`
2. `make install`
after installing Conda. I have a fresh local clone of the repository. Both steps yield an out of memory error on my system (see #4313). When using mamba instead of conda, everything works.
This PR proposes to use mamba in Makefile if it is available, and conda otherwise.
=> fixes Makefile, prefers mamba over conda if available

topics/imaging/tutorials/hela-screen-analysis/tutorial.md, topics/imaging/tutorials/imaging-introduction/tutorial.md
Updates the tools used in the tutorials
- `imaging-introduction`
- `hela-screen-analysis`
to use up-to-date tool names and parameters.
xref https://github.com/usegalaxy-eu/usegalaxy-eu-tools/pull/646
xref https://github.com/usegalaxy-eu/usegalaxy-eu-tools/pull/643
xref https://github.com/usegalaxy-eu/usegalaxy-eu-tools/pull/616
=> Updates imaging tutorials to up-to-date tool names and parameters

_layouts/base.html, _layouts/base_slides.html, _layouts/base_slides_ai4life.html, _layouts/embed.html, workflows/embed.html, workflows/list.html
Fixes https://github.com/galaxyproject/training-material/issues/4494
This does not implement a proper query language which would be more expensive to execute, instead we supply a simpler set of filters:
- all: must include all of these terms
- any: includes *at least one* of these terms
- none: reject anything with these terms.
E.g. `?all=single-cell&any=mehmet+wendi` would find workflows either by @nomadscientist or @mtekman.
Again this doesn't implement a query language that supports arbitrarily complex queries, we keep it simple.
Also includes some changes to the templates to read `page.description` for a better blurb, and more uniform image loading.
=> Improved workflow listing query language

_plugins/jekyll-topic-filter.rb
Found in https://github.com/galaxyproject/training-material/pull/4064, we checked that the filename was actually `tutorial.md` precisely, which isn't a good testing mechanism. This fixes that with a more generic test. We can probably drop the filename test, but, just to be conservative it's kept.
=> More defensive layout testing

Makefile, _plugins/api.rb, _plugins/gtn/toolshed.rb, _plugins/jekyll-topic-filter.rb, bin/fetch-categories.rb
cc @lldelisle
fixes #4513 
depends on:
Demo using data from those three PRs, for the atac-seq tutorial:
quite a bit nicer than all going to "Epigenetics"
=> Implement nicer categories for toolshed install instructions

CONTRIBUTORS.yaml
Adds an affiliation field for my entry in CONTRIBUTORS.yaml, adding uni-freiburg.
=> Add uni-freiburg affiliation for ElectronicBlueberry

topics/metagenomics/tutorials/metagenomics-binning/tutorial.md
Adding microGalaxy tag to the new training
Thanks a lot :)
=> adding microGalaxy tag to the new training

_includes/default-header.html, _includes/extras.html, assets/css/main.scss, user/privacy.md, user/theme.md
Fixes #4572
this should help make it easier for (new) users to locate the correct setting to toggle.
=> Improve 'extras' menu by renaming, making theme choice more explicit

.github/workflows/ci-main.yml, .github/workflows/matrix.yml, _layouts/base.html, _layouts/base_slides.html, _layouts/slides-plain.html, _layouts/tutorial_hands_on.html, _layouts/workflow-list.html, _plugins/gtn.rb, _plugins/gtn/mod.rb, _plugins/jekyll-bundler.rb, _plugins/jekyll-jsonld.rb, _plugins/jekyll-scholar.rb, _plugins/jekyll-topic-filter.rb, assets/css/main.scss, search-tools.html, search.md, search2.html, stats/index.md, workflows/list.html
- improve `<title>` for search pages
- improve OG settings for all pages, removes duplicate "GTN Tutorial: " that wasn't necessary since the 'owner' is shown just above it.
- Fix news based on `--first-parent` in the diff to ensure we're really only selecting new things on the right branch
- Leverage `--first-parent` plus tracing renames to give us the 'first published' date for each material, when it hit the main branch.
- Expose that everywhere, including json-ld.
- Update stats page to show both recently added + modified as two separate lists
=> Misc improvements

_config.yml, faqs/galaxy/histories_transfer_entire_histories_from_one_galaxy_server_to_another.md
=> fix icon names

bin/lint.rb, topics/contributing/tutorials/create-new-tutorial-content/tutorial.md
xref https://github.com/galaxyproject/training-material/pull/4581
=> Add linting for an unknown icon

_config.yml, _plugins/author-page.rb, _plugins/gtn.rb, _plugins/gtn/contributors.rb, topics/contributing/tutorials/create-new-tutorial-content/faqs/icons_list.md, topics/contributing/tutorials/create-new-tutorial-content/tutorial.md
to make them a bit nicer for contributors
=> de-dupe icons

.github/workflows/scrna-galaxyhelp-matrix.yml, bin/galaxy-help-news.sh
This is a Matrix bot written in Bash to fetch posts from https://help.usegalaxy.org that match certain tags, filter for less than N replies and post a nicely formatted table to a Matrix room of your choice.
Inspired by a great idea from @pavanvidem and @nomadscientist , and inspired further by @hexylena's Ruby bot.
I'm not sure if I'm adding it to the right location in the file system, or how/where to deploy it (other than running it from my own account on my own system), but here goes.
=> Add UseGalaxy Help Forum to Matrix channel Bot

_includes/tutorial_list.html
Tutorials that are in draft mode can still be shown when the entire page (e.g. topic or learning pathway) is also in draft mode
=> Display draft materials on draft pages (draft topics, LPs)

.dockstore.yml
Hello,
I am a software developer at Dockstore and we are approaching our 1.15 release.
Prior to this release, relative paths were being inconsistently and unreliably processed in various parts of our system.
Therefore, in this release, we have more explicitly deprecated the use of relative file paths in our `.dockstore.yml` so all workflows with relative paths will now be deemed as invalid.
Thus, I have created this PR to change the file paths to absolute paths such that your workflows will still be valid after our release.
If you have any questions, please feel free to comment below.
Thank you!
Nayeon - Dockstore
=> .dockstore.yml: Change relative file paths to absolute paths for Dockstore 1.15 

CONTRIBUTORS.yaml, topics/admin/faqs/data-source-with-pulsar.md
This tripped me up and I felt it would be useful for other small Galaxy admins.
=> FAQ for using data sources tools with Pulsar as default

_plugins/jekyll-topic-filter.rb, utils/stellar-nursery.md
based on a discussion with @shiltemann, it would be a resource we can point new contributors to, and they could discover tutorials they may want to work on.
It's an ugly table but I think that's fine, even a good thing, in this case, to help show that it's not a resource we want people looking at, more a place for "maintainer notes" or so.
=> Implement stellar nursery

topics/assembly/tutorials/mrsa-illumina/data-library.yaml, topics/assembly/tutorials/mrsa-illumina/tutorial.md, topics/assembly/tutorials/mrsa-illumina/workflows/main_workflow-test.yml, topics/assembly/tutorials/mrsa-nanopore/data-library.yaml, topics/assembly/tutorials/mrsa-nanopore/tutorial.md
Fixes https://github.com/galaxyproject/training-material/issues/4730
=> Fix odd bzip2 record

topics/admin/tutorials/apptainer/tutorial.md, topics/admin/tutorials/celery/tutorial.md, topics/admin/tutorials/connect-to-compute-cluster/tutorial.md, topics/admin/tutorials/customization/tutorial.md, topics/admin/tutorials/cvmfs/tutorial.md, topics/admin/tutorials/data-library/tutorial.md, topics/admin/tutorials/ftp/tutorial.md, topics/admin/tutorials/job-destinations/tutorial.md, topics/admin/tutorials/monitoring/tutorial.md, topics/admin/tutorials/pulsar/tutorial.md, topics/admin/tutorials/reports/tutorial.md, topics/admin/tutorials/sentry/tutorial.md, topics/admin/tutorials/tiaas/tutorial.md, topics/admin/tutorials/tus/tutorial.md
Based on a recent pull request which was requesting support, and some help forum posts recently which are on a specific server that requires being contacted for tool support
Here we add a small section encouraging admins in training to configure the support and ToS URLs.
@jennaj would you like us to say anything specific in the tutorial? Can you check the wording in this patch for me to see if you think it will be useful?
Given @nomadscientist's [issue](https://github.com/galaxyproject/galaxy/issues/17362), I personally find that the semantic distance between "galaxy help" and "support" is approximately 0 if you squint at it, so I look forward to the conclusion of her issue  when we find a good solution to those, but maybe in the interim this is a good way to push users to useful places. …
=> Add support url to customisations tutorial for GAT

topics/fair/tutorials/ro-crate-intro/tutorial.md
There were two typos in the RO Crate Intro tutorial, in URLs for the RO Crate docs webpages.
=> fixes broken RO Crate documentation links

topics/galaxy-interface/tutorials/galaxy-intro-jupyter/tutorial.md
Changed mentions of the RNA-seq file suffix from ".count" to ".counts" to match up with the actual linked file.
=> Typo fix in "Use Jupyter notebooks in Galaxy" tutorial

_plugins/jekyll-tool-tag.rb
This reverts commit dcbb34f3fc316c4bf869588d25cfbcfe4efc6235.
fixes #4767
=> Revert "Swap for semantic a, provide href"

_config.yml, _layouts/base.html, _layouts/home.html, _plugins/jekyll-bundler.rb, _plugins/jekyll-mathjax.rb, bin/commit-cache-update.rb
since it's a chonker. This also deprecates `list.min.js` which I *think* is not used anywhlere but I am not completely sure yet, so we wait to see if Sentry reports any complaints to properly remove it.
(this was pulling our load time metrics down a wee bit.)
```
$ du -h assets/js/* | sort -h
4.0K	assets/js/bootstrap-toc.min.js
4.0K	assets/js/details-element-polyfill.js
8.0K	assets/js/main.js
8.0K	assets/js/theme.js
12K	assets/js/clipboard.min.js
16K	assets/js/chartjs-plugin-datalabels@0.7.0.js
20K	assets/js/emfed
20K	assets/js/list.min.js
20K	assets/js/popper.min.js
52K	assets/js/bootstrap.min.js
60K	assets/js/chartjs-plugin-colorschemes.js
68K	assets/js/jquery.slim.min.js
144K	assets/js/leaflet-1.9.3.js
188K	assets/js/dompurify
568K	assets/js/Chart.bundle.js
652K …
```
=> Conditional loading of mermaid.js library

topics/introduction/tutorials/galaxy-intro-short/tutorial.md
Just seems like a really important tip to get across early on - then maybe we can remove it from the beginning of literally every tutorial I write...
{% snippet faqs/galaxy/tutorial_mode.md %}
=> Add tutorial mode to short intro to Galaxy

learning-pathways/beyond_single_cell.md
This is the second batch of training I give my interns when they are upskilling in single-cell analysis. This takes them from the intro towards an intermediate skillset, and points them towards resources for beginning the journey into a coding environment.
PS: I'm happy for this to be a 'hidden' page that we just have links to, so as to now crowd the general learning pathway page, as I know it isn't necessarily set up for a beginner/intermediate evolution. I just don't know how to make an available page hidden.
=> New learning pathway: Intermediate single cell analysis

topics/assembly/tutorials/vgp_genome_assembly/tutorial.md
hello! 👋🏼 changed some text in the VGP assembly tutorial by removing a comment callout box and integrating it into the main text.
=> [VGP assembly] removwd purge_dups comment box in genomescope section

topics/ecology/tutorials/MetaShARK_tutorial/tutorial.md
=> Update tutorial.md ameliorate details

topics/transcriptomics/tutorials/ref-based/tutorial.md
Choose your own tutorial for DESeq2 run. The current DESeq2 hands-on based on collection inputs with tags is not for everyone. It also needs 3 more steps to prepare the data for DESeq2. In most cases, users have only one factor with ~3 replicates to deal with. A basic datasets-based DESeq2 run should be sufficient.
=> Alternative DESeq2 hands-on for ref-based RNA-seq tutorial

CONTRIBUTORS.yaml, topics/fair/tutorials/ro-crate-in-python/tutorial.md
Hello again GTN team, a new job has brought me back :)
Suggesting these changes after following the tutorial myself:
- updated output of `get_entities()` because `./ Dataset` always appears first
- added "name" property to Donald Duck because if you re-export the crate and then continue with the tutorial, the name can appear as `None` when you print authors in a later section causing confusion
- switched bash commands to Python where possible so it's easier to follow along with the auto-generated notebook
- added explanation of what happens when including the `exp/logs` dataset in the crate
- added extra CLI commands
One question:
The command-line interface section has the student clone an entire repository just to get one folder of test data to run `rocrate` on. I think it'd be better to …
=> Improvements to RO-Crate in Python tutorial

topics/variant-analysis/tutorials/aiv-analysis/tutorial.md, topics/variant-analysis/tutorials/pox-tiled-amplicon/tutorial.md
The latest wrapper version of MAFFT allows generating MSAs of sequences from multiple input datasets.
This eliminates the need to concatenate those datasets as an extra step.
=> Simplify MSA generation steps in tutorials by using latest MAFFT version

topics/single-cell/tutorials/scrna-case_alevin/tutorial.md
Update made to Basic QC -Adding in Gene Metadata section under the Hands-on: Generate gene information section
Wording "Filter a FASTA-format cDNA file to match annotations?" has been updated to "Filter the cDNA file to match the annotations?" as per the GTF2GeneList tool
=> Fix wording under Basic QC>Adding in Gene Metadata

topics/microbiome/tutorials/nanopore-16S-metagenomics/tutorial.md
=> Fix spacing/indentation in nanopore 16s

topics/fair/tutorials/ro-crate-in-python/tutorial.md
The example of adding new files and directories to a crate (newly added in the latest `rocrate` release) is more widely applicable than adding workflow testing metadata, so I think it makes sense to switch to that for this tutorial. The other example will remain documented in the ro-crate-py repo for more advanced users.
=> RO-Crate in Python: Update CLI section to use simpler example and remove repeated cd commands

CONTRIBUTORS.yaml, topics/galaxy-interface/tutorials/upload-data-to-ena/tutorial.md
based on ena_upload_tool v0.7.1+galaxy1
Still a question about some links in there:
The link `toolshed.g2.bx.psu.edu/repos/iuc/ena_upload/ena_upload/0.6.1` does not exist. Can it be changed to a link to the latest commit (= tip), a link that does work: `https://toolshed.g2.bx.psu.edu/repos/iuc/ena_upload/rev/tip`?
Same goes for the link: `toolshed.g2.bx.psu.edu/repos/ieguinoa/ena_webin_cli/ena_webin_cli/7d751b5943b0` not working, I think it should be: `https://toolshed.g2.bx.psu.edu/repos/ieguinoa/ena_webin_cli/rev/tip`.
=> Update tutorial.md to match ENA upload tool wrapper update

.github/workflows/ci.yml, .rubocop.yml, bin/check-indent.rb, bin/lint.rb, topics/assembly/tutorials/vgp_genome_assembly/tutorial.md, topics/assembly/tutorials/vgp_workflow_training/tutorial.md, topics/computational-chemistry/tutorials/zauberkugel/tutorial.md, topics/ecology/tutorials/regionalGAM/tutorial.md, topics/ecology/tutorials/x-array-map-plot/tutorial.md, topics/introduction/tutorials/galaxy-intro-short/tutorial_ES.md, topics/single-cell/tutorials/scrna-data-ingest/tutorial.md, topics/single-cell/tutorials/scrna-ncbi-anndata/tutorial.md, topics/transcriptomics/tutorials/rna-seq-counts-to-genes/tutorial.md
Remove spaces in front of zenodo file names, because if not, the files may not upload correctly in Galaxy. 
I think this formatting still looks ok in the preview but could someone else also check, thanks.
=> Remove spaces in front of zenodo file names in VGP tutorial

_plugins/jekyll-bundler.rb, _plugins/jekyll-webfinger.rb, _plugins/sitemap.rb
This cherry-picks a commit from #4896 which moved some more bundling functionality to prod-only, But still in dev environments we need the JS loading properly. Which means bundling, or, synchronous loading. So we opt for that.
Fixes https://github.com/galaxyproject/training-material/issues/4897
=> Fix js loading in dev environments

_layouts/topic.html, _plugins/feeds.rb, _plugins/gtn/mod.rb, _plugins/jekyll-topic-filter.rb, feed.xslt.xml
it works. Per-topic RSS feeds announcing new (only, not updated) materials.
We could add more for e.g. updated materials per topic, all material changes, just let us know what's useful.
=> per topic rss feeds

_includes/resource-handson.html, _includes/resource-slides.html
On GTN，when checking the **Curated translations** of Slides and Hands-on，will see blank content, like this:
this pull request fixes the bugs.
=> fix bug for curated translations display

topics/assembly/tutorials/vgp_workflow_training/tutorial.md
These are not the latest versions. Added a note about this, and link to latest versions.
We could always add in the latest versions but would need to test them with this data set. There may also be a way to automatically link in new versions as they get updated? 
But for now I just wanted to put in a note about the versions of these in case people use them for actual analysis.
=> Add note about workflow versions in this tutorial

topics/genome-annotation/tutorials/annotation-with-prokka/tutorial.md, topics/genome-annotation/tutorials/annotation-with-prokka/workflows/Galaxy-Workflow-Workflow_constructed_from_history__prokka-workflow_.ga
- Updated the workflow to change one of the inputs to Jbrowse. 
- It was using `contigs.fasta` as input where it should have been using the output from prokka (the `fna file`). 
- I edited the workflow in Galaxy, downloaded as a `workflow.ga` file, then copied that text to overwrite the existing workflow file in the repo. (For some reason couldn't directly upload the `workflow.ga` file). 
- The version of Jbrowse has also changed in the workflow. 
- I don't think these changes affect the existing workflow tests. 
- Thanks, Anna
=> update annotation workflow with correct input to JBrowse

topics/fair/tutorials/bioimage-REMBI/tutorial.md
A small mistake found in preparations for the training event. 
Objective value fixed in image acquisition section.
@kkamieniecka
=> Bioimaging tutorial typo fixed

topics/assembly/tutorials/vgp_genome_assembly/tutorial.md
The snippet was pointing to fasta instead of cmap. 
Also removed the line "in case you forgot" above it since we don't use similar ones for the other snippets.
=> Fixed a "import with link" snippet that was using the wrong format

_includes/display_extra_training.md, _plugins/gtn.rb, _plugins/search.rb
xref #4956 
Screenshot | Comments
--- | ---
=> Simplify requirements display, fix duplicated hands-on

_includes/help.html, _layouts/base.html, _layouts/topic.html, assets/css/main.scss
Currently when viewing the training materials in (e.g.) arabic, it does not render correctly according to RTL expectations. 
Ignoring my lack of font support, everything is displayed incorrectly, on the left.
It should all be on the right, but note that the 'tab' on the box is still on the wrong side, it should be on the right.
This PR fixes that by replacing `-left` with `-inline-start` in the appropriate places and adding `dir="auto"` to ensure that if the GTN is loaded in an RTL language (through google translate) that we are giving the user the experience they are used to and expect.
See this for more details
https://firefox-source-docs.mozilla.org/code-quality/coding-style/rtl_guidelines.html
=> Fix our RTL support for RTL languages

.github/workflows/ci-main.yml, CONTRIBUTORS.yaml
since the change got missed in #4980 and has a key that's causing other PRs to fail.
=> ensure contribs/orgs/funders are linted

topics/genome-annotation/tutorials/lncrna/data-library.yaml, topics/genome-annotation/tutorials/lncrna/tutorial.md
Changes for "Long non-coding RNAs (lncRNAs) annotation with FEELnc)" tutorial :
- The input dataset all_RNA_mapped.bam was replaced by SRR8534859_RNASeq_mapped.bam
- This dataset was added in a new version (v2) of the data repository Zenodo :
https://zenodo.org/records/11367439
- Solution of the last question was also corrected because new results were obtained with this new dataset
Thanks in advance for the review :-)
=> updating tutorial with new bam file

_layouts/home.html
External events were not yet included in the events-list shown on the homepage
ping @hexylena
=> Add external events to eventstable on homepage

topics/single-cell/tutorials/scrna-case-jupyter_basic-pipeline/tutorial.md, topics/single-cell/tutorials/scrna-case_FilterPlotandExploreRStudio/tutorial.md, topics/single-cell/tutorials/scrna-case_FilterPlotandExplore_SeuratTools/tutorial.md, topics/single-cell/tutorials/scrna-case_JUPYTER-trajectories/tutorial.md, topics/single-cell/tutorials/scrna-case_basic-pipeline/tutorial.md, topics/single-cell/tutorials/scrna-case_monocle3-rstudio/tutorial.md, topics/single-cell/tutorials/scrna-case_monocle3-trajectories/tutorial.md, topics/single-cell/tutorials/scrna-case_trajectories/tutorial.md
I moved the toolsuite (i.e. seurat) from the () in each title to make it clearer that the () refers to the programming language
=> Change names to distinguish package and language

topics/variant-analysis/tutorials/tb-variant-analysis/tutorial.md
Due to the change from Trimmomatic to fastp some numbers changed:
* Snippy output number of variants called and number of reads supporting the first SNP
* TB Variant Filter number of variants filtered
=> Update tb variant analysis tutorial: fix some numbers

_plugins/snippet.rb, assets/css/main.scss, faqs/galaxy/workflows_import.md, faqs/galaxy/workflows_import_from_dockstore.md, faqs/galaxy/workflows_import_from_workflowhub.md, faqs/galaxy/workflows_run_ds.md, faqs/galaxy/workflows_run_trs.md, faqs/galaxy/workflows_run_wfh.md, news/_posts/2023-12-12-tutorial-run-wfh-ds.md, news/_posts/2024-03-28-by-covid-pathways.md, topics/contributing/tutorials/create-new-tutorial-content/tutorial.md, topics/transcriptomics/tutorials/minerva-pathways/tutorial.md, topics/transcriptomics/tutorials/minerva-pathways/workflows/Galaxy-Workflow-BY-COVID__Data_Download.ga
For @pvanheus. Each of the "if this does not work" includes diretions specific to the defined workflow (e.g. the gtn workflow's instructions in the snippet include the URL you must copy and paste
=> Improve fallback behaviour of workflow import snippets

_layouts/home.html
The events list on the homepage will now also show ongoing events, not just upcoming ones, making it easier for participants to navigate to the course page during the event.
=> Show ongoing events on home page

topics/introduction/tutorials/galaxy-intro-101-everyone/tutorial.md
Reorder parameters to match tool form. Unless this was on purpose?
=> Reorder parameters to match tool form

topics/genome-annotation/tutorials/annotation-with-maker/content.md
The previous links returned  "Failed to fetch URL" errors when using the URLs to upload data into Galaxy.
=> Replace broken zenodo links in Annotation with Maker trainings

faqs/galaxy/support_admins.md
The email doesn't exist and I think we ideally want everything to go through the help forum.
=> Drop help@galaxyproject.org from US help

bin/google-form-event.rb
Just a freetext field to keep it simple on the submitter's side, reviewers can split it into name/city/country properly if needed
=> [Events] added location field to Google Form

bin/google-form-news.rb
we are terribly inconsistent with these metadata keys between news, learning pathways, events etc, but for news it should be `cover` and `coveralt` currently
=> [News From] fix key names for cover image metadata

topics/evolution/tutorials/mtb_transmission/tutorial.md
The removed part doesn't seem to belong to the Join step.
=> Remove duplicated instructions in hands-on box

topics/single-cell/tutorials/scatac-standard-processing-snapatac2/data-library.yaml
The latest version of this  Zenodo record has a compressed fragments file which is 4 times smaller than the old one.
=> SnapATAC2 tutorial: update data-library.yaml

topics/admin/tutorials/interactive-tools/tutorial.md
Since I wrote #5179, I took some extra time to update the other parts of the training. 
Include instructions to enable path-based interactive tools. Lift all sections one level up: it looks like the tutorial was intended to include a section to set up the Interactive Tools using Ansible and another to do it manually, but it includes only the former. As a result of this change, some warnings and comments had to have their location and/or type changed. Two questions, and @kysrpex as editor, were also added.
=> Update Galaxy Interactive tools training (path-based tools and general review)

topics/single-cell/tutorials/scrna-case-jupyter_basic-pipeline/tutorial.md
Some of the code blocks were not being rendered correctly in the tutorial and generated Jupyter notebook due to some missing python tags and trailing whitespaces after closing one of the code blocks.
Also made some minor updates to some of the code blocks:
- The initial call to ```get()``` should get the first file since that will likely be the position of the required file if following the tutorial
- Fixed the name of the file saved at the end using ```adata.write()``` not matching the name of the file being saved in the next code block using ```put()``` (MarkersCluster.h5ad)
- Changed the filename of the exported Jupyter notebook file to make it slightly more clear that it needs to be the name of the current Jupyter notebook
=> Fix rendering issue in Filter Plot and Explore (Python) tutorial

topics/assembly/tutorials/vgp_genome_assembly/tutorial.md
Changed Salsa to YaHS in one spot (Salsa was the older tool, now replaced with YaHS)
=> Fix typo in VGP tutorial

topics/single-cell/tutorials/scrna-case_alevin-combine-datasets/tutorial.md, topics/single-cell/tutorials/scrna-case_alevin/tutorial.md, topics/single-cell/tutorials/scrna-case_basic-pipeline/tutorial.md, topics/single-cell/tutorials/scrna-case_trajectories/tutorial.bib, topics/single-cell/tutorials/scrna-case_trajectories/tutorial.md
- Some minor updates to tool names, links 
- Also changed the bit on the order in which Anndata are concatenated in the combining datasets tutorial - the first one you click is the first one added, so they should click N702 to N707 not 7 to 2
New changes:
-  The Filter, Plot, Explore tutorial has also been checked now - only change is that we need to include the older input history as the new one doesn't work for the current tool versions/workflow - I'm not sure if we should have both available for now or just have the older one until we update the tools?
- Also added a note for people using the newer tools on the trajectories tutorial as they need to change n-pcs (again, we can improve this when we update the tool versions)
=> Updating case study tutorials

_includes/youtube.html, _layouts/recordings.html, bin/schema-tutorial.yaml, topics/transcriptomics/tutorials/ref-based/tutorial.md
The end screens which presented the choice of next video in the CYOA transcriptomics video were not showing up in the embedded videos (due to the youtube-nocookie domain). Added metadata field to indicate whether a video is CYOA.
Fixes the issue we discussed today @teresa-m
=> Fix for CYOA videos

_includes/instance-dropdown.html, _layouts/topic.html
since the base image unfortunately hasn't been updated in a bit.
=> temporarily hide docker images while they aren't updated

topics/admin/tutorials/interactive-tools/slides.html, topics/admin/tutorials/interactive-tools/tutorial.md
=> update IT entrypoint subdomain

_config.yml, assets/js/main.js, assets/js/tutorial-mode.js
This adds a new bit of javascript code which will let us progress towards a better tutorial mode that doesn't require as many changes on the galaxy side, and can make the interactions a bit cleaner.
This will not change anything for anyone now, it'll simply enable the code needed for such a method to work. In the future, when the galaxy side is updated, this will become useful. But for now it's a nop for all of our users. Which is excellent as it gives us a slow roll out period where we can explore the implementation on the Galaxy side without affecting anyone.
e.g. this would let us change our tool button semantics without waiting years for everyone to update galaxy, and provides a cleaner boundary between the two.
=> Support tutorial mode via postMessage

topics/genome-annotation/tutorials/amr-gene-detection/data/trackList.json, topics/genome-annotation/tutorials/bacterial-genome-annotation/data/trackList.json
@jennaj reported in GTN chat that a name popup was triggering a page scroll. This didn't happen in the past but it does now, not sure when that changed. @scottcain explained the root cause of jbrowse doing this. Not sure how these were generated by the tool.
As the browser level policy isn't implemented yet, we cannot prevent this happening in the future: https://github.com/w3c/csswg-drafts/issues/7134 so we need to fix them individually.
=> Remove incorrectly configured names

_includes/tutorial_list.html
The information hierarchy is kinda sub-optimal, but, not something I think we should fix now, so last minute.
=> Ensure event page content is shown on small screens as well

_plugins/generator-workflows.rb, _plugins/gtn.rb, search2.html
per request from @sujaikumar, now tutorials without short IDs will show up in search results. Additionally workflows are now included as well.
=> Ensure pages without short IDs are part of search results

topics/variant-analysis/tutorials/aiv-analysis/tutorial.md
Also bumps tool versions used and adds a bit of explanation on how phylogenetic trees can be visualized in Galaxy.
Most importantly, this will enable people to follow the tutorial on usegalaxy.org in addition to Galaxy Europe.
Agreed that this is sort of a quick fix and that the data in question should really live on zenodo, but I'm still in the process of figuring out the final shape of this tutorial.
=> Add link to AIV reference history on Galaxy US

topics/assembly/tutorials/vgp_workflow_training/tutorial.md
video here: https://www.youtube.com/watch?v=_LO-migvwcM
I am hoping this underscore has just been omitted and not removed by some sanitize process
=> fix link to GTA video

bin/schema-tutorial.yaml
=> Youtube IDs are 11 characters only

topics/dev/tutorials/tool-from-scratch/tutorial.md
=> fix copypasta

_layouts/contributor_index.html, _plugins/gtn/contributors.rb, _plugins/jekyll-jsonld.rb
per discussion with @shiltemann over the precise use of 'organisation' and 'funder'.
=> fix funder/funding split in json metadata

topics/statistics/tutorials/regression_machinelearning/tutorial.md
Remove the dreprecated`searchCV` option in the Pipeline Builder tool. Fixes https://github.com/galaxyproject/training-material/issues/5431
=> Remove the dreprecated`searchCV` option in the Pipeline builder tool

topics/genome-annotation/tutorials/helixer/tutorial.md
In the tutorial, for the tool gffread, for `select fasta outputs`, I think the wrong item is specified. 
I have changed it from `fasta file with spliced exons` to `protein fasta file`, because the next step in the tutorial (using Busco) needs this protein fasta file.
=> Update Helixer tutorial.md - gffread inputs

topics/dev/tutorials/community-tool-table/tutorial.md
The process on the Codex has been improved. This PR reflects the changes
=> [Community Tool Table Generation] Update the process to curate TS filtered community tool table

topics/transcriptomics/tutorials/ref-based/tutorial.md
replace "rename" with "name". This way it should be more obvious, that the naming should be done while creating the collection and not afterwards (which is impossible anyway)
=> Update Reference-based RNA-Seq data analysis

topics/contributing/metadata.yaml, topics/contributing/tutorials/create-new-topic/tutorial.md, topics/contributing/tutorials/create-new-tutorial-content/tutorial.md, topics/contributing/tutorials/create-new-tutorial-slides/slides.html, topics/contributing/tutorials/create-new-tutorial/tutorial.md, topics/contributing/tutorials/gitpod/tutorial.md, topics/contributing/tutorials/running-jekyll/tutorial.md
Reorder the tutorials on the contributing page to make it easier for people to know where to start
Tutorials in the "Getting Started" section can/should be followed in order
=> Reorder tutorrials in Contributing topic

topics/transcriptomics/tutorials/ref-based/tutorial.md
I forgot a `-` and this lead to not hiding the third option when choosing the first or second one.
@hrhotz this is the fix.
=> Fix CYOA of collection split in Ref-based

_plugins/gtn.rb, _plugins/util.rb, bin/lint.rb, topics/contributing/tutorials/create-new-tutorial-content/tutorial.md, topics/galaxy-interface/tutorials/workflow-posters/tutorial.md, topics/single-cell/tutorials/scrna-case_FilterPlotandExplore_SeuratTools/tutorial.md
for @lldelisle, xref https://github.com/galaxyproject/training-material/pull/5529  featuring a number of new warnings:
```
$ ruby bin/lint.rb --limit GTN:041
./topics/climate/tutorials/ocean-variables/tutorial.md:1:1:1:1:GTN041 You have non-unique options in your Choose Your Own Adventure. Please ensure that each option is unique in its text. Unfortunately we do not currently support re-using the same option text across differently disambiguated CYOA branches, so, please inform us if this is a requirement for you.We identified the following duplicate options in your CYOA: Options xview, xview became the key: xview; Options png, png became the key: png
$ ruby bin/lint.rb --limit GTN:042
./topics/contributing/tutorials/create-new-tutorial-content/tutorial.md:1:1:1:1:GTN042 We recommend …
```
=> lint cyoa branches

Makefile
The onCreateCommand or onStartCommand directive wasnt always working, so just do it as part of the startup command to make sure its really gone.
Free accounts cannot use the 64GB storage machines, so we have to make it work with 32GB machines
=> [CodeSpaces] free up some disk space in preview command

Makefile
this file seems to grow uncontrollably, filling up disk space, so remove it whenever we build the website
=> more codespaces config

_layouts/tutorial_hands_on.html
My bibtex parser failed after copying in the citations for a GTN piece (https://training.galaxyproject.org/training-material/topics/fair/tutorials/ro-crate-in-galaxy/tutorial.html). This PR fixes the two formatting issues.
=> Fixes bibtex formatting issues in training material bibtex export

topics/genome-annotation/tutorials/helixer/tutorial.md, topics/genome-annotation/tutorials/helixer/workflows/Helixer-tests.yml, topics/genome-annotation/tutorials/helixer/workflows/Helixer.ga
Hello, 
I'm opening this PR to add a section with OMArk in this training. 
Thank you! Have a good day!
=> add omark section on Helixer GTN

_layouts/learning-pathway.html, _plugins/jekyll-duration.rb, bin/schema-learning-pathway.yaml, bin/schema-tutorial.yaml
fixes https://github.com/galaxyproject/training-material/issues/5584
The author can set LOs per-module, or they will be taken from the constituent tutorials.
=> Add total module duration + LOs per module in LPs

topics/admin/tutorials/beacon/tutorial.md
Thank you for the report @Nota30, it is much appreciated.
Fixes https://github.com/galaxyproject/training-material/issues/5618
- manually installs the collection, it'll have to be done properly at some stage in the future when we re-work the entire requirements.yml to support collections, but that day isn't today.
- password is moved up to correct location
- renamed yml file
=> Fix beacon tutorial issues

topics/admin/tutorials/beacon/tutorial.md, topics/admin/tutorials/connect-to-compute-cluster/tutorial.md, topics/admin/tutorials/monitoring/tutorial.md, topics/admin/tutorials/reports/tutorial.md, topics/admin/tutorials/tiaas/tutorial.md
fixes https://github.com/galaxyproject/galaxy/issues/15966 by applying patch from @jdwhatsup from
https://github.com/jdwhatsup/training-material/commit/c88b7561e36ae8c4c467e0b96d6e41216eed4da5
I tested this on a fairly standard instance with reports under `/reports` and it loads jobs fine
=> fix reports nginx config to avoid localhost issues

topics/proteomics/tutorials/maxquant-msstats-tmt/tutorial.md
In the MaxQuant version used in this tutorial variable modification and enzyme have no default value, therefore I now added the values for these two parameters in the tutorial.
=> Maxquant and MSstats TMT: Adding missing MaxQuant parameters

.github/workflows/video.yml
the automated video deploy started failing due to dependency issues. use ubunut-latest again so we can make it work there
=> [CI] return to latest ubuntu since its failing now anyway

.github/workflows/ci-main.yml
Because of the pipes, error exit codes were being ignored
=> Set test to fail if one part of the pipe fails

faqs/galaxy/datasets_import_from_data_library.md, topics/introduction/tutorials/galaxy-intro-peaks2genes/tutorial.md
1. I re-run the tutorial using usegalaxy.eu on 06.02.2025. There were a few discrepancies between the tutorial and GUI. I tried to modify them.
2. The snippet for importing data was outdated. Tried to change as little as possible while make it usable.
3. I added myself as an editor.
=> Dadrasarmin updated galaxy intro peaks2genes tutorial

topics/contributing/faqs/github-fork-master-main.md
There is a mistake in step 1 "Point your browser to your fork of the GTN repository" URL.
=> Correct underscore to hyphen in repo URL

topics/single-cell/tutorials/pseudobulk-analysis/tutorial.md, topics/single-cell/tutorials/scrna-intro/slides.html, topics/single-cell/tutorials/scrna-plates-batches-barcodes/slides.html
There were a couple remaining X on the maintainer page. I *think* if you remove the zenodo line from a slide deck, it no longer is 'missing' zenodo.
=> Update metadata for single-cell materials

Makefile
The output from `mamba env list` now starts with a space. Fix the grep regular expression to allow that, so that the `create-env` Make target doesn't try to recreate the `galaxy_training_material` environment.
=> Fix ``create-env`` Make command

learning-pathways/intro-to-galaxy-and-genomics.md
One of the metadata tags was 'introcuction'. I corrected it to 'introduction'.
=> Fixed typo in tag 'introcuction'

topics/admin/tutorials/ansible-galaxy/tutorial.md
Surround value with raw tags; otherwise template is evaluated, resulting in this:
```
galaxy_user: {name: "", shell: /bin/bash}
```
Should be:
```
{name: "{{ galaxy_user_name }}", shell: /bin/bash}
```
(username cannot be empty)
=> Fix galaxy installation tutorial: add raw tags to ensure template not evaluated

_plugins/feeds.rb
Enhance feed details by uncommenting category tags for event start, end, and duration in the XML output.
=> Uncomment category tags for event details in XML output

faqs/galaxy/re_use_equivalent_jobs.md
Recently, multiple opportunities for using job cache were discussed and we decided toe prepare a FAQ page for it. This way, maybe we can encourage instructors (and trainee) to use job cache, so they get the results faster, reduce the load on computational resources, and limit carbon footprint.
We would like to test the functionality of this feature in a course next week and potentially during the GTA2025.
=> Created a post in the FAQ section for Job Cache feature (re_use_equivalent_jobs)

topics/single-cell/tutorials/scrna-case-jupyter_basic-pipeline/tutorial.md, topics/single-cell/tutorials/scrna-case_FilterPlotandExploreRStudio/tutorial.md, topics/single-cell/tutorials/scrna-case_FilterPlotandExplore_SeuratTools/tutorial.md, topics/single-cell/tutorials/scrna-case_JUPYTER-trajectories/tutorial.md, topics/single-cell/tutorials/scrna-case_alevin-combine-datasets/tutorial.md, topics/single-cell/tutorials/scrna-case_alevin/tutorial.md, topics/single-cell/tutorials/scrna-case_basic-pipeline/tutorial.md, topics/single-cell/tutorials/scrna-case_cell-cycle/tutorial.md, topics/single-cell/tutorials/scrna-case_monocle3-rstudio/tutorial.md, topics/single-cell/tutorials/scrna-case_monocle3-trajectories/tutorial.md, topics/single-cell/tutorials/scrna-case_trajectories/tutorial.md
While the Case Study works for 10x data, it actually uses Drop-Seq data, so that's an unnecessary tag.
Also, no point in labelling both R and markdown notebook; same for jupyter-notebook
Basically, we had too many tags
=> Fix tags of tutorials

topics/ecology/tutorials/ref-based-rad-seq/tutorial.md
I changed the tutorial to use Falco instead of FastQC.
=> Change from fastqc to falco in ref-based-rad-seq tutorial

topics/ecology/tutorials/de-novo-rad-seq/tutorial.md
I changed this tutorial to use Falco instead of FastQC.
=> Change from fastqc to falco in de-novo-rad-seq tutorial

topics/variant-analysis/tutorials/somatic-variants/tutorial.md
I changed the tutorial to use Falco instead of FastQC.
=> Change from fastqc to falco in somatic-variants tutorial

topics/imaging/tutorials/imaging-introduction/tutorial.md
There was a factually wrong explanation for the low contrast of an image in the tutorial:
> The original image is 16-bit and the intensity values are spread over a **larger** range than the display can render. Therefore, for improved visibility the intensity histogram of the image can be normalized first.
This is now corrected to:
> The original image is 16-bit and the intensity values of the image (33069 to 36863) are spread over a **very small** fraction (only about 6%) of the intensity values that can be represented using 16 bits (0 to 65535, where 0 corresponds to black and 65535 corresponds to white). Therefore, for improved visibility the intensity histogram of the image should be normalized first.
=> Introduction to Image Analysis using Galaxy: Fix explanations about 16bit images

CODEOWNERS, editorial-board.md, metadata/one-health.yaml, topics/assembly/metadata.yaml, topics/dev/metadata.yaml, topics/epigenetics/metadata.yaml, topics/galaxy-interface/metadata.yaml
I realized our CODEOWNERS file was very outdated (missing/renamed topics etc)
The team based approach was not working for us, so I've written down all editorial board members individually. 
So all editorial board members should get notified about any PRs concerning their topic.
Everybody is free to add/remove themselves to parts of this file as they want
I also made a section on the editorial-board page that autogenerates the codeowners from metadata, so that it is easy to update in the future.
=> update CODEOWNERS file

_layouts/contributor_index.html
fixes https://github.com/galaxyproject/training-material/issues/5838
We were actually including learning pathways (under editorial roles), but not indicating that fact
=> indicate type of editorial role on hall of fame page

_layouts/topic-maintainer.html
fixes https://github.com/galaxyproject/training-material/issues/5757
@nomadscientist fixed the issue where it didn't detect your topic LPs, and removed the red X symbols for optional items (e.g. notebook). 
So your maintainer page looks a lot greener ;P
=> Maintainter page fixes

CONTRIBUTORS.yaml, events/2025-05-12-galaxy-academy-2025.md, events/tracks/gta2025-climate.md
- Added Climat track program (events/tracks/gta2025-climate.md)
- Linked track in the gta-event page, and added all helpers
- Added Even to Contributors.yaml
ToDo:
@annefou: could you have a look at the program looks ok and add some descriptions to the individual section and a general one on top?
=> Event page gta added Climat track

_plugins/feeds.rb
Introduce a new category for external links in the event feeds generation process.
This could be used in Galaxy Hub to link directly to the external link.
Related to https://github.com/galaxyproject/galaxy-hub/issues/3124
=> Add external link to event feeds

topics/statistics/tutorials/RNN/tutorial.md
@teresa-m @anuprulez please review. Screenshots added for clarity. 
_When following step-by-step tutorial instructions, job error due to `default` parameter value for the tool `Deep learning training and evaluation ( Galaxy version 1.0.10.0)` failure:_
_Wording solution in step-by-step instructions which originated from ["Run Workflow in Galaxy" version](https://training.galaxyproject.org/training-material/topics/statistics/tutorials/RNN/workflows/Intro_To_RNN_v1_0_10_0.html) of tutorial which used `f1` parameter value successfully:_
=> Hotfixes for Machine Learning: Intro to RNN Hands-On tutorial

events/tracks/gta2025-ml.md
Adds the missing FNN tutorial, and fixes order of RNN/CNN
=> Update GTA ML track

topics/microbiome/tutorials/metagenomics-binning/tutorial.md
The Zenodo links appear to have stray spaces. Reported over email (thanks Karl!)
=> Fix zenodo links - binning of metagenomic data tutorial

.github/workflows/workflowhub.yml
The GTN workflows are currently automatically pushed to the development instance of WorkflowHub, this changes that to target production WFH
=> Switch to production WorkflowHub

.github/workflows/monthly-release-backfill.yml
this was failing because it ran out of diskspace, so free up some unneeded space in the runner
=> [GH actions] free disk space action

bin/wfh-upload.py
Fixes this issue: https://github.com/galaxyproject/training-material/actions/runs/15389089921/job/43294210078#step:8:1030
which was due to WorkflowHub not handling partial updates of the policy very well. The submission script tried to add a "manage" permission for members of the GTN Team on WorkflowHub, but the WorkflowHub API also requires the public access type to be declared in the request.
(FYI I fixed the policies of the GTN workflows server-side, so future submissions should succeed regardless of this PR)
=> Fix "access_type is too permissive" on WorkflowHub submission

_config.yml
@teresa-m asked for a new icon to be added to GTN for Cloud Upload. I added this one: https://fontawesome.com/icons/cloud-arrow-up?f=classic&s=solid to the `_config.yml` file.
It appears as expected in the FAQ titled: "Which icons are available to use in my tutorial?"
=>  **Ready for Review** added upload cloud icon for Teresa

_plugins/jekyll-jsonld.rb
The FAIRchecker complains about these terms, so we will remove them for now
=> [JSON-LD markup] remove obsolete terms

.github/workflows/optimize-images.yml
@shiltemann I think this should work better for this action, there should always be at most one PR and this achieves that afaik
=> image compress action -- do not create a unique branch each time

topics/proteomics/tutorials/maxquant-msstats-dda-lfq/tutorial.md
The file names had spaces in them; the previous link was not correct
=> update links - maxquant
