ChIPseq/ChIPseq.md

* added table of content
* moved literature to the end of the document

starting restructuring of ChIP-seq docu

---

staging/readme.md

As requested here: https://github.com/bgruening/training-material/issues/8

Create staging area

---

NGS-QC/.gitignore
NGS-QC/README.md
NGS-QC/qc_guide.md

Started NGS-QC section for SOP generation

---

README.md

To also regenerate the `index.html`

Remove the map script from README

---

bin/deploy_docs
bin/gfm2html

Trying to catch error with GitHub API to avoid them to appear in `index.html`

Improve the script for index.html generation

---

GUIDELINES.md

Hi,
To structure the repository (issue #9), I started a `GUIDELINES.md`. It is mainly based on what has be done with exome seq training material.
What do you think?
Bérénice

GUIDELINES.md

---

RNA-Seq/RNA-Seq-hands-on.md

Comments from @blankclemens, edited by @erxleben

RNA-Seq tutorial update

---

.gitmodules
Exome-Seq/slides/index.html
shared/slides/project_presentation.html

Hi,
I move `reveal.js` to the shared directory to avoid it at the root.
Bérénice

Move reveal.js to shared directory

---

README.md

Fixed link to Galaxy Introduction

---

Admin-Corner/readme.md

just to make thinks simpler (at least for the initial phase): I suggest to remove the links to 'Moving from MySQL to PostgreSQL' (see also #105), while keeping the directories

Galaxy Server administration update readme.md

---

templates/slides/index.html
templates/slides/tutorial.html

Using standard indent of 4 spaces.
Also added a few speaker notes.

Converted tabs to spaces in slide templates.  

---

README.md

Would be possible you include the IFB's logo here

---

.travis.yaml
.travis.yml

We will start with testing links automatically.
If anyone wants to contribute to this project this should be an easy way to get involved.

Add initial travis testing

---

CONTRIBUTING.md

fixed some singular/plural grammar issues
changed words to match the tense used
statements read as questions were rewritten as questions

fixed tense and plural/singular grammar issues

---

Dev-Corner/slides/tool_integration.html

@lecorguille & co, here are the data collection slides, I hope there's not too much or too few :smile:

Dev-corner: add data collections

---

Dev-Corner/readme.md

Hey,
the final step to finish with github contribution slides ^^

add github contribution slides in Devcorner readme.md

---

Dev-Corner/slides/github_contribution.html

add font-awesome link in html head

---

RNA-Seq/tutorials/ref_based.md

Among other things I removed the step to sort the BAM file for htseq-count - it didn't change my result and I can't see why this could be necessary.

Updates to ref_based.md

---

Dev-Corner/slides/toolshed.html
metadata/Dev-Corner.yml

Add the general schema for planemo utilities and checklist 3/3 (dealing with shed commands), taken from the tool_integration slides

Dev-corner/toolshed: adding the general schema for planemo utilities 

---

README.md

Second try. This time no conflicts.

Added / updated some links in the Readme.md

---

Dev-Corner/slides/tool_integration.html
_layouts/base_slides.html
assets/css/slides.css

I have not finished reviewing, but here's a PR I will update...

Various corrections to dev-corner

---

Admin-Corner/readme.md
Admin-Corner/tutorials/dev_to_production.md
CONTRIBUTING.md
ChIP-Seq/README.md
Dev-Corner/readme.md
Exome-Seq/README.md
Introduction/README.md
MethylC-Seq/README.md
NGS-QC/README.md
NGS-mapping/README.md
README.md
RNA-Seq/README.md
_config.yml
_includes/main_header.html
shared/slides/project_presentation.html
templates/README.md
templates/slides/index.html
templates/slides/tutorial.html
templates/tutorials/tutorial.md

Hi,
To fit the migration, I correct 
- the `_config.yml` file to fit the new URL
- some links
- the template examples as some links were inside the template
Bérénice

Fix migration, URL and template examples

---

Dev-Corner/tutorials/visualizations.md

template doesn't recognize xml as highlighting option and did not display this as a code block, change to html for now

fix section that was not being displayed properly

---

Dev-Corner/tutorials/visualizations.md

Visualization tutorial: fix display issue?

---

Dev-Corner/tutorials/visualizations.md
metadata/Dev-Corner.yml

update some text to fit with new input dataset we're using and remove unrelated objectives from metadata

small updates to visualizations tutorial

---

Dev-Corner/tutorials/visualizations.md
_config.yml
_layouts/base.html
assets/css/syntax_highlighting.css

Hi,
To solve #179, we found how to have syntax highlighting in the tutorials.
Bérénice

Code highlighting

---

LICENSE.md
README.md
_layouts/home.html

See https://wiki.creativecommons.org/wiki/License_Versions for the list of changes in version 4.0 .
Hopefully we can get the explicit approval of all the contributors.

Change the license to CC BY 4.0

---

metadata/Genome-Annotation.yml

added in a new section on microbial genome annotation, using the tool Prokka

Update Genome-Annotation yml

---

_config.yml
_includes/main_footer.html
_includes/main_header.html
_layouts/home.html
assets/css/landing_page.css
assets/css/tutorial.css

rounded corners
different fonts
update to main page

Style updates

---

RNA-Seq/tutorials/ref_based.md

The correct name is used in the Galaxy wrapper since https://github.com/galaxyproject/tools-iuc/pull/1141 .

Change HISAT to HISAT2

---

_layouts/tutorial_hands_on.html

I think the title is self-explanatory 😉 
Cheers,
William

Extra space in "found a typo" paragraph

---

_includes/main_footer.html
_includes/main_header.html
_layouts/base.html
_layouts/home.html
assets/css/landing_page.css

includes fix for broken responsiveness
please see commits
ping @nekrut

Homepage revamp

---

_layouts/base.html
_layouts/home.html

restrict forkme ribbon to the homepage only

---

CONTRIBUTING.md

fixed links within the document

---

Proteomics/tutorials/database-handling.md

Hejhej,
I updated the database handling tutorial. It should be displayed nicely now, even in the github pages.
Cheers, Flo

Database handling tutorial update

---

RNA-Seq/docker/Dockerfile
RNA-Seq/docker/README.md
RNA-Seq/docker/data_manager_rna_seq.yaml
metadata/RNA-Seq.yml

This PR demonstrates how we can easily pre-populate Docker images with reference indices.
ping @nekrut, @bebatut, @MoHeydarian, @malloryfreeberg

Docker - RNA-seq

---

Genome-Annotation/tutorials/general-introduction.md
metadata/Genome-Annotation.yml

formatted genome annotation tutorial+meta

Genome annot

---

README.md

I am still unclear about who is the target audience of this readme, but at least it renders well now. Also removed link to Planemo docs as it seemed unrelated.

fix syntax of root readme

---

topics/chip-seq/tutorials/tal1-binding-site-identification/metadata.yaml

Added: edam_ontology : "topic_3169" => ChIP-seq

update metadata yaml_file

---

topics/assembly/tutorials/debruijn-graph-assembly/tutorial.md
topics/assembly/tutorials/general-introduction/tutorial.md

Fixing links

---

CONTRIBUTING.md
templates/index.md
templates/slides/index.html
templates/tutorials/tutorial1/slides.html
templates/tutorials/tutorial1/tutorial.md

Some little modifications of the template

some improvement around the template

---

topics/sequence-analysis/tutorials/mapping/slides.html
topics/sequence-analysis/tutorials/quality-control/slides.html

paths in slides

---

topics/introduction/tutorials/galaxy-intro-get-data/slides.html
topics/introduction/tutorials/options-for-using-galaxy/slides.html

ping @nsoranzo, I think this fixes what you meant in your [comment](https://github.com/galaxyproject/training-material/pull/354#issuecomment-308826275)?

change slide deck type

---

_layouts/tutorial_hands_on.html
topics/transcriptomics/tutorials/de-novo/tutorial.md

Add @MoHeydarian's feedback form to end of all tutorials
preview of how it looks

Feedback form

---

topics/assembly/metadata.yaml
topics/transcriptomics/tutorials/ref-based/tutorial.md

metadata + small fix in tutorial layout

---

topics/chip-seq/tutorials/ChIPseq/tools.yaml
topics/chip-seq/tutorials/tal1-binding-site-identification/tools.yaml

Chipseq tools

---

topics/dev/tutorials/architecture/slides.html

add webhook slides, xref: https://github.com/galaxyproject/training-material/issues/365

add webhook slides

---

topics/admin/tutorials/advanced-galaxy-customisation/slides.html

Linguistic cleanups, welcome page

---

topics/dev/tutorials/conda/slides.html
topics/dev/tutorials/containers/slides.html

For these smaller commits that just fix things should I opening PRs or committing directly - I can do either no problem - just curious what the best practice is?

Important clarifications/fixes for Conda/Container slides.

---

topics/assembly/tutorials/general-introduction/tools.yaml
topics/assembly/tutorials/general-introduction/workflows/Galaxy-Workflow-assembly-general-intro.ga

changed tool and created workflow

---

topics/dev/tutorials/conda/slides.html

Fill out an advanced Conda section.

---

topics/training/metadata.yaml
topics/training/tutorials/create-new-tutorial-content/tutorial.md
topics/training/tutorials/create-new-tutorial-docker/tutorial.md
topics/training/tutorials/create-new-tutorial-jekyll/tutorial.md
topics/training/tutorials/create-new-tutorial-metadata/tutorial.md
topics/training/tutorials/create-new-tutorial-tours/tutorial.md

train the trainer

---

topics/training/tutorials/create-new-tutorial-metadata/tutorial.md

Metadata tutorial: Rephrase the beginning of metadata tutorial and remove mention of duplication

---

topics/sequence-analysis/tutorials/de-novo-rad-seq/tools.yaml
topics/sequence-analysis/tutorials/genome-annotation/tools.yaml
topics/sequence-analysis/tutorials/quality-control/workflows/quality_control.ga
topics/sequence-analysis/tutorials/quality-control/workflows/quality_control_2.ga
topics/sequence-analysis/tutorials/quality-control/workflows/workflow.ga
topics/sequence-analysis/tutorials/ref-based-rad-seq/tools.yaml
topics/sequence-analysis/tutorials/srna/tools.yaml

Sequence analysis workflows tools

---

topics/training/metadata.yaml
topics/training/tutorials/create-new-tutorial-docker/tutorial.md

Add metadata for the Train trainers tutorials

---

topics/training/metadata.yaml
topics/training/tutorials/create-new-tutorial-tours/tutorial.md

Fill the Interactive tour hands on

---

_layouts/topic.html

Fix the detection of docker_image empty tag in topic

---

topics/transcriptomics/tutorials/srna/tutorial.md

ping @malloryfreeberg 
made some fixes for the display of the hand-on/agenda boxes, one of them was missing a title, I made one based on what it sounded like to me but you may have a better suggestion :)

sRNA tutorial: small fixes for display

---

topics/metagenomics/tutorials/general-tutorial/tours/metagenomics-general-tutorial-amplicon.yml
topics/metagenomics/tutorials/general-tutorial/tours/metagenomics-general-tutorial-shotgun.yml
topics/metagenomics/tutorials/general-tutorial/tutorial.md

ping @shiltemann 
You can test them on any Galaxy instance with the tourbuilder extension

Add tours for the general metagenomics tutorial

---

topics/admin/tutorials/database-schema/tutorial.md

reverse back to http (just one case) and fix typo

 fixes for database tutorial

---

_layouts/base.html
topics/training/tutorials/create-new-tutorial-content/tutorial.md

Hi,
I added support for mathematical expressions written in LaTeX: they will be rendered using [MathJax](https://www.mathjax.org/)
Bérénice

Support mathematical expressions written in LaTeX

---

topics/transcriptomics/tutorials/srna/workflows/sRNA_seq_Step_2_Salmon_and_DESeq2.ga

Fixed missing --writeMappings parameters, updated to newest Salmon version, rearranged input boxes.

Update Salmon parameters in workflow Part 2

---

topics/sequence-analysis/tutorials/quality-control/tours/tour.yaml

added tour

---

.travis.yml

Reverts galaxyproject/training-material#425

Revert "Test site building with travis"

---

Gemfile
Makefile

I found a tool ([html-proofer](https://github.com/gjtorikian/html-proofer)) to check the site to ensure all links and images exist.
This PR is a first step to test it locally and fix all the links and images.
I am thinking about integrating then it to Travis.
Bérénice

Add makefile command to check site structure

---

topics/proteomics/metadata.yaml
topics/proteomics/tutorials/metaproteomics/metadata.yaml

Update questions for metaproteomics tutorial

---

README.md

I am so lost without such a badge on a project page 😛

Add Travis badge + link to it

---

.gitignore
.travis.yml
Makefile
_config.yml
topics/training/tutorials/create-new-tutorial-jekyll/tutorial.md

Hi,
With @willdurand, we worked on the Makefile to clean it and add help for the commands.
But most important, we added a command to generate PDF for all tutorials and slide decks. Currently the PDF are created locally in `_pdf`. The next step would be to upload them automatically on a server and link to them on the website.
Bérénice

Add PDF generation

---

assets/css/main.css

As a colorblind person, I cannot read the `<details>` content. This PR fixes
this :)

Switch to a more visible color for HTML details

---

topics/variant-analysis/tutorials/exome-seq/tutorial.md

Currently attending the workshop on that topic, and this was incorrect.

FreeBayes was not in Phenotype Association section

---

topics/introduction/tutorials/galaxy-intro-101/tools.yaml
topics/introduction/tutorials/galaxy-intro-peaks2genes/tools.yaml
topics/introduction/tutorials/galaxy-intro-peaks2genes/tutorial.md

Added a missing tools to galaxy 101 and peaks2genes.
Small fix in peaks2genes.

missing tools in 101 and peaks2genes

---

_layouts/base.html

This should resolve the current rendering for some people without having to hard refresh.

Cache bust assets to avoid broken rendering

---

_config.yml

As I've suggested in https://github.com/galaxyproject/training-material/pull/463#issuecomment-320281087 .

Use fa-laptop icon for tutorials

---

_config.yml
_includes/default-header.html
_layouts/base_slides.html
_layouts/tutorial_hands_on.html

Broken in commit 379a80ab7dc2d589f58fda5221042947cb0c86aa .

Show full-size logo on slide first page

---

_layouts/home.html
assets/css/main.scss
assets/css/syntax_highlighting.css
topics/dev/tutorials/visualization-charts/tutorial.md
topics/metagenomics/tutorials/general-tutorial/tutorial.md
topics/metagenomics/tutorials/mothur-miseq-sop/tutorial.md

Hi!
Here are a few UI improvements:
- Replace some more icons (missed the `:book:` ones)
- Add colored background on code snippets
- Wrap text to avoid problems on small devices (long words break the layout)
- Display two columns on bottom homepage for medium/large devices

Minor UI improvements

---

_layouts/home.html

I noticed a link was broken, the other was not configurable.

Fix broken link on homepage

---

templates/metadata.yaml
topics/admin/metadata.yaml
topics/assembly/metadata.yaml
topics/chip-seq/metadata.yaml
topics/dev/metadata.yaml
topics/epigenetics/metadata.yaml
topics/introduction/metadata.yaml
topics/metagenomics/metadata.yaml
topics/proteomics/metadata.yaml
topics/sequence-analysis/metadata.yaml
topics/training/metadata.yaml
topics/transcriptomics/metadata.yaml
topics/usegalaxy/metadata.yaml
topics/variant-analysis/metadata.yaml

This PR fixes YAML issues for metadata, reported by `yamllint`.

Fix YAML linting for metadata

---

topics/chip-seq/tutorials/tal1-binding-site-identification/tutorial.md

Output of the "Map With BWA" Tool is a BAM format, but not SAM format.

Output of the "Map With BWA" Tool

---

topics/epigenetics/tutorials/methylation-seq/tools.yaml
topics/epigenetics/tutorials/methylation-seq/tours/tour.yaml
topics/epigenetics/tutorials/methylation-seq/workflows/workflow-methylation-seq.ga
topics/epigenetics/tutorials/methylation-seq/workflows/workflow.ga

Missing methyldackel tool on toolsched

added tour, tools, workflow

---

topics/proteomics/tutorials/metaproteomics/tutorial.md

Added some links and more information.

Metaproteomics update

---

_layouts/base_slides.html
_layouts/introduction_slides.html
_layouts/tutorial_slides.html

Add thank you slide at the end and remove the welcome slide

---

_includes/default-header.html

Add github link on the header of main and topic pages

---

.travis.yml
bin/publish

Skip travis testing on master and move build on publish script

---

_layouts/home.html
topics/introduction/metadata.yaml
topics/sequence-analysis/metadata.yaml

It is a first attempt to re-order the topics (here in alphabetical order)

Reorder alphabetically the topics

---

_layouts/topic.html
_layouts/tutorial_hands_on.html

Hide Docker image section on topic page and link on tutorial when none provided

---

topics/metagenomics/tutorials/general-tutorial/tutorial.md

add missing link to zenodo

---

topics/training/tutorials/create-new-tutorial-content/tutorial.md

I edited the "create new tutorial" tutorial.
In particular, I made modifications for:
- fixing spelling, syntax, small/upper-cases
- re-wording explanations

Creating tutorial edits

---

topics/introduction/slides/index.html

xref. https://twitter.com/galaxyproject/status/913473050087006208

Update Galaxy publication library link

---

topics/sequence-analysis/tutorials/quality-control/slides.html

- extended the explanation of the "Duplicated sequences" plot
- extended the explanation of the "K-mer plot" plot

"Quality control" slide edits

---

topics/proteomics/tutorials/protein-id-sg-ps/tools.yaml
topics/proteomics/tutorials/protein-id-sg-ps/tours/tour.yaml

added tools and tour for proteomics-protein-id-sg-ps

added tools and tour for proteomics-protein-id-sg-ps

---

bin/docker-install-tutorials.sh

so that it no longer fails if certain files or folders are missing 
(ping @Delphine-L, this should solve your issue)

Update docker install script

---

CONTRIBUTORS.yaml
topics/introduction/metadata.yaml
topics/introduction/slides/index.html

- edited the content of a few slides
- edited the comment section (presentation mode) of a few slides

introduction to Galaxy edits

---

topics/chip-seq/tutorials/estrogen-receptor-binding-site-identification/tutorial.md

thanks for reporting @AisanjiangW

chip-seq: fix link in tutorial

---

topics/dev/tutorials/conda/slides.html

Small fix in conda slides

---

topics/proteomics/tutorials/labelfree-vs-labelled/tutorial.md

Small changes in the text, used HTML for italics in the question answers.

Minor text update for labelfree_vs_labelled tutorial

---

topics/proteomics/tutorials/protein-id-oms/tours/tour.yaml

Added tour for proteomics-protein id with oms

tour for protein id with oms

---

topics/proteomics/tutorials/protein-id-oms/tutorial.md
topics/proteomics/tutorials/protein-id-oms/workflows/workflow.ga
topics/proteomics/tutorials/protein-id-oms/workflows/workflow_two-search-engines.ga

- Added a section for using multiple search engines
- updated workflows
- minor fixes

Updated tutorial for protein ID with OpenMS

---

topics/introduction/metadata.yaml
topics/introduction/tutorials/galaxy-intro-peaks2genes/data-library.yaml
topics/introduction/tutorials/galaxy-intro-peaks2genes/tutorial.md

As discussed yesterday, the data for the peaks2gene tutorial is now in zenodo, here's the updated yaml + tutorial
ping @cmonjeau

Peaks2gene: add data to zenodo

---

templates/tutorials/tutorial1/tutorial.md

with an example of a tool configuration description, to encourage a uniform look and feel of these hands-on parts
ping @bebatut

Update tutorial template

---

topics/proteomics/tutorials/metaproteomics/tools.yaml
topics/sequence-analysis/tutorials/mapping/tours/tour.yaml

- added tour for mapping tutorial
- adjusted style in tools file

Mapping tour and style fixes

---

topics/sequence-analysis/tutorials/mapping/workflows/Galaxy-Workflow-mapping.ga
topics/sequence-analysis/tutorials/mapping/workflows/workflow.ga

added  workflow for the topic of mapping

workflow for seq-an-mapping

---

_layouts/base.html

fix favicon

---

Makefile
_layouts/base.html
assets/js/main.js

It also configures the PDF generation to use this.
Fix #600

Allow to display all answers with ?with-answers

---

_layouts/topic.html

Reorder topic tables

---

_config.yml
_includes/default-header.html
_includes/help.html
_layouts/tutorial_hands_on.html

Add dropdown for help, share logic across pages

---

topics/transcriptomics/tutorials/de-novo/tutorial.md

Fix quoting inside a box

---

_layouts/topic.html
topics/admin/metadata.yaml
topics/assembly/metadata.yaml
topics/chip-seq/metadata.yaml
topics/dev/metadata.yaml
topics/epigenetics/metadata.yaml
topics/introduction/metadata.yaml
topics/metagenomics/metadata.yaml
topics/proteomics/metadata.yaml
topics/sequence-analysis/metadata.yaml
topics/training/metadata.yaml
topics/training/tutorials/create-new-tutorial-metadata/tutorial.md
topics/transcriptomics/metadata.yaml
topics/usegalaxy/metadata.yaml
topics/variant-analysis/metadata.yaml

I replaced the quoted yes/no by non quoted yes/no, such that they can be used as booleans

Use real booleans for "hands-on" and "slides" in metadata

---

Makefile

like we do in htmlproofer. these links are failing the slide checking jobs currently. ping @bebatut

whitelist vimeo in awesomebot

---

_layouts/topic.html
topics/admin/metadata.yaml
topics/assembly/metadata.yaml
topics/chip-seq/metadata.yaml
topics/dev/metadata.yaml
topics/epigenetics/metadata.yaml
topics/introduction/metadata.yaml
topics/metagenomics/metadata.yaml
topics/proteomics/metadata.yaml
topics/sequence-analysis/metadata.yaml
topics/training/metadata.yaml
topics/training/tutorials/create-new-tutorial-metadata/tutorial.md
topics/transcriptomics/metadata.yaml
topics/usegalaxy/metadata.yaml
topics/variant-analysis/metadata.yaml

I linked the tours to the tours on GitHub

Fix path to tours in the topic page and update tour metadata

---

topics/chip-seq/metadata.yaml
topics/chip-seq/tutorials/tal1-binding-site-identification/tours/tour.yaml

Created galaxy tour for chip-seq: tal1-binding-site-identification based on this [workflow](https://github.com/galaxyproject/training-material/pull/601)

added the tour for tal1 binding site identification

---

environment.yml

Add libiconv to environment file

---

topics/transcriptomics/tutorials/ref-based/tutorial.md

'condition' should be in lower case as stated in next paragraph

small correction in ref-based tutorial

---

topics/admin/metadata.yaml
topics/admin/tutorials/deployment-platforms-options/slides.html

Add "deployment and platform options" from dagobah training

---

topics/dev/tutorials/tool-integration/slides.html

"confort" replaced with "comfort"

Fix a typo in the slides

---

topics/admin/tutorials/connect-to-compute-cluster/tutorial.md

See https://bugs.launchpad.net/ubuntu/+source/munge/+bug/1287624

Munge under Ubuntu has been fixed

---

topics/sequence-analysis/tutorials/de-novo-rad-seq/tutorial.md

PNG deletion to be in accordance with PR ref_based_RADseq

---

topics/admin/tutorials/monitoring-maintenance/slides.html

remove nagios links

---

topics/chip-seq/metadata.yaml
topics/chip-seq/tutorials/estrogen-receptor-binding-site-identification/tours/tour.yaml

added tour for _chipseq: estrogen receptor binding site identification_

new tour for chipseq

---

topics/dev/metadata.yaml
topics/dev/tutorials/conda/slides.html
topics/dev/tutorials/conda_sys/slides.html

Hey,
I've prepared these few slides for our small training next week (with @cmonjeau).
In previous sessions I sometimes saw despair and sadness in some students' eyes when the time came to write their first build.sh.
I think that's because they had no idea what are configure, make, make install, env vars, ...
So this time I'll try to explain them the minimum they should know to write a build.sh and understand why they get some errors.
We'll see if it helps them or not. (If not, well... I'll have to make some introspection on my training skills in a buddha temple (or accuse @cmonjeau))

Survival kit for writing Conda's build.sh

---

topics/dev/tutorials/conda/slides.html
topics/dev/tutorials/tool-integration/slides.html
topics/dev/tutorials/toolshed/slides.html

Hi,
Just a few corrections for problems found while presenting + a fix for broken slides in the toolshed presentation (http://galaxyproject.github.io/training-material/topics/dev/tutorials/toolshed/slides.html#61 and following)

Small fixes for dev corner

---

topics/epigenetics/metadata.yaml
topics/epigenetics/tutorials/hicexplorer/tools.yaml
topics/epigenetics/tutorials/hicexplorer/tutorial.md
topics/epigenetics/tutorials/hicexplorer/workflows/empty_workflow.ga

tutorial for hicexplorer

---

topics/metagenomics/tutorials/mothur-miseq-sop/tutorial.md

based on comments from manuscript reviewer

small fixes to mothur miseq SOP

---

topics/transcriptomics/metadata.yaml

Add tour metadata for de-novo transcriptomics tutorial

---

topics/epigenetics/tutorials/methylation-seq/tutorial.md

This bugged OCD-me at the workshop today ...

Methyl-C: Very minor improvements

---

topics/variant-analysis/metadata.yaml
topics/variant-analysis/tutorials/mapping-by-sequencing/tutorial.md

The new title gives a better notion of the topic of the tutorial. Minor changes to the introduction preserve the logic flow.

mapping-by-sequencing tutorial: change title

---

topics/introduction/tutorials/galaxy-intro-peaks2genes/tutorial.md

Hi, 
This is my first contribution.
I think adding these extra lines makes the tutorial clearer.
Thanks.
Regina

Peak to Gene Introduction: Improving the tool description

---

topics/metagenomics/tutorials/general-tutorial/tutorial.md

Hi,
This is my first contribution. I just saw a small error.
JP Maree

Fix the answer for pre.cluster

---

topics/variant-analysis/tutorials/exome-seq/tutorial.md

Hi!
Just correcting some typos
Thanks

Suggested typo correction

---

topics/variant-analysis/tutorials/exome-seq/tutorial.md

Hello, 
Added an extra step to clarify which BAM file to run FreeBayes on.
Please verify.
Thanks

Instruction on which bam file to select

---

topics/epigenetics/tutorials/hicexplorer/tours/tour.yaml

galaxy tour for hicexplorer

---

topics/epigenetics/tutorials/hicexplorer/tours/tour.yaml

Update of HiCExplorer tour

---

CONTRIBUTORS.yaml

As I stumbled upon this file, here are a few more details for me

Add contributor info

---

topics/variant-analysis/tutorials/microbial-variants/workflows/microbial_variant_calling.ga

This PR and especially this [commit](https://github.com/galaxyproject/training-material/commit/dfb97360348d32210f7c4bae68f1154a2336e520) is annotating workflow outputs so we can use it for automatic testing as used in https://github.com/jmchilton/planemo-workflow-test-template/pull/3.
Thanks to @jmchilton for making this so easy now!

prettify json workflow and annotate the workflow outputs

---

topics/introduction/metadata.yaml

@jennaj has kindly agreed to be a maintainer for the introduction topic :)

Add Jen as maintainer for the Galaxy introduction topic

---

CONTRIBUTORS.yaml
topics/sequence-analysis/tutorials/mapping/tutorial.md

There is still some links failing:
- https://tinyurl.com/GTNdenovoRNAseqWorkflow: @MoHeydarian it seems it is your workflow. Can we have access to it?
- https://www.france-bioinformatique.fr: I do not know why

Fix some links

---

CONTRIBUTORS.yaml

Complementing #794 ;-) Thank you!

Add Katrin's email & ORCiD

---

CONTRIBUTORS.yaml

@katrinleinweber Thanks for your PR: I added you in the contributors
If you want to add more information about you (gitter, twitter, email, orcid), feel free 😄

Add katrinleinweber in contributors

---

topics/admin/tutorials/upgrading/slides.html

Minor tweaks/updates to the 'upgrading galaxy' slide related to the client build.

Update client upgrading slide

---

topics/metagenomics/tutorials/mothur-miseq-sop/tutorial.md

I partially modified the document.

---

topics/admin/metadata.yaml
topics/dev/metadata.yaml
topics/introduction/metadata.yaml
topics/sequence-analysis/metadata.yaml

Remove placeholder metadata

---

topics/transcriptomics/tutorials/de-novo/tutorial.md

Remove mention of the external de novo workflow inside the tutorial

---

topics/transcriptomics/tutorials/ref-based/tutorial.md

Add icons for insert tags

---

topics/epigenetics/tutorials/hicexplorer/tours/tour.yaml

corrected double input [issue](https://github.com/galaxyproject/training-material/issues/744)
@joachimwolff

small fix for hicexplorer_tour

---

CONTRIBUTORS.yaml

Add information to erxleben contributor

---

_layouts/topic.html

imo this whole section could be excluded from the admin training topic, since it does not make much sense

improve grammar

---

topics/contributing/tutorials/github-command-line-contribution/tutorial.md

Clarify command line contribution tutorial

---

topics/contributing/tutorials/github-interface-contribution/tutorial.md

Clarify some steps in the GitHub interface tutorial

---

topics/admin/tutorials/connect-to-compute-cluster/slides.html

Fix image path

---

topics/contributing/tutorials/running-jekyll/tutorial.md

the script installs miniconda3

fix the path alteration

---

CONTRIBUTORS.yaml

@cganote Thanks for your PR #852. I added you in the contributor file. You can add more information if you want (email, twitter, etc)

Add cganote as contributor

---

_includes/default-header.html

Comes across as trying to be unnecessarily friendly and personifying an html page.

"Me" is not necessary in edit link

---

topics/sequence-analysis/tutorials/genetic-map-rad-seq/tutorial.md

I'm working on simplifying and fixing grammar in the tutorial language. I am not evaluating the tutorials for functionality. http://galaxyproject.github.io/training-material/topics/sequence-analysis/tutorials/genetic-map-rad-seq/tutorial.html
Attempts were made to remove extraneous words.

Language RAD-Seq to construct genetic maps

---

topics/contributing/tutorials/github-command-line-contribution/tutorial.md

Fix internal link inside command line tutorial

---

topics/assembly/tutorials/general-introduction/tutorial.md

Mostly small tweaks to prepositions and verbs. Added periods at ends of sentences in lists, but this is style choice. Added some blank lines to fix rendering.

grammar and style

---

topics/assembly/tutorials/debruijn-graph-assembly/tutorial.md

That's the only problem I see here.

typo: "m" -> ","

---

topics/variant-analysis/tutorials/microbial-variants/tutorial.md

edited for Text and language changes

microbial-variant-tutorial.md

---

topics/contributing/tutorials/create-new-tutorial/tutorial.md

@bgruening did you mean I should add something like this here?

Add recommendation for tool run times in tutorials

---

CONTRIBUTORS.yaml

Thanks @nvk747 for your contributions.
Feel free to add more of your information there

Add vijay as contributor

---

topics/variant-analysis/tutorials/dip/tutorial.md

@bebatut 
Edited for text and language corrections

dip_tutorial.md

---

topics/introduction/tutorials/galaxy-intro-101/tutorial.md

Added in additional Tip for most common root problems users run into or ask about when executing the 101 tutorial.

Update Intro 101 tutorial.md

---

topics/variant-analysis/tutorials/non-dip/tutorial.md

@bebatut 
Edited for Text and language changes

non-dip-tutorial.md

---

CONTRIBUTORS.yaml

thanks for your contribution @frederikcoppens! I've added you to the contributors file, please feel free to add/edit your information here as you like

add contributor

---

topics/epigenetics/tutorials/hicexplorer/tutorial.md

Added section about how to get public data.

Update HiCExplorer tutorial

---

topics/variant-analysis/tutorials/microbial-variants/tutorial.md

I was just trying to run this tutorial. After downloading, the genbank file was not recognized as such (but as 'txt')

small addition to snippy tutorial

---

topics/variant-analysis/tutorials/exome-seq/tutorial.md

spotted a broken box in this tutorial

exome-seq tutorial: fix comment box

---

topics/admin/tutorials/database-schema/tutorial.md
topics/epigenetics/tutorials/methylation-seq/tutorial.md
topics/genome-annotation/tutorials/genome-annotation/tutorial.md
topics/introduction/tutorials/galaxy-intro-101/tutorial.md

Sorry @shiltemann missed some in #935

More missed boxes

---

topics/variant-analysis/metadata.yaml
topics/variant-analysis/tutorials/mapping-by-sequencing/tours/tour.yaml

galaxy tour for variant-analysis/mapping-by-sequencing
@bebatut

tour for mapping-by-sequencing

---

topics/variant-analysis/metadata.yaml
topics/variant-analysis/tutorials/microbial-variants/tours/tour.yaml

Microbial variants tour

---

faq.md

adds a small checklist for people who would like to contribute to the project by checking existing tutorials.
ping @bebatut

FAQ: add checklist for tutorial editors

---

shared/datatypes.yaml

It is needed for https://github.com/galaxyproject/planemo/pull/861

Add yaml file with correspondance between Zenodo ext and Galaxy datatype

---

topics/admin/tutorials/galaxy-docker/slides.html
topics/dev/tutorials/conda/slides.html
topics/dev/tutorials/containers/slides.html
topics/dev/tutorials/interactive-tours/slides.html
topics/dev/tutorials/tool-integration/slides.html
topics/dev/tutorials/toolshed/slides.html
topics/dev/tutorials/webhooks/slides.html

Replace fa fa-pencil by hands_on icon

---

metadata/templates.yaml
topics/templates

remove dummy topic and tuto, was only needed to test colour scheme, ping @erasche

remove temporary template topic

---

topics/sequence-analysis/metadata.yaml
topics/sequence-analysis/tutorials/genetic-map-rad-seq/tours/tour.yaml

tour for genetic map rad seq

---

topics/transcriptomics/metadata.yaml
topics/transcriptomics/tutorials/rna-seq-viz-with-cummerbund/tours/tour.yaml

tour for rna-seq-viz-with-cummerbund

---

faq.md

added some instructions about how to easily test/review interactive tours using the Tour builder browser extension

FAQ: add instructions on testing interactive tours

---

_layouts/topic.html

Otherwise the dataset icon is sometimes displayed

Check if zenodo parameter exists in topic page

---

topics/variant-analysis/tutorials/microbial-variants/workflows/microbial_variant_calling-job.yml
topics/variant-analysis/tutorials/microbial-variants/workflows/microbial_variant_calling-test.yml

This is working and is meant as documentation for other working on workflow testing. I would like to get rid of the input test data files here before merging.

add workflow testing files

---

bin/publish

Add .nojekyll for gh-page

---

404.md
_layouts/404.html

Add custom 404 page

---

CONTRIBUTORS.yaml

@mblue9 you were not in the list of contributor 😟 
Feel free to add more details 😄

Add mblue9 in the contributors

---

CONTRIBUTORS.yaml
topics/transcriptomics/tutorials/limma-voom/tutorial.md
topics/transcriptomics/tutorials/limma-voom_fastqs_to_counts/tutorial.md

For https://github.com/galaxyproject/training-material/pull/1012#pullrequestreview-158136108

Add contributor info for limma-voom tutorial

---

topics/contributing/slides/introduction.html
topics/contributing/tutorials/create-new-tutorial-content/tutorial.md
topics/introduction/tutorials/galaxy-intro-101/tutorial.md

Update tool parameter style.
Various fixes.
Also small fixes to `contributing` training.

Update Galaxy 101 tutorial

---

_layouts/base.html

Forgot this commit, sorry y'all

Link previews part 2

---

topics/introduction/tutorials/galaxy-intro-peaks2genes/tutorial.md

This is a couple of tiny fixes and adds a comment on what Interval format is (BED had a comment to explain it but not Interval)

Peaks2genes: small edits

---

CONTRIBUTORS.yaml

Thanks @foellmelanie for the PRs #1035 #1032 and #790
You can add more information if you want :smile:

Add foellmelanie to the contributors

---

Makefile
topics/contributing/tutorials/running-jekyll/tutorial.md

Also update conda env if it already exists when executing `make create-env` .

Activate conda env in Makefile rule recipes

---

_layouts/topic.html

To avoid having it for the dev, admin, contributing topics

Display instance section only for 'use' topic

---

metadata/instructors.yaml
topics/instructors/README.md
topics/instructors/index.md
topics/instructors/metadata.yaml

As discussed during the GTN instructor meetings #1009

Create topic for material for instructors

---

topics/proteomics/tutorials/protein-quant-sil/tutorial.md

consensusXML is the output of featurefindermultiplex tool, not fidoadapter

corrected tool name

---

topics/introduction/slides/introduction.html

Hey all,
A little fix for a broken link on http://galaxyproject.github.io/training-material/topics/introduction/slides/introduction.html#14

Fix broken link from intro to get-data

---

topics/transcriptomics/tutorials/network-analysis-with-heinz/tutorial.md

oops, my mistake, fixed the time estimation format for recently merged heinz tutorial

Heinz: fix time estimation format

---

_plugins/jekyll-jsonld.rb

the json ld probably expects upper case letters for the time. While any case is fine internally, it needs to match spec on output.

Fix casing of the time string

---

.yamllint
Makefile
metadata/instances.yaml
topics/assembly/tutorials/general-introduction/workflows/assembly-general-introduction-job.yml
topics/assembly/tutorials/general-introduction/workflows/assembly-general-introduction-test.yml
topics/assembly/tutorials/unicycler-assembly/workflows/unicycler-job.yml
topics/assembly/tutorials/unicycler-assembly/workflows/unicycler-test.yml
topics/chip-seq/tutorials/formation_of_super-structures_on_xi/workflows/formation_of_super_structures_on_xi-job.yml
topics/chip-seq/tutorials/formation_of_super-structures_on_xi/workflows/formation_of_super_structures_on_xi-test.yml
topics/epigenetics/tutorials/methylation-seq/workflows/methylation-seq-job.yml
topics/epigenetics/tutorials/methylation-seq/workflows/methylation-seq-test.yml
topics/metagenomics/tutorials/general-tutorial/workflows/amplicon-job.yml
topics/metagenomics/tutorials/general-tutorial/workflows/amplicon-test.yml
topics/sequence-analysis/tutorials/mapping/workflows/mapping-job.yml
topics/sequence-analysis/tutorials/mapping/workflows/mapping-test.yml
topics/sequence-analysis/tutorials/quality-control/workflows/quality_control-job.yml
topics/sequence-analysis/tutorials/quality-control/workflows/quality_control-test.yml
topics/transcriptomics/tutorials/ref-based/workflows/ref_based-job.yml
topics/transcriptomics/tutorials/ref-based/workflows/ref_based-test.yml
topics/variant-analysis/tutorials/microbial-variants/workflows/microbial_variant_calling-job.yml
topics/variant-analysis/tutorials/microbial-variants/workflows/microbial_variant_calling-test.yml

Started trying to run the workflow tests against usegalaxy.eu only to find many contained yaml issues that caused immediate test failures.

Fix workflow testing YAML

---

snippets/extract_workflow.md
topics/transcriptomics/tutorials/network-analysis-with-heinz/tutorial.md

Hi, everyone:
Thank you for the feedback and encouragement for the Heinz training material. #962 
I quickly updated it to include your feedback.
The main change includes:
1. Changed the title to "network analysis with Heinz"
2. Emphasized the fact that Heinz can be applied to transcriptomics dataset thanks to @mblue9 
3. Typo corrections.
4. Added a new task for learners at the end of the tutorial.
5. Adjusted the contributor list of this tutorial.
Best regards,
Cico

A small update to Heinz based on the feedback

---

Makefile

Here's the fix suggested by @nsoranzo for #1095 
Tested located, it works fine

Repair make pdf

---

topics/genome-annotation/tutorials/annotation-with-maker/tutorial.md

A tiny error in some dataset names...

Maker: fix wrong dataset names

---

_includes/help.html

in order to avoid using possibly unknown terms

reword masthead help

---

topics/genome-annotation/tutorials/annotation-with-prokka/tutorial.md

- genome-annot/annotation-with-prokka
@bebatut

remove screenshots from genome-annot/annot-w-prokka

---

topics/contributing/tutorials/create-new-tutorial-technical/tutorial.md

Hey @mtekman did you get the collections test working? (If not can you just comment with the link?)

Document workflow testing briefly

---

topics/assembly/tutorials/ecoli_comparison/tours/tour.yaml

tour for assembly-ecoli comparison

---

topics/transcriptomics/tutorials/network-analysis-with-heinz/tours/tour.yaml

tour for transcriptomics/network-viz-heinz

---

topics/transcriptomics/tutorials/network-analysis-with-heinz/tours/tour.yaml

Fix lint issue added with #1118

Fix yaml linting

---

_layouts/base_slides.html
_layouts/topic.html
_layouts/tutorial_hands_on.html

fix some missing defaults

---

_includes/help.html

Search! (by TeSS)

---

_includes/help.html

Move dropdown left

---

topics/chip-seq/tutorials/formation_of_super-structures_on_xi/tours/formation_of_super-structures_on_xi_main.yaml
topics/chip-seq/tutorials/formation_of_super-structures_on_xi/tours/formation_of_super-structures_on_xi_qualitycontrol_mapping.yaml

chipseq - formation_of_super-structures_on_xi
@bebatut

tours for formation_of_super-structures_on_xi

---

_config.yml

As requested this morning by @pvanheus

Support arabic translation

---

CONTRIBUTORS.yaml
topics/chip-seq/tutorials/formation_of_super-structures_on_xi/tours/formation_of_super-structures_on_xi_qualitycontrol_mapping.yaml

Add @mtekman to training materials contributors

---

topics/transcriptomics/metadata.yaml

Add Maria Doyle as maintainer for transcriptomics topic

---

Makefile

to make it possible to locally check....

Add internal link check in make check command

---

bin/validate-frontmatter.rb
topics/chip-seq/tutorials/estrogen-receptor-binding-site-identification/tutorial.md
topics/chip-seq/tutorials/tal1-binding-site-identification/tutorial.md
topics/transcriptomics/tutorials/rb-rnaseq/tutorial.md
topics/variant-analysis/tutorials/dip/tutorial.md
topics/variant-analysis/tutorials/dunovo/tutorial.md

And also add a missing Zenodo link

Disable tutorials without Zenodo link and some chip-seq

---

topics/sequence-analysis/tutorials/quality-control/tutorial.md

ping @bebatut: as discussed at EGD I added the algorithmic details of quality filtering of cutadapt. For the adapter alignment I added a short QA section.

QC: added details on cutadapt

---

CODEOWNERS

Per @slugger70's request in https://github.com/galaxyproject/training-material/pull/1154#issuecomment-441775096

Add Simon to assembly

---

_config.yml
topics/introduction/tutorials/galaxy-intro-peaks2genes/tutorial.md

- use the full tag since only clarified in the note which someone could skip that you need the `#` sign
- the bar chart doesn't seem to include the icon for me?

peak2genes tiny update

---

topics/sequence-analysis/tutorials/quality-control/tutorial.md

Add example in algorithmic details of cutadapt

---

assets/js/main.js

Now you must click on the tab itself with the + icon.

Fixes #1121

---

topics/variant-analysis/tutorials/non-dip/tours/tour.yaml

tour for var-an/non-dip

---

topics/variant-analysis/tutorials/dip/workflows/diploid.ga

@bebatut 
* workflow for variant-analysis / diploid

workflow for diploid

---

topics/admin/tutorials/users-groups-quotas/slides.html

drop deprecated openid
remove unwanted exercise
ini>yml
etc.

round of up-to-dates

---

.travis.yml
Makefile
package-lock.json
package.json

Hopefully it should fix the current error in Travis

Clean Makefile and update packages

---

topics/dev/tutorials/architecture/slides.html
topics/dev/tutorials/conda/slides.html

See failing Travis job:
https://travis-ci.org/galaxyproject/training-material/jobs/483607820

Fix broken links

---

topics/admin/tutorials/ansible-galaxy/tutorial.md

I didn't want to commit them directly to `admin` since things are still in flux.

Changes to #1195 as the galaxyproject.galaxy role evolves

---

topics/admin/tutorials/ansible/tutorial.md
topics/admin/tutorials/terraform/tutorial.md
topics/admin/tutorials/tool-management/slides.html
topics/admin/tutorials/tool-management/tutorial.md

add basic ephemeris exercise

---

topics/admin/tutorials/gxadmin/tutorial.md

Anything to add @Slugger70 @natefoo @bgruening? It reads a lot like an advert and I don't know how to fix it :(

Add gxadmin tutorial

---

CONTRIBUTORS.yaml
topics/admin/tutorials/production/slides.html

and fix dblank reference.
Fixes the broken build.

Add abdulrahmanazab to contributors

---

topics/admin/tutorials/ansible-galaxy/tutorial.md

still needs more details IMO but better than nothing I suspect.

letencrypt fixes

---

topics/admin/tutorials/reports/tutorial.md

Somebody please check whether the `"` are correct now. @natefoo ?

reorganize reports training to be more intuitive

---

bin/publish

should help the travis failure on `bin/publish-archive` file not found error

add git reset for subsequent actions

---

bin/publish

Sorry, broke the build due to misunderstanding the execution flow.

Move directory instead

---

Makefile
_config.yml
_layouts/base.html
_layouts/tutorial_hands_on.html
bin/publish
topics/admin/tutorials/tool-management/tutorial.md
topics/dev/tutorials/interactive-tours/slides.html
topics/dev/tutorials/webhooks/slides.html
topics/instructors/tutorials/setup-tiaas-for-training/tutorial.md
topics/introduction/README.md
topics/proteomics/tutorials/database-handling/workflows/readme.md
topics/proteomics/tutorials/protein-id-sg-ps/workflows/readme.md
topics/transcriptomics/README.md

It did not work quite as expected, need to do some more testing or try something else.

Revert proxying update

---

topics/transcriptomics/tutorials/rna-seq-viz-with-cummerbund/workflows/workflow.ga

with the parameter `features: gene`, resulting plot is different from the hands-on page

rna-seq-viz-with-cummerbund: isoforms instead of gene

---

topics/assembly/tutorials/ecoli_comparison/tutorial.md
topics/assembly/tutorials/ecoli_comparison/workflows/ecoli-comparison.ga

@bebatut 
- workflow
- typos in tutorial

Ecoli comparison tutorial workflow

---

topics/assembly/tutorials/ecoli_comparison/tours/tour.yaml

update tour -ecoli_comparison

---

assets/css/slides.css
topics/transcriptomics/tutorials/scrna-plates-batches-barcodes/slides.html

* Moves CSS to proper location in assets
* A few minor formatting changes

Fix to Plates and Batches slides

---

topics/assembly/tutorials/debruijn-graph-assembly/tours/tour.yaml
topics/assembly/tutorials/debruijn-graph-assembly/workflows/debruijn-graph.ga

Debruijn wf tour

---

topics/transcriptomics/tutorials/scrna_preprocessing/tutorial.md

This is already a requirement on the topic level.

remove redundant reuquirement from scRNA training

---

topics/contributing/tutorials/create-new-topic/tutorial.md
topics/contributing/tutorials/create-new-tutorial-technical/tutorial.md
topics/contributing/tutorials/create-new-tutorial/tutorial.md

Tools are now installed based on the workflows.

Changed contributing tutorials to not use the tools.yaml file anymore

---

topics/metagenomics/tutorials/mothur-miseq-sop/tutorial.md

fixes https://github.com/galaxyproject/training-material/issues/1293
xref: https://github.com/galaxyproject/training-material/pull/1299

enable mothur-miseq-sop tutorial

---

topics/statistics/tutorials/classification_regression/tutorial.md

This PR improves text in the [training material](https://training.galaxyproject.org/training-material/topics/statistics/tutorials/classification_regression/tutorial.html).
ping @bebatut

Improve tutorial text

---

topics/transcriptomics/tutorials/scrna_preprocessing/tutorial.md

Minor fix to links (Zenodo record updated thanks to fix from their team)
Input names fixed (Thanks to J Kim for spotting these)

Fix to Pre-processing

---

topics/metagenomics/tutorials/mothur-miseq-sop/tutorial.md

Small tweaks to the 16S tutorial based on some feedback: 
- Clarify that files should be renamed before uploading to Phinch (to address this [comment](https://github.com/galaxyproject/training-material/issues/989#issuecomment-471329061))
- Clarify which URLs to use for upload from Zenodo 
- Fix some of the tool numbering in hands_on boxes

16S tutorial tweaks

---

topics/variant-analysis/tutorials/somatic-variants/data-library.yaml
topics/variant-analysis/tutorials/somatic-variants/tutorial.md

Not quite perfect yet, but good enough to be reviewed I hope.

Add new somatic variant calling tutorial

---

snippets/add_tag.md
snippets/create_new_history.md
snippets/rename_dataset.md
snippets/rename_history.md
snippets/select_multiple_datasets.md

Fixes to several snippets

---

_layouts/base_slides.html
_plugins/jekyll-jsonld.rb
snippets/display_extra_training.md
snippets/display_extra_training_slides.md

Fix link to external tutorial for required or follow-up tutorials

---

CONTRIBUTORS.yaml
topics/proteomics/tutorials/protein-quant-sil/tutorial.md
topics/proteomics/tutorials/protein-quant-sil/workflows/workflow.ga

removed highresprecursermasscorrecter and added multiplexresolver
few improvements in ID part of workflow to make more modular training possible
Updated to OpenMS 2.3

Improved and updated Peptide and Protein quantification via SIL

---

CONTRIBUTORS.yaml
topics/transcriptomics/tutorials/rna-seq-counts-to-genes/tutorial.md
topics/transcriptomics/tutorials/rna-seq-genes-to-pathways/tutorial.md
topics/transcriptomics/tutorials/rna-seq-reads-to-counts/tutorial.md

Add Jovana to contributors and unhide the 3 related tutorials.

RNA-seq limma tutorials: unhide

---

CONTRIBUTORS.yaml
topics/proteomics/tutorials/proteogenomics-dbcreation/tutorial.md
topics/proteomics/tutorials/proteogenomics-dbsearch/tutorial.md
topics/proteomics/tutorials/proteogenomics-novel-peptide-analysis/tutorial.md

tutorial.md

---

topics/metagenomics/tutorials/mothur-miseq-sop/tutorial.md

better stress the importance of using the correct pair names in collection creation step

[16S rRNA with mothur] clarify pair naming step and importance

---

topics/transcriptomics/tutorials/scrna-umis/tutorial.md
topics/transcriptomics/tutorials/scrna_preprocessing/tutorial.md

More fixes, updated details, and subsetted the preprocessing data due to massive bottleneck in processing (Reduction from 40 minutes to 5 minutes)

Fixes to scRNA material

---

topics/transcriptomics/tutorials/scrna-plates-batches-barcodes/slides.html
topics/transcriptomics/tutorials/scrna-raceid/tutorial.md
topics/transcriptomics/tutorials/scrna-umis/tutorial.md
topics/transcriptomics/tutorials/scrna_preprocessing/tutorial.md

- Rearranged certain parts again. 
- Slides for barcoding seen more are two parts than as a single tutorial (I am likely to split this at a later time point).
- Reordered certain hands-on sections so that there is less waiting

Last changes to scRNA material

---

_includes/contributor-text-list.html
_layouts/tutorial_hands_on.html

Bug noticed by @nsoranzo in https://github.com/galaxyproject/training-material/pull/1352

Fix contributor list

---

topics/transcriptomics/tutorials/rna-seq-counts-to-genes/tutorial.md

Adds a step to replace the hyphen in the counts file sample ids with dot so the ids match

Counts to genes: add step

---

topics/sequence-analysis/tutorials/quality-control/tutorial.md

"Filter options" to "Read Modification Options"

---

topics/sequence-analysis/tutorials/mapping/tutorial.md

noticed in workshop today, name of tool and the reference parameter slightly out of sync with latest version of the tool

Mapping: update tool name and parameter

---

topics/introduction/tutorials/galaxy-intro-101/tutorial.md

Fix broken box

---

topics/assembly/images/bandage-velvet-21.svg
topics/assembly/images/bandage-velvet-33.svg
topics/assembly/images/bandage-velvet-53.svg
topics/assembly/images/bandage-velvet-77.svg
topics/assembly/images/bandage-velvet.svg
topics/assembly/images/bandage_spades.svg
topics/assembly/tutorials/debruijn-graph-assembly/tutorial.bib
topics/assembly/tutorials/debruijn-graph-assembly/tutorial.md

Ping @Slugger70, we'll probably merge before you have a chance to review but if you review after we can fix anything you see as important :)

Add bandage to de bruijn graph assembly tutorial

---

topics/genome-annotation/tutorials/annotation-with-maker/tutorial.md
topics/genome-annotation/tutorials/annotation-with-maker/workflows/main_workflow.ga

Hi,
A few typo fixes in the tutorial + updated the workflow to use the latest version of tools

Maker: fix typos + update workflow

---

topics/computational-chemistry/tutorials/md-simulation-gromacs/tutorial.md

fix tool name

---

bin/mergeyaml.py
topics/assembly/tutorials/ecoli_comparison/data-library.yaml
topics/epigenetics/tutorials/hicexplorer/data-library.yaml
topics/genome-annotation/tutorials/annotation-with-maker/data-library.yaml
topics/transcriptomics/tutorials/de-novo/data-library.yaml
topics/transcriptomics/tutorials/network-analysis-with-heinz/data-library.yaml
topics/transcriptomics/tutorials/srna/data-library.yaml
topics/variant-analysis/tutorials/dip/data-library.yaml
topics/variant-analysis/tutorials/exome-seq/data-library.yaml
topics/variant-analysis/tutorials/microbial-variants/data-library.yaml
topics/variant-analysis/tutorials/somatic-variants/data-library.yaml

They were populating the top level directories, rather than existing within their topic

Correct indentation for a couple libraries

---

Makefile
bin/check-for-trailing-newline

Just saw this on my todo list from a while and it only took a minute

Check trailing newlines in snippets

---

CONTRIBUTORS.yaml
topics/transcriptomics/tutorials/scrna-raceid/tutorial.md

Raceid tutorial edited to be less verbose and put some text in details boxes. My email was also added to CONTRIBUTORS.yaml

Raceid gcc

---

topics/sequence-analysis/tutorials/mapping/workflows/mapping-job.yml

need both reverse and forward reads; bowtie is run paired-end mode

fix mapping training workflow job yml

---

topics/transcriptomics/tutorials/scrna-raceid/tutorial.md

Fixes to RaceID material

---

topics/variant-analysis/metadata.yaml

- Provide an adequate summary of the material in the variant analysis section.
- Add myself as a maintainer.

Update variant-analysis metadata

---

topics/transcriptomics/tutorials/scrna_preprocessing/tutorial.md

Quick fix to links, spotted by @astrovsky

Fix to Pre-processing links

---

topics/transcriptomics/tutorials/scrna_preprocessing/tutorial.md

Small change to a parameter name.
This should be it for this tutorial
Thanks @shiltemann !

Add (one more final!) fix to pre-processing

---

topics/galaxy-data-manipulation/tutorials/upload-rules/tutorial.md

The ENA links are unavailable atm

Backup links zenodo

---

topics/admin/tutorials/ansible-galaxy/tutorial.md
topics/admin/tutorials/ansible/tutorial.md

Just catching minor recommendations as we go through the admin documentation for GCC2019 training.

Add minor content, syntax fixes

---

topics/assembly/tutorials/general-introduction/tutorial.md

The file 'wildtype.fna' is needed for Quast. Added the upload information for this file at the start of the tutorial.

Added information about uploading reference file

---

CONTRIBUTORS.yaml

I am going to add my name in the contributors list, please

My branch for adding name

---

topics/proteomics/tutorials/proteogenomics-novel-peptide-analysis/tutorial.md

Repair of a hand-on box

---

topics/proteomics/tutorials/biomarker_selection/tutorial.md

Addition of the version of Uniprot (ID conversion tool)

Uniprot version info addition

---

topics/dev/tutorials/bioblend-api/slides.html

Fix error slide 30: remove quotes around role_id

Update slides.html page 30

---

.travis.yml
Makefile
_config.yml
_layouts/tutorial_hands_on.html
_plugins/jekyll-notranslate.rb

This PR implements the list detailed in #1141

Add non translation of words

---

topics/admin/metadata.yaml

Confirmed out-of-band with him

Add @Slugger70 to admin maintainers

---

topics/sequence-analysis/tutorials/genetic-map-rad-seq/tutorial.md

- seq-an/genetic-map-rad-seq
@bebatut

remove screenshot genetic-map-rad-seq

---

_layouts/base.html

messed up my original if statement, now the resources are only loaded on topic pages (and save some console warnings)

Only include topic search javascript on topic pages

---

topics/genome-annotation/metadata.yaml

Hey @Slugger70 @abretaud are y'all good with this? :)

Update maintainers for genome annotation

---

topics/transcriptomics/tutorials/scrna-plates-batches-barcodes/slides.html

Fix to materials found by Md. Abul Hassan Samee

Fix to Plates slides

---

topics/transcriptomics/images/scrna-plates-batches-barcodes_slide11.svg

another small fix to the SVG itself

Small fix to Plates slides again

---

_layouts/tutorial_hands_on.html

Remove list of Galaxies for admin tutorials

---

_layouts/tutorial_hands_on.html

Adds a brief note asking instructors to provide their feedback next to where users are asked.

Request feedback from instructors

---

_config.yml
_includes/instance-dropdown.html

prevent e.g. https://help.galaxyproject.org/t/phinch-visualization-tool-not-found/2116

clarify what 'Galaxies' dropdown does

---

topics/epigenetics/tutorials/estrogen-receptor-binding-site-identification/tutorial.md
topics/epigenetics/tutorials/formation_of_super-structures_on_xi/tutorial.md
topics/epigenetics/tutorials/tal1-binding-site-identification/tutorial.md

Add redirect for chip-seq tutorials

---

topics/transcriptomics/tutorials/scrna-preprocessing-tenx/tutorial.md

do the alignment first, before describing how to use MultiQC to look at “STAR log output”

re-arrange the steps in Pre-processing of 10X

---

bin/mergeyaml.py

for @bedroesb xref https://github.com/galaxyproject/training-material/commit/544524a1652f6cfb41f5622bc31ea98f5f726cc3#r35073263

Support docker/non-docker data library builds

---

topics/transcriptomics/tutorials/scrna-preprocessing-tenx/tutorial.md

in order to get the 7,685,925 reads two parameters are missing

missing parameters

---

topics/transcriptomics/tutorials/rna-seq-counts-to-viz-in-r/tutorial.md

since this works the same for both Rstudio in Galaxy and in Cloud
ping @erasche

R-lesson: use zenodo link for input dataset and import to R by url

---

snippets/launch_rstudio.md

@bgruening oops, forgot to add this file to previous PR

R-lesson: add (temporary) instructions for starting rstudio in Galaxy

---

topics/admin/tutorials/ansible-galaxy/tutorial.md

I spent some time to figure out the python requirements. The comment might help other people who have similar background to me.

add comments for python prerequisites in ansible galaxy installation

---

topics/metagenomics/tutorials/general-tutorial/krona.html
topics/metagenomics/tutorials/general-tutorial/tutorial.md

Embed the interactive Krona plot output directly in the tutorial

Metagenomics global picture: embed interactive krona plot

---

topics/admin/tutorials/ansible-galaxy/playbook.txt
topics/admin/tutorials/ansible-galaxy/tutorial.md

Follow-up on https://github.com/galaxyproject/training-material/pull/1627 .

Use `geerlingguy.pip` role to install pip

---

topics/admin/tutorials/ansible-galaxy/tutorial.md

From @qiagu's comments in gitter

add section on upgrade procedures

---

topics/dev/tutorials/conda/slides.html

following ecoinfoFAIR comment ;)

Update conda activate

---

topics/transcriptomics/tutorials/scrna-preprocessing/tutorial.md

* Fix to the default argument in featurecounts.
* Referenced 10x workflow

smallfix to Preprocessing training

---

topics/transcriptomics/tutorials/clipseq/tours/tour.yaml

@bebatut tour for transcriptomics

tour for clipseq

---

topics/statistics/tutorials/machinelearning/tours/tour.yaml
topics/statistics/tutorials/machinelearning/workflows/machine_learning.ga

Machine Learning: tour and workflow

---

topics/statistics/tutorials/classification_regression/tours/tour.yaml

- tour for statistics/classification_regression
@bebatut

tour for ml: classification and regression

---

shared/datatypes.yaml
topics/ecology/tutorials/de-novo-rad-seq/data-library.yaml
topics/ecology/tutorials/genetic-map-rad-seq/data-library.yaml
topics/ecology/tutorials/ref-based-rad-seq/data-library.yaml
topics/ecology/tutorials/regionalGAM/data-library.yaml
topics/epigenetics/tutorials/formation_of_super-structures_on_xi/data-library.yaml
topics/metabolomics/tutorials/msi-analyte-distribution/data-library.yaml
topics/proteomics/tutorials/mass-spectrometry-imaging-loading-exploring-data/data-library.yaml
topics/proteomics/tutorials/protein-id-oms/data-library.yaml
topics/proteomics/tutorials/protein-id-sg-ps/data-library.yaml

Just some cleanup to the data-libray.yaml files for the ecology topic (found while trying to use some kind of https://github.com/usegalaxy-eu/shared-data for galaxy.genouest.org)

Fix data-library.yaml for ecology

---

.github/labeler.yml
.github/workflows/greetings.yml
.github/workflows/label.yml

Add [Github actions](https://github.com/features/actions) for
- Greeting first-time contributors
- automatically labelling PRs with the `topic:topic_name` labels depending on the files they touch 
thanks @erasche!

Add GitHub actions

---

topics/statistics/tutorials/classification_regression/tutorial.md

Support vector machines (SVMs) for classification tool (Galaxy Version 1.0.7.12) https://ecology.usegalaxy.eu/root?tool_id=toolshed.g2.bx.psu.edu/repos/bgruening/sklearn_svm_classifier/sklearn_svm_classifier/1.0.7.12

Updating parameter options for version 1.0.7.12 SVM

---

_layouts/training_philosophies.html

Add toc to training philosophies

---

topics/genome-annotation/tutorials/tnseq/tutorial.md

Thanks for the bug report @jimhu-tamu

Fix zenodo DOI

---

bin/mergeyaml.py

The automated update produced a big ugly diff. Probably due to machine differences. This seems to reduce that diff. https://github.com/usegalaxy-eu/shared-data/commit/938f0e9fe856d59d2d8be82386a429b6080732e4
It really doesn't matter, only machines should read this anyway, but, it'll make the diffs prettier.

Sort the outputs

---

topics/introduction/tutorials/r-advanced/tutorial.md
topics/transcriptomics/tutorials/rna-seq-counts-to-viz-in-r/tutorial.md

R lesson: add import box for newcomers

---

topics/transcriptomics/tutorials/scrna-scanpy-pbmc3k/tutorial.md

some grammar, spelling, small additions
to #1698 
@bebatut

Minor suggestions to ScanPy tutorial

---

topics/statistics/tutorials/age-prediction-with-ml/tutorial.md
topics/statistics/tutorials/classification_regression/tutorial.md
topics/statistics/tutorials/classification_regression/workflows/classification_LSVC.ga
topics/statistics/tutorials/classification_regression/workflows/regression_GradientBoosting.ga
topics/statistics/tutorials/machinelearning/tutorial.md
topics/statistics/tutorials/machinelearning/workflows/machine_learning.ga

Updated the 'Basics of machine learning' and 'Classification/regression' tutorials and the associated workflows to match the latest tools. Also did some proofreading of all tutorials.

Checking ML tutorials, updating workflows

---

topics/proteomics/tutorials/proteome_annotation/tutorial.md

Lacombe_2018.txt is uploaded, the user could not find `Lacombe_et_al_2017.txt` as was written in inputs

Input File did not match upload, giving a user trouble

---

topics/transcriptomics/tutorials/scrna-scanpy-pbmc3k/tutorial.md

MInor fixes to material, includes parameter issue spotted by @hrhotz 
https://github.com/galaxyproject/training-material/issues/1748

PBMC 3K minor fixes

---

topics/admin/tutorials/monitoring/slides.html
topics/admin/tutorials/monitoring/tutorial.md

some tweaks ahead of admin training

[Admin] monitoring updates

---

topics/transcriptomics/tutorials/scrna-scanpy-pbmc3k/tutorial.md

small improvements in the text in order to make it clearer which tool to use

fixes to Clustering 3K PBMCs with Scanpy

---

topics/metagenomics/tutorials/metatranscriptomics-short/tutorial.md

made a shorter version of the tutorial but forgot to update the time estimate, thanks for spotting @hexylena :)

Metatranscriptomics: update time estimate

---

topics/admin/tutorials/ansible/tutorial.md

tested this one as well, just a few minor updates :)

[Admin] Ansible updates

---

topics/transcriptomics/tutorials/scrna-scanpy-pbmc3k/tutorial.md

small improvements in the second half of the text in order to make it clearer which tool to use (same problem as #1760)

fixes to Clustering 3K PBMCs with Scanpy part II

---

topics/transcriptomics/tutorials/scrna-preprocessing-tenx/tutorial.md

Fix to scRNA 10X Pre-Processing Tutorial

---

topics/transcriptomics/tutorials/ref-based/tutorial.md

Mentioned here in greater detail:
https://github.com/galaxyproject/training-material/issues/1728

Reference-based RNA-seq - fix to DESeq example values

---

topics/admin/tutorials/ansible/tutorial.md
topics/admin/tutorials/cvmfs/tutorial.md
topics/admin/tutorials/jenkins/tutorial.md
topics/admin/tutorials/tool-management/tutorial.md
topics/dev/tutorials/bioblend-api/slides.html

- Add ephemeris installation instructions
- Explain how to get the API key of an admin
-  Test only one tool. Use `shed-tools test`
- Other small fixes.

Ephemeris tutorial improvements

---

topics/admin/tutorials/tiaas/tutorial.md

demos:
https://usegalaxy.eu/tiaas/stats/
https://usegalaxy.eu/tiaas/calendar/

TIaaS - two new urls for users to visit

---

topics/admin/tutorials/ansible-galaxy/slides.html
topics/admin/tutorials/production/slides.html

And move a couple slides to the ansible-galaxy slides (which are really more of "what a production server looks like" slides).

Update production slides

---

topics/admin/tutorials/ansible-galaxy/group_vars/galaxyservers.yml
topics/admin/tutorials/ansible-galaxy/tutorial.md
topics/admin/tutorials/gxadmin/tutorial.md
topics/admin/tutorials/interactive-tools/tutorial.md
topics/admin/tutorials/reports/tutorial.md
topics/admin/tutorials/systemd-supervisor/slides.html
topics/admin/tutorials/tool-management/slides.html

@hexylena feel free to commit directly if you want to change anything

Update systemd slides

---

shared/datatypes.yaml
topics/transcriptomics/tutorials/scrna-scanpy-pbmc3k/data-library.yaml

@shiltemann @mtekman @bebatut whoever is awake :)

Add library for 3k pbmcs

---

topics/transcriptomics/tutorials/scrna-preprocessing-tenx/data-library.yaml

Training library

---

topics/admin/tutorials/ansible-galaxy/tutorial.md

The small supervisord section was duplicated in the trianing.

Remove duplicated text from the training

---

_layouts/base_slides.html

add a tip about how to view presenter modes during a presentation

Add hint about using presenter mode to slide template

---

topics/dev/tutorials/bioblend-api/slides.html

- Remove references to ambiguous "web API"
- Update supported Python versions and Galaxy releases

Update BioBlend slides

---

topics/admin/tutorials/object-store/tutorial.md

Requires: https://github.com/galaxyproject/galaxy/pull/7294

admin s3 support training whee

---

topics/admin/tutorials/connect-to-compute-cluster/tutorial.md
topics/admin/tutorials/general-monitoring/slides.html
topics/admin/tutorials/pulsar/tutorial.md
topics/admin/tutorials/reports/tutorial.md
topics/admin/tutorials/uwsgi/slides.html

:us::fireworks::us::fireworks:

Pulsar to py3k

---

topics/admin/tutorials/pulsar/tutorial.md

Fix typo in pulsar tutorial

---

topics/admin/tutorials/connect-to-compute-cluster/tutorial.md
topics/admin/tutorials/monitoring/tutorial.md

- Clarify which playbook to run
- Remove unneeded `-i hosts`

More fixes

---

topics/admin/tutorials/ansible/slides.html
topics/admin/tutorials/ansible/tutorial.md

xref https://github.com/galaxyproject/training-material/issues/1809

Ansible tutorial TODOs from Barcelona

---

topics/admin/tutorials/ansible-galaxy/tutorial.md

Reported by @lldelisle , thanks!

Fix solution of "Minimal Galaxy Playbook" hands-on

---

topics/contributing/tutorials/running-jekyll/tutorial.md

add some tips for when running on a VM with possibly limited space (e.g. in a training)

Contributing: add some tips

---

Makefile
bin/add_galaxy_instance_badges.py

fixes #1820, and a few other minor tweaks

Do not fail on badges error

---

topics/transcriptomics/tutorials/scrna-preprocessing/slides.html
topics/transcriptomics/tutorials/scrna-preprocessing/tutorial.md

Related to updates from #1854 and #1853

Add Cross Contamination Slides to Pre-processing material

---

topics/epigenetics/tutorials/atac-seq/tutorial.md

I added a question after the `Cut` step to have people check if their output is a valid BED file. There is a second Cut tool with almost identical title that produces the wrong output, this might help catch that in time.

ATAC-seq: add a question to check output of Cut step

---

topics/computational-chemistry/tutorials/cheminformatics/tutorial.md

ping @galaxyproject/training-computational-chemistry for a merge

Add tip box to docking tut

---

topics/climate/tutorials/panoply/tutorial.md

Precise dataset/variable articulation

---

topics/statistics/tutorials/classification_regression/workflows/classification_LSVC-test.yml
topics/statistics/tutorials/classification_regression/workflows/classification_LSVC.ga
topics/statistics/tutorials/classification_regression/workflows/regression_GradientBoosting-test.yml
topics/statistics/tutorials/classification_regression/workflows/regression_GradientBoosting.ga
topics/statistics/tutorials/machinelearning/workflows/machine_learning-test.yml
topics/statistics/tutorials/machinelearning/workflows/machine_learning.ga

- Add workflow_outputs for machine_learning.ga
- Add labels to workflow_outputs for classification_LSVC.ga and regression_GradientBoosting.ga
- Copy and update workflow tests for these 3 workflows from workflow-testing and add them here
The workflows load and run as they did before.  Any alterations have been for the purpose of testing the outputs with planemo.
@bgruening this follows from https://github.com/usegalaxy-eu/workflow-testing/pull/52

Update some statistics workflows for workflow testing

---

topics/epigenetics/tutorials/atac-seq/data-library.yaml
topics/epigenetics/tutorials/atac-seq/tutorial.md

update zenodo link and create data-library.yaml

Small update in ATAC-Seq training material

---

topics/epigenetics/tutorials/atac-seq/data-library.yaml

ATAC-SEQ: update datalibrary.yaml

---

topics/computational-chemistry/metadata.yaml

Depends on https://github.com/galaxyproject/training-material/pull/1914

Add cheminformatics gitter

---

_layouts/tutorial_hands_on.html

Follow-up on https://github.com/galaxyproject/training-material/pull/1900/files/053bc100d5acf0492fdd5d599ec7187b3bca5c72#r438757998

Fix "And more!" link

---

topics/epigenetics/tutorials/atac-seq/workflows/main_workflow.ga

change bedtools to allow to sort encodePeak

ATAC-seq change bedtools version

---

topics/admin/tutorials/ansible-galaxy/tutorial.md
topics/admin/tutorials/ansible/tutorial.md
topics/admin/tutorials/connect-to-compute-cluster/tutorial.md
topics/admin/tutorials/cvmfs-manual/tutorial.md
topics/admin/tutorials/cvmfs/manual.md
topics/admin/tutorials/cvmfs/tutorial.md
topics/admin/tutorials/external-auth/tutorial.md
topics/admin/tutorials/gxadmin/tutorial.md
topics/admin/tutorials/job-metrics/tutorial.md
topics/admin/tutorials/pulsar/tutorial.md
topics/admin/tutorials/tool-management/tutorial.md
topics/admin/tutorials/troubleshooting/slides.html
topics/admin/tutorials/users-groups-quotas/slides.html

We [collected Q&A from the students](https://docs.google.com/document/d/1mmhZRpV4XQnMB5UoPGDw0qT8I3oF2DIEYPxvPH4tDz0/edit#) during the GAT in Barcelona.
As such, I'm finally getting around to re-incorporating all of the student questions into the tutorial(s). I think it's the first time we're doing this (google doc q&a back into doc) so I've tagged it as highlight for that reason.
This has resulted in dozens of tips and small reminders of content that will hopefully answer student questions as they arise.

Incorporate GAT feedback

---

topics/statistics/tutorials/regression_machinelearning/tutorial.md

Fix comments from @erxleben for Regression tutorial

Fix comments for Regression tutorial

---

topics/statistics/tutorials/clustering_machinelearning/data-library.yaml
topics/statistics/tutorials/clustering_machinelearning/tutorial.md

Add fixes already made by @erxleben and fix additional comments.
ping @khanteymoori

[WIP] Fix comments

---

Makefile
bin/validate-workflow-tags.sh
topics/metagenomics/tutorials/metatranscriptomics-short/workflows/workflow2_community_profile.ga

And should be ~20% speedup due to not loading python every time.

Simplifies the wf testing

---

topics/statistics/tutorials/clustering_machinelearning/tutorial.md

Rephrase many sections of the clustering tutorial and add links and references suitably.
ping @khanteymoori

Rephrase Clustering tutorial

---

topics/admin/tutorials/cvmfs/tutorial.md

Just a tiny fix for a broken markdown link

Admin/cvmfs: fix broken markdown link

---

topics/statistics/tutorials/regression_machinelearning/tutorial.md

The PR fixes the comments provided at https://github.com/galaxyproject/training-material/issues/989#issuecomment-648464605
ping @khanteymoori

Fix tutorial comments

---

topics/statistics/tutorials/clustering_machinelearning/tutorial.md

Fix minor issues

---

topics/transcriptomics/tutorials/rna-seq-analysis-with-askomics-it/tutorial.md

A followup to #1947, with corrections of spelling errors + a few rewordings
@xgaia can you review this one?

Askomics tutorial: spell check, rewording

---

assets/css/main.scss
topics/admin/tutorials/ansible-galaxy/group_vars/galaxyservers.yml
topics/admin/tutorials/ansible-galaxy/templates/nginx/galaxy.j2
topics/admin/tutorials/ansible-galaxy/tutorial.md

I've used the new In/Out feature heavily. Feedback desired!
https://gat-0.training.galaxyproject.eu/
for the live deployment.

GAT Update for BCC

---

CONTRIBUTORS.yaml
Makefile
_plugins/jekyll-topic-filter.rb
bin/schema-contributors.yaml
bin/validate-contributors.rb
stats.md

Some things @shiltemann and I wanted to further include in the stats page.
**Recently Updated Tutorials**
(more coming over the next week.)

But wait, there's more Stats!

---

topics/transcriptomics/tutorials/scrna-preprocessing-tenx/tutorial.md

another fix for the 3M barcode list

small fixes for scrna-preprocessing-tenx

---

Makefile
topics/dev/tutorials/bioblend-api/slides.html

Also:
- Replace embedded tutorial with Jupyter notebooks on Binder.
- Update objectives and key points.
- Fix Makefile typos.

Update BioBlend slides for v0.14.0

---

topics/transcriptomics/tutorials/scrna-scanpy-pbmc3k/tutorial.md

sorry for yet another last minute change - I hope it is now consistent. Eventually we need to fix the gene tables as well

Update Clustering with Scanpy

---

topics/admin/tutorials/connect-to-compute-cluster/tutorial.md
topics/admin/tutorials/cvmfs/tutorial.md
topics/admin/tutorials/interactive-tools/tutorial.md
topics/admin/tutorials/pulsar/tutorial.md

@gmauro ping 
- Commits should be readable on their own, I recommend that way of reviewing.
- Safe: updating pulsar to be OK even with basic galaxy
- Adventure: Uses CVMFS during pulsar tutorial

Pulsar + CVMFS update

---

topics/transcriptomics/tutorials/rna-seq-analysis-with-askomics-it/tutorial.md

I made some last minutes changes to my tutorial. Is it possible to merge them for my training session ?
Thanks a lot,
X

Last minute changes

---

topics/statistics/tutorials/clustering_machinelearning/workflows/clustering-test.yml
topics/statistics/tutorials/clustering_machinelearning/workflows/clustering.ga

Workflow outputs for the workflow and a test.   Passes on .au and .eu

test for statistics clustering workflow

---

topics/genome-annotation/slides/introduction.html

Fix spelling errors:
* Statistical
* clade
* Apollo

Fix spelling errors in genome annotation intro slides

---

Makefile
bin/check-broken-boxes
topics/admin/tutorials/ansible-galaxy/tutorial.md
topics/admin/tutorials/external-auth/tutorial.md
topics/epigenetics/tutorials/ewas-suite/tutorial.md
topics/introduction/tutorials/galaxy-intro-101-everyone/tutorial.md
topics/metabolomics/tutorials/lcms-preprocessing/tutorial.md
topics/proteomics/tutorials/maxquant-label-free/tutorial.md
topics/statistics/tutorials/clustering_machinelearning/tutorial.md
topics/transcriptomics/tutorials/rb-rnaseq/tutorial.md
topics/variant-analysis/tutorials/non-dip/tutorial.md
topics/variant-analysis/tutorials/sars-cov-2/tutorial.md
topics/variant-analysis/tutorials/tb-variant-analysis/tutorial.md

Much of what was caught wasn't a 'true' breakage, just a completely unnecessary use of blockquotes to wrap images or other text.
But a few real problems were found!
Will conflict with #2007

Fix broken boxes & make checking mandatory

---

topics/introduction/tutorials/galaxy-intro-101/tutorial.md

They may get "Invalid column choice" error & if so they need to specify the column.

101 tutorial: add note about error

---

snippets/build_paired_list_collection.md

I noticed it was missing, or at least I could not find one for my specific needs.
It is based on the snippet `snippets/build_list_collection.md`
On my machine it looks like I have removed the last newline character, but please double check this

Add "created paired list collection" snippet

---

topics/computational-chemistry/tutorials/covid19-docking/workflows/workflow.ga
topics/proteomics/tutorials/maxquant-label-free/workflows/maxquant_label_free.ga
topics/visualisation/tutorials/circos/workflows/main_workflow.ga

Update some workflow names to make it a little easier to keep track of imported workflows from GTN.

Update some workflow names for consistency

---

topics/admin/tutorials/gxadmin/tutorial.md

Update external link on gxadmin tutorial

---

topics/transcriptomics/tutorials/scrna-scanpy-pbmc3k/tutorial.md

Add hrhotz and mtekman as contributors for scanpy tutorial

---

topics/admin/tutorials/connect-to-compute-cluster/tutorial.md

See https://github.com/galaxyproject/ansible-repos/issues/1

update galaxyproject.repos for ubuntu>18.04

---

topics/transcriptomics/tutorials/rna-seq-analysis-with-askomics-it/tutorial.md

Add more details about launching and accessing gxit. Asked by participants during the bcc tutorial
ping @xgaia

Askomics: add more info on gxit launching

---

environment.yml

Remove wkhtmltopdf package which caused OSX builds to fail

---

topics/galaxy-interface/tutorials/collections/tutorial.md
topics/variant-analysis/tutorials/dip/tutorial.md
topics/variant-analysis/tutorials/non-dip/tutorial.md

Fixes #2050 
@hexylena : until these are converted to zenodo datasets?

Fix links to Galaxy libraries

---

topics/proteomics/tutorials/metaproteomics/tutorial.md

this tutorial had some custom instructions for collection building, replaced it with the snippet

[Metaproteomics] use snippet for dataset collection creation instructions

---

_includes/help.html
assets/css/main.scss
assets/css/slides.css
topics/admin/tutorials/object-store/tutorial.md

Document per user/os object store with link to galaxy PRs.

---

topics/introduction/tutorials/galaxy-intro-101/tutorial.md
topics/introduction/tutorials/galaxy-intro-101/workflows/galaxy-intro-101-workflow-test.yml
topics/introduction/tutorials/galaxy-intro-101/workflows/galaxy-intro-101-workflow.ga
topics/introduction/tutorials/galaxy-intro-101/workflows/index.md

- Added workflow (https://github.com/galaxyproject/training-material/issues/1459).
- Added link to [Zenodo](https://doi.org/10.5281/zenodo.4104428) object with input data.
Both `planemo test` and `planemo workflow_lint` pass.

Added Galaxy 101 workflow

---

topics/genome-annotation/tutorials/tnseq/tutorial.md
topics/genome-annotation/tutorials/tnseq/workflows/essential-genes-detection-transposon-insertion-sequencing-workflow-test.yml
topics/genome-annotation/tutorials/tnseq/workflows/essential-genes-detection-transposon-insertion-sequencing-workflow.ga
topics/genome-annotation/tutorials/tnseq/workflows/index.md

- Added workflow (https://github.com/galaxyproject/training-material/issues/1459).
- Fixed minor typos and formatting.
- Updated tags in "Separate Files from the collection" step so they are assigned to the corresponding files.
Both `planemo test` and `planemo workflow_lint` pass.

Added Transposon insertion sequencing workflow

---

topics/proteomics/tutorials/metaquantome-data-creation/workflows/main_workflow-test.yml
topics/proteomics/tutorials/metaquantome-data-creation/workflows/main_workflow.ga

- Added workflow test
- Updated workflow

Added workflow test for metaquantome data creation tutorial

---

topics/introduction/tutorials/galaxy-intro-peaks2genes/workflows/Galaxy-Introduction-Peaks2Genes-Part-1-Workflow-test.yml
topics/introduction/tutorials/galaxy-intro-peaks2genes/workflows/Galaxy-Introduction-Peaks2Genes-Part-1-Workflow.ga
topics/introduction/tutorials/galaxy-intro-peaks2genes/workflows/index.md

- Added workflow for "From peaks to genes" tutorial (https://github.com/galaxyproject/training-material/issues/1459)
- Added workflow tests.
Both `planemo test` and `planemo workflow_lint` pass.

Add Peaks2Genes workflow

---

topics/contributing/tutorials/slides-with-video/tutorial.md

Forgot to include documentation in video PR

---

topics/galaxy-interface/metadata.yaml
topics/galaxy-interface/tutorials/collections/tutorial.md

A couple of typing error were corrected. Fix https://github.com/galaxyproject/training-material/issues/2077

Fixed error in the term collection/collections

---

topics/genome-annotation/tutorials/annotation-with-prokka/workflows/Galaxy-Workflow-Workflow_constructed_from_history__prokka-workflow_-test.yml
topics/genome-annotation/tutorials/annotation-with-prokka/workflows/Galaxy-Workflow-Workflow_constructed_from_history__prokka-workflow_.ga

- Both `planemo test` and `planemo workflow_lint` pass.

Add workflow test for Genome annotation with Prokka tutorial

---

topics/introduction/tutorials/galaxy-intro-short/workflows/Galaxy-Workflow-galaxy-intro-short-test.yml
topics/introduction/tutorials/galaxy-intro-short/workflows/Galaxy-Workflow-galaxy-intro-short.ga

- Both `planemo test` and `planemo workflow_lint` pass.

Add workflow test for Short Intro to Galaxy tutorial

---

topics/introduction/tutorials/galaxy-intro-101-everyone/workflows/main_workflow-test.yml
topics/introduction/tutorials/galaxy-intro-101-everyone/workflows/main_workflow.ga

- Both `planemo test` and `planemo workflow_lint` pass.

Add workflow test for Galaxy 101 for Everyone tutorial

---

topics/galaxy-interface/tutorials/upload-rules/tutorial.md

Fix part of #2078.
As simple as that.

Fix ENA broken link in tutorial.

---

topics/proteomics/tutorials/database-handling/tutorial.md
topics/proteomics/tutorials/database-handling/workflows/wf_database-handling.ga
topics/proteomics/tutorials/database-handling/workflows/wf_database-handling_mycoplasma.ga
topics/proteomics/tutorials/protein-id-oms/tutorial.md
topics/proteomics/tutorials/protein-id-oms/workflows/workflow.ga
topics/proteomics/tutorials/protein-quant-sil/tutorial.md
topics/proteomics/tutorials/protein-quant-sil/workflows/workflow.ga

Updating Tutorials to OpenMS 2.6, adjusting of parameters and tools, adding tool versions
For database tutorial: updating to current GTN syntax
Setting OpenMS ID and quant trainings to "advanced" level

Updating Proteomics tutorials based on OpenMS

---

topics/imaging/tutorials/tutorial-CP/workflows/main_workflow.ga

(this was causing travis to fail)

[Imaging] add missing annotation field to workflow

---

bin/ari.sh
topics/admin/tutorials/ansible-galaxy/slides.html
topics/admin/tutorials/ansible/slides.html
topics/introduction/tutorials/galaxy-intro-short/slides.html

There was a bug where I ignored the questions/objectives, so, had to fix that up quickly. Works now, and the video is live.
https://galaxy-training.s3.amazonaws.com/videos/topics/introduction/tutorials/galaxy-intro-short/slides.mp4

Enable video for new intro slides from @shiltemann

---

topics/transcriptomics/tutorials/rna-seq-reads-to-counts/tutorial.md
topics/transcriptomics/tutorials/rna-seq-reads-to-counts/workflows/qc_report.ga

Sorry, a few more edits @shiltemann

Update rnaseq mouse

---

topics/proteomics/tutorials/protein-quant-sil/tutorial.md

hopefully it is now better understandable how to change the workflow

OpenMS SIL tutorial tiny clarifications

---

topics/instructors/tutorials/galaxy-admin-training/tutorial.md

A tiny PR as the the url has changed recently

GAT: fix url to terraform file

---

topics/introduction/tutorials/r-basics/tutorial.md

R for Data science link for lists was updated

Fixed broken link

---

assets/css/main.scss

not sure how I screwed this up, not sure how it looked correct locally. Oops!

fix inverted css width condition

---

topics/ecology/tutorials/PAMPA-toolsuite-tutorial/tutorial.md

as only this one accept the multiple selection

Change the concatenate tool ID from cat1 to tp_cat

---

CONTRIBUTING.md
topics/contributing/tutorials/create-new-tutorial-content/tutorial.md
topics/contributing/tutorials/create-new-tutorial-technical/tutorial.md
topics/contributing/tutorials/create-new-tutorial/tutorial.md

Moved in 503017a3ca5978c29690e63bcf056b30d10cfd57

Fix link, minor typos

---

topics/admin/tutorials/ansible-galaxy/tutorial.md
topics/admin/tutorials/ansible/tutorial.md
topics/admin/tutorials/interactive-tools/tutorial.md

xref https://github.com/galaxyproject/admin-training/issues/99

Update ansible-galaxy for 2021

---

topics/contributing/tutorials/running-jekyll/tutorial.md

small additions about using conda

Update tutorial.md in Contributing 

---

.github/workflows/deploy.yml

Fixes https://github.com/galaxyproject/training-material/issues/2163

fix dependencies for pre-build annotation

---

topics/admin/tutorials/ansible/tutorial.md

Ansible tuto: fix display of ansible var

---

.github/workflows/deploy-s3.yml
.github/workflows/deploy.yml

add bundler install to deploy actions

---

topics/contributing/tutorials/create-new-tutorial-content/tutorial.md

I saw this in an a11y newsletter I receive, thought it was useful guidance.

Alt text vs figure captions guidelines

---

_includes/default-footer.html
_plugins/jekyll-environment_variables.rb

will help debug future deployment issues as well.

Expose revision number in GTN site

---

stats.md

Expose website statistics in stats page

---

topics/admin/tutorials/interactive-tools/tutorial.md

Some students weren't sure which file to edit

Interactive tools: add full path to diffs

---

topics/climate/tutorials/fates-jupyterlab/tutorial.md

Fix the secon part of  #2099 and open this tutorial for review.
The first part of this issue #2099 is in PR #2141

fix  #2099 typos/errors identified during FATES JupyterLab training

---

topics/proteomics/tutorials/database-handling/workflows/wf_database-handling_mycoplasma.ga

The file wf_database-handling_mycoplasma.ga has been modified. In the previous version the data corresponding to Mycoplasma fermentans had been included in duplicate, while those corresponding to M. hominis and Acholeplasma laidlawii had not been included.

Update wf_database-handling_mycoplasma.ga workflow

---

topics/admin/tutorials/cvmfs/tutorial.md

Fixes https://github.com/galaxyproject/ansible-cvmfs/issues/30

Bumped cvmfs version for focal fossa

---

topics/proteomics/tutorials/DIA_Analysis_OSW/data-library.yaml

Just a quick fix for an invalid yaml

Fix invalid data lib yaml

---

.github/workflows/ci.yml
topics/proteomics/tutorials/DIA_lib_OSW/data-library.yaml

Just as #2225 with another yml (tested now, no new similar pr hopefully)

Fix another yml

---

topics/assembly/tutorials/assembly-with-preprocessing/slides.html

Update assembly covid19 slides.html with tags

---

topics/assembly/tutorials/assembly-with-preprocessing/slides.html

Update Unicycler SARS-CoV-2 image extensions

---

topics/contributing/metadata.yaml
topics/contributing/tutorials/create-new-tutorial-content/tutorial.md
topics/contributing/tutorials/create-new-tutorial-slides/slides.html
topics/contributing/tutorials/create-new-tutorial-technical/tutorial.md
topics/contributing/tutorials/create-new-tutorial-tours/tutorial.md
topics/contributing/tutorials/create-new-tutorial/tutorial.md
topics/contributing/tutorials/github-command-line-contribution/tutorial.md
topics/contributing/tutorials/github-interface-contribution/tutorial.md
topics/contributing/tutorials/running-jekyll/tutorial.md
topics/contributing/tutorials/slides-with-video/tutorial.md

Reorganise contributing page

---

topics/transcriptomics/tutorials/scrna-preprocessing-tenx/tutorial.md

Put note about the MultiQC tool sometimes not being findable

Multiqc findability

---

chat.html

training.galaxyproject.org/chat → to gitter
in support of the PoC video

Add chat quick link

---

topics/admin/tutorials/interactive-tools/slides.html

So bullet points in notes are well aligned.

GxIT slide notes: remove extra whitespaces

---

.github/workflows/video.yml
_includes/contributor-badge-list.html
_layouts/base_slides.html
assets/css/slides.css
bin/ari.sh

The current cover is quite boring and makes for a sub-optimal cover image for videos. So I'd like this instead:
1. highlights GTN
2. highlights contributors
3. very screenshotable

New tutorial slide cover design

---

topics/assembly/tutorials/chloroplast-assembly/tutorial.md
topics/assembly/tutorials/ecoli_comparison/tutorial.md
topics/genome-annotation/tutorials/annotation-with-maker/content.md
topics/genome-annotation/tutorials/annotation-with-prokka/tours/tour.yaml
topics/genome-annotation/tutorials/annotation-with-prokka/tutorial.md
topics/variant-analysis/tutorials/microbial-variants/tours/tour.yaml
topics/variant-analysis/tutorials/microbial-variants/tutorial.md
topics/variant-analysis/tutorials/tb-variant-analysis/tutorial.md

Just a few corrections for tiny problems in the maker tutorial - short version

Maker short: little fixes

---

topics/assembly/tutorials/ecoli_comparison/tutorial.md

Fix issue discovered by a student

---

bin/ari-extract-script.rb
bin/ari-map.yml
bin/ari.sh
topics/dev/tutorials/bioblend-api/slides.html

xref. https://github.com/galaxyproject/admin-training/issues/105

Update BioBlend slides for video

---

topics/assembly/tutorials/assembly-with-preprocessing/tutorial.md

Just 3 tiny fixes for the sars-cov-2 assembly tutorial

sars-cov-2 assembly: minor fixes

---

topics/assembly/tutorials/assembly-with-preprocessing/slides.html

Just a few typos found while reading the slides

sars-cov-2 slides typos

---

topics/admin/tutorials/connect-to-compute-cluster/tutorial.md
topics/admin/tutorials/job-destinations/tutorial.md
topics/admin/tutorials/singularity/tutorial.md

- wrong param in singularity
- heard myself saying "we write the var only once and reference it to ensure there is less duplication and one point to change" while looking at a couple of unfixed variables below.

More last minute admin fixes

---

topics/admin/tutorials/data-library/tutorial.md

[Admin] Data libraries tutorial: fix link and parameter

---

topics/admin/tutorials/tool-management/tutorial.md

Let them know that they can get out of screen splits with `Ctrl-D`

Ephemeris tutorial: add extra byobu hint for mac users

---

topics/galaxy-interface/metadata.yaml

In our last GTN meeting, @nomadscientist and others remarked that "Interface" is a very tech/dev term, and probably not very clear to most users. Here I've rephrased the topic title to be more accessible.

Rephrase title of UI topic

---

topics/galaxy-interface/metadata.yaml

Follow-up on https://github.com/galaxyproject/training-material/pull/2293/files#r564659983

Rephrase UI in subtopic description

---

_config-dev.yml
snippets/edit_workflow.md
snippets/install_tool.md
topics/admin/tutorials/cvmfs/tutorial.md
topics/admin/tutorials/pulsar/tutorial.md

Also:
- Some rephrasing in the Pulsar tutorial
- Fix icon in `snippets/edit_workflow.md`

Add snippet to install bwa to CVMFS tutorial

---

topics/climate/tutorials/fates/slides.html

hopefully this will fix the errors and generate the video
ping @hexylena

CLimate: break up too long sentences for TTS

---

topics/climate/tutorials/fates/slides.html

Climate: TTS doesn't like % characters, replace last one I forgot

---

topics/climate/tutorials/fates/slides.html

to fix syncing of TTS with slides

FATES: update layout of slides

---

topics/genome-annotation/tutorials/annotation-with-prokka/tutorial.md

Just spotted this typo, making a PR now before I forget...

Fix prokka tuto typo

---

topics/proteomics/tutorials/proteogenomics-dbcreation/tutorial.md
topics/proteomics/tutorials/proteogenomics-dbcreation/workflows/galaxy-workflow-mouse_rnaseq_dbcreation.ga
topics/proteomics/tutorials/proteogenomics-dbsearch/tutorial.md
topics/proteomics/tutorials/proteogenomics-dbsearch/workflows/galaxy-workflow-mouse_rnaseq_dbsearch.ga
topics/proteomics/tutorials/proteogenomics-novel-peptide-analysis/workflows/galaxy-workflow-mouse_novel_peptide_analysis.ga

@subinamehta These changes reflect what I did in the latest workflow.   Please check that I formatted things correctly, feel free to change anything.

Update Proteogenomics1 Database Creation

---

topics/admin/tutorials/cvmfs/tutorial.md

xref https://github.com/galaxyproject/training-material/issues/2274#issuecomment-768552580

Remove wrong reference to `galaxyservers.yml` in CVMFS tutorial

---

bin/check-broken-boxes
bin/schema-slides.yaml
bin/schema-tutorial.yaml
bin/validate-frontmatter.rb
topics/admin/tutorials/job-destinations/tutorial.md
topics/assembly/tutorials/ecoli_comparison/tutorial.md
topics/ecology/tutorials/PAMPA-toolsuite-tutorial/tutorial.md
topics/proteomics/tutorials/metaquantome-data-creation/tutorial.md

Some of the tests appeared to be passing while they were actually detecting errors. Should be fixed now for frontmatter linting en broken box checking.
also fixes some problems that have slipped through because of this
ping @hexylena

Fix linting exitcodes for GitHub actions

---

topics/admin/tutorials/interactive-tools/tutorial.md

*Trying to* clarify at least! Hope it's better like this

GxIT: clarify wildcard certificate

---

topics/climate/tutorials/fates-jupyterlab/tutorial.md

Make sure we open all the netCDF files and not only the first one (the first one contains one month of data only).

fix #2099 for fates with climate jupyterlab

---

bin/ari-map.yml

fixes how she pronounced scRNA-seq

fix TTS map for scRNA

---

topics/statistics/metadata.yaml

@martenson could you add him to the @galaxyproject/training-statistics group?

Make @anuprulez a maintainer for ML/stats

---

topics/assembly/metadata.yaml

Thanks for volunteering @gallardoalba!
@martenson could you please add him to the @galaxyproject/training-assembly group?

Add Cristóbal Gallardo as a maintaianer

---

topics/visualisation/tutorials/circos/tutorial.md
topics/visualisation/tutorials/circos/workflows/main_workflow.ga
topics/visualisation/tutorials/circos/workflows/nature_workflow.ga

This pull request fixes some problems in the workflow (#1714) and updates the tutorial in order to adapt it to the latest tool version.

Circos training papercuts

---

topics/assembly/tutorials/chloroplast-assembly/tutorial.md

just adding some tags that might help people discover this tutorial

Chloroplast tutorial: add tags

---

topics/transcriptomics/tutorials/scrna-intro/slides.html

just touching this file to trigger a rebuild of the video (and hopefully better pronunciation of scRNA-seq)

small change for triggering video rebuild

---

topics/transcriptomics/tutorials/scrna-preprocessing-tenx/tutorial.md
topics/transcriptomics/tutorials/scrna-preprocessing/tutorial.md
topics/transcriptomics/tutorials/scrna-raceid/tutorial.md
topics/transcriptomics/tutorials/scrna-scater-qc/tutorial.md
topics/transcriptomics/tutorials/scrna-umis/tutorial.md

This adds the latest tool versions as tool links to some of the training materials:
* scrna-umis
* scrna-raceid
* scrna-scater-qc
* scrna-preprocesing
The scanpy 3k stuff was left because that requires some manual verification on the tool versions, and will be addressed in a separate PR

[Update] Tool-links to some scrna materials

---

topics/transcriptomics/tutorials/scrna-scanpy-pbmc3k/tutorial.md

I merged too quickly (there was transient errors in the ci so figured it was fine, silly me.) and missed this link issue. Thanks @nomadscientist for letting me know!

fix broken link

---

topics/contributing/tutorials/running-jekyll/tutorial.md

Changed `galaxy_training_network` to `galaxy_training_material`

Corrected installation instructions

---

topics/sequence-analysis/tutorials/mapping/jbrowse.md

This is what I see on usegalaxy.org. I assume this is the equivalent (updated) option?

Update JBrowse option

---

bin/ari-extract-script.rb
bin/ari-map.yml

This caught an issue I'd missed in admin slides. Thanks so much for raising the issue @foellmelanie!!!

Correct ari build for replacement words next to various kinds of punctuation

---

topics/introduction/tutorials/galaxy-intro-ngs-data-managment/tutorial.md

Small typos and other omissions.

Update to NGS tutorial

---

topics/transcriptomics/tutorials/scrna-umis/tutorial.md

Thanks to @ic4f at https://github.com/galaxyproject/training-material/issues/2351 for finding this

Delete unneeded reference

---

topics/transcriptomics/tutorials/scrna-preprocessing-tenx/tutorial.md

and remove dupe zenodo in header

fix wrong tool linking reference

---

_includes/program_table.html
_includes/simple.md
_layouts/home.html
metadata/training_sessions.yaml
smorgasbord.md

Revert this in a week. Copied and pasted directly from the smörg website.
here it is
links to:

Add a simple smörgåsbord view

---

topics/transcriptomics/tutorials/ref-based/tutorial.md

and add links to subsampled datasets

Ref-based RNA-seq tutorial: Update Zenodo link

---

topics/transcriptomics/tutorials/ref-based/tutorial.md

... spotted by a participant during workshop today

Ref-based RNA-seq tutorial: Fix 2 small errors

---

topics/transcriptomics/tutorials/scrna-scanpy-pbmc3k/tutorial.md

AnnData 0.7.4 no longer works for Import or Manipulate, though it did at most two weeks ago.
@mvdbeek  is patching it as we speak https://github.com/galaxyproject/tools-iuc/pull/3483
Surprisingly no links need to be updated, as all the relevant versions are correctly linked in the source material.... 
This is just a formatting fix PR then

Formatting fixes to the scanpy tutorial

---

topics/transcriptomics/tutorials/scrna-scanpy-pbmc3k/tutorial.md

Query replace:
toolshed.g2.bx.psu.edu/repos/iuc/anndata_inspect/anndata_inspect/0.7.4+galaxy1
with:
toolshed.g2.bx.psu.edu/repos/iuc/anndata_inspect/anndata_inspect/0.6.22.post1+galaxy4
WIP to check if it lints and serves corrects

Quickfix Scanpy tutorial

---

topics/proteomics/tutorials/maxquant-msstats-dda-lfq/tutorial.md

some of the question boxes were missing their header

minor fixes to MaxQuant tutorial

---

topics/proteomics/tutorials/proteogenomics-dbcreation/tutorial.md

now I figured out that it was also wrong in the other filter tabular tool.

again filter tabular regex

---

topics/galaxy-interface/tutorials/workflow-parameters/tutorial.md

I think it has grown over time without an update to this.

Increase time estimated for workflow parameters tutorial.

---

topics/introduction/tutorials/galaxy-intro-101-everyone/tutorial.md

Hi! this is my first contribution to the GTN Cofest!
[Galaxy 101 for everyone](https://training.galaxyproject.org/training-material/topics/introduction/tutorials/galaxy-intro-101-everyone/tutorial.html) is an awesome tutorial and really inspiring for newcomers I learned a lot with it!
These are the tiny changes that I made to fix #2400:
- Replaced the old `asterisks` with `checkbox` to mark outputs as important in the workflow editor.
- Renamed the Unique default output name to `outfile` to match the current name in the screenshots.

Minor update in Galaxy 101 for everyone tutorial

---

.github/workflows/deploy-s3.yml

doesn't seem to be working on building them

Fix the action?

---

_plugins/jekyll-icon-tag.rb
topics/contributing/tutorials/create-new-tutorial-content/tutorial.md

for @nomadscientist! thanks for the good suggestion :)

Add icon table

---

topics/transcriptomics/tutorials/ref-based/tutorial.bib
topics/transcriptomics/tutorials/ref-based/tutorial.md

- Add pages to bib entry
- Fix featureCounts advanced options for updated wrapper
- Fix typos, clarify text

Misc fixes for ref-based RNA-Seq tutorial

---

topics/transcriptomics/metadata.yaml
topics/transcriptomics/tutorials/scrna-preprocessing-tenx/tutorial.bib
topics/transcriptomics/tutorials/scrna-preprocessing-tenx/tutorial.md
topics/transcriptomics/tutorials/scrna-preprocessing/tutorial.bib
topics/transcriptomics/tutorials/scrna-preprocessing/tutorial.md
topics/transcriptomics/tutorials/scrna-raceid/tutorial.bib
topics/transcriptomics/tutorials/scrna-raceid/tutorial.md
topics/transcriptomics/tutorials/scrna-scanpy-pbmc3k/tutorial.bib
topics/transcriptomics/tutorials/scrna-scanpy-pbmc3k/tutorial.md
topics/transcriptomics/tutorials/scrna-scater-qc/tutorial.bib
topics/transcriptomics/tutorials/scrna-scater-qc/tutorial.md
topics/transcriptomics/tutorials/scrna-umis/tutorial.bib
topics/transcriptomics/tutorials/scrna-umis/tutorial.md

Add 2020 singlecell paper, and the 2019 paper.
Mention the singlecell portal in relevant materials

Add citations to scRNA galaxy papers

---

topics/transcriptomics/tutorials/scrna-scanpy-pbmc3k/tutorial.md
topics/transcriptomics/tutorials/scrna-scanpy-pbmc3k/workflows/main_workflow.ga

* Fixes a clustering parameter which changed the default action during upgrade
* Version tool fixes

Fixes to scanpy tutorial

---

topics/transcriptomics/tutorials/scrna-preprocessing-tenx/tutorial.md
topics/transcriptomics/tutorials/scrna-preprocessing-tenx/workflows/scrna_tenx.ga

no rush on merging this, current version works fine

Update to 10x training/workflow

---

topics/climate/slides/introduction.html

for slides introducing Climate data analysis

Climate intro: adding speaker notes for text-to-speech video

---

topics/admin/tutorials/pulsar/tutorial.md

I prepared a section on how to manage the retrying of staging actions

add a section about Retries of the staging actions

---

topics/climate/slides/introduction.html

I just noticed listening to the video that there were a few errors in speaker notes (for text-to-speech video) so this PR will hopefully fix them.

fix a few errors in speaker notes

---

topics/epigenetics/metadata.yaml
topics/transcriptomics/metadata.yaml

Add @lldelisle as topic maintainer for the epigenetics topic 
Add @heylf as topic maintainer to epigenetics and transcriptomics topics
Thanks a lot to both of you!!
ping @martenson could you add them to the respective groups?

Add new topic maintainers

---

videos/index.md
videos/watch.md

it's all tough to test locally due to CORS :(

fix domain for video urls

---

bin/check-broken-tool-links.sh
topics/epigenetics/tutorials/atac-seq/tutorial.md
topics/epigenetics/tutorials/atac-seq/workflows/main_workflow.ga

Hi,
I used the new syntax for tool which is super useful when you want to use it through the galaxy integration. Thanks for that.
I just have an issue, the {{page.topic_name}} is not correctly set when I serve it locally:
Do you have an idea how to fix it?
Thanks

Update ATAC-seq tutorial: use new way to specify tool

---

faqs/galaxy/interactive_tools_jupyter_launch.md
topics/galaxy-interface/tutorials/jupyterlab/tutorial.md

Fixes https://github.com/galaxyproject/training-material/issues/2397

Papercuts - adding in jupyter stuff to tutorial

---

topics/transcriptomics/tutorials/mirna-target-finder/slides.html

sorry, the image locations in the previous PR were wrong.

correct image locations in plant RNA-seq slides

---

faqs/galaxy/datasets_convert_datatype.md

Overheard during @hexylena's workshop today

[FAQ] add missing step to datatypes conversion instructions

---

topics/sequence-analysis/tutorials/mapping/workflows/mapping-jbrowse.ga
topics/sequence-analysis/tutorials/mapping/workflows/mapping.ga
topics/sequence-analysis/tutorials/quality-control/workflows/quality_control.ga

This PR updates the tool versions since the current workflows use FASTQ v1.70 and it doesn't work properly.

Update mapping and quality control trainings workflows

---

topics/transcriptomics/tutorials/scrna-preprocessing-tenx/tutorial.md

Change to previous version until newer version can be fixed

Fix to 10x pre-processing workflow

---

topics/transcriptomics/tutorials/mirna-target-finder/data-library.yaml
topics/transcriptomics/tutorials/mirna-target-finder/tutorial.md

This PR updates the optional target for the datasets to be imported from the data library.

Plant transcriptomics: Update optional exercise data from library

---

topics/transcriptomics/tutorials/scrna-preprocessing-tenx/tutorial.md

Working with newest history: https://usegalaxy.eu/u/mehmet-tekman/h/pre-processing-of-10x-single-cell-rna-star-278a
Related to: https://github.com/usegalaxy-eu/website/pull/645 https://github.com/galaxyproject/training-material/pull/2513
https://github.com/galaxyproject/tools-iuc/issues/3540 will need to be fixed in a wrapper upgrade

Fix to STARsolo parameters for use with 2.7.8a

---

topics/transcriptomics/tutorials/scrna-seq-basic-pipeline/tutorial.md

Small glitch where a few participants fell into.

SC basic: Asks to use Final matrix, should be asking for Final object

---

topics/galaxy-interface/tutorials/group-tags/tutorial.md

- there seems no way to define a URL colum
- be a bit more precise on how to add multiple tag columns

group tags tutorial improvements

---

topics/dev/tutorials/bioblend-api/slides.html

This adds a new slide to the `Scripting Galaxy using the API and BioBlend` slide deck with a bit of information about the Galaxy API modernization using FastAPI.
Ping @nsoranzo for the review :)

Add slide to BioBlend/API tutorial

---

topics/dev/tutorials/bioblend-api/slides.html
topics/dev/tutorials/tool-integration/slides.html

e.g. move from Gitter to Matrix for BioBlend chat.
Also small fix to a tool-integration slide.

Small updates to BioBlend slides

---

.github/workflows/optimize-images.yml

@hexylena The repository name needs to match, I'm sorry I didn't notice earlier in #2535 😓

Change repo name in GH Action to optimize images

---

topics/contributing/tutorials/slides-with-video/tutorial.md

fyi @nsoranzo since I remember you mentioning this the other day. The main issue was "too much text in one screen" in the caption, but that's now fixed.

Remove note on long sentence issue

---

topics/admin/tutorials/monitoring/tutorial.md
topics/admin/tutorials/object-store/tutorial.md

* Minor text corrections
* Minor formatting corrections

* Minor formatting and text corrections

---

topics/metagenomics/tutorials/metatranscriptomics/content.md

The answer box for the Krona plot said 55% instead of 5%

typo in metatranscriptomics tutorial

---

_layouts/topic.html
topics/dev/metadata.yaml
topics/dev/slides/introduction.html
topics/dev/tutorials/architecture/slides.html
topics/dev/tutorials/bioblend-api/slides.html
topics/dev/tutorials/bioblend-dev/tutorial.md
topics/dev/tutorials/conda/slides.html
topics/dev/tutorials/conda_sys/slides.html
topics/dev/tutorials/containers/slides.html
topics/dev/tutorials/data-source-integration/tutorial.md
topics/dev/tutorials/interactive-environments/slides.html
topics/dev/tutorials/interactive-tours/slides.html
topics/dev/tutorials/tool-generators-advanced/tutorial.md
topics/dev/tutorials/tool-generators/tutorial.md
topics/dev/tutorials/tool-integration/slides.html
topics/dev/tutorials/toolshed/slides.html
topics/dev/tutorials/visualization-charts/tutorial.md
topics/dev/tutorials/visualization-generic/slides.html
topics/dev/tutorials/visualization-generic/tutorial.md
topics/dev/tutorials/webhooks/slides.html
topics/dev/tutorials/webhooks/tutorial.md

Split up and reorganise dev tutorials

---

CONTRIBUTORS.yaml
topics/galaxy-interface/tutorials/ncbi-sarf/tutorial.md

@shiltemann said she had some time to work on this as well
I think from my side the main fix that's needed is to replace the awk tool with just use of the rule based uploader.

Import and tidy NCBI tutorial

---

CONTRIBUTORS.yaml

I added a few information such as twitter, orcid, GitHub and email to my account

Updated information

---

topics/statistics/tutorials/CNN/slides.html

since no speaker notes are present yet

CNN: disable video slides

---

topics/admin/tutorials/ansible-galaxy/requirements.yml
topics/admin/tutorials/ansible-galaxy/tutorial.md

Nginx config validation for #2274.

Update galaxyproject.nginx role to 0.7.0.

---

topics/admin/tutorials/tool-management/tutorial.md

@hexylena I was talking about changing the order of steps for this to address a feedback comment but I don't think that would be an improvement so am leaving the order as is.  I'll probably make another PR for this topic (updated tips, slides) but none of the code blocks will need to change.

switch installed and tested tools back to bwa and bamtools_filter

---

.github/workflows/ci.yml
.github/workflows/workflow-testing.yml
bin/add_galaxy_instance_badges.py
bin/check-broken-symlinks.sh
topics/metadata/assembly.yaml

Missed this unexpected broken symlink in the vgp pr. @bgruening https://github.com/galaxyproject/training-material/pull/2590/files#diff-54a870e36cadec0f44bac0ff7df874adef7f9cdb0f8cb2ca5a426618cc0ba8f7

Fix build failure from vgp

---

topics/assembly/tutorials/vgp_genome_assembly/tutorial.md

This PR updates the cutadapt section with the most recent version and includes some additional parameters in accordance with Giulio's suggestions.

Update VGP tutorial: modify cutadapt options and version

---

topics/introduction/slides/introduction.html

* Updated the public servers
* Citations numbers

Updated the numbers on the galaxy introduction tutorial

---

topics/admin/tutorials/tool-management/tutorial.md

Changes for ephemeris tutorial: check for global ephemeris, instructions for importing workflow, look at output files from shed-tools test and get-tool-list, rephrase production best practices and some Q&A.

Ephemeris tutorial word updates

---

Makefile

Addresses https://github.com/galaxyproject/training-material/issues/1655, which still seems to be an issue in some circumstances.

Libiconv fix

---

topics/admin/tutorials/job-destinations/tests/3.sh
topics/admin/tutorials/singularity/tests/1-run-minimap2.sh

and use `set -e` when running multiple commands in test script.

Install minimap2 in singularity tutorial tests

---

_plugins/jekyll-jsonld.rb

Workaround for accessing non-existent contributor

---

_layouts/tutorial_hands_on.html

Fix wrong link for text citation

---

faqs/galaxy/histories_create_new.md
topics/introduction/tutorials/galaxy-intro-short/slides.html

- Add contributors and some text from topics/introduction/slides/introduction.html
- Use different wording between slides and notes.
Working towards making the old "Introduction to Galaxy" slide deck obsolete. I'd like to port some content from the "Tool Shed" and "Datatypes" slide in a future PR, then replace it for good.

Small enhancements to Short Intro slides

---

CONTRIBUTORS.yaml
topics/galaxy-interface/tutorials/ncbi-sarf/tutorial.md

There may be some typos and formatting issues (still getting used to the markdown tools for Galaxy) so please review. Also forgot to add the time zone converter.
Once the text is correct, I'll add an image that is a roadmap.

Rhodes review of tutorial content

---

CONTRIBUTORS.yaml
topics/dev/tutorials/debugging/tutorial.md

Apologies for the numerous typos - will fix.
Any feedback very much appreciated!
TODO:

New tutorial: Debugging Galaxy

---

topics/genome-annotation/tutorials/apollo/data-library.yaml
topics/genome-annotation/tutorials/apollo/tutorial.md

Just fixing a typo in the input data url, found while recording (~50% done, will finish tomorrow)

Apollo: fix broken url

---

topics/galaxy-interface/tutorials/ncbi-sarf/tutorial.md

Added workflow diagram to tutorial

Added workflow diagram

---

topics/galaxy-interface/tutorials/upload-rules/tutorial.md

The tutorial works great, just a tiny typo.

Fix tiny typo in Rule Based Uploader

---

topics/metagenomics/tutorials/mothur-miseq-sop-short/workflows/workflow1_quality_control.ga
topics/metagenomics/tutorials/mothur-miseq-sop-short/workflows/workflow2_data_cleaning.ga
topics/metagenomics/tutorials/mothur-miseq-sop-short/workflows/workflow3_classification.ga
topics/metagenomics/tutorials/mothur-miseq-sop-short/workflows/workflow4_mock_otu_clustering.ga
topics/metagenomics/tutorials/mothur-miseq-sop-short/workflows/workflow5_otu_clustering.ga
topics/metagenomics/tutorials/mothur-miseq-sop-short/workflows/workflow6_alpha_diversity.ga
topics/metagenomics/tutorials/mothur-miseq-sop-short/workflows/workflow7_beta_diversity.ga
topics/metagenomics/tutorials/mothur-miseq-sop/content.md

Adding all tools links to the usegalaxy, for easier access. 
That was done to the metagenomics "16S Microbial Analysis with mothur (extended)" tutorial
I followed the same way and comments from the last pull request of the ref-based tutorial.

Adding tools links for thr mother miseq sop extended tutorial

---

topics/dev/tutorials/bioblend-dev/tutorial.md

There's a possible paste error at step 5 of the example of writing a bioblend method.  @simonbray could you please check if this is the right change?

change 4 lines of bioblend dev tutorial

---

topics/admin/tutorials/ansible-galaxy/tutorial.md
topics/contributing/tutorials/admin-knitting/tutorial.md

- Subdirs of `/srv/galaxy` differ in ownership
- Fix typo for `cleanup_job` value
- Update updating example with more recent releases
- Fix 2 broken links

Small fixes for ansible-galaxy tutorial

---

bin/knit.py
topics/admin/tutorials/gxadmin/tutorial.md
topics/admin/tutorials/monitoring/tutorial.md
topics/admin/tutorials/pulsar/tutorial.md

xref https://github.com/galaxyproject/ansible-pulsar/pull/21

Update ansible-pulsar role for bugfix

---

topics/dev/tutorials/debugging/tutorial.md

I think we do checking that would be useful for the tutorial developer. I think this is the better route and correct abstraction?

Revise debugging tutorial setup of Galaxy's virtual environment.

---

faqs/gtn/issues_galaxy.md

Remove bug reporting from title

---

news/_posts/2021-06-25-gitpod.md
topics/contributing/tutorials/gitpod/tutorial.md

Add a newsitem for the GitPod tutorial, and some minor updates to said tutorial

News item for GitPod tutorial

---

_config.yml
faqs/galaxy/analysis_troubleshooting.md
faqs/galaxy/histories_sharing.md
faqs/index.md

- Add FAQ about what to do when you encounter an error with one of your datasets
- Update history sharing faq to new style, and expand to include sharing with specific users

FAQs on troubleshooting errors and sharing histories

---

topics/transcriptomics/tutorials/de-novo/tutorial.md

Fix for issue noticed by GCC2021 training week participants

de novo: perform paired-end counting with featurecounts

---

news/_posts/2021-06-30-tutorial-sars-cov-2-variant-discovery.md

@wm75 @bgruening @beatrizserrano

Add news for sars-cov-2-variant-discovery tutorial

---

topics/variant-analysis/tutorials/sars-cov-2-variant-discovery/tutorial.md

- Added linksa to video and bioRxiv paper
- Fixed English

Small tweaks for sars-cov-2 tutorial

---

topics/introduction/tutorials/galaxy-intro-short/tutorial_ES.md

xref https://github.com/galaxyproject/training-material/pull/2688

Update Analyze Data to Home icon (spanish)

---

topics/metabolomics/tutorials/lcms-preprocessing/tutorial.md

Some external links were broken. 
Now fixed!
All done following the "Running the GTN website online using GitPod" GTN tutorial!

Fix of some broken links

---

_config.yml
_layouts/base.html
_layouts/home.html

fixes https://github.com/galaxyproject/training-material/issues/2708

Fix lack of news feed icon

---

topics/genome-annotation/tutorials/annotation-with-maker/workflows/main_workflow.ga

In the previous PR the protein dataset was disconnected.

Fix workflow maker

---

topics/proteomics/tutorials/DIA_Analysis_MSstats/tutorial.md
topics/proteomics/tutorials/DIA_Analysis_OSW/tutorial.md
topics/proteomics/tutorials/DIA_lib_OSW/tutorial.md

enable DIA tutorials

---

topics/statistics/tutorials/intro-to-ml-with-r/tutorial.md

Add missing setup step to ML/R tutorial

---

topics/metagenomics/tutorials/metatranscriptomics-short/workflows/workflow1_preprocessing.ga

Updated Workflow1 to include the output QC reverse and forward reads needed for the next workflow

Metatranscriptomics training

---

topics/proteomics/tutorials/DIA_Analysis_MSstats/data-library.yaml
topics/proteomics/tutorials/DIA_Analysis_MSstats/tutorial.md
topics/proteomics/tutorials/DIA_Analysis_OSW/tutorial.md
topics/proteomics/tutorials/DIA_lib_OSW/tutorial.md

I added some information to the tools and updated the zenodo links

Updated zenodo links and added additional information to tools

---

topics/galaxy-interface/tutorials/collections/tutorial.md

fixes a comment by @bgruening and expands collection figure legend

Small fix to collections tutorial

---

topics/metabolomics/tutorials/lcms-preprocessing/slides.html

Hi there,
Here comes an update of the 'Mass spectrometry: LC-MS preprocessing with XCMS' tutorial. 
This follows on from the huge work made [here](https://github.com/galaxyproject/training-material/pull/2594) to add plain text to slides. I can not imagine the work it represented to add a text to all these pictures, especially when people may not know well the domain it refers to! 
I added some enhancements to the texts concerning the slides from the LCMS preprocessing. The previous texts helped so much to do so! Thank you again for the work.
Thank you for your time,
Mélanie

Metabolomics -  LCMS preprocessing update

---

topics/variant-analysis/tutorials/sars-cov-2-variant-discovery/tutorial.md

Also fixes a few typos and adds param info to the consensus workflow run hands-on.
All this based on user feedback from our SARS-CoV-2 Data Analysis and Monitoring with Galaxy workshop.

Fix variant numbers mentioned in question boxes

---

topics/admin/tutorials/ftp/tutorial.md
topics/admin/tutorials/reports/tutorial.md
topics/admin/tutorials/tiaas/tutorial.md

xref:
- usegalaxy-eu/tiaas2#21
- usegalaxy-eu/ansible-tiaas2#7

Update TIaaS tutorial for new role feature that disassociates training groups from roles after the training has ended.

---

topics/transcriptomics/metadata.yaml

@nomadscientist has done amazing work with single cell tutorials and is leading the Spanish translation project, and she has graciously agreed to be a maintainer for the transcriptomics topic, thanks!
ping @hexylena

Add Wendi Bacon as transcriptomics topic maintainer :tada: 

---

_layouts/feedback.html
bin/prepare_feedback.py
metadata/feedback.csv

Fix #2755:
- Fix object id for translated tutorials
- Remove a feedback for a tutorial still in PR
- Rename a tutorial

Feedback page: fix graphs

---

topics/transcriptomics/tutorials/rna-seq-reads-to-counts/tutorial.md

'Column Join on Collection' is now called 'Column join on multiple datasets'  so updated that in tutorial

Reads to counts: update tool name

---

topics/metagenomics/tutorials/nanopore-16S-metagenomics/tutorial.bib
topics/metagenomics/tutorials/nanopore-16S-metagenomics/tutorial.md

also remove dupe ref for gtn that everyone includes

Fix missing reference for nygaard

---

_includes/default-header.html

xref https://www.w3.org/TR/wai-aria-1.1/#search https://accessibility.oit.ncsu.edu/it-accessibility-at-nc-state/developers/accessibility-handbook/aria-landmarks/

Add ARIA landmark for search component

---

_layouts/workflow-list.html

For anybody  directed to the workflows not in the context of a tutorial, a reminder of how to start using them could be nice:

Add workflow import FAQ to bottom of workflow page

---

_plugins/jekyll-figurify.rb

Remove stray debugging statement

---

_layouts/base_slides.html
_layouts/tutorial_slides.html
_plugins/plaintext-slides.rb
metadata/lang/es.yml

@nomadscientist and @galaxyproject/training-spanish team. Here are  a few more strings to translate, for the slides framework

Locale support for slides

---

topics/introduction/tutorials/galaxy-intro-short/slides.html

- Reduce size of UseGalaxy.* servers image
- Move number of public servers to list
- Briefly explain what a workflow is (in speaker's notes)
- Replace Gitter with Matrix

Small update to galaxy-intro-short slides

---

_includes/contributor-badge.html
metadata/lang/es.yml

In response to issue #2835, I created a pull request to create a precise Call-to-action which invites users to make contributions to the tutorial.
In this PR, I added the Spanish translation of the **Add Contributions!** CTA to the metadata es.yml file. 
Is this okay?

Added Spanish translation of the Add Contributions! CTA

---

topics/contributing/slides/introduction.html

In respect to [issue 2833](https://github.com/galaxyproject/training-material/issues/2833) and [issue 2883](https://github.com/galaxyproject/training-material/pull/2883), I added speaker notes to some slides and correct some typos.

Added speaker notes to some slides

---

_layouts/faqs.html

addition to #2973

---

CONTRIBUTORS.yaml

I made my first contribution here #2984
I hope it won't be the last!

 first contribution

---

_plugins/api.rb
_plugins/jekyll-topic-filter.rb

We had a `videos.json` "api", this adds a few more:
```
contributors.json
contributors/
gtn.bib
topics.json
topics/
videos.json
```

Implement a very basic GTN API with our data available in JSON format

---

topics/introduction/tutorials/options-for-using-galaxy/slides.html

I made speaker notes for the tutorial "Options for using Galaxy" to turn it into a video

speaker notes 

---

.github/workflows/deploy.yml
_plugins_dev/api-fake.rb

Also disable the API build in the dev

Wrong path used in build process preventing OpenAPI from working

---

topics/assembly/tutorials/vgp_genome_assembly/tutorial.md

Initial assembly evaluation with Quast and BUSCO section:
- Include additional questions

VGP training: Biohackaton update

---

topics/assembly/tutorials/vgp_genome_assembly/tutorial.md

Edits to the VGP assembly tutorial - HiC scaffolding section. These are basic edits to re-arrange the structure a little bit.

Hackathon VGP edits - tutorial - HiC scaffolding section

---

_layouts/base_slides_rdmbites.html
assets/css/slides-rdmbites.css
assets/css/slides.css

I moved this into a separate file @kpoterlowicz (not sure about Rob's github handle to ping him)

Separate out RDM bites css

---

topics/galaxy-interface/tutorials/collections/tutorial.md

Added Hands-on activities  in hands-on boxes
[issue ](https://github.com/galaxyproject/training-material/issues/2785)
Resolved No. 1 and 2

 Hands-on activities  in hands-on boxes

---

topics/assembly/tutorials/vgp_genome_assembly/tutorial.md

Some more additions to the HiC section. Added in some "TODO's" with notes. Sending a PR now in case others want to use or work on during the Hackathon.

Hackathon vgp edits- hiC scaffolding section

---

topics/assembly/tutorials/vgp_genome_assembly/tutorial.md

Matching the tool descriptions to the tutorial description

Update VGP tutorial

---

CONTRIBUTORS.yaml
_plugins/api.rb
_plugins/search.rb
topics/galaxy-interface/tutorials/ncbi-sarf/tutorial.md

Update GitHub username for Adelaide

---

topics/data-science/tutorials/snakemake/tutorial.md

Fix typos in Snakemake Tutorial

---

topics/transcriptomics/faqs/amplification.md
topics/transcriptomics/faqs/dimension_reduction.md
topics/transcriptomics/faqs/gene_profile.md
topics/transcriptomics/faqs/techniques.md
topics/transcriptomics/faqs/variable_genes.md

According to [issue 3015](https://github.com/galaxyproject/training-material/issues/3015), I added an FAQ file to the transcriptomic (topic level).

Added FAQ files to transcriptomics topic

---

topics/proteomics/faqs/tools_versions.md

I created 10 FAQ files in accordance with discussion to issue #3015 for Proteomics (subtopic Metaproteomics). This is the first one of them. I know it needs a review and I will be glad to receive any corrections and comments.

Added FAQ files to proteomics topic

---

topics/contributing/slides/introduction.html

Corrected 'Creata' to 'Create'

Corrected a typo

---

topics/introduction/tutorials/galaxy-intro-101-everyone/tutorial.md

In response to [this feedback comment](https://github.com/galaxyproject/training-material/issues/989#issuecomment-964725889) on the Galaxy 101 for everyone tutorial:
-I've added a small clarification note regarding the name of the tool in the search bar.

Update Galaxy 101 for everyone tutorial

---

CONTRIBUTORS.yaml
topics/genome-editing/tutorials/crispr-screen/tutorial.md

Would be great if someone could merge this if it passes (tutorial is still enable:FALSE).

Crispr edits 2

---

topics/proteomics/faqs/comparing_measurement.md
topics/proteomics/faqs/convert_to_MGF.md
topics/proteomics/faqs/converting_FASTA.md
topics/proteomics/faqs/determine_taxonomic_composition.md
topics/proteomics/faqs/functional_analysis_tools.md
topics/proteomics/faqs/reusing_workflows.md
topics/proteomics/faqs/search_algorithms.md
topics/proteomics/faqs/search_strategies.md
topics/proteomics/faqs/studying_microbiome_state.md

These are additional files to issue #3015 for Proteomics (subtopic Metaproteomics) for review mentioned before

Additional FAQs to proteomics

---

.gitignore
topics/transcriptomics/tutorials/rna-seq-reads-to-counts/tutorial.md

fixes https://github.com/galaxyproject/training-material/issues/3054

Add a tool ID to a single tool in a tutorial because a user could not find that tool

---

.github/workflows/matrix.yml
bin/news.rb

Thank you @shiltemann for figuring out the secrets issue.

Fix matrix bot try 2 and ignore whitespace in change detection

---

topics/data-management/tutorials/0013_file-naming/slides.html

@robertmand here's the fixes for that. I'll go ahead and merge this and get the video regenerated. 
When you get a chance you'll want to make a PR from galaxyproject:main to rdmfellow:main and merge these changes into your fork :)

Fix line breaking and missing slide separator

---

topics/assembly/tutorials/flye-assembly/tutorial.md
topics/genome-annotation/tutorials/funannotate/tutorial.bib
topics/genome-annotation/tutorials/funannotate/tutorial.md
topics/genome-annotation/tutorials/repeatmasker/tutorial.md

A small PR addressing comments from @srobin's (late :stuck_out_tongue: ) review

Funannotate: minor changes

---

_layouts/faq-page.html
_layouts/faq.html
_layouts/news.html
_plugins/jekyll-environment_variables.rb
faqs/gtn/collaborative_development.bib
faqs/gtn/collaborative_development.md
faqs/gtn/fair_training.bib
faqs/gtn/fair_training.md
news/_posts/2021-12-01-FAIR.md

@bebatut maybe you can review, I extracted these from the paper since we get asked it occasionally and maybe it's nice to 'show off'.

Add two new FAQs: How the GTN stays fair + collaborative development

---

topics/proteomics/tutorials/maxquant-msstats-tmt/tutorial.md

Removed tabs from FTP links and simplified the data import for thermo.raw files.

Fix FTP links and simplify data import
