galaxyproject/training-material

_layouts/hall-of-fame.html
_layouts/home.html

We don't need the big ones, let's expend less network data / load a bit faster hopefully.

Request smaller PNGs from GitHub for HoF

---

topics/dev/tutorials/tool-from-scratch/tutorial.md

So here's a few changes to the conda recipe tutorial, to make it more clear and less potentially dangerous for bioconda github repo

Update Conda tuto

---

topics/genome-annotation/slides/introduction.html
topics/genome-annotation/tutorials/funannotate/tutorial.md

Just some typos found last week

Annotation: fix typos

---

topics/statistics/tutorials/CNN/tutorial.md
topics/statistics/tutorials/fruit_360/tutorial.md

These are just a few typos that I fixed as I was reviewing these tutorials. I am presenting this tutorial in a workshop next week, and appreciate and speedy merge! Thanks!

Fixed some typos in 2 tutorials

---

topics/proteomics/tutorials/maxquant-msstats-dda-lfq/tutorial.md

and adding one line in order to make snippet work properly

Update links to new ftp location in PRIDE

---

topics/proteomics/tutorials/maxquant-msstats-dda-lfq/data-library.yaml
topics/proteomics/tutorials/maxquant-msstats-tmt/data-library.yaml
topics/proteomics/tutorials/maxquant-msstats-tmt/tutorial.md
topics/proteomics/tutorials/protein-id-sg-ps/tours/tour.yaml

PRIDE moved archive files on the FTP server.

Change PRIDE FTP base path

---

topics/dev/tutorials/tool-from-scratch/tutorial.md

A few small problems (indentation, name/url stuff) in the conda recipe tuto found while teaching it this morning

Conda recipe tuto: small fixes for conda recipe

---

topics/proteomics/tutorials/maxquant-msstats-dda-lfq/tutorial.md
topics/proteomics/tutorials/maxquant-msstats-tmt/tutorial.md

- updating MSstats to v4.0 including adjusting new file names and new results in Q&A 
- correcting MSstatsTMT parameters and adjusting training time to include MSstatsTMT runtime

Updating MaxQuant & MSstats tutorials

---

topics/variant-analysis/tutorials/mapping-by-sequencing/tutorial.md

Addresses https://github.com/galaxyproject/training-material/issues/2857

Update variant annotation step to use SnpEff 4.3

---

topics/contributing/tutorials/create-new-tutorial-content/tutorial.md

xref: https://github.com/galaxyproject/training-material/pull/3148/commits/0c342ef20a635deefa645763307982a20dc732cf

fix reference to bibtex entry

---

topics/proteomics/tutorials/proteogenomics-dbsearch/tutorial.md

fix a broken box

---

topics/admin/tutorials/interactive-tools/tutorial.md

- Following branch updating (master > main)
- https://github.com/galaxyproject/gx-it-proxy/commit/62fd619bd2bad542077e6a87498a47b00e05f91f

GxIT admin: change repo reference for gx-it-proxy

---

topics/computational-chemistry/tutorials/zauberkugel/tutorial.md

See https://github.com/galaxyproject/training-material/pull/3163#issuecomment-1042072859

Fix rendering of workflow import snippet

---

topics/genome-annotation/tutorials/funannotate/data-library.yaml
topics/genome-annotation/tutorials/funannotate/tutorial.md
topics/genome-annotation/tutorials/funannotate/workflows/funannotate-tests.yml
topics/genome-annotation/tutorials/funannotate/workflows/main_workflow.ga
topics/genome-annotation/tutorials/funannotate/workflows/test-data/NCBI_submission_template.txt
topics/genome-annotation/tutorials/funannotate/workflows/test-data/busco_sum.txt

Small changes to the funannotate tuto before recording https://github.com/gallantries/video-library/issues/38
First, an updated version of eggnog-mapper => with the old version the "funannotate annotate" was not able to parse the output and include it in the final gff3 file

Funannotate tapas update

---

topics/genome-annotation/tutorials/funannotate/tutorial.md
topics/genome-annotation/tutorials/funannotate/workflows/main_workflow.ga
topics/genome-annotation/tutorials/repeatmasker/tutorial.md

Just a commit I forgot to push earlier + a typo correction
(currently recording repeatmasker tuto :movie_camera: )

Annotation: tool update + typo

---

topics/sequence-analysis/tutorials/mapping/slides.html

Fix another link in read mapper overview slide

---

topics/transcriptomics/tutorials/rna-seq-genes-to-pathways/workflows/rna-seq-genes-to-pathways.ga

The previous workflow had two errors:
- **Compute** _an expression on every row_ tool: old version non functional because using Python 2
- Wrong parameters in **Cut columns from a table** step.

RNA Seq Genes to Pathways: update workflow

---

_config.yml
_layouts/faq-page.html
faqs/galaxy/analysis_jobs_not_running.md
faqs/galaxy/tools_change_version.md
topics/dev/tutorials/debugging/faqs/no_tests_no_yarn.md
topics/dev/tutorials/debugging/faqs/selenium_error.md
topics/dev/tutorials/tool-from-scratch/faqs/bioconda_files_exist.md
topics/dev/tutorials/tool-from-scratch/faqs/get_planemo.md
topics/dev/tutorials/tool-generators/faqs/collections_test.md
topics/dev/tutorials/tool-generators/faqs/error_closure_args.md
topics/dev/tutorials/tool-generators/faqs/error_compose.md
topics/dev/tutorials/tool-generators/faqs/formats.md
topics/dev/tutorials/tool-generators/faqs/job_grey.md
topics/dev/tutorials/tool-generators/faqs/local_install.md
topics/dev/tutorials/tool-generators/faqs/planemo_multiple.md
topics/dev/tutorials/tool-generators/faqs/replace_manual_install.md
topics/metagenomics/tutorials/metatranscriptomics/faqs/fastq_interlacer_vs_joiner.md
topics/metagenomics/tutorials/metatranscriptomics/faqs/multiple_inputs.md
topics/metagenomics/tutorials/metatranscriptomics/faqs/single_end.md
topics/metagenomics/tutorials/metatranscriptomics/faqs/vsearch.md
topics/proteomics/tutorials/encyclopedia/faqs/advantages.md
topics/proteomics/tutorials/encyclopedia/faqs/without_spectral_library.md
topics/transcriptomics/tutorials/de-novo/faqs/different_results.md
topics/transcriptomics/tutorials/droplet-quantification-preprocessing/faqs/alevin_version.md
topics/transcriptomics/tutorials/scrna-seq-basic-pipeline/faqs/findmarkers_empty.md
topics/transcriptomics/tutorials/scrna-seq-basic-pipeline/faqs/plotembed_fails.md
topics/transcriptomics/tutorials/scrna-seq-basic-pipeline/faqs/plotembed_results_missing.md

Add rest of the FAQs from previous events

Add more FAQs

---

faqs/galaxy/tools_missing.md
faqs/galaxy/tutorial_mode.md
topics/transcriptomics/tutorials/droplet-quantification-preprocessing/tutorial.md
topics/transcriptomics/tutorials/scrna-JUPYTER-trajectories/tutorial.md
topics/transcriptomics/tutorials/scrna-seq-basic-pipeline/tutorial.md

Transcriptomics tutorial tools are outdated, so need users to access older tool versions
Also changed name 'GTN in Galaxy' to 'Tutorial mode' because I'm a PR genius

tutorial mode FAQ and add to transcriptomics tutorials

---

bin/ari-map.yml
topics/climate/tutorials/pangeo-notebook/slides.html
topics/climate/tutorials/pangeo/slides.html

- Pronounce netCDF properly e.g. net C D F
- Try to shorten sentences
- Use bullet points for each sentence

Try to fix issues with Pangeo videos

---

bin/knit-automated.sh
topics/admin/faqs/diffs.md
topics/admin/tutorials/ansible-galaxy/tutorial.md
topics/admin/tutorials/connect-to-compute-cluster/tutorial.md
topics/admin/tutorials/cvmfs/tutorial.md
topics/admin/tutorials/ftp/tutorial.md
topics/admin/tutorials/gxadmin/tutorial.md
topics/admin/tutorials/monitoring/tutorial.md
topics/admin/tutorials/pulsar/tutorial.md
topics/admin/tutorials/reports/tutorial.md
topics/admin/tutorials/singularity/tutorial.md
topics/admin/tutorials/tiaas/tutorial.md
topics/admin/tutorials/tool-management/tutorial.md
topics/admin/tutorials/tus/tests/1.sh
topics/admin/tutorials/tus/tutorial.md

Feel free to join on this PR y'all
relevant issues: https://github.com/galaxyproject/training-material/issues/2583 https://github.com/galaxyproject/training-material/issues/2715 https://github.com/galaxyproject/training-material/issues/1809 please feel free to work on any of those

GAT 2022 Updates

---

topics/genome-annotation/tutorials/funannotate/tutorial.md

Move the busco tool usage a bit later

Funannotate: move busco

---

_layouts/faq-page.html
topics/proteomics/tutorials/proteogenomics-dbcreation/faqs/alignment_tools.md
topics/proteomics/tutorials/proteogenomics-dbcreation/faqs/chromosome_names.md
topics/proteomics/tutorials/proteogenomics-dbcreation/faqs/proteogenomics_example_histories.md
topics/proteomics/tutorials/proteogenomics-dbcreation/faqs/proteogenomics_own_data.md
topics/proteomics/tutorials/proteogenomics-dbcreation/faqs/proteogenomics_querytabular.md
topics/proteomics/tutorials/proteogenomics-dbcreation/faqs/proteogenomics_variants.md
topics/proteomics/tutorials/proteogenomics-dbcreation/faqs/variant_mapping_file.md
topics/proteomics/tutorials/proteogenomics-dbsearch/faqs/mvp.md
topics/proteomics/tutorials/proteogenomics-dbsearch/faqs/proteogenomics_example_histories.md
topics/proteomics/tutorials/proteogenomics-dbsearch/faqs/proteogenomics_own_data.md
topics/proteomics/tutorials/proteogenomics-dbsearch/faqs/proteogenomics_querytabular.md
topics/proteomics/tutorials/proteogenomics-dbsearch/faqs/proteogenomics_variants.md
topics/proteomics/tutorials/proteogenomics-dbsearch/faqs/search_gui.md
topics/proteomics/tutorials/proteogenomics-novel-peptide-analysis/faqs/proteogenomics_example_histories.md
topics/proteomics/tutorials/proteogenomics-novel-peptide-analysis/faqs/proteogenomics_own_data.md
topics/proteomics/tutorials/proteogenomics-novel-peptide-analysis/faqs/proteogenomics_querytabular.md
topics/proteomics/tutorials/proteogenomics-novel-peptide-analysis/faqs/proteogenomics_variants.md

Last of the FAQ from the Google docs used at Smorg/GCC 2021

[FAQs] Add proteogenomics FAQs (for realsies the last ones now)

---

topics/computational-chemistry/tutorials/htmd-analysis/tutorial.md

@nagoue do you think this is helpful?

Clarification about the G5E ligand in the HTMD tutorial

---

topics/computational-chemistry/tutorials/analysis-md-simulations/tutorial.md
topics/computational-chemistry/tutorials/analysis-md-simulations/workflows/advanced_workflow-tests.yml
topics/computational-chemistry/tutorials/analysis-md-simulations/workflows/advanced_workflow.ga

Fix #3200, thanks for pointing that out @hexylena

Fix link to advanced mdanalysis workflow

---

topics/genome-annotation/tutorials/crispr-screen/slides.html

Fix for https://github.com/galaxyproject/training-material/pull/3219#issuecomment-1060982931

CRISPR: Add speaker notes to slide

---

_plugins/notebook.rb
topics/climate/tutorials/pangeo-notebook/tutorial.md

based on an issue @annefou saw

Cherry-pick notebook plugin fixes from python-modular branch

---

topics/transcriptomics/tutorials/scrna-seq-basic-pipeline/tutorial.md

People commonly test something for fun then use that dataset instead of the correct one. Fixing it here by adding a warning and a labelling schematic

Common mistake fix

---

_plugins/api.rb
_plugins/jekyll-topic-filter.rb

Both internally and externally accessible, we can use this information in ruby or via the api for e.g. the video library.
The tool list will be helpful and we can re-structure the supported servers around it maybe.

Annotate workflows, wf tests, and tools in the API

---

topics/statistics/tutorials/CNN/tutorial.md

Reverts galaxyproject/training-material#3068

Revert "Added section to explain OHE and calculate the OHE of training labels."

---

topics/statistics/tutorials/CNN/tutorial.md

Fixes https://github.com/galaxyproject/training-material/pull/3068 and adds its suggested change

[Fixes revert] Added section to explain OHE and calculate the OHE of training labels.

---

topics/admin/tutorials/ansible-galaxy/tutorial.md
topics/admin/tutorials/connect-to-compute-cluster/tutorial.md
topics/admin/tutorials/cvmfs/tutorial.md
topics/admin/tutorials/ftp/tutorial.md
topics/admin/tutorials/gxadmin/tutorial.md
topics/admin/tutorials/job-destinations/tutorial.md
topics/admin/tutorials/monitoring/tutorial.md
topics/admin/tutorials/pulsar/tutorial.md
topics/admin/tutorials/reports/tutorial.md
topics/admin/tutorials/singularity/tutorial.md
topics/admin/tutorials/tiaas/tutorial.md
topics/admin/tutorials/tus/tutorial.md

- TUS was missing the galaxy var required for it to be useful, wow that's an omission
- galaxy needs to be updated to the latest version
- the galaxy_group.name is fake news, have to use `__galaxy_group` thing.

Last minute update for GAT 

---

CONTRIBUTORS.yaml
topics/ecology/tutorials/PAMPA-toolsuite-tutorial/tutorial.md

Just a tiny PR to add a contributor we forgot to mention at first !

Adding a contributor to our PAMPA ecology tutorial

---

topics/introduction/tutorials/galaxy-intro-101-everyone/tutorial.md
topics/introduction/tutorials/galaxy-intro-101-everyone/workflows/main_workflow.ga

The old referenced version is broken.

Update ggplot2 tool in galaxy101 for everyone

---

topics/sequence-analysis/tutorials/mapping/tutorial.md

Confusion reported here: https://gtnsmrgsbord.slack.com/archives/C01F6JHCFT6/p1647281187765399?thread_ts=1647271479.003609&cid=C01F6JHCFT6

Clarified a tool name in tutorial.md

---

_includes/tutorial_list.html
_plugins/search.rb
assets/css/main.scss
bin/lunr-index.js
search.md
topics/admin/tutorials/ansible-galaxy/tutorial.md

you can search just on FAQs, e.g. to find that pesky chrome problem

Search and index FAQs

---

topics/admin/tutorials/data-library/tutorial.md

Replace ln with cp in admin tutorial because this does not work (expected)

---

topics/admin/tutorials/tus/tutorial.md

tusd tutorial: Correct reference to role name in steps to add to requirements.yml

---

topics/evolution/tutorials/mtb_phylogeny/tutorial.md

Some minor edits in the phylogenetics tutorial for the tuberculosis NGS workshop next week

MTB phylogenetics tutorial: corrected typos and some polishing

---

topics/transcriptomics/tutorials/ref-based/tutorial.md

"As for the GO terms, 2 files are generated:" is confusing, since 3 file were generated above

small fix (to reduce confusion)

---

topics/assembly/tutorials/vgp_genome_assembly/tutorial.md

It is very difficult to understand that Meryl needs to be run three times here. This needs to be said explicitly

Edits for Meryl section

---

topics/transcriptomics/tutorials/rna-seq-reads-to-counts/tutorial.md

This has just a couple of small updates
-updates Cutadapt parameter name to new version Minimum length -> Minimum length (R1)
-adds tool links for tutorial mode

RNA-seq reads counts: small update

---

topics/statistics/tutorials/CNN/tutorial.md

Fixes a minor issue

---

faqs/galaxy/analysis_jobs_keep_running.md
topics/admin/tutorials/gxadmin/tutorial.md
topics/admin/tutorials/singularity/tutorial.md
topics/sequence-analysis/tutorials/quality-control/tutorial.md
topics/transcriptomics/tutorials/rna-seq-counts-to-viz-in-r/tutorial.md

I can't believe we didn't have this? Review on the text of this FAQ is very welcome.

"Jobs keep running" - an FAQ

---

faqs/galaxy/collections_rename.md
faqs/galaxy/histories_import.md

- Changed Import an History to Importing History
- Removed the space to delete the unnecessary name info seen on the image

Made some minor changes to GTN FAQs

---

faqs/galaxy/analysis_reporting_issues.md

The following Pull Request is a part of the Issue: Move FAQs to GTN of the [Galaxy_Hub repository](https://github.com/galaxyproject/galaxy-hub).
I have added [Issue Reporting and Feature Requests](https://galaxyproject.org/issues/) in the GTN. 
I couldn't find a suitable area for adding issues, so I added it under analysis.

[FAQs] Added Reporting Issues and Feature Requests

---

faqs/galaxy/tools_select_collection.md

changes made to this pull request were:
-  adjusted spelling error

Adjusted spelling error 

---

CONTRIBUTORS.yaml

to fix #3360
ping @Samanthaanjei

Add Samantha to contributors

---

faqs/galaxy/histories_find_purge.md

all this mess is trying to fix #3360

Fix Samantha's id in FAQ

---

CONTRIBUTORS.yaml
faqs/galaxy/datasets_download_using_command_line.md

Moving FAQ Download Datasets using Command-line option

---

faqs/galaxy/dataset_incomplete_download.md

The link added to the command-line text is connected to the PR #3336

Moving FAQ - Incomplete Dataset Downloads

---

faqs/galaxy/updating_account_preferences.md

Changes included in this pull request are:
-  steps in updating a users account preference.

Moving FAQ updating account preference

---

faqs/galaxy/dataupload_NCBI_SRA.md

This FAQ is part of [Reformatting fastq data loaded with NCBI SRA](https://galaxyproject.org/support/ncbi-sra-fastq/).

Moving FAQ - Data retrieval with “NCBI SRA Tools” (fastq-dump)

---

faqs/galaxy/datasets_not_downloading_at_all.md

Fixing the problem shown on the image (the first three steps).

Fixing FAQ dataset not downloading at all

---

faqs/galaxy/dataset_incomplete_download.md

Fixing the issue shown on the image.

Fixing FAQ Incomplete dataset download

---

faqs/galaxy/dataupload_NCBI_SRA_sourced_fastq_data.md

This FAQ is part of [Reformatting fastq data loaded with NCBI SRA](https://galaxyproject.org/support/ncbi-sra-fastq/).

Moving FAQ - NCBI SRA sourced fastq data

---

faqs/galaxy/analysis_extended_Extended_help_differential_expression_analysis_tools.md

Moving FAQ [Extended Help for Differential Expression Analysis Tools](https://galaxyproject.org/support/diff-expression/)

Moving FAQ - Extended Help for Differential Expression Analysis Tools

---

faqs/galaxy/datasets_UCSC_sourced_genome.md

This FAQ is part of [Mismatched Chromosome identifiers (and how to avoid them)](https://galaxyproject.org/support/chrom-identifiers/)

Moving FAQ - Directly obtaining UCSC sourced *genome* identifiers

---

faqs/galaxy/user_preferences_account_usage_quota.md

There was already a `User preferences` area, fixing this one to make it match

Fix area in FAQ

---

faqs/galaxy/datasets_custom_genomes.md

Hi everyone! 
I am moving FAQ custom genomes .

FAQ custom genomes 

---

faqs/galaxy/tools_help.md

This file answers the FAQ "Where is the tool help?"

Moving FAQ Where is the tool help? 

---

faqs/galaxy/datasets_sorting_reference_genome.md

Hi !
I am moving FAQ Sorting Reference Genome.

Moving FAQ Sorting Reference Genome

---

faqs/galaxy/datasets_troubleshooting_custom_genome.md

Hi !
I am moving Troubleshooting Custom Genome.

Moving FAQ Troubleshooting Custom Genome

---

faqs/galaxy/datasets_BAM_dataset_identifiers.md

This FAQ is part of [Mismatched Chromosome identifiers (and how to avoid them)](https://galaxyproject.org/support/chrom-identifiers/)

Moving FAQ - Finding BAM dataset identifiers

---

faqs/galaxy/datasets_working_with_reference_annotation.md

This PR is to create an FAQ regarding _Working with  GFF GFT GTF2 GFF3 reference annotation_ and further link it with all of its occurrences. Kindly suggest any improvements or amendments.

[FAQ] Added Working with  GFF GFT GTF2 GFF3 reference annotation

---

faqs/galaxy/datatypes_understanding_datatypes.md

This PR is to create an FAQ regarding _Understanding Datatypes_ and further link it with all of its occurrences.
_This FAQ shall go to the top of datatype FAQs, for the rest to be nested underneath._

[FAQ] Added Understanding Datatypes

---

faqs/galaxy/datasets_working_with_fasta.md

This PR is to create an FAQ regarding _Working with a huge fasta dataset_ and further link it with all of its occurrences.

[FAQ] Added Working with huge fasta Dataset

---

faqs/galaxy/datasets_working_with_fastq.md

This PR is to create an FAQ regarding _Working with huge fastq dataset_ and further link it with all of its occurrences.

[FAQ] Added Working with fastq dataset

---

faqs/gtn/galaxy_usage.md

This PR is to create an FAQ regarding _Ways to use Galaxy_ and further link it with all of its occurrences. 

[FAQ] Added Ways to use Galaxy

---

faqs/galaxy/datasets_chromosome_identifiers.md

This FAQ is part of [Mismatched Chromosome identifiers (and how to avoid them)](https://galaxyproject.org/support/chrom-identifiers/). I separated the FAQ to different FAQs because the content was too long.

Moving FAQ - Mismatched Chromosome identifiers and how to avoid them

---

faqs/galaxy/analysis_job_failure_excess_memory.md
faqs/galaxy/analysis_job_failure_walltime.md

This PR is to update the links in the PRs #3406 #3407

[FAQ] Edit missing links in FAQs

---

faqs/galaxy/tools_tool_doesnt_recognize_any_input_datasets.md

Fixing broken links
I think this was why it was failing

Fixing FAQ - Tool doesn't recognize input datasets

---

_includes/cyoa-choices.html
_plugins/notebook-jupyter.rb
assets/js/main.js
topics/contributing/tutorials/create-new-tutorial-content/tutorial.md
topics/transcriptomics/tutorials/ref-based/tutorial.md

@bebatut @lldelisle it now supports a default, which is set for your tutorial, and we can choose which branch based on the URL parameter (probably good for linking to a specific version in a course)

CYOA: Set a default, and allow taking it from a URL parameter

---

topics/transcriptomics/tutorials/ref-based/tutorial.md

Fix Typos in ref-based RNAseq tutorial

---

faqs/galaxy/datasets_sorting_reference_genome.md

Earlier, the FAQ description contained a non-functional link and repeated data.
Through this PR, I have modified the content to remove content redundancy and make the link functional.

[FAQ] Added minor content edits

---

faqs/galaxy/datasets_working_with_deleted_datasets.md

This PR is a part of the issue: _Move FAQs to the GTN_. in the Galaxy Hub.
Through this PR, a FAQ for working with deleted datasets is generated in the GTN.
Kindly suggest any changes or improvements.

[FAQ] Added Working With Deleted Datasets

---

topics/transcriptomics/tutorials/ref-based/tutorial.md

Mostly moving boxes around :smile: and adding 1 question
@lldelisle what do you think?

[Transcriptomics] Minor changes in the ref-based rna-seq tutorial

---

assets/js/main.js

cc @abretaud if you want to approve

fixes #3351

---

bin/lunr-index.js

@beatrizserrano would you like to approve this :) it will fix the igv issue.

Fixes #3411

---

_plugins/jekyll-environment_variables.rb
assets/css/main.scss
assets/css/slides.css
stats.md
topics/introduction/tutorials/galaxy-intro-short/slides.html

Always bemoaned that our display wasn't as nice as grafana's
and also in slides
so the image is no longer constantly outdated.

Add a nicer stats display

---

_layouts/base.html
_layouts/workflow-list.html
_plugins/jekyll-jsonld.rb

This also adds the DC terms to our header metadata. It's not a huge change
I cannot test this currently, as the best checker available (fair-checker) only accepts public URLs and doesn't seem to process a few of my tests, and it isn't clear why. xref https://github.com/IFB-ElixirFr/FAIR-checker/issues/115
But I think this is right.

Update bioschemas markup for TrainingMaterial profile release

---

.github/workflows/ci-symlinks.yml
_plugins/author-page.rb
bin/check-snippet-links.sh
topics/admin/faqs/ansible-connection.md
topics/admin/faqs/ansible_define-once.md
topics/admin/faqs/ansible_diff.md
topics/admin/faqs/ansible_error-no-hosts-matched.md
topics/admin/faqs/ansible_role-prefix.md
topics/admin/faqs/ansible_role-properties.md
topics/admin/faqs/ansible_yaml.md
topics/admin/faqs/galaxy-how-many-mules.md
topics/admin/tutorials/ansible-galaxy/faqs/custom-welcome.md
topics/admin/tutorials/ansible-galaxy/tutorial.md
topics/admin/tutorials/ansible/tutorial.md

- Add an FAQ for a custom welcome page (per discussion in matrix)
- Move some of our existing tips into FAQs for better visibility
- Add a checker script for incorrectly referenced `snippet`s since the jekyll message is useless ("could not find file ''")

Admin FAQs

---

topics/dev/tutorials/bioblend-api/slides.html

BioBlend tutorial: Replace IPython requirement with JupyterLab

---

_plugins/jekyll-scholar.rb
bin/workflow_to_tool_yaml.sh

@heylf I noticed in your slides the other day that you were manually linking citations, this should fix that :)

slide cite

---

assets/js/main.js
topics/admin/tutorials/ansible-galaxy/tutorial.md

honestly not sure how we missed this
Fixes #3494

Fix admin diff presentation view, and a diff typo.

---

topics/instructors/tutorials/organize-workshop/tutorial.md

I forget who shared this to me, but it's a nice guide on accessible meetings, it's maybe helpful for other workshop organisers.

Add ada resource for workshop organisers

---

_layouts/faq.html

xref @heylf's question about which snippets available

Add how to use snippet in GTN

---

CONTRIBUTORS.yaml
_plugins/notebook.rb
topics/dev/tutorials/bioblend-api/tutorial.md

Converted from https://github.com/nsoranzo/bioblend-tutorial via jupytext and basically directly into the GTN with a little bit of extra formatting for questions to be prettier.
Tutorial | Notebook
--- | ---

Import the existing bioblend tutorial, exercises 

---

topics/transcriptomics/tutorials/ref-based/tutorial.bib

RNAseq tutorial: fix url featurecounts

---

topics/admin/tutorials/ansible-galaxy/tutorial.md

move acl at the PG step, otherwise natefoo.postgresql_objects fails - on ubuntu22.04

fix ERROR: Failed to set permissions on the temporary files

---

topics/admin/tutorials/ansible-galaxy/tutorial.md
topics/admin/tutorials/connect-to-compute-cluster/tutorial.md
topics/admin/tutorials/ftp/tutorial.md
topics/admin/tutorials/monitoring/tutorial.md
topics/admin/tutorials/pulsar/tutorial.md
topics/admin/tutorials/singularity/tutorial.md
topics/admin/tutorials/tiaas/tutorial.md
topics/admin/tutorials/tus/tutorial.md

This is a better default, not sure why we haven't been using this forever.

Add gzip to nginx configuration

---

topics/dev/tutorials/architecture/slides.html

Update architecture tutotial slides (model+migrations)

---

_layouts/news.html
_plugins/jekyll-jsonld.rb
_plugins/jekyll-scholar.rb
topics/admin/tutorials/ansible-galaxy/tutorial.md

Fixes #2457
@hexylena Kindly let me know what you think.
I am new to jekyll and still learning around it. Do let me know what I can do to make it better if this cannot be merged.
Thanks.

Add json-ld markup to news posts

---

_layouts/base.html
_layouts/base_slides.html

Add canonical headers to training materials, decreasing indexing of proxies.

---

topics/dev/tutorials/debugging/tutorial.md

Updates for GCC 2022.
Ping @assuntad23

Update "debugging Galaxy" dev tutorial for 2022

---

topics/dev/tutorials/writing_tests/api2.md

Use of populator at this stage was one step premature.

[URGENT] Fix bug in sample code

---

topics/genome-annotation/tutorials/funannotate/data-library.yaml
topics/genome-annotation/tutorials/funannotate/tutorial.md
topics/genome-annotation/tutorials/functional/content.md
topics/genome-annotation/tutorials/functional/data-library.yaml
topics/genome-annotation/tutorials/functional/faqs/index.md
topics/genome-annotation/tutorials/functional/tutorial.md
topics/genome-annotation/tutorials/functional/workflows/functional-tests.yml
topics/genome-annotation/tutorials/functional/workflows/index.md
topics/genome-annotation/tutorials/functional/workflows/main_workflow.ga

As the funannotate tutorial is veeeery long, and sometimes we want to have a small annotation tutorial, I've extracted a short functional annotation tutorial, doing the same as in the funannotate tuto, but on a small number of protein sequences.
We'll probably use it for https://lepidoptera-2022.workshop.inrae.fr/

Short tutorial for functional annotation

---

topics/introduction/tutorials/data-manipulation-olympics/tutorial.md

- update tool version, remove stray curly brace

small fixes to data manipulation tutorial

---

CONTRIBUTORS.yaml
topics/statistics/metadata.yaml
topics/statistics/tutorials/iwtomics/tutorial.md

I recently changed my GitHub id.
This is just to update the list of maintainers of the statistics topic with my new id.

Updating statistics maintainers

---

Gemfile

closes https://github.com/galaxyproject/training-material/issues/3582

include webrick as a conditional dependency

---

topics/contributing/faqs/contributing_a_notebook.md

Add ipynb faq

---

topics/dev/tutorials/interactive-tools/tutorial.md

notably galaxy tools directory PATH, without /server/

Corrections

---

topics/data-science/tutorials/r-basics/tutorial.md

Fixed a typo, corrected the object names

fix errors

---

topics/dev/tutorials/visualization-charts/tutorial.md

there is no specs but setting
https://github.com/galaxyproject/galaxy/blob/629a5134cbdf78365a642c960011b33ac3c83ab2/config/plugins/visualizations/example/config/example.xml#L17

replace <specs> by <setting>

---

_layouts/tutorial_hands_on.html
_plugins/jekyll-jsonld.rb

handle complex contributions correctly in citation  @jdavcs

fixes #3564

---

news/_posts/2022-09-11-data-manipulation-tutorial.md

added the tutorial just before summer but didnt have time to make a news post yet

[News] add post for new data manipulation tutorial

---

accessibility.md
assets/js/main.js
faqs/gtn/a11y.md

Fixes #3599 and documents them on the new accessibility page/faq

Expand all fixes/a11y

---

topics/assembly/tutorials/vgp_genome_assembly/data_library.yml

Added data library links for yeast (HiFi, bionano, HiC) and zebra finch (HiFi, bionano, HiC) for the VGP assembly tutorials

added VGP data_library (yeast and zebra finch)

---

topics/metabolomics/tutorials/lcms-dataprocessing/tutorial.md

Hi there,
The "Mass spectrometry: LC-MS data processing" training material have been accessible in an "under dev" state for a while now. I wanted to test it in training before to let it be in the menus, to be able to consolidate it if necessary. 
Since then, I had the opportunity to test it and get feedback in in-site training as well as autonomous online training, and appart from minor adjustments everything was ok. 
So now I made the little improvments needed and here is the Pull Request to update all this and make it findable in menus. 
Thank you in advance for the review, and I am looking forward to seeing the material without the "Under dev" notice :)
Mélanie

[Metabo lcmsproc] Update of material and end of "In-dev" state

---

topics/transcriptomics/tutorials/scrna-case_alevin-combine-datasets/tutorial.md

such a tiny error
I feel so dumb
Please fix

missed character

---

topics/admin/tutorials/wireguard-headscale/tutorial.md

I wrote two, couldn't figure out why @natefoo didn't see it. Yeah. Of course. Because I forgot to add it :woman_facepalming:

Headscale/Tailscale tutorial 

---

topics/transcriptomics/tutorials/clipseq/tutorial.md

Adaptation for the change in the graphical interface over time, supposed to perform the same action with same results.

Clip-Seq tutorial: Updated cutadapt instructions from v1.6 to v4.0

---

topics/genome-annotation/tutorials/repeatmasker/tutorial.md

Just a tiny fix for a broken box

Repeat masking: fix broken box

---

Makefile
environment-osx.yml

Could someone with a mac test if this env resolves?
Fixes #3218

Add separate OSX environment

---

CONTRIBUTORS.yaml

Remove duplicate entry

---

metadata/schema-quiz.yaml

Add missing metadata entry

---

topics/admin/tutorials/ansible-galaxy/tutorial.md
topics/admin/tutorials/jenkins/tutorial.md
topics/admin/tutorials/monitoring/tutorial.md
topics/assembly/tutorials/mrsa-nanopore/tutorial.md
topics/genome-annotation/tutorials/apollo-euk/tutorial.md
topics/genome-annotation/tutorials/apollo/tutorial.md

Use built in abbr

---

topics/contributing/tutorials/design/tutorial.md

Hey, I just spotted some small typos while reading your tutorial. Cheers

Small typos

---

quiz/poll.yaml
topics/data-science/tutorials/python-functions/tutorial.md

Add a simple poll to quizzes

---

bin/workflow_to_tool_yaml.sh

something broke the annotations of supporting Galaxy servers, this seems to fix it @hexylena (fixes https://github.com/galaxyproject/training-material/issues/3607)

fix galaxy server annotation

---

feedback.md

The feedback page is currently broken due to indentation of the script blocks. This also escapes user feedback for security.

Fix Feedback page

---

topics/metagenomics/tutorials/mothur-miseq-sop/content.md

Few small changes and additions to the 16S tutorial

---

topics/introduction/tutorials/galaxy-intro-peaks2genes/tutorial.md

Deleted c in line 589 because it should be adding 1 not adding column 1

Correcting a typo

---

CONTRIBUTORS.yaml

Hi, I'm just adding my name as I'm about to change a typo in one of the tutorials!

Add < MarisaJL > as contributor

---

bin/lint.rb

Enable linting for new boxes

---

topics/metagenomics/tutorials/beer-data-analysis/tutorial.md

fixes https://github.com/galaxyproject/training-material/issues/3663
ping @bebatut

[Metagenomics] Beer Tutorial: fix file import link

---

topics/admin/tutorials/singularity/tutorial.md
topics/climate/tutorials/fates-jupyterlab/tutorial.md

fix some final boxes

---

topics/transcriptomics/tutorials/clipseq/workflows/init_workflow.ga

Strictly speaking, now the original version is also functional after Björn's fix.

clipseq workflow.ga cutadapt v1.6 -> v4.0

---

faqs/galaxy/datasets_detect_datatype.md

The current tutorial in galaxy 101 for everyone has `detect datatype` button  text but the button text is `Auto-detect

Fix label of Auto-detect button in edit dataset snippet

---

topics/assembly/tutorials/get-started-genome-assembly/slides.html
topics/dev/tutorials/bioblend-dev/tutorial.md
topics/transcriptomics/tutorials/network-analysis-with-heinz/tutorial.md

Just minor typos found while preparing a new session

Fix minor typos

---

topics/dev/tutorials/tool-from-scratch/tutorial.md

Reported by @hexylena, fixes https://github.com/galaxyproject/training-material/issues/3274

[Dev] Tools from scratch: add missing macro file import statement

---

topics/contributing/tutorials/create-new-tutorial-content/tutorial.md

fixes https://github.com/galaxyproject/training-material/issues/3682
(added zero-width spaces) ping @hexylena

[Contributing] Stop markdown rendering by figurify plugin

---

.github/labeler.yml

Fix typo in labeler conf

---

faqs/galaxy/analysis_regular_expressions.md

Hello,
I added a resource, Cyrilex (I am the founder), a regex visualizer and tester.
It is also possible to generate strings corresponding to regular expressions.

Added a regex resource

---

_includes/news-card.html
_layouts/home.html
_layouts/news.html

got lost somewhere, but, we weren't doing that and it makes sense to, that page loads slowly otherwise.

load news images lazily

---

topics/admin/tutorials/ansible-galaxy/tutorial.md
topics/admin/tutorials/job-destinations/tutorial.md
topics/admin/tutorials/pulsar/tutorial.md

Thanks to @simonbray for noticing this issue!

Replace execution with environment

---

chat.html

I have added DOCTYPE to chat.html which should be the first line of code in an HTML DOC.

Added DOCTYPE

---

topics/introduction/tutorials/data-manipulation-olympics/tutorial.md

See all the relevant discussion in galaxyproject/tools-iuc#4674.

Update Data Manipulation Olympics for Compute 2.0

---

topics/admin/tutorials/ansible-galaxy/tutorial.md

Fixes #3738 by documenting the error message for others
Additionally adds YAML output to ansible.cfg to help debugging because json is miserable to read.

Misc gat fixes

---

.github/workflows/video.yml

Oh. Sorry @hexylena Hold the beer.
I forgot to add the recurse option - that works on my fork in an action that makes a single target as a sample.
Let's see how this goes?

video.yml write permission fix part 2: Add recursive flag

---

assets/js/main.js

Add self-link to hands on box

---

CONTRIBUTORS.yaml
_layouts/contributor_index.html
bin/schema-contributors.yaml
topics/transcriptomics/tutorials/de-novo/tutorial.md

I've added one for James, as well.

Add small section on Simon's profile, remembering him.

---

topics/transcriptomics/tutorials/clipseq/workflows/init_workflow.ga

The current clipseq tutorial .ga works with the tutorial data without any issues, but applying it to user-provided data sometimes raises an error due to a bug in the old version pysam.py. Updated all tools to recent versions to avoid this problem.

clipseq workflow.ga updated

---

topics/metagenomics/tutorials/metagenomics-assembly/workflows/workflow-generate-dataset-for-assembly-tutorial.ga

In this PR I improve metagenomics-assembly tutorial (first, add .ga file for workflow of generation of dataset that is used in this tutorial)

add workflow for dataset generation for meta assembly tutorial

---

assets/js/main.js

Add url param for hands on only

---

topics/variant-analysis/tutorials/tb-variant-analysis/tutorial.md
topics/variant-analysis/tutorials/tb-variant-analysis/workflows/tb-variant-analysis.ga

* New version of tb_variant_filter
* More detail on filtering variants
* New version of tbprofiler
WIP because workflow not yet tested, because database that supports TB Variant Report is currently offline.
(apologies for use of main branch - a mistake)

WIP: Update TB Variant Analysis tutorial

---

_layouts/home.html

Add mastodon link

---

_plugins/plaintext-slides.rb

Break redirects to plain text slides

---

topics/single-cell/tutorials/bulk-music-3-preparebulk/tutorial.md

@nomadscientist which is right? there were two time estimates. If not correct, please feel free to edit + merge it :)

Duplicate time key, I picked one randomly

---

_includes/resource-video-library.html

This reverts commit a69cf26dab625859f795ed380afdf0f99ecd9af4.
to fix recordings not showing up in tutorial overview box
ping @hexylena

Revert "Update for new plugin based data structure"

---

topics/metagenomics/tutorials/pathogen-detection-from-nanopore-foodborne-data/workflows/nanopore_preprocessing.ga

This WF got partially messed up by #3856.

Revert foodborne tutorial preprocessing WF to correct state

---

_includes/resource-workflows.html
_includes/resource-zenodo.html

It was driving me crazy every time I open a tutorial :sweat_smile:

Add insecable space between icon and text in tutorial overview

---

topics/metagenomics/tutorials/pathogen-detection-from-nanopore-foodborne-data/tutorial.md

Otherwise it introduces columns to the page

foodborne tutorial - fixed unescaped pipes

---

topics/single-cell/tutorials/bulk-music-3-preparebulk/tutorial.md

Main change was that I switched the values filtered in the Manipulate Expression Set Tools - it should filter for the healthy cells to make the healthy expression set object, filter for diabetes to make the diseased dataset.

Editing and typos

---

.github/workflows/monthly-release.yml
.github/workflows/video.yml
_layouts/faq.html
_plugins/gtn.rb
_plugins/gtn/boxify.rb
_plugins/snippet.rb
assets/css/main.scss
assets/css/themes.scss
faqs/galaxy/interactive_tools_jupyter_launch.md
topics/genome-annotation/tutorials/annotation-with-maker/content.md
topics/genome-annotation/tutorials/annotation-with-maker/tutorial.md
topics/genome-annotation/tutorials/functional/tutorial.md
topics/introduction/tutorials/galaxy-intro-short/tutorial_ES.md
topics/metagenomics/tutorials/metatranscriptomics/content.md
topics/metagenomics/tutorials/metatranscriptomics/tutorial.md
topics/metagenomics/tutorials/mothur-miseq-sop/content.md
topics/metagenomics/tutorials/mothur-miseq-sop/tutorial.md
topics/teaching/tutorials/hybrid-training/tutorial.bib
topics/teaching/tutorials/hybrid-training/tutorial.md
topics/transcriptomics/tutorials/rna-seq-counts-to-genes/tutorial.md
topics/transcriptomics/tutorials/rna-seq-reads-to-counts/tutorial.md

Fix box titles in included snippets

---

topics/single-cell/tutorials/bulk-music/tutorial.md

The total bulk expression should be T not C 
The cell types should be C3 and C4

Minor corrections

---

faqs/galaxy/tutorial_mode.md
topics/introduction/tutorials/galaxy-intro-short/tutorial.md
topics/single-cell/tutorials/scrna-case_JUPYTER-trajectories/tutorial.md
topics/single-cell/tutorials/scrna-case_alevin-combine-datasets/tutorial.md
topics/single-cell/tutorials/scrna-case_alevin/tutorial.md
topics/single-cell/tutorials/scrna-case_basic-pipeline/tutorial.md
topics/single-cell/tutorials/scrna-case_cell-cycle/tutorial.md
topics/single-cell/tutorials/scrna-case_monocle3-trajectories/tutorial.md

This is stuff that will hopefully make it easier to run the next time :)

updates from scRNA-seq course

---

topics/single-cell/tutorials/scrna-case_alevin/tutorial.md

Fixed typo

---

CONTRIBUTORS.yaml

Hello - just adding myself as a contributor as I'm about to correct a typo, and as I'm supervised by Wendi Bacon, hopefully I'll be making more meaningful contributions in future :)

Add miRlyKayleigh as contributor

---

topics/assembly/tutorials/vgp_genome_assembly/tutorial.md

hello! 👋🏼 
- added disclaimer in intro paragraph about some results having minor differences depending on software versions
- fixed misleading sentence about the merqury plots
- specified tool version in body of text so users know the tutorial is referring to an older version (only done for `compute expression` as the newer version has different options, and for `bionano` as newer version was giving some errors we haven't had a chance to look into yet)

`VGP assembly pipeline`: some textual changes

---

_plugins/api.rb
topics/variant-analysis/tutorials/trio-analysis/workflows/main_workflow.ga

My ugly hack to name the files `1?gtn=true` didn't work, sadly, I guess github strips query params off rather than saying "ah yes a file with exactly that name exists" like many other static file servers will do, allowing you to work around file + folder with the same name.
So we'll just end it in `.json` properly, and then rewrite in nginx. https://github.com/galaxyproject/infrastructure-playbook/pull/39

ga4gh/trs/Write files ending with json, rewrite in nginx

---

topics/single-cell/tutorials/scrna-case_cell-cycle/tutorial.md

Here are some changes
- But we majorly need to look at the step from "Filter the cell cycle genes" onwards

Cell cycle feedback

---

_layouts/workflow-list.html

Add import to eu

---

CONTRIBUTORS.yaml

I added my name in the CONTRIBUTORS.yaml file.

Fist commit

---

CONTRIBUTORS.yaml

Forgot about that old address...
Thinking about it, there's no mastodon support yet?

Update email address

---

faqs/galaxy/datasets_change_datatype.md
faqs/galaxy/datasets_convert_datatype.md

Update FAQ to change datatype or convert datatype due to the new 23.0 version.

Fix FAQ relative to datatype due to 23.0

---

CONTRIBUTORS.yaml
topics/transcriptomics/tutorials/network-analysis-with-heinz/slides.html
topics/transcriptomics/tutorials/network-analysis-with-heinz/tutorial.md

Per request from  @ChaoZhang123 :)

Update contributor information

---

.github/pull_request_template.md

@lldelisle is this clearer that we don't want to keep the whole template? it's best if you delete the entire message and just write your own message? (the template is a lot of visual noise, and you're the first to encounter it sorry, it needed some user testing :sweat_smile:)

Try different language to make the PR template clearer

---

CONTRIBUTORS.yaml

Update my info in the CONTRIBUTOR file

Update my info

---

CONTRIBUTORS.yaml
topics/introduction/tutorials/galaxy-intro-short/tutorial.md

A pull request to fix some grammar and spelling mistakes I noticed in the lesson "A short introduction to Galaxy".

Fix some grammar and spelling in short intro to Galaxy

---

topics/introduction/tutorials/galaxy-intro-short/slides.html
topics/variant-analysis/tutorials/sars-cov-2/tutorial.md

- Fix sars-cov-2 variant analysis tutorial tool name
- Available contents changed in sars-cov-2
- Fix minor typos
- Update of numbers in galaxy-intro-short tutorial

Update of numbers and few minor typos

---

assets/css/themes.scss

Work around Gareths broken emoji support

---

topics/single-cell/tutorials/scrna-case_JUPYTER-trajectories/tutorial.md

@nomadscientist hopefully it fixes stuff
checked against commit abbe1e4 to fix changes that PR 'Tutorial Monocle3 R notebook - WIP #3893' made to scrna-case_JUPYTER-trajectories tutorial

revert the Scanpy tutorial to the updated correct version

---

topics/admin/tutorials/monitoring/tutorial.md
topics/admin/tutorials/tiaas/tutorial.md

This should fix the issues with keys during installation.

Update telegraf role to use a specific commit

---

CONTRIBUTORS.yaml

Add my orcid

---

topics/dev/tutorials/bioblend-api/tutorial.md

- Some clarifications
- Add how to install BioBlend from inside Jupyter
- `pprint()` variable for portability

Small fixes for the BioBlend tutorial

---

topics/admin/tutorials/pulsar/tutorial.md

needed for installation of pulsar

Pulsar tutorial: add python3-venv to pulsar playbook packages

---

topics/admin/tutorials/sentry/tutorial.md

Minor sentry tutorial tweaks

---

topics/single-cell/tutorials/scatac-preprocessing-tenx/tutorial.md

Only the tools links are fixed. Nothing changed in the tutorial content.

update sctac tutorial tool links

---

faqs/galaxy/analysis_concatenate.md
topics/variant-analysis/tutorials/aiv-analysis/tutorial.md

Some updates for the Avian influenza tutorial

---

.github/workflows/monthly-release.yml

[monthly archives] revert changes

---

CONTRIBUTORS.yaml

I am trying to put ORCID to all contributors of the Reference-based tutorial.
Please @blankclemens @malloryfreeberg @pavanvidem
Confirm your orcid is correct.
@MoHeydarian I could not find yours

Update CONTRIBUTORS with orcid I found

---

.github/workflows/monthly-release-backfill.yml
bin/yaml2json.rb

maybe this'll be it. at least we'll have a separate WF that's easier to work around.

[monthly archive] try 4

---

topics/single-cell/tutorials/scrna-case_alevin/tutorial.md

See line 529 - change ../transcriptomics/.. to ../single-cell/..
<details>
As a small contribution to sustainable computing, we skip the most energy intensive of these tests for pull requests marked as drafts. Once your pull request …

Update link in Mitochondrial Flagging

---

topics/admin/tutorials/ansible-galaxy/tutorial.md
topics/admin/tutorials/interactive-tools/tutorial.md

I noticed a few typos while following.
In addition, I observed some warnings etc. that I tried to clarify.

Typo/minor hiccups in ansible galaxy/IT

---

topics/transcriptomics/tutorials/ref-based/data-library.yaml

I forgot to update data library...

Ref-based: update data library

---

faqs/galaxy/histories_sharing.md
topics/introduction/tutorials/galaxy-intro-short/tutorial.md

- Fix history sharing FAQ.
- Clarify hands-on solution.

Small fixes to Intro short tutorial

---

topics/assembly/tutorials/chloroplast-assembly/workflows/Galaxy-Workflow-Chloroplast-genome-assembly-and-annotation.ga

Updated the version of Fasta Stats in the workflow (in two places), and re-joined to required inputs.

Updated workflow with new version of Fasta Stats

---

topics/statistics/tutorials/classification_machinelearning/tutorial.md
topics/statistics/tutorials/regression_machinelearning/tutorial.md

Add versions of a few ML tools to point to correct tools

Add versions of a few ML tools 

---

topics/assembly/tutorials/largegenome/tutorial.md

Two commits - one for user to check input datatypes, and one to recommend using either of Galaxy Eu or Au servers.

Updates to assembly tutorial for large genome

---

CONTRIBUTORS.yaml
topics/metagenomics/tutorials/taxonomic-profiling/tutorial.bib
topics/metagenomics/tutorials/taxonomic-profiling/tutorial.md

* fixed wrong image 
* small changes in wording 
* small addition to content
* added info on difference to amplicon analysis
* added citation
Additional note:
Should the MetaPhlAn part be in the Details ? I think it would be better in the main text.

Review taxonomic profiling

---

topics/metagenomics/tutorials/taxonomic-profiling/tutorial.md

- Fix paths to input data
- Move database explanation to detail box
- Move MetaPhlAn into a section

Fix and update taxonomic profiling tutorial

---

assets/js/main.js
bin/schema-slides.yaml
topics/admin/tutorials/data-library/slides.html
topics/ecology/tutorials/x-array-map-plot/tutorial.md
topics/metabolomics/tutorials/lcms-preprocessing/slides.html
topics/teaching/tutorials/workshop-intro/slides.html
topics/variant-analysis/tutorials/sars-cov-2/tutorial.md
topics/visualisation/tutorials/circos/tutorial.md

- fixes #4096 
- fixes slides not building (again) due to use of base_slides instead of tutorial slides.
- misc other image link changes/fixes

Smorg misc

---

topics/metagenomics/tutorials/mothur-miseq-sop/content.md

it was already enabled for the first workflow in the tutorial, but not the others, want to show off this super nice feature for the smorg video

[Metagenomics] Enable click-to-run workflows for 16S tutorial

---

_plugins/gtn.rb
topics/genome-annotation/tutorials/apollo-euk/tutorial.md
topics/variant-analysis/tutorials/sars-cov-2-variant-discovery/tutorial.md
topics/variant-analysis/tutorials/trio-analysis/tutorial.md

This reverts commit 0aea3ea739d00f208d441764409e801fe0f7b394.
Change did not do what I expected.

Revert "Move Zenodo choice below EGA-Archive choice"

---

CONTRIBUTORS.yaml
topics/metagenomics/tutorials/metatranscriptomics-short/tutorial.md
topics/metagenomics/tutorials/metatranscriptomics/tutorial.md
topics/metagenomics/tutorials/taxonomic-profiling/tutorial.md

change to github name

---

_layouts/learning-pathway.html
learning-pathways/intro-to-galaxy-and-ecology.md
learning-pathways/train-the-trainers.md

Updates for Learning Pathways

---

topics/transcriptomics/tutorials/differential-isoform-expression/tutorial.md

Alternative splicing training: fix typo in abbreviation definition

---

topics/metagenomics/tutorials/mothur-miseq-sop-short/workflows/workflow1_quality_control.ga
topics/metagenomics/tutorials/mothur-miseq-sop-short/workflows/workflow2_data_cleaning.ga
topics/metagenomics/tutorials/mothur-miseq-sop-short/workflows/workflow3_classification.ga
topics/metagenomics/tutorials/mothur-miseq-sop-short/workflows/workflow4_mock_otu_clustering.ga
topics/metagenomics/tutorials/mothur-miseq-sop-short/workflows/workflow5_otu_clustering.ga
topics/metagenomics/tutorials/mothur-miseq-sop-short/workflows/workflow6_alpha_diversity.ga
topics/metagenomics/tutorials/mothur-miseq-sop-short/workflows/workflow7_beta_diversity.ga
topics/metagenomics/tutorials/mothur-miseq-sop/content.md

There is no more integration with Galaxy and Phinch since phinch v2, so comment out that section for now.
Fix some bugs with the workflows and add metadata (test will follow later)

[16S mothur tutorial] update workflows and remove Phinch section

---

topics/metagenomics/tutorials/mothur-miseq-sop-short/workflows/workflow2_data_cleaning.ga
topics/metagenomics/tutorials/mothur-miseq-sop-short/workflows/workflow3_classification.ga

16S short: update workflows

---

topics/assembly/tutorials/largegenome/tutorial.md

Kmer counting workflow name was incorrect.

Update tutorial.md - workflow name typo

---

topics/assembly/tutorials/largegenome/tutorial.md
topics/computational-chemistry/tutorials/zauberkugel/tutorial.md
topics/fair/tutorials/ro-crate-in-galaxy/tutorial.md
topics/galaxy-interface/tutorials/workflow-reports/tutorial.md
topics/introduction/tutorials/galaxy-intro-101-everyone/tutorial.md
topics/proteomics/tutorials/metaproteomics/tutorial.md
topics/proteomics/tutorials/metaquantome-data-creation/tutorial.md
topics/synthetic-biology/tutorials/basic_assembly_analysis/tutorial.md
topics/synthetic-biology/tutorials/pathway_analysis/tutorial.md
topics/synthetic-biology/tutorials/retrosynthesis_analysis/tutorial.md
topics/transcriptomics/tutorials/rna-seq-reads-to-counts/tutorial.md

This one should be checked a bit carefully, I don't think we have any linting currently on that snippet that might tell us if it was e.g. used incorrectly.

Convert numerous workflow imports to automatic versions

---

topics/ai4life/tutorials/contribute-materials/slides.html
topics/ai4life/tutorials/getting-started/slides.html

Additional comment
- community partners are not listed in the order of their icons

Suggestions for BioImage Model Zoo slides

---

topics/galaxy-interface/tutorials/workflow-parameters/tutorial.md

Fix workflow parameter tutorial for updated Add_a_column1 tool

---

faqs/galaxy/datasets_import_from_data_library.md
topics/epigenetics/tutorials/methylation-seq/tutorial.md

Added the Zenodo URLs to the upload section, based on feedback from Smorgasbord, and updated some formatting while I was there
In general this tutorial could probably use some love, mainly adding some narrative text around the hands-on boxes, if any of the @galaxyproject/training-epigenetics gang has some time some day.

Methyl-seq updates

---

_plugins/jekyll-figurify.rb
assets/css/main.scss

Fix homepage image sizes

---

_layouts/hall-of-fame.html
_layouts/home.html
assets/css/main.scss
faqs/gtn/gtn_stats.md

Added some more stats cards to the contributors section on the homepage and the hall of fame page itself

Show off GTN stats in more places

---

topics/contributing/tutorials/learning-principles/tutorial.md

Add as contributor to Learning principles training

---

faqs/galaxy/collections_change_datatype.md
faqs/galaxy/collections_convert_datatype.md

add an FAQ about setting a datatype for an entire collection, and one for converting the datatype of an entire collection

add FAQS about collection datatypes

---

CONTRIBUTORS.yaml
_layouts/contributor_index.html
bin/schema-contributors.yaml
news/_posts/2023-06-21-fair.md

@kkamieniecka could you review this?

Add news post about fair training

---

stats/index.md

this won't change dynamically when you change the theme, but, if you refresh the pgae it'll be correct and I think that's sufficient for us now.

Contrasting colour for charts based on theme

---

_config.yml
_includes/contributor-badge.html
_includes/default-header.html
_layouts/base.html
_layouts/news.html
_plugins/jekyll-bundler.rb
assets/css/main.scss
assets/js/main.js

It smushes the JS files together at the end of the build. dead simple.
also moves some of the default JS we run on every page into `main.js` which makes a bit more sense? and preloads the bundle.

implement simple JS bundling

---

CONTRIBUTORS.yaml
_includes/contributor-badge.html
_layouts/contributor_index.html
_layouts/hall-of-fame.html
_layouts/topic.html
_plugins/jekyll-topic-filter.rb
assets/css/main.scss
topics/variant-analysis/tutorials/aiv-analysis/tutorial.md
topics/variant-analysis/tutorials/pox-tiled-amplicon/tutorial.md
topics/variant-analysis/tutorials/sars-cov-2-variant-discovery/tutorial.md

@hexylena could you add by-covid and elixir converge tags to this one and to:
- /home/wolma/training_galaxyproject/topics/variant-analysis/tutorials/sars-cov-2-variant-discovery/
- /home/wolma/training_galaxyproject/topics/variant-analysis/tutorials/pox-tiled-amplicon/
?
Thanks!

Add AIV tutorial to one-health

---

news/_posts/2023-06-27-ai4life.md

@beatrizserrano do you want to add a 'funder' for the ai4life project? E.g.  https://github.com/galaxyproject/training-material/blob/main/CONTRIBUTORS.yaml#L1766

Add news post ai4life

---

learning-pathways/intro-to-r-and-ml.md

A learning path for a very introductory course on the foundational skills for R and on how to construct simple ML models in R.

Create an ML Learning Path

---

_plugins/file_exists.rb
learning-pathways/genome-annotation-eukaryote.md
learning-pathways/genome-annotation-prokaryote.md
topics/genome-annotation/tutorials/apollo-euk/tutorial.md
topics/genome-annotation/tutorials/apollo/tutorial.md
topics/genome-annotation/tutorials/gene-centric/tutorial.md
topics/genome-annotation/tutorials/repeatmasker/tutorial.md

Annotation learning paths

---

learning-pathways/intro-to-r-and-ml.md

Switched the `topic` and `name` entries that were failing,

Fixed topic and name links

---

CONTRIBUTORS.yaml

cause who wouldn't want to profit from https://mstdn.science/@gtn/110628391201479353 :-)

Add two more Mastodon accounts (and a matrix id)

---

CONTRIBUTORS.yaml

Adding AI4Life to the list as suggested by @hexylena [here](https://github.com/galaxyproject/training-material/pull/4229).

Add AI4Life to the list of funders

---

CONTRIBUTORS.yaml

adding https://genomic.social/@hrhotz

add another Mastodon account (CONTRIBUTORS.yaml)

---

learning-pathways/climate-learning.md

Add pathways for climate and galaxy discovering

---

topics/metagenomics/tutorials/pathogen-detection-from-nanopore-foodborne-data/tutorial.md

Added missing step-by-step part for all sample analysis step

---

topics/single-cell/tutorials/scrna-case_cell-cycle/tutorial.md

Add tags to tutorial.md

---

topics/single-cell/tutorials/bulk-music-4-compare/tutorial.md

Changed the link to the correct file in the images folder

Correct link for image in Figure 6

---

topics/single-cell/tutorials/scrna-case_basic-pipeline/tutorial.md

Adding link to cell cycle tutorial

---

topics/metagenomics/tutorials/pathogen-detection-from-nanopore-foodborne-data/tutorial.md

Small change to `Krakentools: Extract Kraken Reads By ID`

Correct krakentools input

---

topics/metagenomics/tutorials/pathogen-detection-from-nanopore-foodborne-data/tutorial.md

kraken2 was using the kraken-mpa-report param in the long version, this does not work with extract kraken reads

Foodborne update v2

---

.github/workflows/shortlinks.yaml

Only add changed shortlinks, not e.g. gemfile

---

topics/metagenomics/tutorials/pathogen-detection-from-nanopore-foodborne-data/tutorial.md

Fixes small changes that we found in the last workshop

Small updates from feedback from the last workshop

---

topics/single-cell/tutorials/scanpy_parameter_iterator/tutorial.md

I'm testing the parameter iterator tutorial as a user and providing edits as I go

testing_parameter_iterator_updates

---

topics/single-cell/metadata.yaml

Previous link didn't work, now they'll add an issue to a separate repository, until we get a better system

Update broken link to single cell requests

---

_config.yml
topics/single-cell/tutorials/scanpy_parameter_iterator/tutorial.md

Adding eye-slash icon and updating the Parameter Iterator tutorial which needed this

Add eye-slash icon

---

topics/data-science/tutorials/online-resources-gene/tutorial.md
topics/data-science/tutorials/online-resources-protein/tutorial.md

Fixed typos in BioNT tutorials

---

_includes/pathway-card.html
_plugins/gtn.rb
learning-pathways/python.md
learning-pathways/sql.md

Add two learning pathways for avans/erasmus+

---

topics/admin/faqs/python-memory-leaks.md
topics/admin/tutorials/connect-to-compute-cluster/tutorial.md

@mvdbeek this is based on your message in the admins channel, is this OK for you?

Add python memory leak debugging faq

---

topics/single-cell/tutorials/scrna-case-jupyter_basic-pipeline/tutorial.md

Python tutorial to code section

---

_includes/instance-dropdown.html
_layouts/tutorial_hands_on.html
_plugins/jekyll-topic-filter.rb

Fixes #904, shouldn't affect #4323

Fixes instance list dropdown for 'empty' tutorials

---

topics/single-cell/metadata.yaml
topics/single-cell/tutorials/scrna-case_FilterPlotandExploreRStudio/tutorial.md

This is just putting it in the right section

RStudio tutorial moved to rstudio section

---

search2.html

which i broke in the user prefs pr and didn't notice.

try and fix search

---

learning-pathways/intro_single_cell.md

This is the first single cell learning pathway
Full disclosure Gitpod is taking ages so I've not rendered it yet...

single cell learning pathway addition

---

_layouts/learning-pathway.html

@nomadscientist please merge this and it'll look better.

Fix editorial board display

---

.github/workflows/ci-main.yml

expand linting triggers

---

_layouts/embed.html

Missing embed layout

---

bin/news.rb
topics/single-cell/metadata.yaml

Switching weird issue thing to a user tool request spreadsheet

Add user tool request spreadsheet

---

topics/single-cell/metadata.yaml

There used to be a button/bar around the 'user requests' section, but I think I deleted it...

Trying to add the bar

---

bin/news.rb

@nomadscientist merge please :)

fix sending empty news

---

bin/news.rb

handle `|`, and fix the 'slides' titles

fix news again

---

_plugins/jekyll-topic-filter.rb

sorry @nomadscientist I broke your singlecell home.

fix including tags

---

workflows/embed.html

@nomadscientist this should fix your embed with no other changes, you can then query for `singlecell`, `single cell`, or `single-cell`, and all three of those search terms will include the same results, namely for: singlecell, single-cell, single cell

Allow search in embed to be a bit more lenient

---

topics/single-cell/index.md
topics/single-cell/metadata.yaml

I added the workflows widget to the single cell training page

add workflows widget

---

_layouts/home.html

Remove twitter embed

---

.github/workflows/ci.yml
.github/workflows/deploy.yml
.github/workflows/monthly-release-backfill.yml
.github/workflows/monthly-release.yml
.github/workflows/video-dry.yml
.github/workflows/video.yml
workflows/embed.html

open links in _blank to avoid x-frame-options

---

topics/proteomics/tutorials/proteogenomics-dbcreation/tutorial.md

Update tutorial.md with new link for fasta file

---

topics/genome-annotation/tutorials/crispr-screen/data-library.yaml
topics/genome-annotation/tutorials/crispr-screen/tutorial.md

Fix zenodo links

---

topics/transcriptomics/tutorials/ref-based/tutorial.md

several small fixes as discussed yesterday with Lucille

small fixes to Reference-based RNA-Seq data analysis tutorial

---

faqs/galaxy/histories_copy_dataset.md

Update the snippet copy dataset between histories to fit the new galaxy layout.

Fix snippet copy dataset

---

topics/transcriptomics/tutorials/ref-based/workflows/qc-mapping-counting-test.yml
topics/transcriptomics/tutorials/ref-based/workflows/qc-mapping-counting.ga

Update workflow that follows the tutorial to have steps in the same order as in the tutorial

Use subworkflows in Ref-based Transcriptomics GTN

---

topics/transcriptomics/tutorials/ref-based/workflows/qc-mapping-counting-test.yml

Fix typo in workflow test

---

topics/single-cell/tutorials/scrna-case_FilterPlotandExploreRStudio/preamble.md

Line edits: missing spaces and poor formatting w/in comment boxes

Update preamble.md in RStudio Seurat Filter, Plot, and Explore (small line edit changes)

---

bin/lint.rb
bin/news.rb

Remove updates from SC news

---

topics/admin/faqs/galaxy-update-22.05.md

finally getting around to it myself so documenting what i know/experience

add FAQ about upgrading through 22.05

---

topics/fair/tutorials/fair-clinical/tutorial.md
topics/fair/tutorials/fair-ena/tutorial.md

add authorship to FAIR lessons 

---

_includes/default-footer.html
_includes/pathway-card.html
bin/schema-learning-pathway.yaml
bin/validate-frontmatter.rb
learning-pathways/climate-learning.md
learning-pathways/io1.md
learning-pathways/io2.md
learning-pathways/io3.md
learning-pathways/io4.md
learning-pathways/io5.md
topics/contributing/tutorials/create-new-tutorial-content/faqs/remote-teaching-cyoa.md
topics/contributing/tutorials/create-new-tutorial-content/faqs/remote-teaching-faqs.md
topics/contributing/tutorials/create-new-tutorial-content/faqs/remote-teaching-selfstudy.md
topics/contributing/tutorials/create-new-tutorial-content/faqs/remote-teaching.md
topics/contributing/tutorials/create-new-tutorial-content/tutorial.md
topics/genome-annotation/tutorials/official-gene-set/tutorial.md
topics/teaching/tutorials/gallantries-async/helper-after.md
topics/teaching/tutorials/gallantries-async/helper-before.md
topics/teaching/tutorials/gallantries-async/helper-during.md
topics/teaching/tutorials/gallantries-async/instructor-after.md
topics/teaching/tutorials/gallantries-async/instructor-before.md
topics/teaching/tutorials/gallantries-async/instructor-during.md
topics/teaching/tutorials/gallantries-async/organizer-after.md
topics/teaching/tutorials/gallantries-async/organizer-before.md
topics/teaching/tutorials/gallantries-async/organizer-during.md
topics/teaching/tutorials/gallantries-async/tutorial.md
topics/teaching/tutorials/gallantries-coursebuilder/tutorial.md
topics/teaching/tutorials/running-workshop/tutorial.md
videos/index.md

Added some draft mode LPs (@nomadscientist we'll support draft learning pathways now) and a real quick n dirty asynchronous training handbook
fixes https://github.com/galaxyproject/training-material/issues/4419

Final updates for gallantries

---

assets/js/main.js

thanks for finding it @shiltemann, fixed the selector. not sure when it broke, but, maybe something we move out of JS eventually

fix selector for faq links

---

_plugins/jekyll-bundler.rb

add hash to js bundle

---

_layouts/base.html
_layouts/base_slides.html
_layouts/base_slides_ai4life.html
_layouts/tutorial_hands_on.html
_plugins/jekyll-mathjax.rb

I'm not sure this is 100% correct, but it seems to be correct in every instance i've tested.

Conditionally load mathjax

---

topics/single-cell/tutorials/bulk-music-2-preparescref/tutorial.md

Remove unnecessary label

---

.github/workflows/workflow-list.yaml
bin/workflows-fetch.rb
metadata/workflows.yml
workflows/list.html

And update the metadata file weekly.
Not sure if you have feelings about this @shiltemann, half a megabyte file, do we keep it as part of the build process, or bake it into the GTN. It takes about 1.25 minutes to collect the data. It would be fresher, but, it's already a slow deploy process.

Add workflowhub to cross .* workflow list page

---

topics/admin/tutorials/interactive-tools/tutorial.md
topics/data-science/tutorials/git-cli/tutorial.md
topics/data-science/tutorials/python-multiprocessing/tutorial.md
topics/data-science/tutorials/sql-basic/tutorial.md
topics/data-science/tutorials/sql-python/tutorial.md
topics/data-science/tutorials/sql-r/tutorial.md
topics/dev/tutorials/bioblend-api/tutorial.md
topics/galaxy-interface/tutorials/search/tutorial.md

to make them more amenable to extracting 'abstracts'.

fix some misc intros

---

topics/admin/tutorials/apptainer/tutorial.md

xref https://github.com/galaxyproject/training-material/issues/4524

Fix container resolvers in admin tutorial

---

topics/visualisation/tutorials/bad-graphs/slides.html

feels like a children's book author reading it, it's fantastic. Definitely want to keep that.

Hardcode voice for bad graphs, it is perfect

---

news/_posts/2023-11-20-workflow-search.md

Fix link to workflowhub in news post

---

topics/metagenomics/tutorials/mothur-miseq-sop/content.md

alternatively, just give links for 5+5 pairs

fix number of samples for mothur tutorial

---

CONTRIBUTORS.yaml
topics/metagenomics/tutorials/pathogen-detection-from-nanopore-foodborne-data/tutorial.md

Adding Affliation: uni-freiburg, to me in the contribution.yaml and to the foodborne training

Adding afflication

---

CONTRIBUTORS.yaml
topics/assembly/tutorials/ecoli_comparison/tutorial.md
topics/assembly/tutorials/unicycler-assembly/tutorial.md
topics/evolution/tutorials/mtb_phylogeny/tutorial.md
topics/evolution/tutorials/mtb_transmission/tutorial.md
topics/genome-annotation/tutorials/annotation-with-prokka/tutorial.md
topics/genome-annotation/tutorials/apollo/tutorial.md
topics/genome-annotation/tutorials/gene-centric/tutorial.md
topics/metagenomics/tutorials/beer-data-analysis/tutorial.md
topics/metagenomics/tutorials/general-tutorial/tutorial.md
topics/metagenomics/tutorials/metagenomics-assembly/tutorial.md
topics/metagenomics/tutorials/metatranscriptomics-short/tutorial.md
topics/metagenomics/tutorials/metatranscriptomics/tutorial.md
topics/metagenomics/tutorials/mothur-miseq-sop-short/tutorial.md
topics/metagenomics/tutorials/mothur-miseq-sop/tutorial.md
topics/metagenomics/tutorials/pathogen-detection-from-nanopore-foodborne-data/tutorial.md
topics/proteomics/tutorials/metaproteomics/tutorial.md
topics/proteomics/tutorials/metaquantome-data-creation/tutorial.md
topics/proteomics/tutorials/metaquantome-function/tutorial.md
topics/proteomics/tutorials/metaquantome-taxonomy/tutorial.md
topics/variant-analysis/tutorials/microbial-variants/tutorial.md
topics/variant-analysis/tutorials/non-dip/tutorial.md
topics/variant-analysis/tutorials/tb-variant-analysis/tutorial.md

Adding microgalaxy tag to the Microbiom training materials, so we can add then in the microgalaxy webserver
I have also added myself as a contributor to the Metatranscriptomics training material, as edited the training in PR #2675 and forgot to add myseld :D

Adding MicroGalaxy tag to Microbiom training materials, so we can add then in the microgalaxy webserver

---

faqs/galaxy/analysis_getting_help.md

We often get very vague questions asking for help with analysis, maybe an FAQ about how to ask good questions to point to will be useful?

Add FAQ about how to ask for help with your analysis

---

topics/metagenomics/tutorials/nanopore-16S-metagenomics/tutorial.md
topics/metagenomics/tutorials/plasmid-metagenomics-nanopore/tutorial.md
topics/metagenomics/tutorials/taxonomic-profiling/tutorial.md

missing Microgalaxy tag in 3 metagenomics training materials :) 
Thank you

more microgalaxy tags to metagenomics training materials

---

topics/single-cell/tutorials/scrna-case-jupyter_basic-pipeline/tutorial.md
topics/single-cell/tutorials/scrna-case_alevin-combine-datasets/tutorial.md

Tiny - final tag and fix snippet rendering

---

topics/dev/tutorials/interactive-tools/tutorial.md

Depends on https://github.com/Lain-inrae/geoc-gxit/pull/3 merge.
Update interactive tool development docs to run Shiny app with `shiny-server`, as this prevents websocket timeout when run as a GxIT.

Update dev GxITs to run with shiny-server

---

.github/workflows/ci-main.yml
news/_posts/2023-12-20-matrix-bots.md

I don't know if there's already been a post about the GTN bot -- if so, I will happily reference it here.

Add News/Event: helper bots event

---

CONTRIBUTORS.yaml
learning-pathways/genome-annotation-eukaryote.md
learning-pathways/genome-annotation-prokaryote.md
topics/genome-annotation/tutorials/apollo-euk/tutorial.md
topics/genome-annotation/tutorials/apollo/tutorial.md
topics/genome-annotation/tutorials/funannotate/tutorial.md
topics/genome-annotation/tutorials/functional/tutorial.md
topics/genome-annotation/tutorials/repeatmasker/tutorial.md

Preparing for ESG mid-project review, we'd like to list annotation stuff on https://training.galaxyproject.org/training-material/hall-of-fame/eurosciencegateway/

Add eurosciencegateway affiliation to some GGA stuff

---

.github/workflows/ci.yml
faqs/gtn/gtn_stats.md
feedback.md
learning-pathways/index.md
search2.html
stats/index.md

fix site.pages into meta descriptions

---

assets/css/main.scss

Ports some of the missing SCSS variables from #3876 to CSS variables, allowing them to be easily adjusted by themes.

Port more SCSS variables to CSS variables

---

CONTRIBUTORS.yaml

Update bebatut info

---

learning-pathways/data-driven-biology.md

A simple addition of two bash tutorials to gnmx learning pathway.

Added bash to gnmx leaning pathway

---

topics/single-cell/tutorials/scrna-case_trajectories/tutorial.bib
topics/single-cell/tutorials/scrna-case_trajectories/tutorial.md

These are some suggested changes based on testing this tutorial: https://training.galaxyproject.org/training-material/topics/single-cell/tutorials/scrna-case_trajectories/tutorial.html#conclusion
It's an awesome tutorial, great work!

Trajectories test feedback

---

CONTRIBUTORS.yaml

@nomadscientist for the future. Once we start auto-posting news, it'll let us ping you when you wrote it :)

mastodon links

---

CONTRIBUTORS.yaml

fix affiliation

---

CONTRIBUTORS.yaml

adding uni-freiburg affi

---

topics/ecology/tutorials/biodiversity-data-exploration/tutorial.md

Update tutorial.md add pndb funding

---

assets/css/main.scss

Please add the hacktoberfest label. It would be great

Added for navbar for GalaxyFold

---

topics/ecology/tutorials/obisindicators/tutorial.md

Update of the tutorial. Added the possibility to retrieve data with a new Galaxy tool.

New obisindicators version

---

CONTRIBUTORS.yaml
_includes/contributor-list.html
_layouts/contributor_index.html
_plugins/gtn.rb
bin/schema-contributors.yaml
learning-pathways/data-driven-biology.md

@bgruening fyi, you can annotate these now.

Add support for former_affiliations

---

.github/workflows/google-form.rb
bin/google-form-news.rb
bin/schema-news.yaml
faqs/gtn/gtn_news_create_post.md
news/_posts/2024-01-29-simplified-gtn-news-submission-via-google-form.md

it's "good enough", though of course linting *must* pass for these branches to be merged. Based on @nomadscientist's feedback, thanks so much for the suggestion of how we can make this process easier!

Implement GTN News posting via Google Form

---

CONTRIBUTORS.yaml

Hello, I opened this PR to correct my speudo on Git. 
Have a nice day.

git name error

---

_layouts/base.html

@jennaj or @martenson or @nomadscientist  if one of y'all can merge this, then we can test it live :)

Testing oembeds

---

topics/data-science/tutorials/gnmx-lecture3/tutorial.md

Added zenodo data and most explanations

cleaned up practical part

---

topics/statistics/tutorials/RNN/tutorial.md

Minor clarifications and consistency improvements for the ML RNN tutorial

---

learning-pathways/amr-gene-detection.md

- Add annotation module
- Add description for AMR gene module

Update AMR gene detection pathway

---

_plugins/jekyll-topic-filter.rb

Add mod_date/pub_date to api responses

---

topics/proteomics/tutorials/clinical-mp-3-verification/tutorial.md

the number was wrong, so I corrected it!

renamed verification tutorial

---

learning-pathways/data-driven-biology.md
topics/data-science/tutorials/gnmx-lecture1/tutorial.md
topics/data-science/tutorials/gnmx-lecture2/tutorial.md
topics/data-science/tutorials/gnmx-lecture3/tutorial.md
topics/data-science/tutorials/gnmx-lecture4/tutorial.md
topics/data-science/tutorials/gnmx-lecture5/tutorial.md
topics/data-science/tutorials/gnmx-lecture6/tutorial.md

adding pandas lecture

---

CONTRIBUTORS.yaml

Credit Dominique PElletier contribution

Update CONTRIBUTORS.yaml add Dominique Pelletier

---

CONTRIBUTORS.yaml

Hello ! Pleased to meet you, 
The purpose of this pull-request is to add my name to the list of contributors to the Galaxy project. This is a project in which I am likely to be involved as part of my work as a biodiversity metadata engineer at the [national biodiversity data centre ](https://www.pndb.fr/) (PatriNat - MNHN Paris), where Yvan le Bras, who is part of this git project, is one of my work colleagues. 
I would like to thank you for your time and wish you a pleasant day, 
Thibaud

Add ThibaudGlinez as contributor

---

topics/ecology/tutorials/PAMPA-toolsuite-tutorial/tutorial.md

Update tutorial.md add dominique contribution

---

topics/ecology/tutorials/MetaShARK_tutorial/tutorial.md

Update tutorial.md modify images links

---

topics/ecology/tutorials/MetaShARK_tutorial/tutorial.md

Update tutorial.md try to make hyperlink and bold work

---

bin/schema-tutorial.yaml
topics/assembly/tutorials/chloroplast-assembly/tutorial.md
topics/assembly/tutorials/largegenome/tutorial.md
topics/computational-chemistry/tutorials/htmd-analysis/tutorial.md
topics/computational-chemistry/tutorials/zauberkugel/tutorial.md
topics/ecology/tutorials/Obitools-metabarcoding/tutorial.md
topics/ecology/tutorials/biodiversity-data-exploration/tutorial.md
topics/ecology/tutorials/regionalGAM/tutorial.md
topics/galaxy-interface/tutorials/galaxy-intro-jupyter/tutorial.md
topics/imaging/tutorials/object-tracking-using-cell-profiler/tutorial.md
topics/introduction/tutorials/galaxy-intro-101-everyone/tutorial.md
topics/introduction/tutorials/galaxy-reproduce/tutorial.md
topics/proteomics/tutorials/encyclopedia/tutorial.md
topics/sequence-analysis/tutorials/Manage_AB1_Sanger/tutorial.md
topics/statistics/tutorials/age-prediction-with-ml/tutorial.md
topics/statistics/tutorials/classification_machinelearning/tutorial.md
topics/statistics/tutorials/classification_regression/tutorial.md
topics/statistics/tutorials/intro_deep_learning/tutorial.md
topics/statistics/tutorials/machinelearning/tutorial.md
topics/statistics/tutorials/regression_machinelearning/tutorial.md
topics/statistics/tutorials/text-mining_simtext/tutorial.md
topics/transcriptomics/tutorials/de-novo/tutorial.md
topics/transcriptomics/tutorials/goenrichment/tutorial.md

- remove unnecessary tracking hash
- ensure https
- standardise which formats of urls + schema

restrict zenodo link, cleanup

---

learning-pathways/building_tutorials.md

These are the materials I give my interns when they go to build their tutorials in Galaxy. Seemed like we should make a learning pathway!

New learning pathway - building training material in Galaxy

---

topics/microbiome/tutorials/metagenomics-assembly/tutorial.md

This PR adds EDAM topic and operation terms to the tutorial

Add EDAM terms for metagenomics assembly tutorial

---

topics/microbiome/tutorials/pathogen-detection-from-nanopore-foodborne-data/tutorial.md

Adding EDAM topics to the training material

Update tutorial.md to add EDAM topics

---

topics/microbiome/tutorials/mothur-miseq-sop-short/tutorial.md
topics/microbiome/tutorials/mothur-miseq-sop/tutorial.md

- mothur is super outdated, seems not updated anymore and creates lots of problems
- unfurtunatelly we have an excellent tutorial and people keep using it
- so lets at least put it on the end of the list
Was also wondering if we could/should add more structure to this topic. In particular I think it might be good to differentiate between amplicon and (real) metagenomics. Maybe by subtopics or just tags?
3. Check that your …

move mothur tutorials to the end

---

_includes/resource-handson.html
_includes/resource-slides.html

google moved stuff to a separate domain (smart)

fix translation links, dropdown

---

topics/microbiome/tutorials/beer-data-analysis/tutorial.md

Update tutorial.md to include EDAM topics microbiome Beer data analysis tutorial

---

topics/microbiome/tutorials/metatranscriptomics-short/tutorial.md

Update tutorial.md to include EDAM topics metatransciptimics tutorial

---

topics/microbiome/tutorials/mothur-miseq-sop-short/tutorial.md

Adding EDAM topics to mothur miseq sop short tutorial

---

topics/microbiome/tutorials/taxonomic-profiling/tutorial.md

Adding to include EDAM topics to the Microbiome Taxonomy profiling Tutorial

---

topics/microbiome/tutorials/plasmid-metagenomics-nanopore/tutorial.md

Adding EDAM topics for Plasmid metagenomics nanopore tutorial

---

topics/microbiome/tutorials/mothur-miseq-sop/tutorial.md

Adding to include EDAM topics to mothur miseq sop tutorial in microbiome

---

topics/microbiome/tutorials/general-tutorial/tutorial.md

Update tutorial.md To include EDAM topics microbiome General Tutorial

---

topics/microbiome/metadata.yaml
topics/microbiome/tutorials/beer-data-analysis/tutorial.md
topics/microbiome/tutorials/general-tutorial/tutorial.md
topics/microbiome/tutorials/metagenomics-assembly/tutorial.md
topics/microbiome/tutorials/metagenomics-binning/tutorial.md
topics/microbiome/tutorials/metatranscriptomics-short/tutorial.md
topics/microbiome/tutorials/metatranscriptomics/tutorial.md
topics/microbiome/tutorials/mothur-miseq-sop-short/tutorial.md
topics/microbiome/tutorials/mothur-miseq-sop/tutorial.md
topics/microbiome/tutorials/nanopore-16S-metagenomics/tutorial.md
topics/microbiome/tutorials/pathogen-detection-from-nanopore-foodborne-data/tutorial.md
topics/microbiome/tutorials/plasmid-metagenomics-nanopore/tutorial.md
topics/microbiome/tutorials/qiime2-cancer-microbiome-intervention/tutorial.md
topics/microbiome/tutorials/taxonomic-profiling/tutorial.md

Add subtopics to microbial catecory

---

topics/microbiome/tutorials/qiime2-cancer-microbiome-intervention/tutorial.md
topics/microbiome/tutorials/qiime2-moving-pictures/tutorial.md

Not sure if/how we can change the interface to Galaxy (it defaults to CLI).
Can/want we to add a link to https://youtube.com/playlist?list=PLbVDKwGpb3XmvnTrU40zHRT7NZWWVNUpt (see https://docs.qiime2.org/2024.2/jupyter-book-tutorials/)
- Then the automated …

add another (external) qiime2 tutorial

---

topics/microbiome/tutorials/metagenomics-binning/tutorial.md

Adding EDAM topics to metagenomics-binning tutorial

---

topics/proteomics/tutorials/metaquantome-data-creation/tutorial.md

Adding EDAM topics to proteomics metaquantome data creation tutorial

---

topics/microbiome/tutorials/qiime2-cancer-microbiome-intervention/tutorial.md

Adding EDAM topics for qiime2 caner microbiome intervention tutorial

---

topics/variant-analysis/tutorials/tb-variant-analysis/tutorial.md

Adding EDAM topics to tb variants analysis tutorial

---

topics/variant-analysis/tutorials/microbial-variants/tutorial.md

Adding EDAM topics microbial variants tutorial

---

topics/variant-analysis/tutorials/non-dip/tutorial.md

Adding EDAM topics non-dip variant-analysis

---

topics/proteomics/tutorials/metaquantome-function/tutorial.md

Adding EDAM topics metaquantome function proteomics tutorial

---

topics/proteomics/tutorials/metaproteomics/tutorial.md

Adding EDAM topics metaproteomics tutorial

---

topics/proteomics/tutorials/metaquantome-taxonomy/tutorial.md

Adding EDAM topics to metaquantome taxonomy tutorial

---

topics/genome-annotation/tutorials/gene-centric/tutorial.md

Adding EDAM topics to genome annotation gene centric tutorial

---

bin/check-url-persistence.sh
news/_posts/2024-03-18-url-persistence.md
topics/admin/tutorials/upgrading/tutorial.md

feel free to make suggestions to make this clearer for end-users.
xref https://github.com/galaxyproject/training-material/pull/4774

Add a news post bragging about our URL persistence

---

topics/ecology/tutorials/obisindicators/tutorial.md
topics/ecology/tutorials/obisindicators/workflows/Obis-indicators.ga

Small update to fill in correctly the Advanced cut tool according to its new version.

update advanced cut tool

---

CONTRIBUTORS.yaml

I have added myself as a contributor as I wish to create a PR to update an existing tutorial in the Single Cell training materials
I am an Intern with the Open University UK working under Wendi Bacon
Thanks!

Add Mehgan-E as contributor

---

faqs/galaxy/datasets_job_status.md

changes
* Reorganized content to be in the order of usual processing.
* Linked in some other FAQs

Cleanup datasets_job_status.md

---

faqs/gtn/gtn_stats.md
stats/index.md

we should redo the colours some other day.

add LPs to stats page

---

_config.yml
faqs/galaxy/analysis_troubleshooting.md
topics/single-cell/faqs/single_cell_omics.md
topics/single-cell/index.md
topics/single-cell/tutorials/scrna-case_alevin-combine-datasets/tutorial.md
topics/single-cell/tutorials/scrna-case_alevin/tutorial.md
topics/single-cell/tutorials/scrna-case_basic-pipeline/tutorial.md
topics/single-cell/tutorials/scrna-case_trajectories/tutorial.md

I've added single-cell matrix group optionality to the troubleshooting FAQ and then pushed it into a bunch of tutorials and our general single cell site

Troubleshooting faq

---

CONTRIBUTORS.yaml
topics/ecology/tutorials/bacterial-isolate-species-contamination-checking/tutorial.md
topics/ecology/tutorials/bacterial-isolate-species-contamination-checking/workflows/Checking-expected-species-and-contamination-in-bacterial-isolate.ga

Hello, 
i changed:
- "What are the kindgoms found?" to "What are the domains found?"
- "Centrifuge" to "Recentrifuge"
Thanks

Checking expected species and contamination in bacterial isolate: Fix spelling errors

---

faqs/galaxy/analysis_differential_expression_help.md

Minor reorganization of formatting values.
Linked in Bioconductor support forum for troubleshooting. 
New: added in a link to a search _against_ the GTN (a test, not sure if this will work..)

Update analysis_differential_expression_help.md new link type and minor reorg

---

CONTRIBUTORS.yaml

Here we are adding ELIXIR affiliations to a lot of ELIXIR members and also a few other affies that I could spot.

Add ELIXIR and a few other affiliations

---

topics/fair/tutorials/fair-intro/tutorial.md

fix fair pointers link FAIR in a nutshell tutorial (suplementary)

fix fair pointers link FAIR in a nutshell tutorial (suplementary)

---

faqs/galaxy/collections_build_list.md

Hi,
I wanted to use the snippet in a tutorial I'm making, but I got a few questions:
Is it even possible to use the include.name in this file?
The last picture "creating a simple collection", does it have a meaning? It looks a bit much at the end of this short explanation.
Thank you!

Change create list to create collection and add include.name in snippet link

---

Makefile

Add quick gitpod serve

---

CONTRIBUTORS.yaml
news/_posts/2024-05-15-galaxy-europe-freiburg-job.md

Initial setup of job posting for Systems Engineer / DevOps Engineer at Freiburg team, May 2024

Create Freiburg Team job posting May 2024

---

.github/workflows/cron-commit-cache.yml
.github/workflows/update-libraries.yaml

fixes https://github.com/galaxyproject/training-material/pull/4954

Fix a couple actions

---

_includes/slides-youtube-selector.html
assets/css/main.scss

also use new tab styling from events page.

Fix slide/youtube selector when included multiple times

---

_layouts/event.html
events/2023-10-02-mtb-ngs.html

add slack version, schedule version

---

topics/genome-annotation/tutorials/introduction/slides.html

Hello, I'm opening this MR to add new information to these slides: addition of Helixer, compleasm and OMArk.
Thank you!  Have a nice day!

Add new informations: Helixer, compleasm and OMArk

---

_includes/event-table.html
_layouts/tutorial_hands_on.html
_plugins/gtn.rb
_plugins/util.rb

Link to events from a tutorial that's included in those events

---

_layouts/event.html
events/2024-06-18-FAIR-data-management.md
events/index.md
faqs/gtn/gtn_event_create.md

I am adding the FAIR Training event but I can't see it in the event list once I test the website

add FAIR training event

---

_includes/news-card.html
news/_posts/2024-06-04-tool-form-integration.md

fixes the latest news item and hides already-on-hub tag

Fix news item

---

events/2024-06-10-mtb-ngs.html

fix a broken link and some formatting

MTB event: Fix link

---

ORGANISATIONS.yaml
bin/filter-pyolite-safe
bin/prepare_feedback.rb
events/2024-06-10-mtb-ngs.html

based on feedback from @dbrites

Final tweaks to mTB course

---

topics/single-cell/faqs/user_community_join.md

Add SPOC to the Talk to other users FAQ

Add SPOC to the Talk to other users FAQ

---

topics/microbiome/tutorials/dada-16S/tutorial.md

Change 2nd 'Taxonomy table' to 'Sample table'

Edit dada-16S tutorial.md

---

_includes/youtube.html
assets/css/main.scss
news/_posts/2021-06-26-tutorial-volcanoplot-r.md
topics/climate/tutorials/climate-101/tutorial.md
topics/galaxy-interface/tutorials/collections/tutorial.md
topics/introduction/tutorials/galaxy-intro-ngs-data-managment/tutorial.md
topics/introduction/tutorials/vsi_qc/tutorial.md
topics/teaching/tutorials/gtn-for-instructors/slides.html
topics/teaching/tutorials/learner_participation_engagement/tutorial.md

to use our youtube snippet so we can ensure that:
1. the layout is properly controlled everywhere
2. we're setting all of the no-cookie/restrictions on youtube where it is embedded.

fix remaining youtube snippets

---

_plugins/api.rb

somehow missed when i re-arragend in the other pr

fix api build

---

feed-html.xslt.xml

same as the other one but it renders `content` instead of `summary` (and does so rendering the actual nodes which is important for html contents.)

missing feed stylesheet

---

topics/microbiome/tutorials/pathogen-detection-from-nanopore-foodborne-data/tutorial.md
topics/microbiome/tutorials/pathogen-detection-from-nanopore-foodborne-data/workflows/allele_based_pathogen_identification-test.yml
topics/microbiome/tutorials/pathogen-detection-from-nanopore-foodborne-data/workflows/allele_based_pathogen_identification.ga

Correcting some training explanations in the preprocessing workflow, and adding a missing step in the long version of the training
Thanks @paulzierep for spotting them :) 
Thanks,
Engy

Pathogen detection from (direct Nanopore) sequencing data using Galaxy - Foodborne Edition

---

topics/dev/tutorials/writing_tests/api1.md
topics/dev/tutorials/writing_tests/api2.md
topics/dev/tutorials/writing_tests/api3.md
topics/dev/tutorials/writing_tests/api5.md
topics/dev/tutorials/writing_tests/tutorial.md
topics/dev/tutorials/writing_tests/unit15.md
topics/dev/tutorials/writing_tests/unit16.md

Update testing tutorial for GCC-24

---

topics/dev/tutorials/writing_tests/unit6.md
topics/dev/tutorials/writing_tests/unit7.md

GCC-24: testing tutorial update

---

topics/ecology/tutorials/obisindicators/tutorial.md

1. The c[...] expression comes from the workflow, but cannot be used when launching Advanced cut individually.
2. The column numbers were outdated (and different in the 2 scenarios). As these seem to be changing n the source data model, better not mention them.

Fixed columns selection

---

topics/ecology/metadata.yaml
topics/ecology/tutorials/MetaShARK_tutorial/tutorial.md
topics/ecology/tutorials/Metashrimps_tutorial/tutorial.md
topics/ecology/tutorials/Obitools-metabarcoding/tutorial.md
topics/ecology/tutorials/PAMPA-toolsuite-tutorial/tutorial.md
topics/ecology/tutorials/QGIS_Web_Feature_Services/tutorial.md
topics/ecology/tutorials/bacterial-isolate-species-contamination-checking/tutorial.md
topics/ecology/tutorials/biodiversity-data-exploration/tutorial.md
topics/ecology/tutorials/champs-blocs/tutorial.md
topics/ecology/tutorials/de-novo-rad-seq/tutorial.md
topics/ecology/tutorials/gbif_cleaning/tutorial.md
topics/ecology/tutorials/genetic-map-rad-seq/tutorial.md
topics/ecology/tutorials/ndvi_openeo/tutorial.md
topics/ecology/tutorials/obisindicators/tutorial.md
topics/ecology/tutorials/panoply_ebv/tutorial.md
topics/ecology/tutorials/phylogeny-data-prep/tutorial.md
topics/ecology/tutorials/ref-based-rad-seq/tutorial.md
topics/ecology/tutorials/regionalGAM/tutorial.md
topics/ecology/tutorials/remote-sensing/tutorial.md
topics/ecology/tutorials/species-distribution-modeling/tutorial.md
topics/ecology/tutorials/x-array-map-plot/tutorial.md

Add subtopics

---

CONTRIBUTORS.yaml
_includes/help.html

Changed Gittr to Matrix.

---

topics/climate/tutorials/ocean-variables/tutorial.md
topics/ecology/tutorials/QGIS_Web_Feature_Services/tutorial.md
topics/ecology/tutorials/ndvi_openeo/tutorial.md

just some small fixes that we saw during the trainings

Small fixes 

---

assets/images/workflowhub-icon.svg

I'm not sure if the image was ever added or deleted recently, but it causes the build to fail.
Maybe this one is related: https://github.com/galaxyproject/training-material/pull/5082/files

adds the missing workflow-hub icon

---

topics/dev/tutorials/core-contributing/tutorial.md

Script was deleted in [PR #14537](https://github.com/galaxyproject/galaxy/pull/14537/). Got verbal agreement the mention of it should be removed (and .e.g. not replaced) by @jdavcs himself.

Deleted mention of create_db.py (deleted script)

---

topics/dev/tutorials/visualization-charts/tutorial.md

Updated tutorial especially to reflect use for Developers

---

_layouts/tutorial_hands_on.html

As I thought the feedback box was broken (was just a guide that hadn't received feedback yet), I added an 'if-else' statement that will display placeholder text that incentivizes people to give feedback through the forms on that page ('be the first one to fill in the form').  
I left a comment to debug the feedback amount as I was very lost on how to find/change the variable behind the feedback amount. Delete if not desired.

Added placeholder text when no feedback has been recieved yet.

---

_includes/tutorial_list.html
_layouts/event.html
_plugins/jekyll-jsonld.rb
assets/js/anchor.min.js
search2.html
topics/contributing/tutorials/create-new-tutorial-content/tutorial.md
workflows/embed.html

- fixes #5096 
- fixes #5095 
- fixes #5077 
- fixes @abueg's privately reported issue with documentation around using new dockstore snippet (as all the vgp tutorials are being updated to use our new snippet! :tada::tada:)
- fixes 'external resources' in tess, will simultaneously fix the remaining 'bad url' reports i receive from tess.

misc small fixes

---

_includes/calendar-buttons.html
_includes/event-table.html
_layouts/event.html
_plugins/gtn.rb
_plugins/jekyll-jsonld.rb
events/2023-04-17-gat-gent.md
faqs/gtn/gtn_event_create.md

make events a bit more robust to missing metadata.
Even if required metadata is missing, the website should still build successfully now

[Events] allow missing metadata

---

.github/workflows/google-form-events.yml
.github/workflows/google-form-faqs.yml
bin/google-form-event.rb

Add support for Google form for (external) events

Event Google form

---

_layouts/recordings.html
bin/google-form-event.rb
events/index.md
faqs/gtn/gtn_event_create.md
faqs/gtn/recordings_add.md
faqs/gtn/recordings_create.md
news/_posts/2024-06-14-gtn-video-library.md

Add a link to the Google form for submitting events to the FAQ, and fix date formatting

Event form updates

---

_includes/calendar-buttons.html

that is currently breaking events layout. Thanks @teresa-m for reporting!

Fix location formatting

---

topics/dev/tutorials/visualization-charts/tutorial.md

Apologies- had some minor design issues around the Comment box from the [prior PR](https://github.com/galaxyproject/training-material/pull/5098/files). Hopefully, this PR change works (btw tried following the [repo dev setup instructions](https://training.galaxyproject.org/training-material/topics/admin/tutorials/ansible-galaxy/tutorial.html#installing-galaxy) but ran into `find: _site/training-material: No such file or directory` error).

Minor formatting change to make yellow-outline Comment box appear in UI

---

CONTRIBUTORS.yaml

Hello! I would like to have my name in the contributors file (and pages on the GTN website) updated to reflect my correct name. 
Is there anything else I need to do to have these changes propogated to the GTN contributors web page? 
Thanks!

Correct my name in contributors.yaml

---

topics/community/faqs/governance_gcb.md

Update governance FAQ typos

---

CONTRIBUTORS.yaml

I got promoted last year, woo!

Update my job title

---

CONTRIBUTORS.yaml
news/_posts/2024-07-12-tutorial-snapatac-standard.md

Blog post announcing the new single cell ATAC-seq analysis tutorial with SnapATAC2. 
(and added ORCID to contributors.yaml)

new-tutorial-announcement-snapatac2-standard

---

_layouts/event.html
_plugins/feeds.rb
feeds/index.md

like the digests, but, cleaned up a bit to work better with our integrations. (many things don't like long summaries / html content, so, we'll split them because we like our nicely formatted categories of items.)

Itemised feed

---

_includes/default-footer.html
_plugins/feeds.rb
_plugins/gtn/mod.rb
feed-widget.xslt.xml
feeds/index.md

- fixes dark mode rendering
- adds date posted to widget
- plausible for stats

final feed widget improvements

---

news/_posts/2024-07-08-4th-mycobamycobacterium-tuberculosis-complex-ngs-made-easy.md

Correct title for Mycobacterium tuberculosis NGS made easy blog post

---

topics/transcriptomics/tutorials/ref-based/tutorial.md

Change of `(Chromosome 4 between 540 kb to 560 kb)` to `(Chromosome 3 between 9,445kb to 9,448 kb)`

Ref-based RNA-seq: updated tutorial.md before training

---

topics/microbiome/tutorials/diversity/tutorial.md

Its still needs a update before usable, so set to draft for now

Set diversity toturial to draft until finalized

---

topics/genome-annotation/tutorials/bacterial-genome-annotation/tutorial.md
topics/genome-annotation/tutorials/bacterial-genome-annotation/workflows/Bacterial-Genome-Annotation.ga

In this PR, the tools used in the Bacterial Genome Annotation tutorial are updated

[Bacterial Genome Annotation] Update tool versions

---

topics/microbiome/tutorials/diversity/tutorial.md

This should be the place to put it

Add subtopic for diversity toturial

---

topics/variant-analysis/tutorials/beaconise_1000hg/tutorial.md

Minor correction to the tutorial

fix typing error

---

bin/google-form-recordings.rb

some optimizations for the recordings import

improve recordings metadata yaml formatting

---

CONTRIBUTORS.yaml
topics/introduction/tutorials/data-manipulation-olympics/tutorial.md

This pull request enhances the **Filtering** section of the **Data Manipulation Olympics** tutorial in the Galaxy Training Network (GTN) by adding a new hands-on exercise.
- **Added Hands-on Exercise**:
- Demonstrates the use of Python-based filtering expressions in Galaxy.
- Includes practical examples such as:
- Filtering based on substring occurrence.
- Filtering based on whether values start or end with specific characters.
- Filtering based on counting occurrences of a substring within columns.
This addition aims to provide users with a more comprehensive understanding of advanced filtering techniques in Galaxy.

Add Filtering Hands-on to Data Manipulation Olympics.md

---

topics/climate/tutorials/ocean-variables/tutorial.md
topics/climate/tutorials/ocean-variables/workflows/main_workflow-tests.yml
topics/climate/tutorials/ocean-variables/workflows/main_workflow.ga

Hello hello all !!
New version of the tutorial. The main change is that I allow the user to choose which workflow he wants to run the one with only interactive tools or the one with both interactive and batch tools (thus, I also changed the main-workflow.ga).
Thus, I added 2 "Choose your own workflow" boxes and locally it seems to me that he first "Choose your own workflow" works fine but then the others inside does not seem to work. 
Do you know why @hexylena @shiltemann  ?
Beside, for this new version I added a new dataset. I saw that you created a file to say the location of the data. Should I add the new dataset there too ?
Thank you !!

Ocean variables big update

---

topics/single-cell/index.md

Update matrix link

---

CONTRIBUTORS.yaml

Adding Natalie WA to GTN contributors list

---

CONTRIBUTORS.yaml
topics/single-cell/tutorials/scrna-scanpy-pbmc3k/tutorial.md

- pbmc3k tutorial: added a question about gene annotations other than Mitochondrial genes
- Added myself as a contributor

Add a new question about gene annotations to PBMC3k tutorial

---

_layouts/event.html
bin/schema-event.yaml
bin/validate-other.rb
events/2024-04-01-example-event.md
events/2024-07-22-freiburg-july.md
events/galaxy-academy-2024.md
learning-pathways/fair-training.md

Events framework updates

---

_layouts/event.html
assets/css/main.scss
events/galaxy-academy-2024.md

Used subsection for the monday program rather than putting the headers in the table, what do you think @teresa-m ?

Academy tweaks

---

events/2024-10-17-biont-python.md

Adding the python workshop in October as an external event with the link to the event page.

added python workshop

---

CONTRIBUTORS.yaml

Related to this issue #5176 
Also, side note: I see this error on this PR `At least 1 approving review is required by reviewers with write access.` However, I do not seem to have permission to even add Reviewers (video below).
[Cc](https://github.com/galaxyproject/training-material/pull/5176#discussion_r1722013619): @teresa-m

Updating my contact info in Contributors section

---

_layouts/event.html
events/galaxy-academy-2024.md

Update the GTA event page:
1. Update of the introduction program
2. Add registration link

registration link and intro program update

---

events/tracks/gta2024-assembly.md
events/tracks/gta2024-bacterial-genomeics.md
events/tracks/gta2024-single-cell.md

Added @SaimMomin12 @bgruening to the assembly track as instructors
Added @EngyNasr to the Bacterial genome as an instructor
Added @dianichj to Single Cell as an instructor

[Event] updated instructor lists

---

topics/fair/tutorials/ro-crate-in-galaxy/tutorial.md

Hi !
After working a bit on ro-crate I'm making another update of this to where I had problems my self :) 
Just adding how to enable ro-crate locally.
Thanks !

add enabling rocrate locally

---

CONTRIBUTORS.yaml

Nikos Pechlivanis, `npechl`, contribution to microGalaxy technical paper

Update CONTRIBUTORS.yaml - contribution to microGalaxy technical paper

---

topics/genome-annotation/tutorials/lncrna/tutorial.md

Hello,  I'm opening this PR to update the version of the tools for the GTA.
Thank you, have a good day !

update version tools

---

topics/ecology/tutorials/MetaShARK_tutorial/tutorial.md

Update tutorial.md http => https metadatacenter cedar api

---

faqs/galaxy/analysis_regular_expressions.md

Add a couple of useful regex : 
- Conversion to lower and upper cases
- get whole match with `&`
- a couple useful examples for matching fasta files (I am not attached to it I can remove it if you think that is too specific)

Add tips to regular expression FAQ

---

topics/assembly/tutorials/general-introduction/tutorial.md

306 Contigs are built after running velvetg

Contigs built - Update tutorial.md

---

topics/single-cell/faqs/sc_version.md

This will help users debug a weird error message to check the tool version when doing the scRNA-seq tutorials using the EBI Scanpy tool suite

Create tool version FAQ to help debugging

---

topics/ecology/tutorials/marine_omics_bgc/tutorial.md

Update tutorial.md to put in "analysis" section

---

_plugins/jekyll-jsonld.rb
topics/teaching/tutorials/galaxy-admin-training/tutorial.md
topics/variant-analysis/tutorials/trio-analysis/tutorial.md
topics/visualisation/tutorials/circos-microbial/tutorial.md
topics/visualisation/tutorials/circos/tutorial.md
topics/visualisation/tutorials/jbrowse/tutorial.md

we should make level mandatory someday but, for now annotated a handful.

Fix bad link in circos, other minor 

---

topics/single-cell/tutorials/scrna-case_basic-pipeline/tutorial.md

I only changed the one in the header before, but forgot to change the link in the text

Updating input history link in text

---

topics/ecology/tutorials/Ecoregionalization_tutorial/tutorial.md

Update tutorial.md add analysis topic

---

topics/single-cell/tutorials/scrna-case_JUPYTER-trajectories/tutorial.md

A new version of Scanpy was released so no more need to change the location of fa2-modified
Also, added a back-up option to download input data using a link

match updated Scanpy fa2-modified, add an option to download input data

---

_layouts/event.html
_plugins/gtn.rb

issue reported by @teresa-m, linking to sections in the GTA program tab was not opening to the right tab, this should fix that

Fix linking to sections within tabs

---

.github/pull_request_template.md
.github/workflows/ci.yml

tiny tweaks to ci name and pr template

minor GitHub tweaks

---

topics/single-cell/tutorials/scrna-scanpy-pbmc3k/tutorial.md

- Scanpy tool names were changed in the latest Scanpy tool update. Corrected these tools names here.

correct the scanpy tool names in the tutorial

---

_layouts/event-track.html
events/galaxy-academy-2024.md
events/tracks/gta2024-assembly.md
events/tracks/gta2024-bacterial-genomics.md
events/tracks/gta2024-bycovid.md
events/tracks/gta2024-microbiome.md
events/tracks/gta2024-ml.md
events/tracks/gta2024-proteomics.md
events/tracks/gta2024-single-cell.md
events/tracks/gta2024-transcriptomics.md

I added Slack channels to the Program page.
@shiltemann: the links within the program tracks do not work. Could you have a look?

added Slack channels to the gta event page

---

_plugins/jekyll-jsonld.rb
_plugins/util.rb

all of our materials are e-learning, rather than simply 'material'. They're all available online, constantly, and have both interactive components and self-check points where the learner can be sure they are understanding the material and test their knowledge.
Thus we move from 'hands-on tutorial' to 'e-learning' so we can show up in the appropriate section of TeSS and learners looking for real hands on materials will be able to find us.

Move to e-learning learningResourceType

---

topics/data-science/tutorials/sql-advanced/tutorial.md

truly not sure how this got through. clearly a linting error 😭

broken box

---

topics/microbiome/tutorials/lotus2-identifying-fungi/tutorial.md

!!! DELETE THIS BEFORE SUBMITTING!!! It's just a checklist to help you :)
4. Not ready for review yet? Make it a **Draft** pull request
- Once you are done making changes, choose **Ready for Review**

tiny edits to LOTUS2

---

events/tracks/gta2024-bycovid.md

@teresa-m this provides more context and fixes the issue with linking to the video **and** the infectious diseases toolkit showcase page for the "automated SARS-CoV-2 genome surveillance system built around Galaxy".

BY-COVID track update

---

events/tracks/gta2024-microbiome.md

Update usegalaxy note and add pratik

Update microbiome track

---

_layouts/topic-maintainer.html
_plugins/gtn/supported.rb
_plugins/jekyll-environment_variables.rb
_plugins/jekyll-topic-filter.rb
topics/contributing/faqs/new-contributions.md
topics/contributing/faqs/why-prerequisites.md

Implement compat matrix on maintainer page

---

.github/pull_request_template.md
events/galaxy-academy-2024.md

GTA add intro video

---

topics/single-cell/tutorials/scrna-data-formats/slides.html

revert slides accidentally removed in https://github.com/galaxyproject/training-material/pull/5385
@teresa-m

restore slides removed by recordings bot

---

events/galaxy-academy-2024.md
events/tracks/gta2024-assembly.md

Added the daily icebreaker questions to the program
FYI @teresa-m @natalie-wa

[GTA2024] add icebreakers to program

---

events/galaxy-academy-2024.md

just adding a line of description about the format

GTA intro description

---

CONTRIBUTORS.yaml
faqs/galaxy/visualisations_igb.md

Added an FAQ for visualizing Galaxy History files in the Integrated Genome Browser.

Add IGB FAQ to the GTN

---

events/tracks/gta2024-assembly.md

- Replace the trainings "coming soon" with the right links

[GTA] Update links for the Assembly track

---

_layouts/tutorial_hands_on.html
assets/css/main.scss

Safer plausible handling

---

topics/sequence-analysis/tutorials/quality-contamination-control/tutorial.md

minor change - correct genus to family in solution

Update tutorial.md - bacterial genomics QC

---

topics/transcriptomics/tutorials/ref-based/tutorial.md

update deseq2 parameter setting

updated deseq2 paramter selection

---

topics/transcriptomics/tutorials/ref-based/tutorial.md

second hands-on box update deseq2 advanced parameter setting

Update ref based

---

CONTRIBUTORS.yaml

fix contributors yaml

---

topics/epigenetics/tutorials/ewas-suite/tutorial.bib
topics/epigenetics/tutorials/ewas-suite/tutorial.md

TODO: add additional reference paper to publication

update Infnum trainng

---

CONTRIBUTORS.yaml
_layouts/contributor_index.html

makes it far easier to collect stats for grant reporting.

plausible stats for materials contributed to by an individual/org/funder

---

topics/sequence-analysis/tutorials/quality-control/tutorial.md
topics/transcriptomics/tutorials/ref-based/tutorial.md
topics/transcriptomics/tutorials/ref-based/workflows/qc-mapping-counting-paired-and-single.ga
topics/transcriptomics/tutorials/ref-based/workflows/qc-mapping-counting.ga

Also bump cutadapt version in ref-based transcriptomics

Update to latest cutadapt interface in quality control

---

.github/workflows/social.yml
assets/branding/social/event.svg
assets/branding/social/faq.svg
assets/branding/social/learning-pathway.svg
assets/branding/social/news.svg
assets/branding/social/recording.svg
assets/branding/social/slides.svg
assets/branding/social/topic.svg
assets/branding/social/tutorial.svg
assets/branding/social/workflow.svg

maybe fixes social media cards

---

bin/ari-map.yml
topics/fair/tutorials/dataplant-arcs/slides.html

added some pronounciation maps and tweaked speaker notes

Optimize ARC slides for automatic video

---

topics/single-cell/faqs/single_cell_omics.md

It isn't formatting the links properly

Fix FAQ format

---

topics/imaging/tutorials/hela-screen-analysis/tutorial.md

The "HeLa screen analysis" tutorial received an update in #5499.
I had forgotten to push the last commit, which updates the last section of the tutorial.

Fix last section of the `hela-screen-analysis` tutorial

---

_layouts/contributor_index.html
_plugins/author-page.rb

Fixes https://github.com/galaxyproject/training-material/issues/5485

fixes faqs on contribs

---

bin/pdf2slides.py

in case @shiltemann ever needs this again

add wip pdf2slides script

---

topics/transcriptomics/tutorials/ref-based/tutorial.md

Currently there are 2 ways proposed:
- Select each count file for each category (I find it error prone)
- Use tags (this is not easy for new users as it requires to use regex)
I propose a third way where a collection is created and then identifiers are selected using patterns.

Add a third way to run DESeq2 in Ref-based tuto

---

.github/workflows/cron-commit-cache.yml
.github/workflows/google-form-events.yml
.github/workflows/google-form-faqs.yml
.github/workflows/google-form-news.yml
.github/workflows/google-form-recordings.yml
.github/workflows/shortlinks.yaml
.github/workflows/update-libraries.yaml

This pull request includes updates to several GitHub workflow files to enhance permissions and upgrade the `peter-evans/create-pull-request` action version from v3 to v7.

Update GitHub Actions workflows

---

.github/workflows/optimize-images.yml

This PR updates the image optimization workflow by:
- Adding write permissions for `contents` and `pull-requests` in the build job.
- Upgrading `peter-evans/create-pull-request` action from v3 to v7.

Update GitHub Actions Workflow for Image Optimization

---

.github/workflows/workflowhub.yml

This PR includes updates to the `workflowhub.yml` GitHub Actions workflow by:
- Added permissions for `contents` and `pull-requests`.
- Updated the `actions/checkout` action from version 2 to version 4.
- Updated the `peter-evans/create-pull-request` action from version 3 to version 7.

Update GitHub Actions Workflow for workflowhub

---

faqs/galaxy/analysis_reporting_issues.md
topics/admin/tutorials/upgrading/tutorial.md

Small PR - Commit https://github.com/galaxyproject/galaxy/commit/989fc135e1bac6d098a8fd68b8813e091051ddd9 renamed the security guide. This PR adjusts sources to changes.

Update security guide reference

---

topics/microbiome/tutorials/metagenomics-assembly/tutorial.md

Fix percentage

---

topics/assembly/tutorials/mrsa-nanopore/tutorial.md
topics/microbiome/tutorials/beer-data-analysis/tutorial.md

the branches did not work at all, thankfully i want to use illumina data so, it is not an issue for me now but
new linting i added in #5531  would have caught this
This tutorial would benefit significantly from tagging the datasets, rather than renaming them, but I don't have bandwidth for that currently.

Fix MRSA nanopore tutorial CYOA

---

_layouts/workflow-list.html

simplifies the page and looks a bit cleaner

use workflow listing to point to our new workflow pages

---

CONTRIBUTORS.yaml
assets/css/slides.scss
topics/sequence-analysis/tutorials/quality-control/slides.html

Update slides.html- Including ASCII code

---

topics/dev/tutorials/interactive-tools/tutorial.md

Hello it's me again !
I tried to update this tuto by adding some more info on how to develop applications on Galaxy (some more recent examples mainly)
Plus, I added the possibility to create to follow the tutorial to build a jupyterlab . I hope this make sense (I find it harder to update well than write from scratch)
Thanks you all for the review !!

Add jupyterlab stuff & other small updates

---

topics/contributing/tutorials/running-codespaces/tutorial.md

Forgot to add @teresa-m as contributor to the codespaces tutorial

Add teresa as contributor

---

topics/sequence-analysis/metadata.yaml
topics/sequence-analysis/tutorials/mapping/tutorial.md
topics/sequence-analysis/tutorials/quality-control/tutorial.md

Add subtopics to sequence analysis topic

---

topics/microbiome/tutorials/dada-16S/tutorial.md

- Change 'Hands on' with 'History creation'

 Edit dada-16S tutorial.md

---

topics/single-cell/tutorials/scrna-case_FilterPlotandExplore_SeuratTools/tutorial.md

[Fix failing deploy] Remove duplicate metadata

---

topics/ecology/tutorials/Metashrimps_tutorial/tutorial.md

Fix some typos

---

topics/admin/tutorials/monitoring/tutorial.md

Renamed the Telegraf plugin from `io` to `diskio`
Fixes #5601

update plugin name

---

_layouts/home.html
_layouts/topic.html
assets/css/main.scss
bin/schema-topic.yaml
topics/single-cell/metadata.yaml

Fixes https://github.com/galaxyproject/training-material/issues/5580 (mostly)

Improve single cell topic page

---

topics/single-cell/tutorials/scrna-raceid/data-library.yaml
topics/single-cell/tutorials/scrna-raceid/tutorial.md
topics/single-cell/tutorials/scrna-raceid/workflows/RaceID-Workflow-tests.yml
topics/single-cell/tutorials/scrna-raceid/workflows/RaceID-Workflow.ga
topics/single-cell/tutorials/scrna-raceid/workflows/index.md

first version of the wf test for this tutorial

add workflow test for single-cell raceid tutorial

---

topics/single-cell/tutorials/scrna-plant/tutorial.md
topics/single-cell/tutorials/scrna-plant/workflows/scRNA-Plant-Analysis-tests.yml
topics/single-cell/tutorials/scrna-plant/workflows/scRNA-Plant-Analysis.ga

- First version of WF tests for this tutorial
- added an archived example history

Add scrna-plant WF tests

---

topics/single-cell/tutorials/scrna-case_basic-pipeline/workflows/CS3_Filter,-Plot-and-Explore-Single-cell-RNA-seq-Data-tests.yml
topics/single-cell/tutorials/scrna-case_basic-pipeline/workflows/CS3_Filter,-Plot-and-Explore-Single-cell-RNA-seq-Data.ga

Add first version of WF tests for the old workflow

add WF tests for scrna basic pipeline

---

_includes/tutorial_list.html
events/2025-03-10-hts-workshop-freiburg.md

@teresa-m this should fix your issue for events on small screens:
I also updated the event to have a section per day instead of one big table, please check if it is ok for you:

Fix event program for small screens

---

events/2025-02-04-biont-software-best-practice.md

Adding the next BioNT event as an external event.

Biont software

---

topics/admin/tutorials/surf-research-cloud-galaxy/tutorial.md
topics/admin/tutorials/surf-research-cloud-pulsar/tutorial.md

missed it in review. 
put them both in the cloud subtopic, and both tagged with 'deploying'

small tweak to unify metadata on the two SURF tutorials

---

topics/community/faqs/governance_gcb_join.md

Add one line to better track membership
Should they also add something to their 'Contributor' list, you reckon? Membership of groups?

Add one line

---

news/_posts/2024-12-18-spoc.md

What we've learned is I am much better at reviewing text in the final render than in coding spaces/text editors

Typo_again

---

_includes/contributor-badge.html
_includes/news-card.html
assets/css/main.scss
news.md

use the same layout as learning pathways for the news index
We can tweak further later but already an improvement I think

News layout same as LP layout

---

topics/community/tutorials/community_content/tutorial.md

remove duplicate key

---

topics/community/tutorials/community_content/tutorial.md

It was too easy to get stuck in scrolling
Also seeing the final produce, @shiltemann put a lot of edits in so deserves authorship

Add borders

---

news/_posts/2024-12-19-community_page.md

To make it easier for people who read the news to find the pages

Add some links to community home pages to Wendi's news posts

---

CONTRIBUTORS.yaml

Update CONTRIBUTORS with my updated affiliations

---

bin/workflows-fetch.rb

Deploy was failing today because workflowhub was giving HTTP 500 errors, this fixes our script to not fail deploy in such cases.

Fix deploy

---

bin/google-form-event.rb

This broke when we got a submission with empty contributors field, this should fix that

Fix event google form processing

---

topics/fair/tutorials/data-management/tutorial.md

Update tutorial.md good link ?

---

.github/workflows/video.yml

latest will change soon, fix it to upcoming version

fix to upcoming version

---

README.md

thanks to @dadrasarmin for the suggestion

add link to codespaces tutorial to readme

---

topics/single-cell/metadata.yaml

It makes the buttons more similarly sized more frequently

Shorten text in button

---

faqs/galaxy/datasets_import_from_data_library.md

An addition of 'and' in the tutorial https://training.galaxyproject.org/training-material/topics/introduction/tutorials/galaxy-intro-101-everyone/tutorial.html

Grammar edit

---

.github/workflows/blueskyfeedbot.yml

This will automatically create a post on GTN's Bluesky account for every news post added to the GTN.
Using feed-to-bluesky: https://github.com/marketplace/actions/feed-to-bluesky

RSS-to-Bluesky action

---

.github/workflows/blueskyfeedbot.yml

Bluesky feed

---

.github/workflows/blueskyfeedbot.yml

add description

---

.github/workflows/blueskyfeedbot.yml

shorted template to make it less likely to hit character limit

---

topics/introduction/tutorials/galaxy-intro-short/tutorial.md

Made a lot of edits and merged it earlier but didn't add as an editor. Giving Phil credit!!

Giving Phil credit for edits

---

topics/single-cell/tutorials/scrna-case-cell-annotation/slides.html

The automated cell annotation tools in Galaxy never fully worked / became antiquated, so instead, we are going to link follow-up training to general analysis.

add follow up training to cell annotation slide deck

---

.github/workflows/blueskyfeedbot.yml

posts were failing if summary too long

update template to be shorter

---

events/2025-03-06-biont-fair

I forgot to add that the fair workshop and registration deadline is approaching very soon. @shiltemann if you have time, could you review this PR?

added biont fair workshop as an external event

---

CONTRIBUTORS.yaml

Keeping the world up-to-date with the changes in my life :)

Update abretaud infos

---

metadata/shortlinks.yaml

Hopefully that is the good way to do that 😅

Add microgalaxy search short link

---

editorial-board.md
topics/admin/metadata.yaml
topics/genome-annotation/metadata.yaml
topics/introduction/metadata.yaml

Created a page that lists all the editorial board members. Mostly for myself so I can start organising maintainers a bit more.

Editorial board page

---

topics/assembly/metadata.yaml
topics/imaging/metadata.yaml

- Added @kostrykin and @beatrizserrano to the Imaging Editorial Board to take over from @Tthomaswollmann. Thanks a lot all!

Updates to Editorial Boards

---

topics/introduction/tutorials/introduction/slides.html

replace `Execute` with `Run Tool`

tiny edits to intro slides

---

topics/epigenetics/tutorials/formation_of_super-structures_on_xi/slides.html

Update slides.html (fix typo)

---

topics/proteomics/tutorials/multiGSEA-tutorial/tutorial.bib
topics/proteomics/tutorials/multiGSEA-tutorial/tutorial.md

Add missing reference to MultiGSEA tutorial

---

GRANTS.yaml
learning-pathways/deconvolution_projects.md
news/_posts/2023-06-21-fair.md
news/_posts/2024-01-17-sc-fair-data.md
news/_posts/2025-03-03-deconvo-project.md
topics/single-cell/tutorials/EBI-retrieval/tutorial.md
topics/single-cell/tutorials/bulk-deconvolution-evaluate/tutorial.md
topics/single-cell/tutorials/scrna-data-ingest/tutorial.md
topics/single-cell/tutorials/scrna-ncbi-anndata/tutorial.md

Defeating software smog and duplication, one PR at at a time

integrate tags for the elixir-uk-dash funding

---

topics/imaging/tutorials/multiplex-tissue-imaging-TMA/tutorial.md

Adds @kostrykin and @beatrizserrano to reviewers for imaging tutorial

add reviewers to contributions metadata

---

topics/contributing/faqs/where-to-report.md

Heading 1 looked ridiculous with full sentences

Minor format fix

---

topics/assembly/tutorials/chloroplast-assembly/tutorial.md
topics/genome-annotation/tutorials/annotation-with-prokka/tours/tour.yaml
topics/genome-annotation/tutorials/annotation-with-prokka/tutorial.md
topics/variant-analysis/tutorials/microbial-variants/tours/tour.yaml
topics/variant-analysis/tutorials/microbial-variants/tutorial.md

Updated a few tutorials that were using an obsolete JBrowse option

Update Jbrowse parameter

---

topics/ecology/tutorials/ENA_Biodiv_submission/tutorial.md

I changed this tutorial to use Falco instead of FastQC.

Change from fastqc to falco in ENA_Biodiv_submission

---

.github/workflows/google-form-recordings.yml

to fix pushing unrelated recording info to open PR

add suffix to recordings PR branch

---

CODEOWNERS
topics/galaxy-interface/metadata.yaml
topics/introduction/metadata.yaml

for the introduction and galaxy-interface topics. Thanks Delphine!

add @delphine-l as EB member 

---

topics/sequence-analysis/tutorials/quality-control/tutorial.md

fixes https://github.com/galaxyproject/training-material/issues/5737
Thanks to @Achukwunta for reporting the mistake!

Fix quality calculation in QC tutorial

---

news/_posts/2025-03-26-gta-registration-open.md

added link to restiration from

added register link

---

topics/admin/tutorials/ansible-galaxy/tutorial.md
topics/admin/tutorials/apptainer/tutorial.md
topics/admin/tutorials/connect-to-compute-cluster/tutorial.md
topics/admin/tutorials/cvmfs/tutorial.md
topics/admin/tutorials/tool-management/tutorial.md

Fix broken GAT tutorials, minor edits

---

CONTRIBUTORS.yaml
events/2025-05-12-galaxy-academy-2025.md
events/tracks/gta2025-variant-analysis.md

Added the following to the GTA2025 event page
- FR server
- Variant Analysis track
@khaled196: Can you check your track? See what should be changed, and add more descriptions and helpers who will help you in preparing and during the event?

added FR server and Variant Analysis

---

CODEOWNERS
topics/galaxy-interface/metadata.yaml
topics/introduction/metadata.yaml

@teresa-m agreed to be on the editorial board for Introduction and "Using Galaxy and Managing your Data" topics, thanks!

Add Teresa to editorial board

---

GRANTS.yaml
ORGANISATIONS.yaml

Good morning,
I updated the grants file to update de.kcd, as @bgruening suggested yesterday. 
However, there was an error therefore I am pushing again.
@shiltemann thanks again for your help, I really hope all is in the clear now.
TODO: @bgruening, could you help me with the funding id, or should I ask the de.kcd coordination?
Thank you all!

adding de.kcd to GRANTS.yaml

---

CONTRIBUTORS.yaml

Hi,
I added de.kcd in my affiliations, as we spoke about in the earlier PR.
@shiltemann I hope this works despite the information's move from grants to organisations. Otherwise, please let me know!
Thank you :)

Adding de.kcd to my information in CONTRIBUTORS.yaml

---

topics/ecology/tutorials/openrefine_gbif/tutorial.md

Hi, I forgot to add myself as a reviewer when reviewing this tutorial, I'm sorry for the extra work and thanks for your help!

Adding reviewer to OR tutorial

---

topics/imaging/tutorials/process-image-bioimageio/tutorial.md

The PR replaces the unsupported model based on TensorFlow by a Pytorch based model supported by "Process image using a BioImage.IO model" tool

Replace TensorFlow model to a Pytorch one

---

events/tracks/gta2025-ml.md

ping @teresa-m @paulocilasjr  thanks!

Update GTA ML track table

---

news/_posts/2025-04-16-admin-training-survey.md

added admin survey as a news post
@dadrasarmin and @nsoranzo, please change whatever you don't like. I more or less took @nsoranzo text.

Added admin survey as a news post

---

topics/microbiome/tutorials/dada-16S/tutorial.md
topics/microbiome/tutorials/dada-16S/workflows/workflow.ga

Hello, I'm opening this PR to update the version of the dada tool. It's for the GTA. 
Thank you and have a nice day!
Romane

updating dada's version for GTN

---

CONTRIBUTORS.yaml
events/2025-05-12-galaxy-academy-2025.md
events/tracks/gta2025-bioNT.md
events/tracks/gta2025-ml.md

1. Added Gießen trainers to the event page:    
- Jochen_Blom, PfisterMaxJLU, lfenske, Oliver_Rupp, oschwengers, jhahnfeld
2. Updated ML track:
- Added trainer emmaustin20
3. Updated BioNT track:
-  added training materials more noticeable

Update gta event page

---

topics/statistics/tutorials/text_mining_chinese/tutorial.md

I updated the tutorial with @itisAliRH's updated tool version of the diff tool for better display of Chinese characters in the diff tool. Thank you :)

Update Tool-versions in Tutorial Text Mining Chinese

---

workflows/embed.html

fixes https://github.com/galaxyproject/training-material/issues/4418 from @nomadscientist

embedded workflow list: open links in full body of the window

---

redirects/scrna_basic-pipeline_spanish.md

[fix deploy] move redirect

---

topics/genome-annotation/tutorials/introduction/slides.html

Hello, I saw two typo errors.
Thank you! Have a nice day!
Romane

typo error

---

events/tracks/gta2025-variant-analysis.md

Update the GTA varinat analysis learninig path

Update the GTA varinat analysis learninig path

---

topics/single-cell/tutorials/pseudobulk-analysis/tutorial.md

Updated the tutorial.md file to improve the clarity of explanations and ensure the content is easier to follow during the video recording. Changes are limited to text edits only.

Improve tutorial text for clarity of the video recording

---

events/2025-05-12-galaxy-academy-2025.md

[GTA] add usegalaxy.fr tiaas link

---

events/tracks/gta2025-ml.md

Added text clarity on ML track Slack link
Replaced text-links with icon-links

GTA ML track landing page, adjustments and fixes for readability

---

events/tracks/gta2025-variant-analysis.md

fix issue reported by @khaled196 (thanks!)
fixes https://github.com/galaxyproject/training-material/issues/6032

[GTA] fix track layout issue

---

topics/proteomics/tutorials/proteogenomics-dbcreation/tutorial.md
topics/proteomics/tutorials/proteogenomics-dbcreation/workflows/galaxy-workflow-mouse_rnaseq_dbcreation.ga

Updated tools to the latest version, added tools id to the hands-on boxes,  some cosmetic changes, and added more file renaming for clarity.

Proteogenomics 1: Database Creation - update tools in tutorial and workflow

---

events/2025-05-19-dh-lab.md

@Sch-Da this adds your upcoming workshop also to the GTN events page :)

[Event] Add DHLab workshop as external event

---

topics/proteomics/tutorials/proteogenomics-dbcreation/tutorial.md
topics/proteomics/tutorials/proteogenomics-dbcreation/workflows/galaxy-workflow-mouse_rnaseq_dbcreation.ga

The previous regex for identifying duplicates when merging fasta files was not picking up on the full accessions.

Proteogenomics 1 - fix regex for merging fasta files

---

topics/microbiome/tutorials/diversity/tutorial.md

The wrong collection FAQ was used; fixed.
Thanks @SantaMcCloud for spotting it !

Fix collection input for diversity toturial

---

events/2025-05-12-galaxy-academy-2025.md
events/tracks/gta2025-assembly.md
events/tracks/gta2025-bioNT.md
events/tracks/gta2025-climate.md
events/tracks/gta2025-microbiome.md
events/tracks/gta2025-ml.md
events/tracks/gta2025-proteomics.md
events/tracks/gta2025-single-cell.md
events/tracks/gta2025-transcriptomics.md
events/tracks/gta2025-variant-analysis.md

updated people who signed up for Slack support

updated people who signed up for Slack support

---

topics/digital-humanities/tutorials/text_mining_chinese/tutorial.md

I found typos/errors from my update last week. It would be great if you could merge this streamlined version.
Thanks so much :)

Update Chin Text-mining tutorial.md

---

topics/microbiome/tutorials/metagenomics-binning/tutorial.md

Update of the FAQ.
@paulzierep it is according to the question on GAT Slack.

updated FAQ on collection

---

learning-pathways/neoantigen.md

added neoantigen to learning pathways

---

faqs/galaxy/analysis_differential_expression_help.md

Update analysis_differential_expression_help.md typo fix

---

CONTRIBUTORS.yaml
events/2025-05-19-dh-lab.md
topics/digital-humanities/tutorials/text_mining_chinese/tutorial.md

update contributors for Teresa and Lisanna

update contributors for Teresa and Lisanna

---

topics/transcriptomics/tutorials/rna-seq-analysis-clustering-viz/tutorial.md

corrected answer to question

---

CODEOWNERS
topics/admin/metadata.yaml

Thanks for agreeing to be topic maintainer for the Admin topic @mira-miracoli!
You should feel free to review and merge anything in the admin topic, but of course feel free to ping me for any GTN-technical questions you have or a second pair of eyes.
Perhaps you would like to start by merging this one? :)

add Mira as topic maintainer

---

topics/genome-annotation/tutorials/apollo-euk/tutorial.md

Done @joanapauperio and Emily Clark

add Genomics as EDAM topic

---

topics/genome-annotation/tutorials/gene-centric/tutorial.md

Done @joanapauperio and Emily Clark

add one more EDAM topic to gene-centric tutorial

---

topics/genome-annotation/tutorials/repeatmasker/tutorial.md

Done @joanapauperio and Emily Clark

add EDAM topic to "Masking repeats with RepeatMasker"

---

topics/assembly/tutorials/vgp_workflow_training/tutorial.md

adding edam ontology

---

topics/ecology/tutorials/obisindicators/tutorial.md

EDAM terms were suggested for this tuto during the ELIXIR All Hands meeting

Add EDAM to OBS marine indicators tutorial

---

topics/assembly/tutorials/assembly-decontamination/tutorial.md

Following suggestion from the community during the All Hands, EDAM topics are added to this tuto

Add EDAM to assembly decontamination tutorial

---

topics/genome-annotation/tutorials/helixer/tutorial.md

Adding terms suggested during the Elixir All Hands meeting

Adding EDAM terms to helixer annotation tuto

---

topics/assembly/tutorials/ERGA-post-assembly-QC/tutorial.md

EDAM terms suggested during the Elixir All Hands workshop

Add EDAM to ERGA post assembly QC tutorial

---

topics/assembly/tutorials/vgp_genome_assembly/tutorial.md

During the Elixir All Hands, EDAM terms were suggested for this tutorial

Added EDAM to vgp genome assembly tutorial

---

faqs/galaxy/cite-tools-used-in-a-history.md
faqs/galaxy/cite-tools-used-in-a-history.yaml

I added a FAQ to the feature section to explain how a user can get the list of all publications they should cite based on the history of their analysis.

Added a FAQ for exporting citations of a history.

---

topics/transcriptomics/tutorials/rna-seq-analysis-clustering-viz/tutorial.md

added parentheses in line 459 and 468

---

topics/genome-annotation/tutorials/comparison-braker-helixer-annotation/tutorial.md

Hello, I am opening this PR to correct a typo.
Thank you, have a nice day.
Romane

typo error in the download URL for the bam file

---

CONTRIBUTORS.yaml
_layouts/learning-pathway.html
learning-pathways/biont-python.md

Added Learning pathway for the BioNT From Zero to Hero Python course. This course is a copy of the Learning track hosted at the GTA2025
@Lisanna @hvelab @silviadg87: I also updated some of your contributor info. I hope that it is ok like this. If not, please remove or update them.

[WIP] Biont learning path

---

_plugins/util.rb

Adding Bar chart tool ID (https://usegalaxy.eu/root?tool_id=barchart_gnuplot)

adding barchart tool ID to the Allowed_Short_IDs

---

topics/ecology/metadata.yaml

add Galaxy Ecology reference & data access and management on the description

Update metadata.yaml to add Galaxy Ecology ref & data access and mngt

---

topics/introduction/tutorials/galaxy-intro-ngs-data-managment/tutorial.md

Just two minor fixes for issues discovered during a workshop.

Small fixes to the NGS data logistics tutorial

---

.github/workflows/ci-main.yml

Reverts galaxyproject/training-material#6284

Revert "use PAT for reviewdog to allow comments on PRs from forks"

---

news/_posts/2025-07-17-gta-overview.md

Fix typo on GTA2025 news

---

events/2025-11-24-gat-brno.md

fix link to registration form

---

topics/assembly/tutorials/vgp_workflow_training/tutorial.md

Adding a new intput history.
@SaimMomin12 does this look ok to you, can we merge that?

add input history

---

ORGANISATIONS.yaml

Add two French Organisations in the list
- RFMF Frenchspeaking Metabolomics and Fluxomics Society
- MetaboHUB Metabolomics and Fluxomics Infrastructure

Update ORGANISATIONS.yaml rfmf metabohub

---

news/_posts/2025-09-12-gta-orga-2026.md

@Delphine-L: Here is the draft of the blog post for the organization of the GTA 2026.

added new blog post for gta orga call

---

topics/digital-humanities/tutorials/introduction_to_dh/tutorial.md

Add one task for consistency
remove typo in renamed item
Could you merge this @bgruening - some cosmetics for tomorrow - but it will also be fine without the update

Update DH tutorial.md

---

topics/fair/tutorials/dataplant-arcs/tutorial.md

Updated a few links that were no longer working :)

Fix broken links for installation steps

---

topics/proteomics/tutorials/maxquant-msstats-dda-lfq/tutorial.md

Updates the zenodo links to the latest record.

maxquant training update links

---

events/2025-09-24-wokshop-graz.md

correcting the organizer - graz workshop

---

.github/labeler.yml

@shiltemann I tried to adjust here the labeler bot to the new version 6

try migrating labeller to new version
